detekt_custom.yml, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/wrappers/BitmapWrapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt, sample/kotlin/src/main/res/drawable/ic_dd_shape_oval.xml, sample/kotlin/src/main/res/drawable/ic_dd_shape_rect.xml, sample/kotlin/src/main/res/layout/fragment_image_components.xml
Implement bitmap downscaling similar to what was done on iOS, aiming to end up with a bitmap of 10kb or less. We calculate the expected dimensions sizes for a perfect square with the required filesize, and then work out the dimensions of the resized bitmap from that.
Things to consider: 
- We are later compressing the bitmaps to webp and this gives additional savings in file size, but it's difficult to predict in advance how much the savings will be. Should we be taking this into account in the scaling of the raw bitmap?
Some numbers from testing:
Initial bitmap size: 26544 
Size of bitmap after downscaling: 9400
After webp compression: 3136
This pr will allow us to more accurately size the lrucache
- [ ] Make sure you discussed the feature or …
=> REPLAY- 1893: Implement bitmap downscaling

detekt_custom.yml, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListenerTest.kt
There is a memory leak in the structure like `WeakHashMap<Window, JankStats>`, because `WeakHashMap` has strongly-referenced values, so it means if `JankStats` holds internally `Window` instance, it won't be GC-ed, even if it is a key of `WeakHashMap`.
In this PR we are removing the keys explicitly if activity is destroyed and there are no more activities left. This may increase the number of times we create `JankStats` instance, but it is not a big deal compared to the memory leak mitigation.
Even if there is a configuration change and activity will be re-created, it may be backed by new/another window anyway. …
=> RUMM-3475: Fix memory leak in `JankStats` usage

dogfood.py
Tiny PR to mention Datadog SDK explicitly in the PRs created by dogfood script.
=> Mention Datadog SDK explicitly in dogfood script

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewOnDrawInterceptor.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallback.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorderTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewOnDrawInterceptorTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallbackTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListenerTest.kt
In this PR we are fixing the `StrictMode` `IllegalAccesException` when trying to get the `WindowManager` from the `Application` instead of getting it from a visual `Context` as recommended. 
=> REPLAY-1905 Do not resolve WindowManager from Application context

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactoryTest.kt
In this PR we align with the Session Replay payload upload request format in [iOS](https://github.com/DataDog/dd-sdk-ios/blob/670006d6c3f41ad2652c6f154fd4fda7d04a04a8/DatadogSessionReplay/Sources/Feature/RequestBuilder/RequestBuilder.swift) by dropping the query parameters.
=> REPLAY-1895 Remove the query parameters from SR requests

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/build.gradle.kts, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64LRUCache.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/BitmapPool.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Cache.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageCompression.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/WebPImageCompression.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/Base64Utils.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/CacheUtils.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/InvocationUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64LRUCacheTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/BitmapPoolTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/WebPImageCompressionTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/InvocationUtilsTest.kt
Adds a reusable bitmap pool for base64.
Reduce the number of new bitmaps created.
=> REPLAY-1890: Implement pool of reusable bitmaps

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/InternalLogger.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/SdkInternalLogger.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/SdkInternalLoggerTest.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/Telemetry.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryTest.kt
=> RUMM-924 Introduce the new InternalLogger#metric API

detekt_custom.yml, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/build.gradle.kts, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64LRUCache.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/BitmapPool.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/BitmapPoolHelper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseWireframeMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/CacheUtils.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/InvocationUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64LRUCacheTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/BitmapPoolTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapperTest.kt
Refactor the base64 drawable cache and the bitmap pool to be class instances instead of singletons.
Make things more straightforward to test and remove mutable variables
=> REPLAY-1943: Refactor caches from singletons to class instances

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/DatadogCore.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt
Minor improvement: SDK instance can be stopped, so we should unregister process lifecycle monitor.
=> Unregister process lifecycle monitor in core instance stop

detekt_custom.yml, features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaskInputTabWireframeMapper.kt, features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaskTabWireframeMapper.kt, features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/TabWireframeMapper.kt, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageCompression.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/WebPImageCompression.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseWireframeMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/QueueableViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableDimensions.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/ImageComponentsFragment.kt, sample/kotlin/src/main/res/layout/fragment_image_components.xml
• Gets the bitmap from BitmapDrawable if available (use new EnrichedBitmap class to know if we should later cache it)
• Extraction of the base64 logic from the ImageButtonMapper to ImageWireframeHelper
• Gets background images if they exist (added an example to the sample app)
• Support scaletypes (atm only fitXY and center-crop)
• Move registration of bitmapPool for callbacks from DrawableUtils to Base64Serializer
Additional improvements necessary to rollout base64 imagebutton support
=> REPLAY-1891: Optimize bitmap processing

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt
Fixes #1582 and maybe fixes #1523.
This PR fixes the issue when `ApplicationLaunch` is not reported in case if first RUM event coming is not interaction event. In this case session is not yet active, so we create `ApplicationLaunch` and `ApplicationStarted` action for nothing - they won't be written, because writer is no-op.
This PR moves the logic of creating `ApplicationStarted` event up to the application scope, which makes sense - we have to report it only once in the application lifecycle. Also session we be activated once `ApplicationStarted` event is received by the session scope, meaning that session is created not only by start view or start action events (which makes sense, because we introduced `ApplicationLaunch` view to be independent from background tracking feature).
There …
=> RUM-971: Report ApplicationLaunch view even if first RUM event is not interaction

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListenerTest.kt
The following crash was reported by the customer:
```
java.lang.IllegalArgumentException: attempt to remove OnFrameMetricsAvailableListener that was never added
at android.view.View.removeFrameMetricsListener(View.java:7797)
at android.view.Window.removeOnFrameMetricsAvailableListener(Window.java:995)
at androidx.metrics.performance.DelegatingFrameMetricsListener.remove(JankStatsApi24Impl.kt:253)
at androidx.metrics.performance.JankStatsApi24Impl.removeFrameMetricsListenerDelegate(JankStatsApi24Impl.kt:126)
at androidx.metrics.performance.JankStatsApi24Impl.setupFrameTimer(JankStatsApi24Impl.kt:107)
at androidx.metrics.performance.JankStats.setTrackingEnabled(JankStats.kt:129)
at com.datadog.android.rum.internal.vitals.JankStatsActivityLifecycleListener.onActivityStopped(JankStatsActivityL …
```
=> RUM-986: Fix crash when disabling JankStats tracking

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/ApiSurfacePlugin.kt, buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/GenerateApiSurfaceTask.kt
Android Studio's `Rebuild Project` button performs the equivalent of `./gradlew clean assemble`. Because of that the `genDir` folder used to store `json2kotlin` generated files is cleared and doesn't exists when the `GenerateApiSurfaceTask`is ran. 
The recommended way is to store path instead of actual files when the file is not guaranteed to exists when the task is ran.
Being able to use the `Rebuild Project` feature in AS.
=> Fix Android Studio 'Rebuild Project'

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryConfigurationEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
In this PR we are adding the information for the Session Replay feature configuration in our related Telemetry event.
=> RUM-886 Provide session replay data in configuration telemetry

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueItem.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/SnapshotRecordedDataQueueItem.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/TouchEventRecordedDataQueueItem.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessor.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedQueuedItemContext.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RumContextDataHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseWireframeMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextViewMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/RumContextDataForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/SnapshotRecordedDataQueueItemForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/TouchEventRecordedDataQueueItemForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/TouchEventRecordedDataQueueItemTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessorTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedQueuedItemContextHandlerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseTextViewWireframeMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapperTest.kt
Fixes two issues that were discovered during functional tests. 
The first issue is having the `AsyncImageProcessingCallback` held by the `Base64Serializer` instance, and this can lead to the next bitmap replacing the callback before the first one has completed. This can lead to the decrement of pending images happening on the wrong node. Solution: passing the asyncCallback in every call to handleBitmap.
The second issue is having the previous `RumContext` held by the `RumContextData` object. This can lead to an item being removed from the queue (lost - not processed) with prevContext A and newContext B, and the next item with prevContext B newContext B will no longer be seen as a new view - so no meta data. Solution: the RecordedDataProcessor now holds it's own prevRumContext variable and …
=> RUM-1042 Fix base64 issues with multithreading

.gitlab-ci.yml, build.gradle.kts, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/LayerDrawableExt.kt
=> RUM-721 treat scroll on non scrollable view as tap

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/RumContext.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
The RUM `session_state` and `view_type` were propagated as internal enums in the shared RUM feature context. This means that other modules could not use those values (except with a call to `toString()`, which could have resulted in obfuscated results). 
This PR ensures the data is shared as a String, to be manipulated unobfuscated from any module using it. 
Part of the work done to make the RUM sampling consistent between Webviews and the native app.
=> RUM-985 propagate session state and view type as Strings

features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/java/com/datadog/android/rum/internal/instrumentation/gestures/GestureListenerCompat.java, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
Create a custom Java version of `GestureDetector.OnGestureListener` class to keep compatibility with older versions of Android
Our telemetry is reporting a lot of exception similar to: 
```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter startDownEvent
at com.datadog.android.rum.internal.instrumentation.gestures.GesturesListener.onScroll(Unknown Source:2)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:791)
```
On Android pre API 32, the `onScroll` method could be called with a null `startDownEvent` value. Starting in API 33, this parameter is marked as `@NonNull`, meaning that our Kotlin implementation must accept non-null parameters (trying to force the type as nullable …
=> RUM-700 prevent NPE in GestureListener

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/rum/_common-schema.json, features/dd-sdk-android-rum/src/main/json/rum/resource-schema.json, features/dd-sdk-android-rum/src/main/json/rum/view-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ResourceEventForgeryFactory.kt
Enable cross platform SDKs to specify GraphQL attributes.
We remove all cross-platform attributes first, and only add the graphql object if the operation type is present.
The implementation might change in the future when we support GraphQL requests monitoring for Android, but it should not be hard to migrate the cross platform SDKs then.
Support GraphQL for cross platform SDKs
=> RUM-1034 Add cross platform graphql attributes

features/dd-sdk-android-trace/api/apiSurface, features/dd-sdk-android-trace/api/dd-sdk-android-trace.api, features/dd-sdk-android-trace/src/main/json/trace/span-schema.json, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/assertj/SpanEventAssert.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/domain/event/SpanEventSerializerTest.kt
Make the network info optional in the span schema.
This is part of several PRs to allow enabling/disabling attaching network info in spans collected in an Android app
=> RUM-391 make network info optional in span schema

features/dd-sdk-android-trace/api/apiSurface, features/dd-sdk-android-trace/api/dd-sdk-android-trace.api, features/dd-sdk-android-trace/src/main/json/trace/span-schema.json, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/TraceConfiguration.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/assertj/SpanEventAssert.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/domain/event/SpanEventSerializerTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/TraceConfigurationForgeryFactory.kt, instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt
Add a `setNetworkInfoEnabled` option in the TraceConfiguration used to enable the feature
This is part of several PRs to allow enabling/disabling attaching network info in spans collected in an Android app
=> RUM-391 add networkInfoEnabled option in TraceConfiguration

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/MixedViewTrackingStrategy.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/MixedViewTrackingStrategyTest.kt
Fix #1614
Because the inner Activity and Fragment ViewTrackingStrategies used by the `MixedViewTrackingStrategy` also listen to activity lifecycle callbacks, RUM start view events are called twice, resulting in duplicated events.
=> RUM-1189 fix duplicate views in MixedViewTrackingStrategy

features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/Trace.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/TracingFeature.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/data/TraceWriter.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/domain/event/DdSpanToSpanEventMapper.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/assertj/SpanEventAssert.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/TracingFeatureTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/domain/event/DdSpanToSpanEventMapperTest.kt
Use the `networkInfoEnabled` to decide whether network info should be serialized or not in spans
This is part of several PRs to allow enabling/disabling attaching network info in spans collected in an Android app
=> RUM-391 use networkInfoEnabled to serialize or not network info in spans

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt
Before we were computing the batch duration value for the `batch_close` telemetry event as: `System.currentTimeInMillis - lastTimeBatchWasAccessed` which was completely wrong. In this PR we are addressing this issue.
=> RUM-1095 Fix the batch duration value in batch_close telemetry event

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/FeatureFileOrchestrator.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt
Following the latest discussions regarding the problem with the batch telemetry data for Android SDK we decided to add more information into the related logs:
- thread name (might be useful for potential concurrency debug)
- the batch file name 
- the tracking consent according with the batch origin folder
=> RUM-1187 Add more information into the batch telemetry

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorage.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/FeatureFileOrchestrator.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/file/advanced/FeatureFileOrchestratorTest.kt
It turns out that `FeatureFileOrchesrator` was using default file persistence config which didn't reflect user settings and feature settings for batch size, max item size, etc. This PR fixes it.
=> RUM-1202: Make `FeatureFileOrchesrator` use file persistence config created from user/feature settings

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageTypeResolver.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageTypeResolverTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelperTest.kt
Implement a heuristic image classification to determine whether an image is PII or not. If the image is PII then send a placeholder wireframe identifying the image as a content image. 
The identification is by checking that the dimensions of the image do not exceed 48dp (the largest icon in the material design guidelines). In the case of GradientDrawable we ignore this check, since GradientDrawables cannot be PII and constitute the backgrounds for RippleDrawables. 
Avoid sending PII as part of base64.
=> RUM-938 Implement heuristic image classification

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/FeatureFileOrchestrator.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt
The NDK folders do not produce batching telemetry so we had to simplify the rules a bit by removing the `|` separator case.
=> Fix RegEx in FeatureFileOrchestrator to resolve file consent type

instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_allow_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_user_input_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_allow_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_mask_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_mask_user_input_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_allow_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_mask_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_mask_user_input_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_with_input_mask_user_input_payload.json
Update the jsons for images/textviews due to the changes in the imageview support pr.
• EditText no longer have underline from a shape
• ImageViews are supported, so base64 and no longer shapes
=> Update functional tests due to imageview support

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/DatadogCore.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallback.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtils.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallbackTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
Previously our data upload worker was scheduled only if the device was offline and on any type of network. We are currently scheduling this all the time and only if the network is unmetered (WIFI or any other form of unmetered network)
We also updated the default `inBackground` state in the `BatchMetricsDispatcher` as `true` to handle correctly the metrics sent from the scheduled upload worker.
=> RUM-1194 DataUploadWorker is scheduled every time and on non - roaming network

features/dd-sdk-android-logs/api/apiSurface, features/dd-sdk-android-logs/api/dd-sdk-android-logs.api, features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/Logs.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/LogsTest.kt, instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt
Added a static method to Logs for checking if the feature had been enabled in a core.  This method is needed to properly setup Flutter when using `attachToExisting`.
refs: RUM-1066
=> feat: Add `isEnabled` to Logs

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/EditTextViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseEditTextViewMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/EditTextViewMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapperTest.kt
This reverts commit 3100b414e02641ba8e53f0a84051d8cf5e3bafd4.
Reverts base64 imageview support due to an issue discovered where the "content image" square size would change between when the image begins to download and finishes downloading remotely (the image is resized for centercrop). We will need to implement wireframe cropping and keep the image at a constant size.
=> Revert "RUM-1002 Implement base64 for imageviews"

features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/BatchesToSegmentsMapperTest.kt
We have situations where we have to send records with same timestamp (dummy records) when the view is changed to comply with the browser sdk - player way of working (FocusRecord, MetaRecord, ViewPortRecord) and we wanted to make sure that whenever they are read back from the batch to be sent the order is kept.
=> RUM-891 Unit test to confirm SR records order is kept when having same timestamps

buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt, local_ci.sh
Use the `CI` environment variable to enable the "show warning as errors" in Kotlin compiler
During development, especially when doing TDD, I often find myself having variables/parameters temporarily unused, which prevent from running the tests. 
This new option allows me to to TDD without manually changing the `allWarningsAsErrors` and still keep checks in the CI. 
> [!NOTE] 
> The `local_ci.sh` script will set the environnement variable to ensure one can detect those warnings before pushing to CI
=> Disable warning as errors locally

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/StrictModeExt.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt, detekt_custom.yml, features/dd-sdk-android-ndk/src/main/kotlin/com/datadog/android/ndk/internal/NdkCrashReportsFeature.kt, features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/DDTracer.java, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/core/StrictModeTest.kt
This tries to handle some StrictMode warnings happening during the SDK initialization, which can't easily be deferred to background threads. 
Prevent the SDK from spamming warnings in host application when StrictMode feature is enabled.
=> RUM-501 Handle Android Strict Mode

features/dd-sdk-android-ndk/src/androidTest/kotlin/com/datadog/android/ndk/NdkTests.kt, features/dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.cpp, features/dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.h, features/dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c, features/dd-sdk-android-ndk/src/test/cpp/integration-tests.cpp
We recently had some reported issues in the flutter sdk regarding some ANRs caused by our signal catcher. Basically what was happening is that our code inside the signal catcher was trying to acquire a `mutex` lock which was already acquired by another thread (we could not really reproduce this). We chose to go with the safest mechanism here in order to avoid any other issues and use `try locks` instead of simple `locks`.
https://github.com/DataDog/dd-sdk-flutter/issues/487
=> RUM-1330 Make sure we use try-locks in our NDK signal catcher

.gitlab-ci.yml, dd-sdk-android-core/build.gradle.kts, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/DatadogContextForgeryFactory.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/DeviceInfoForgeryFactory.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/ForgeExt.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/NetworkInfoForgeryFactory.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/ProcessInfoForgeryFactory.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/TimeInfoForgeryFactory.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/UserInfoForgeryFactory.kt, detekt_custom.yml
This PR adds a `testFixtures` source set to the Core module, and adds test fixture classes that will be shared with other modues (in the next PR)
This is part of our effort on improving our test suites across the mobile teams
=> (1/3) RUM-392 create core testFixtures source set

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt, buildSrc/src/main/kotlin/com/datadog/gradle/config/BaseExtensionConfig.kt, dd-sdk-android-core/build.gradle.kts, features/dd-sdk-android-logs/build.gradle.kts, features/dd-sdk-android-ndk/build.gradle.kts, features/dd-sdk-android-rum/build.gradle.kts, features/dd-sdk-android-session-replay-material/build.gradle.kts, features/dd-sdk-android-session-replay/build.gradle.kts, features/dd-sdk-android-trace/build.gradle.kts, features/dd-sdk-android-webview/build.gradle.kts, integrations/dd-sdk-android-coil/build.gradle.kts, integrations/dd-sdk-android-compose/build.gradle.kts, integrations/dd-sdk-android-fresco/build.gradle.kts, integrations/dd-sdk-android-glide/build.gradle.kts, integrations/dd-sdk-android-okhttp/build.gradle.kts, integrations/dd-sdk-android-rum-coroutines/build.gradle.kts, integrations/dd-sdk-android-rx/build.gradle.kts, integrations/dd-sdk-android-sqldelight/build.gradle.kts, integrations/dd-sdk-android-timber/build.gradle.kts, integrations/dd-sdk-android-trace-coroutines/build.gradle.kts, integrations/dd-sdk-android-tv/build.gradle.kts
This PR refactor the `build.gradle.kts` buildscript for all our libraries to extract shared configurations and make it easier to: 
- create new libraries
- add build features to all libraries
This is part of our effort on improving our test suites across the mobile teams
=> (2/3) RUM-392 refactor shared android library build script

dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/ForgeExt.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/RawBatchEventForgeryFactory.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/net/LogsRequestFactoryTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/net/RumRequestFactoryTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactoryTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/net/TracesRequestFactoryTest.kt
Just a minor improvement to share `RawBatchEvent` forgery, so that is can be used in tests in different modules.
=> Share RawBatchEvent forgery for tests between the modules

sample/kotlin/src/main/kotlin/com/datadog/android/sample/logs/LogsFragment.kt, sample/kotlin/src/main/res/layout/fragment_logs.xml, sample/kotlin/src/main/res/values/strings.xml
Adds a better way to send logs from the sample app
Being able to have more control from the Synthetics Tests
=> RUM-1492 Improve Logs Fragment in sample App

.gitlab-ci.yml, Dockerfile.gitlab, gradle.properties, sample/kotlin/build.gradle.kts, sample/kotlin/src/main/kotlin/com/datadog/android/sample/Preferences.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
This task builds and uploads the sample app to our synthetics org and marks it as latest
=> RUM-1493 add ci task to update E2E sample app

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TraverseAllChildrenMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversalTest.kt
Add an internal interface for mappers that need to traverse all children during tree traversal.
This interface is to be used by React Native for traversing RN view groups, as preparation for implementing Session Replay there.
=> RUM-1613 Add mapper interface for traversing all children

sample/kotlin/src/main/kotlin/com/datadog/android/sample/picture/PictureViewModel.kt
To ensure our E2E tests have a consistent number of event, while having some picture load failure, we replace the "pure" random logic with alternating loading failure and success
=> RUM-1492 Have more consistent results when using the load picture sample screen

build.gradle.kts, dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/storage/FeatureStorageConfiguration.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/BatchProcessingLevel.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/configuration/DataUploadConfiguration.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/v2/DataUploadRunnable.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/configuration/DataUploadConfigurationTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/v2/DataUploadRunnableTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationCoreForgeryFactory.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/DataUploadConfigurationForgeryFactory.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/FeatureStorageConfigurationForgeryFactory.kt
Modifies the core logic to get a list of batches instead of single batch. It's done through a new configuration called BatchProcessingLevel that allows controlling the amount of batches processed sequentially without a delay within one reading/uploading cycle. Currently it exposed 3 levels: low, medium and high that translate to 1, 10 and 100 of batches processed. By default it's taking up to 10 batches in a cycle.
This logic improves the data upload when batch back pressure occurs.
=> RUM-1983 Introduce the BatchProcessingLevel API

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalReaderRunnable.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalReaderRunnableTest.kt
RUM data was missing cpu/memory info since SDK v2, because we were safe-casting the property of RUM context to the wrong type.
=> RUM-2104: Fix the issue of missing cpu/memory info with RUM view events

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/WebPImageCompression.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseAsyncBackgroundWireframeMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/WebPImageCompressionTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseTextViewWireframeMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageViewMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt
Benchmarks that I've done show that performance with base64 was around 20ms on the main thread. This PR moves bitmap resizing tasks to a background thread in order to improve performance to around 7ms on the main thread. In addition the PR handles a couple of additional issues:
• Wrap the call to `bitmap.compress` in`WebPImageCompression` in try/catch to prevent an exception if the bitmap was recycled while we were working on it (can happen with the system-cached bitmaps that we take from `BitmapDrawable`)
• Rename some variables that were just called "callback" to make it clearer when reading the code what callback is involved
SDK should not impact the main thread more than 8ms.
- [ ] Make sure you discussed the feature or bugfix with the …
=> RUM-1951 Improve performance with base64

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/net/DefaultFirstPartyHostHeaderTypeResolver.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/net/DefaultFirstPartyHostHeaderTypeResolverTest.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/AndroidTracer.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/AndroidTracerTest.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt
This is Android counterpart of https://github.com/DataDog/dd-sdk-ios/pull/1529
=> RUM-1556: Update default propagation style from `Datadog` to `Datadog`+`TraceContext`

features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/propagation/W3CHttpCodec.java, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/utils/assertj/HeadersAssert.kt
This PR adds `tracestate` header with Datadog-specific information in case of `TRACECONTEXT` tracing. This header will contain the following Datadog-specific tags:
* `p` - parent ID
* `s` - sampling decision
* `o` - origin, if exists. In case of instrumentation with RUM, it will have `rum` value.
Full spec https://www.w3.org/TR/trace-context/#tracestate-header
iOS counterpart https://github.com/DataDog/dd-sdk-ios/pull/1536
=> RUM-1924: Use tracestate header to supply vendor-specific information

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryCoreConfiguration.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/TelemetryCoreConfigurationForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryConfigurationEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryCoreConfigurationTest.kt
`batchProcessingLevel` has type `Int` and not `Long`, this difference made it evaluate to `null` when extracted from the message bus and safe-casted to `Long`.
We probably need to come up with some approach regarding testing the things going through the message bus.
=> Fix batch processing level reporting in core configuration telemetry

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
Create a SetSyntheticsTestAttribute event.
The event will be used to attach Synthetics test run information to the RUM Events
=> (1/9) RUM-2127 Create a SetSyntheticsTestAttribute event

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/RumContext.kt
Add synthetics information to the RUM Context: this will allow us to attach the synthetics test run information to all the RUM events based on the context (and possibly attach the info to other features eventually: Logs, Session Replay, …)
=> (2/9) RUM-2127 Add synthetics information to the RUM Context

features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventConsumerTest.kt
Fix a test that was randomly failing locally and in CI 
Test and CI reliability
The test relied on several threads sending events to the WebViewRumEventConsumerTest. But the assertions expected the events to be processed in the original order, which, on many occasion (10% to 25% of test runs) wasn't true, meaning the assertion would fail.
=> Fix flaky test in WebViewRumEventConsumerTest

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
Store the synthetics test info in the RUM Context.
We store the info directly at the application level, as it will be the same for a given run in Synthetics. If a Synthetics run creates multiple session for any reason, we want  the info to stay available.
=> (3/9) RUM-2127 store the synthetics test info in the RUM Context

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
Add synthetics info to RUM Actions
The info is read from the RUM context and converted into the relevant attributes at write time.
=> (5/9) RUM-2127 Add synthetics info to RUM Actions

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
Add synthetics info to RUM Errors
The info is read from the RUM context and converted into the relevant attributes at write time.
=> (6/9) RUM-2127 Add synthetics info to RUM Errors

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
Add synthetics info to RUM Resources
The info is read from the RUM context and converted into the relevant attributes at write time.
=> (7/9) RUM-2127 Add synthetics info to RUM Resources

dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/ForgeExt.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/UserInfoForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ActionEventForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ErrorEventForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/LongTaskEventForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ResourceEventForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ViewEventForgeryFactory.kt, features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/utils/forge/ActionEventForgeryFactory.kt, features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/utils/forge/ErrorEventForgeryFactory.kt, features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/utils/forge/LongTaskEventForgeryFactory.kt, features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/utils/forge/ResourceEventForgeryFactory.kt, features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/utils/forge/ViewEventForgeryFactory.kt
Fix a flaky test in the RumEventDeserializer.
The test generates random `usr.*` attributes in a RUM event, then serialize and deserialize it and compare with the original one. An issue can arise if one of the random attributes uses a known key name (i.e. `id`, `name`, `email`), as on serialization it would conflict and wouldn't be recoverred via deserialization. 
I also "fixed" this in other ForgeryFactory implementations that could one day cause flakyness in the tests
=> Fix flaky test in RumEventDeserializer

dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/DatadogContextProviderTest.kt
Fix a flaky test in the DatadogContextProvider: 
the test tries to ensure modifying a mutable map after it being injected won't modify the underlying context. 
In some rare case, the following line would create an issue, as no data would be removed from the mutable map, making one of the assertions failed. 
The fix ensures that: 
- the original mutable map has at least 4 items
- at least one entry is removed
=> Fix flaky test in DatadogContextProvider

detekt_custom.yml, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/GlobalRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/security/EncryptionTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/BaseSessionReplayTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt, instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt
This change removes RUM monitor for the given RUM feature (or SDK instance in other words), when the feature is stopped.
=> RUM-1017: Unregister RUM monitor when associated RUM feature is stopped

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/LongTaskEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
Add synthetics info to RUM Long Tasks
The info is read from the RUM context and converted into the relevant attributes at write time.
=> (8/9) RUM-2127 Add synthetics info to RUM Long Tasks

features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
This PR fixes a flaky test in TelemetryEventHandlerTest
The test generates a list of events, and then filters it to ensure to keep only one event per fingerprint. If the number of filtered event is lower than the `MAX_EVENTS_PER_SESSION_TEST` value, the test eventually tries to verify that a warning log is printed a negative amount of times. 
The fix ensures that the filtered list has enough entries to trigger the log at least once.
=> Fix flaky test in TelemetryEventHandlerTest

detekt_custom.yml, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/ActivityLifecycleTrackingStrategyTest.kt
track synthetics info from activity extras
All the provided ViewTrackingStrategy implementation extend the ActivityLifecycleTrackingStrategy, meaning that all supports the Synthetics use case.
=> (9/9) RUM-2127 track synthetics info from activity extras

dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestratorTest.kt
Fix flaky test in BatchFileOrchestratorTest
The main issue here is that were using Kotlin's `mutableListOf()` which is inherently not thread safe, and try to insert elements from multiple concurrent threads. What happens 10% of the time (locally) is that two thread end up appending at the same time, and one of the value is overridden, resulting in one less value in the list than expected.
=> Fix flaky test in BatchFileOrchestratorTest

buildSrc/src/main/kotlin/com/datadog/gradle/config/FlavorBuildConfig.kt, buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/GenerateApiSurfaceTask.kt, sample/kotlin/build.gradle.kts, sample/wear/build.gradle.kts
Replace a `println` with gradle's logger to reduce the noise in our build output
=> Reduce noise in logs when building the project

features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/MainLooperLongTaskStrategyTest.kt
Fix a flaky test in MainLooperLongTaskStrategyTest.
Flakiness arise from the way multithreading can introduce some delays, and some suboptimal assertions:
-  Probably a long task would be detected, we used `Thread.sleep(duration + 1)`, which is a bit weird.
-  we adjusted the random duration to always be 1 more than the threshold.
- The assertion used `.isCloseTo(duration, offset)`, which would be the same as `.isBetween(duration - offset, duration + offset)`. This assertion is not perfect as a detected value less than duration is impossible, and wrong. 
- We adjusted it to be `.isBetween(duration, duration + 16L)`
- The offset itself was set to 10 millisecond, which would prove sometimes to small locally (5% of occurences)
- We increased it to 16 ms
> [!NOTE]
> Although this reduces …
=> Fix flaky test in MainLooperLongTaskStrategyTest

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/BatchSize.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/UploadFrequency.kt
Following the discussions in the [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3138388946/RFC+-+Uploader+Improvements+Strategies) we are going to lower the `BatchSize` and `UploadFrequency` values in order to increase the frequency of our payload uploads.
=> RUM-1835 Lower the upload frequency and batch size enum values

dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/api/StubEvent.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/api/StubFeatureScope.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/api/StubFirstPartyHostHeaderTypeResolver.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/api/StubInternalLogger.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/api/StubSDKCore.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/ktx/JsonObjectExt.kt, features/dd-sdk-android-logs/build.gradle.kts, features/dd-sdk-android-rum/build.gradle.kts
Create a few Stubbed classes to use the SDKCore in integration tests from the Feature modules.
> [!NOTE]
> So far only a few functions in the `StubSDKCore` class are actually implemented, others will be added when needed
=> RUM-1517 Create SDKCore stub classes

detekt_custom.yml, features/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/forge/ShapeWireframeForgeryFactory.kt, features/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/forge/TextWireframeForgeryFactory.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/UniqueIdentifierGenerator.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ImageWireframeForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/PlaceholderWireframeForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ShapeWireframeForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ShapeWireframeMutationForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/TextWireframeForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/TextWireframeMutationForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/UniqueIdentifierGeneratorTest.kt
Generates wireframe IDs as `Int` instead of as `Long`. Also modify the forgery factories to do the same so that tests will reflect this change.
Generating the IDs as `Long` caused an issue on the backend because there the IDs are being parsed as `Int`. When the ID was out of bounds it would be rounded and this could cause problems with removals of wireframes or duplicated wireframes.
=> RUM-2245 Generate wireframe ids as 32bit Int

reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/LoggerTest.kt, tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/ApiUsage.kt
Creates the first real Integration Test class for the `Logger` and `Logger.Builder` classes.
So far overal public API (all modules together) is up to 4%
=> RUM-1520 Logger integration tests

dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/serializer/GsonCompatibilityTests.kt
As a followup on the previous action taken on iOS: https://datadoghq.atlassian.net/browse/RUM-1929, I investigated all the potential issues on our end regarding this topic and came to the following conclusions:
- we are using indeed `.` attributes on our end but most of them are correctly handled in our serializers. 
- it will be quite hard and very intrusive to try to remove all these attributes in the sdk and for no reason momentarily because the serializers are handling this. There is only one problem that could appear if by any chance we adopt a new `Gson` version which changes the implementation in adding the properties into the `toString` method. Right now they are using a `LinkedList` which suites us very well.
In this PR I added a regression test for our Gson dependency to make …
=> RUM-1930 Add regression test for Gson toString method

reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/LoggerTest.kt, reliability/stub-core/build.gradle.kts, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubEvent.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubFeatureScope.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubFirstPartyHostHeaderTypeResolver.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubInternalLogger.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubSDKCore.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/tests/ktx/JsonObjectExt.kt, settings.gradle.kts
Because AndroidStudio doesn't deal well with `testFixtures` source sets, the Stubbed SDKCore (and linked classes) were moved to an independent module which allows code completion and make the IDE happy.
=> RUM-1517 create Stub Core module

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/storage/EventBatchWriter.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/persistence/PersistenceStrategy.kt
> The overall goal is to create a feature allowing customers to store unsent data any way they want (instead of using the official disk batch files)
This first PR creates a "public" `PersistenceStrategy` interface that customers would need to implement to use this new feature.
=> (1/4) RUM-2129 Create PersistenceStrategy interface

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/DatadogCore.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreInitializationTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationCoreForgeryFactory.kt
> The overall goal is to create a feature allowing customers to store unsent data any way they want (instead of using the official disk batch files)
This PR adds the necessary methods to set a custom `PersistenceStrategy.Factory` in the core configuration.
When set, this will be reported in the configuration telemetry, and
the persistenceStrategyFactory will be stored in the CoreFeature instance
=> (2/4) RUM-2129 let customer set custom persistence strategy in configuration

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/AbstractStorage.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorage.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/Storage.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/AbstractStorageTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorageTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/FakeSameThreadExecutorService.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/test/elmyr/PersistenceStrategyBatchForgeryFactory.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt, dd-sdk-android-core/src/testFixtures/kotlin/com/datadog/android/tests/elmyr/RawBatchEventForgeryFactory.kt
> The overall goal is to create a feature allowing customers to store unsent data any way they want (instead of using the official disk batch files)
This PR implements our Internal `Storage` interface based on a `PersistenceStrategy`, in a _Consent Aware_ manner. This means that the tracking of consent is handled internally, and our customers don't need to worry about that part.
=> (3/4) RUM-2129 Implement AbstractStorage

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/image-wireframe-schema.json, features/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/image-wireframe-update-schema.json, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolver.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64LRUCache.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/HashGenerator.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/MD5HashGenerator.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ImageWireframeForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolverTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64LRUCacheTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/MD5HashGeneratorTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt
Adds the resourceId property to ImageWireframe, and additionally removes base64 from the MutationResolver diffing.  
Removing base64 from diffing improved performance on ios and in this PR we align on this change. Additionally, resourceId is a necessary prerequisite for the resource endpoint change.
=> RUM-1654 Add resourceId to ImageWireframe

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/BaseSessionReplayTest.kt
Adds resourceIds to the e2e payloads
We now send resourceIds as part of the ImageWireframes
=> Remove resourceId field from e2e payloads

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskInputTextViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskTextViewMapper.kt
Modify `MaskTextViewMapper` and `MaskInputTextViewMapper` to be open for extension.
Necessary for React Native Session Replay, in order to support masking for text elements.
=> RUM-2446: Open text masking classes for extension

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListenerTest.kt
This pr fixes the issue of duplicate wireframes appearing in the replays, and also adds in telemetry so that we'll know if items are dropped in future from the `RecordedDataQueue`. 
What was happening was that `RecordedDataQueueRefs` was held as a class-level variable inside `RecordedDataQueueHandler`. As a result, for every traversal the value of the `SnapshotRecordedDataQueueItem` held by the ref object was mutating, and this caused asynchronous tasks to occasionally return their callback to the wrong `SnapshotRecordedDataQueueItem`. This further led to the number of pending asynchronous tasks on the previous item never reaching zero, so it became stuck in the queue and eventually cleaned after exceeding the 200ms timeout. 
To handle the issue of duplicate wireframes. 
Anything else we …
=> RUM-2376: Fix duplicate wireframes issue

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorage.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorageTest.kt
We were removing items from collection during its traversal, this PR fixes that.
The issue doesn't reproduce with only single item in the collection, because modification check it done on the next iteration, so I also updated test to have multiple locked batches.
=> RUM-2467: Fix `ConcurrentModificationException` during `ConsentAwareStorage.dropAll` call

.gitlab-ci.yml
Ensure Gitlab has junit reports when necessary
There were several job runs where a test step failed and it wasn't captured by CI app. Having the Junit Reports will help diagnose and improve our coverage
=> Add artifacts in Gitlab test jobs

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
Port of commit from https://github.com/DataDog/dd-sdk-android/pull/1763 in our repo, to be able to run all the checks.
=> Fix leak caused by repeated calls to WeakReference.get()

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/storage/FeatureStorageConfiguration.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/FeatureStorageConfigurationForgeryFactory.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
Because we needed to add a workaround for SR data storage and upload configuration we added the `batchProcessingLevel`, `batchSize` and `uploadFrequency` at the `FeatureStorageConfiguration` level. Based on the latest improvements we added at the `Uploader` and the latest telemetry we concluded that this workaround is not needed anymore and we can remove this noise from our code base.
=> RUM-2075 remove data store/upload config from feature configuration

sample/kotlin/src/main/res/layout/fragment_text_view_components.xml, sample/kotlin/src/main/res/values/strings.xml
Add text overflow examples in sample app. These example overflow in the replays. Now that they're added they will be easier to check on when we apply the fix.
| Emulator | Replay |
|--------|--------|
| ![image](https://github.com/DataDog/dd-sdk-android/assets/8973379/a7c4e14b-c0b3-4910-83f5-3dfd760e0717) | ![image](https://github.com/DataDog/dd-sdk-android/assets/8973379/2d2710b3-2261-472a-b196-31c717601307) | 
=> Add text overflow examples in sample app

detekt_custom.yml, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/RumDataWriter.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/utils/SdkCoreExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/RumDataWriterTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/SdkCoreExtTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/RumEventMapperFactory.kt
This PR improves any error handling in the write pipeline of RUM. Before, if there was any exception thrown inside writing pipeline which wasn't caught, or if write wasn't successful, we didn't notify that event wasn't written (or dropped, in other words). This prevented to decrease `pendingXXX` counters in `RumViewScope`, thus making `isComplete` to evaluate to `false` in such cases.
This PR also centralizes the place where the notification about write success or failure is sent.
=> RUM-2568: Better handling of event write errors in RUM

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rules/NightlyTestRule.kt
The current logic of stopping executors and flushing data after each nightly test is not reliable, because in case of RUM we have a backward loop which cannot be executed if executors are stopped.
This PR adds a delay, so that all the events __possibly__ can get processed.
=> Add delay before executors are flushed and stopped in nightly tests

detekt_custom.yml, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt
This PR optimizes the way we are reporting response body length in OkHttp instrumentation.
We first try to get content length from response body as-is, and if it didn't work, we try to call `peekBody`. The explanation to that is related to the way OkHttp works: the [following doc](https://github.com/square/okhttp/blob/7bcc720d85128c2d663cb0719d0d52850af260f6/docs/features/calls.md?plain=1#L23C4-L23C15) states, that OkHttp will remove `Content-Length` header (and make `contentLength()` return -1) if transparent compression is used. This means that if `body.contentLength` returns positive value, then we are good already, and if it is not, we may try to call `peekBody` which **will apply decompression** and load a decompressed body in memory.
Another benefit is that now we can report body …
=> Optimize response body length reporting in OkHttp instrumentation

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt
This fixes a bug originally introduced in `1.17.2` with the following [commit](https://github.com/DataDog/dd-sdk-android/commit/62139739d7a85c2550ce5e29d3389e96ba68a51b): since we didn't have a special `NavigationKey` handling in the `Any.resolveViewUrl` method, view URL was always displayed as `com/datadog/android/rum/tracking/NavigationViewTrackingStrategy/NavigationKey`.
Also the key used between `stopView` and `startView` calls in `NavigationViewTrackingStrategy` was different because of this bug (`NavDestination` vs `NavigationKey` respectively)
=> RUM-2604: Fix view url in case of `NavigationViewTrackingStrategy` usage

dd-sdk-android-core/src/main/kotlin/com/datadog/android/ndk/internal/DatadogNdkCrashHandler.kt
This is an additional telemetry point for the issue, when sometimes file content is only "\\u0000" (happens when we decode information for NDK crash submission).
I didn't manage to understand why it happens. In theory if decoding from bytes to string fails, broken chars should be mapped to `\ufffd`, but to validate the assumption that the issue is on during decoding I'm adding this.
=> Add telemetry point for null file content

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/BitmapPool.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/BitmapPoolTest.kt
Fixes a ConcurrentModificationException that can occur due a race condition between low memory evicting items from the cache, and threads attempting to query the cache.
3000 iterations is the lower bound to reliably reproduce the issue in a reasonable number of unit test runs when it exists. This number of iterations takes around 4 seconds to run locally.
=> RUM-2314 Fix ConcurrentModificationException in BitmapPool

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rules/NightlyTestRule.kt
Continuation of https://github.com/DataDog/dd-sdk-android/pull/1783, seems 200 ms may not be enough.
=> Increase wait time in NightlyTestRule

.gitlab-ci.yml
We've changed the runner type here https://github.com/DataDog/dd-sdk-android/pull/1789 and since it is now k8s-based, the variables that depends on information related to k8s resources (host IP) needs to be referenced directly from the job otherwise is not going to work.
This PR fixes `dd-trace-java` bootstrap which was failing, because `BUILDENV_HOST_IP` wasn't available at the `variables` set stage.
=> Move reading `BUILDENV_HOST_IP` variable to the job script definition

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
This fixes a race condition that was quite present in RN - see description below.
The solution I choose was to move the responsibility of checking for initialization from `startRecording` into `checkStatusAndApplySample`. 
The `startRecording` method is easier to work with if it just performs an atomic action (like `stopRecording`).
It seems fit to put the check in `checkStatusAndApplySample` since it's the method that registers the `currentRumSessionId` that was creating the lock before.
This can happen in any Android app, it’s just that conditions for creating the race condition are more present in RN since we collect JS framerate through RUM events on every frame.
The race condition happens in SessionReplayFeature.kt, in the onInitialize function:
```kotlin
// first line making the …
```
=> Enable recording session if first RUM message happened before init

.gitlab-ci.yml, Dockerfile.gitlab, buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt
Updates CI Visibility instrumentation: rather than configuring each test task to fork a JVM with the DD Java tracer injected, now the tracer is injected into the Gradle daemon that runs the build.
Instrumenting the Gradle daemon has the following advantages:
- No need to manually change the build files, every test task is instrumented automatically.
- All tests executed within a single build are reported as part of a single test session, and it is possible to see the duration and status for the entire build or individual modules.
- Some background operations (such as reporting Git data or building an index of the repository) are done once for the entire build and not for every test task.
- [ ] Make …
=> Use automatic Gradle daemon instrumentation with CI Visibility instead of manual test tasks instrumentation

features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/handlers/AndroidSpanLogsHandler.kt
Prevent a false positive warning in the logcat when the logs feature is available but no fields is provided to the span.log() method
=> RUM-1520 prevent false positive warning

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
There are use cases (usually support use cases) where clients what to know the current session id without depending on the `sessionStarted` event. This provides that accessor.
refs: RUM-1962
=> feat: Add accessor for current session id

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
Prints the application and session id whenever a view changes. 
The Synthetics team have a delay when fetching logs from the device running the app under test. Because of this the initial Application and Session ID (printed early in the app's lifecycle) are lost and can't be retrieved. Repeating them whenever a view is started provides a workaround if the first logs of the app can't be read.
=> RUM-2441 make synthetics logs more verbose

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
Fix getCurrentSessionId to actually return the correct session id for the currently active session.
refs: RUM-1962
=> fix: getCurrentSessionId returns correct value

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploader.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploaderTest.kt
This PR adds additional status codes which we can get from intake as retryable in order to prevent data loss:
* 502 - bad gateway
* 504 - gateway timeout
* 507 - insufficient storage
=> RUM-2746: Add additional status codes as retryable

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/rum/error-schema.json, features/dd-sdk-android-rum/src/main/json/rum/resource-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumResourceMethod.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutTracesTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt
Fixes #1816.
This PR adds support of `CONNECT`, `TRACE`, `OPTIONS` to the `RumMonitor#startResource` call.
Both RUM resources view and traces/spans created by RUM2APM are working fine for these methods.
=> RUM-1308: Add more HTTP methods to RUM

detekt_custom.yml, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
This PR makes a copy of the attributes used by the different RUM events, because usually these attributes are stored in as the shared property of the RUM scope, they could be modified by the RUM thread while being read during the serialization on the I/O thread.
This will eventually prevent `ConcurrentModificationException`.
=> Make a copy of attributes before passing them to RUM event

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/Rum.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/ActivityTrackingPlaygroundActivity.kt
This change starts RUM session during the `Rum.enable` call. The general rule is like that:
* If application process has `foreground` type, then session will be started (with interaction time set at the moment of initialization), and `ApplicationLaunch` view with `application_started` event will be created.
* Otherwise, if application process has something different from `foreground` as type, session will be initialized only if background tracking is enabled, no `ApplicationLaunch` view will be created.
This PR is using the notion of `SdkInit` class, even though it is possible to use only `ApplicationStarted` event in order to be on-par with the similar logic in iOS SDK. Also it is still using event system for the session initialization in order to minimize the footprint of the change (it …
=> RUM-1702: Start session when RUM is initialized

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/SnapshotRecordedDataQueueItem.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/SnapshotRecordedDataQueueItemTest.kt
Adds a flag to snapshot items that indicates that they have finished traversing the view tree. Also, increases the interval that snapshots are considered stale from 200ms to 1 second
The RecordedDataQueueHandler in some situations could attempt to process an item that was still performing a traversal. Because items are inserted into the queue at the beginning of their traversals without nodes, the handler could regard the item as invalid and drop it from the queue. With this change, items that haven't finished traversals will only be dropped if stale. 
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) …
=> RUM-2600: Add traversal flag to snapshot items

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt
In order to prevent the graphs skewing in the telemetry dashboards we are dropping the metrics for which the batch age and batch duration values are negatives due to the device time manual modification or time zone change. 
=> RUM-1633 Drop batch telemetry where duration or age have negative values

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
Opened from [User property from future set on View Loads · Issue #1836 · DataDog/dd-sdk-android](https://github.com/DataDog/dd-sdk-android/issues/1836) 
As of now view has 3 states: active, stopped and complete. Stopped - view was stopped, because another view started or it was stopped explicitly, but it still exists in the scope hierarchy and will send view updates until all the child scopes are complete.
Imagine the following flow:
View A |--- Active ---|--- Stopped---|Complete
View B                |--- Active -------------....
Here we have View A which moves to the stopped state once View B starts.
Customer is using global RUM attributes, which are updated with the current screen name (or any attribute specific to the current active screen) on each screen transition.
Say on View B …
=> RUM-3012 Do not update RUM View global properties after the view is stopped

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/rum/error-schema.json
A more condensed version of #1853  the only adds the new error source types to the RUM schema
=> Add new error source types to RUM schema

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/Datadog.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/log/LogAttributes.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/ndk/internal/DatadogNdkCrashHandler.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/ndk/internal/DatadogNdkCrashHandlerTest.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumErrorSourceType.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashEventHandlerTest.kt
To properly symbolicate NDK crashes, we need to know that the provided stack trace is an NDK trace, instead of a standard Java stack trace. This changes it so that crashes caught by the NDK crash reporter report an `error.source_type` as "ndk" to both Logs and RUM.
Additionally, because certain platforms will want to override symbolication behavior, we provide a way to change the default native source type by using the `_dd.native_source_type` additional configuration option.
=> RUM-3150 Set source_type on native crashes to `ndk`

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelperTest.kt
If `applicationContext` is null when performing `createImageWireframe`, then log the view to telemetry and return null from the method
Fixes issue where a NPE crash was seen on `applicationContext`
=> RUM-3180: Avoid crash when applicationContext is null

detekt_custom.yml, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/ResourcesFeature.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/DataQueueHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/NoopDataQueueHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/ResourceRequestBodyFactory.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/ResourcesRequestFactory.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/EnrichedResource.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/ResourcesFeatureTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/ResourceRequestBodyFactoryTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/ResourcesRequestFactoryTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/EnrichedResourceTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessorTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt
Captures the bitmaps during traversal and writes them to batches
Third PR of the Resource endpoint 
=> RUM-2709: Implement resource capture during traversal

features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/DatadogEventBridge.kt, features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/DatadogEventBridgeTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebViewModel.kt
Following the updated bridge RFC, we implement `getCapabilities` to let the Browser SDK know which events are supported by the SDK.
=> RUM-3281 Implement webview bridge getCapabilities

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/log/LogAttributes.kt, features/dd-sdk-android-logs/api/apiSurface, features/dd-sdk-android-logs/api/dd-sdk-android-logs.api, features/dd-sdk-android-logs/src/main/json/log/log-schema.json, features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/internal/domain/DatadogLogGenerator.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/domain/DatadogLogGeneratorTest.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/domain/event/LogEventSerializerTest.kt
This will send `source_type` as a property on `error` when the attribute `_dd.error.source_type` is set on the log.
The `source_type` property is not being populated on logs. This isn't too big of an issue as symbolication will default back to `source`, but there are cases where we'll need the `source_type` to do proper symbolication.
=> feat: Add source_type when sent from cross platform logs

dd-sdk-android-core/src/main/kotlin/com/datadog/android/log/LogAttributes.kt
The log attribute for source type had a . instead of an _ which breaks the cross platform contract.
=> Fix typo in source type

CONTRIBUTING.md
📦 Adding a requirement for signing commits to `CONTRIBUTING.md`.
Counterpart to https://github.com/DataDog/dd-sdk-ios/pull/1709
To be specific in what we require for external contributions.
=> chore: Add signed commits requirement to CONTRIBUTING.md

features/dd-sdk-android-logs/api/apiSurface, features/dd-sdk-android-logs/api/dd-sdk-android-logs.api, features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/Logs.kt, features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt, features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/LogsTest.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt, instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt, reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/LoggerTest.kt
Add a `Logs.addAttribute` and `Logs.removeAttribute` function to add attributes to all logs generated by Loggers created from a specific Core.  Individual loggers and log events override global attributes.
These log attributes are also sent on unhandled exceptions and added to errors forwarded to RUM.
=> RUM-3068 Add support for global attributes on logs

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/log/LogAttributes.kt, features/dd-sdk-android-logs/api/apiSurface, features/dd-sdk-android-logs/api/dd-sdk-android-logs.api, features/dd-sdk-android-logs/src/main/json/log/log-schema.json, features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/internal/domain/DatadogLogGenerator.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/domain/DatadogLogGeneratorTest.kt, features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/LoggerTest.kt
This sets up attributes that are automatically transferred to the `Error` objects for Logs and RUM.
For logs, the attribute is  `LogAttributes.ERROR_FINGERPRINT` and sets the fingerprint in the `LogEvent.Error`.
For RUM, the attribute is `RumAttributes.ERROR_FINGERPRINT` and sets the fingerprint member in `ErrorEvent.Error`
Also fixes RUM-2209 by adding the `LogEvent.Error.fingerprint` member
=> RUM-2907 Allow setting custom error fingerprint

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/ThreadExt.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnable.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnableTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt
This PR adds reporting of all threads information for non-fatal ANRs, threads are reported in the same manner as it was done before for crashes (meaning name, state, stacktrace will be reported).
=> RUM-3523: Report all threads for non-fatal ANRs

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumConfiguration.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumConfigurationBuilderTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ConfigurationRumForgeryFactory.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
This PR disables non-fatal ANR reporting (the one which is using watchdog approach) by default for API 30+, but keeps it enabled on Android API 29 and below (because there is no fatal ANR reporting there).
Customer now has an opportunity to explicitly enable/disable it.
=> RUM-2879: Disable non-fatal ANR reporting by default

instrumented/integration/src/androidTest/assets/session_replay_payloads/consent_granted_sr_test_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_image_buttons_allow_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_image_buttons_mask_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_image_buttons_mask_user_input_payload.json, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/imagebuttons/SrImageButtonsAllowTest.kt
Following improvements provided by #1910, some background drawables that were captured as images are now captured as solid color, meaning our hardcoded expected values in integration tests needed to be updated to reflect that.
=> Fix integration tests post SR refactoring

features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt
https://github.com/DataDog/dd-sdk-android/pull/1918 was merged after https://github.com/DataDog/dd-sdk-android/pull/1919 and it turns out it has one `ktlint` violation.
=> Fix formatting

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
Small change to prevent `ConcurrentModificationException` which may happen when feature flags are read during `ErrorEvent` serialization on the worker thread.
=> Prevent `ConcurrentModificationException` when reading feature flags

features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/PendingTrace.java, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/OtelTracerProvider.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/domain/event/OtelDdSpanToSpanEventMapper.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/OtelTracerBuilderProviderTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/domain/event/OtelDdSpanToSpanEventMapperTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/CoreDDSpanForgeryFactory.kt
Following the new rules in APM Java project we will provide the right sampling priority based on the APM tracer configuration.
=> RUM-3516 Provide the correct sampling priority for our Span events based on APM new rules

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/BitmapCachesManager.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ImageCompression.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/MD5HashGenerator.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResolveResourceCallback.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceItemCreationHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolver.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolverCallback.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourcesSerializer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/WebPImageCompression.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/wrappers/CanvasWrapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageViewMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/BitmapCachesManagerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceItemCreationHandlerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolverTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourcesSerializerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/WebPImageCompressionTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt
The previous pr had unresolvable git conflicts so I've recreated the commits on a new branch. 
• Extract cache logic into BitmapCacheManager
• Rename ResourcesSerializer to ResourceResolver
• Move ResourceDataQueueItem insertion into the DataQueueHandler to a new ResourceItemCreationHandler
• Cleanup the callbacks so that all exit points from the ResourceResolver come from the same method
• Add telemetry/maintainer logging to failures in MD5 hash generation and webp compression
• Remove mimetype from the wireframe (no longer needed because resource endpoint requests already contain the content type)
Separate the refactor pr from the pr that removes the feature flag, to make it easier to review
- [ ] Make sure you discussed the feature or bugfix …
=> RUM-2708: Refactor and split classes

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
Fixes https://github.com/DataDog/dd-sdk-android/issues/1899.
The change in https://github.com/DataDog/dd-sdk-android/pull/1832 broke the application startup time measurement (which was bound to the first RUM event before), because with this change application startup time was dependent on the SDK init moment, which is not the correct way to measure it.
This change brings old behaviour back by ignoring SDK init event.
=> RUM-3430: Fix application startup time regression

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt
This changes the RUM error event mapper to call the user supplied mapper even for crashes, which it previously excluded.
The error event mapper still does not support discarding fatal errors, and a warning is sent if the user returns null for a fatal error in the mapper.
=> RUM-2207 Call RUM error mapper even for crashes

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/wrappers/CanvasWrapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/wrappers/CanvasWrapperTest.kt
This PR adds several checks to ensure the bitmap can be used in a canvas.
Fixes #1952
=> RUMM-3774 prevent crash in Canvas Wrapper

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/ActivityLifecycleTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt
It seems that on old Androids (Android 7 and below) calling `Intent#getExtras` sometimes may throw different non-documented exceptions.
This PR creates a safe wrapper around this call.
=> Safe getting of Intent extras

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentGrantedSrTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/imagebuttons/SrImageButtonsAllowTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/imagebuttons/SrImageButtonsMaskTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/imagebuttons/SrImageButtonsMaskUserInputTest.kt
This changes disables flaky Session Replay test and also puts `@Test` annotations back (they don't need to be removed when adding `@Ignore` annotation).
=> Disable flaky Session Replay test

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/DatadogCore.kt, detekt_custom.yml
Otherwise it is possible to have a memory leak when SDK instance is stopped, because reference to the SDK instance still exists through the hook runnable.
=> Remove Runtime shutdown hook when SDK instance is stopped

features/dd-sdk-android-trace/api/dd-sdk-android-trace.api, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/CoreTracer.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/DDSpan.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/PendingTrace.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/PendingTraceBuffer.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/scopemanager/AbstractContinuation.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/scopemanager/ConcurrentContinuation.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/scopemanager/ContinuableScope.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/scopemanager/ContinuableScopeManager.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/scopemanager/ContinuingScope.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/scopemanager/ScopeStack.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/scopemanager/SingleContinuation.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/logger/DatadogCoreTracerLogger.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/logger/ILoggerFactory.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/logger/Logger.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/logger/LoggerFactory.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/logger/NoOpLogger.java, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/OtelTracerProvider.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/OtelTracerBuilderProviderTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/trace/core/CoreTracerTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/trace/core/DDCoreSpecification.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/trace/core/PendingTraceBufferTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/trace/core/PendingTraceTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/trace/logger/DatadogCoreTracerLoggerTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/trace/logger/LoggerFactoryTest.kt
=> RUM-3405 Provide core tracer logger implementation

tools/detekt/src/test/kotlin/com/datadog/tools/detekt/rules/sdk/TodoWithoutTaskTest.kt
Regex `[A-Z]+-\\d{1,8}` may generate something like `ABC-0` because of the `d{1,8}`, and this will fail some tests, because 0 as a task number is not allowed.
This PR fixes that.
Note: In theory it is possible to have  something like `ABC-012`, but generating `012` and avoiding to have all zeros at the same time requires using matching groups/negative lookaheads, which is not supported by `Forge`.
=> Fix flaky `TodoWithoutTask` tests

dd-sdk-android-core/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnable.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnableTest.kt
It seems sometimes it is possible to have result of `Thread.getAllStackTraces()` without the thread impacted by ANR/crashing thread info (or without attached stacktrace, not sure here). It is not clear why it happens, but we clearly can see such issues in the dashboard, when `error.stack` is not found among `error.threads` reported (meaning `error.threads` doesn't have thread for which we reporting `error.stack`).
This change fixes that by making sure ANR thread/crashing thread is always in the `error.threads` - we will always add it to the list, not relying on the match among `Thread.getAllStackTraces()` results. …
=> RUM-3757: Make sure `error.threads` always have content from `error.stack`

.github/workflows/codeql-analysis.yml
This PR updates actions for running CodeQL workflow to address the following warnings (see, for example, [here](https://github.com/DataDog/dd-sdk-android/actions/runs/8539857178)):
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-java@v1, github/codeql-action/init@v2, gradle/gradle-build-action@v2.4.2, github/codeql-action/analyze@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-java@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> CodeQL …
=> Update actions for running CodeQL workflow

detekt_custom.yml, features/dd-sdk-android-trace/api/apiSurface, features/dd-sdk-android-trace/api/dd-sdk-android-trace.api, features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelTracer.java, features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelTracerBuilder.java, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/AndroidTracer.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/OtelTracerProvider.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/OtelTracerBuilderProviderTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentelemetry/trace/OtelTracerTest.kt
=> RUM-3249 Provide the bundleWithRum capability for OtelTracer

detekt_custom.yml, features/dd-sdk-android-trace/api/dd-sdk-android-trace.api, features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelSpan.java, features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelSpanBuilder.java, features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelTracer.java, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/OtelTracerProvider.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/TracingFeature.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/opentelemetry/DatadogContextStorage.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/opentelemetry/OtelContext.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/opentelemetry/OtelScope.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/TracingFeatureTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/opentelemetry/DatadogContextStorageTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/opentelemetry/OtelContextTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/opentelemetry/OtelScopeTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentelemetry/trace/OtelSpanTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/OtelTracesFragment.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/OtelTracesViewModel.kt, sample/kotlin/src/main/res/layout/fragment_otel_traces.xml, sample/kotlin/src/main/res/values/strings.xml
In this PR we are providing our own implementation of https://github.com/open-telemetry/opentelemetryjava/blob/main/context/src/main/java/io/opentelemetry/context/ContextStorage.java
interface which wraps inside the default one in order to be able to provide our own implementation of `Context` -> `OtelContext`. 
The main reason for this update was to be able to tight the Opentelemetry Scopes to the `CoreTracer` ones.
See more here how you can create a `Scope` in Opentelemetry: 
https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/ContextStorage.java
- …
=> RUM-3836 Provide the DatadogContextStorage for Opentelemetry

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListenerTest.kt
Fixes #1976
In Android N (until Android P included), the internal [View. findFrameMetricsObserver()](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/nougat-release/core/java/android/view/View.java#5584) method did not check the nullability of the `mFrameMetricsObservers` field, leading to possible NPE when trying to remove a listener that wasn't yet added.
Some customer have seen a crash with an NPE thrown from the Android [View](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/nougat-release/core/java/android/view/View.java) when removing the `FrameMetricsListener` via the `JankStats` library. 
Even though all versions of the official Android View are written in a way that NPE should never happen, those crash still occurred.
=> RUM-3992 Prevent crash in JankStats listener

.gitlab-ci.yml, Dockerfile.gitlab, gradle/libs.versions.toml, tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/sdk/UnsafeThirdPartyFunctionCall.kt, tools/detekt/src/test/kotlin/com/datadog/tools/detekt/rules/pyramid/ApiSurfaceTest.kt, tools/detekt/src/test/kotlin/com/datadog/tools/detekt/rules/sdk/TodoWithoutTaskTest.kt, tools/detekt/src/test/kotlin/com/datadog/tools/detekt/rules/sdk/UnsafeThirdPartyFunctionCallTest.kt
I noticed some Kotlin 1.7 artifacts downloaded for the test classpath and they were coming from Detekt 1.22.0.
This PR updates Detekt to 1.23.0 to be better aligned with the version we use for the checks (1.23.4) and to stop Kotlin 1.7 artifacts being downloaded.
Detekt 1.23.4 is not used because it will bring Kotlin 1.9, this is not what we want.
Detekt changelog is [here](https://github.com/detekt/detekt/releases).
=> Update Detekt API version used to 1.23.0

tools/detekt/src/test/kotlin/com/datadog/tools/detekt/rules/sdk/UnsafeThirdPartyFunctionCallTest.kt
These usages were added in https://github.com/DataDog/dd-sdk-android/pull/1996. This PR fixes that.
=> Remove the usage of deprecated `TestConfig` constructor

reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/otel/OtelTraceConfigurationTest.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/otel/OtelTracerProviderTest.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/otel/SpanExt.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/otel/TracerExt.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/tests/assertj/SpansPayloadAssert.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/tests/utils/BlockingWriterWrapper.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/OtelTracesFragment.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/OtelTracesViewModel.kt, sample/kotlin/src/main/res/layout/fragment_otel_traces.xml, sample/kotlin/src/main/res/values/strings.xml
=> RUM-3389 Add the Otel API feature integration tests

.gitlab-ci.yml
Redirects existing slack notif to the `#mobile-sdk-ops` channel, and add notification on develop branch CI jobs
=> Redirect slack notif to mobile-sdk-ops channel

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/src/main/kotlin/com/datadog/android/DatadogSite.kt
Constructors of `DatadogSite` shouldn't be public.
This may be see as a breaking change (removing items from public API), but this was never intended to be public.
=> Make constructors of `DatadogSite` private

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
This fixes a bug where we forgot to unregister the vital listeners. This lead to two issues: 
- we created a memory leak, with listeners references being kept in the monitor and never cleaned up
- when a view would wait for event to finish and send its last update, vital value could be skewed because of what happened afterwards. 
Fixes #2008
=> RUM-4821 unregister vital listeners when view is stopped

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/DatadogCore.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt
It is possible to have a crash like that:
```
java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:792)
at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
at com.datadog.android.core.DatadogCore.updateFeatureContext(SourceFile:65)
at com.datadog.android.rum.internal.domain.scope.RumViewScope.<init>(SourceFile:21)
at com.datadog.android.rum.internal.domain.scope.RumViewScope.<init>(SourceFile:31)
at com.datadog.android.rum.internal.domain.scope.RumViewManagerScope.handleEvent(SourceFile:620)
at com.datadog.android.rum.internal.domain.scope.RumSessionScope.handleEvent(SourceFile:246)
at …
```
=> RUM-4329: Fix `ConcurrentModificationException` during features iteration

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadStatus.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadStatusTest.kt
This change aims to help in investigation of #2013: it will be handy to have HTTP status code logged in the user-facing message in case of `UnknownError` during batch upload.
=> RUM-4359: Add status code in user-facing message in case of `UnknownError` during batch upload

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/constraints/DatadogDataConstraints.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/constraints/DatadogDataConstraintsTest.kt
This PR addresses issue #1018: with SDK v2 functionality we can now log a particular message only once. This is useful to avoid logcat spamming.
=> RUM-4358: Log warning about tag modification only once

detekt_custom.yml, features/dd-sdk-android-session-replay-material/build.gradle.kts, features/dd-sdk-android-session-replay-material/consumer-rules.pro, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/consumer-rules.pro, features/dd-sdk-android-session-replay/src/main/kotlin/androidx/appcompat/widget/ActionBarContainerDrawableAccessor.kt, features/dd-sdk-android-session-replay/src/main/kotlin/androidx/appcompat/widget/DatadogActionBarContainerAccessor.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TraversalStrategy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ActionBarContainerMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseViewGroupMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ViewWireframeMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ActionBarContainerMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ViewWireframeMapperTest.kt
This PR allows sessin replay to capture the content of a Toolbar. 
- it let's the default mapping handle all the toolbar's children
- it capture's the `ActionBarContainer`'s background
=> RUM-4148 Add support to the Toolbar in Session Replay

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/SdkInternalLogger.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/SdkInternalLoggerTest.kt, features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/telemetry/_common-schema.json, features/dd-sdk-android-rum/src/main/json/telemetry/configuration-schema.json, features/dd-sdk-android-rum/src/main/json/telemetry/error-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/Telemetry.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryErrorEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryTest.kt
This PR adds support for the `additionalProperties` for the `TelemetryErrorEvent`. They are already supported in `TelemetryDebugEvent`, but were missing for the errors.
Code is updated to propagate these additional properties to the telemetry.
=> RUM-4369: Support additional properties in Telemetry Error events

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/feature/Feature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
In order to better read the performance of the Image Resource upload for Session Replay, we add the telemetry on batch deleted/closed/expired with a dedicated track name.
=> RUM-4413 Add telemetry on SR resources track

features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SeekBarWireframeMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/AbstractWireframeMapperTest.kt
Fix some flaky tests: the tests didn't take into account the fact that the progress computation would change for Android O or legacy APIs
=> Fix SR flaky test

gradle/libs.versions.toml, reliability/single-fit/trace/build.gradle.kts, sample/kotlin/build.gradle.kts
We are enabling desugaring for the sample and single-fit apps as they are the ones using the newly introduced `dd-sdk-android-trace-otel` module.
=> RUM-4501 Enable desugaring for sample and single-fit apps

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/InternalLogger.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/feature/FeatureScope.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/feature/FeatureScopeExt.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/logger/SdkInternalLogger.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/MethodCalledTelemetry.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/metrics/PerformanceMetric.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/logger/SdkInternalLoggerTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/MethodCalledTelemetryTest.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, features/dd-sdk-android-session-replay/consumer-rules.pro, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/DefaultOnDrawListenerProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/OnDrawListenerProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewOnDrawInterceptor.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewOnDrawInterceptorTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListenerTest.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubInternalLogger.kt
Update the MethodCall metric code to allow multiple usage with different operation names + cleanup some SR code
=> Update the Method Call metric usage

features/dd-sdk-android-session-replay/consumer-rules.pro, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt
Our previous mechanism of copying a drawable's content was performed on the main thread. 
When starting an app, this would create a lot of main thread task to run. And any new image would also take some of the main thread time, creating a lot of jank frames in any non hello world app. 
This will fix the performance issue some of our customers started to notice when enabling SR.
=> RUM-4561 Delegate Drawable copy to background thread

features/dd-sdk-android-session-replay/consumer-rules.pro, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueItem.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt
Add more details in the telemetry for it to be actionnable
=> Improve telemetry from RecordedDataQueueHandler

CHANGELOG.md, features/dd-sdk-android-session-replay/consumer-rules.pro, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt
Cherry-pick the perf improvements from #2048
=> RUM-4561 Cherry pick Drawable Performance improvements

CHANGELOG.md
This PR merges `release/2.10.0` branch into `develop` branch with all the conflicts resolved.
=> Merge `release/2.10.0` branch into `develop` branch

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ProgressBarWireframeMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SeekBarWireframeMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ProgressBarWireframeMapperTest.kt
Add progress bar mapper to track those
=> RUM-4514 add support for progress bars

sample/kotlin/proguard-rules.pro, sample/wear/build.gradle.kts, sample/wear/proguard-rules.pro, sample/wear/src/main/java/com/datadog/android/wear/sample/MainActivity.kt, sample/wear/src/main/java/com/datadog/android/wear/sample/WearApplication.kt
=> RUM-4507 Add OpenTelemetry use case into the Wear sample app

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ButtonMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ButtonMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ButtonMapperAllowTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ButtonMapperMaskInputTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ButtonMapperMaskTest.kt
Improve the ButtonMapper by letting it extend TextViewMapper, and add more exhaustive and cleaner tests
=> RUM-4719 Improve ButtonMapper

integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/internal/otel/TraceContextExtTest.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/otel/OtelTracerProviderTest.kt
=> RUM-4894 Fix the CoreTracer flaky tests

features/dd-sdk-android-trace-otel/api/apiSurface, features/dd-sdk-android-trace-otel/api/dd-sdk-android-trace-otel.api, features/dd-sdk-android-trace-otel/src/main/kotlin/com/datadog/android/trace/opentelemetry/OtelTracerProvider.kt, features/dd-sdk-android-trace-otel/src/test/kotlin/com/datadog/android/trace/opentelemetry/OtelTracerBuilderProviderTest.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/otel/OtelTracerProviderTest.kt
=> OtelTraceProvider.Builder introduce the trace rate limit property

detekt_custom.yml, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetric.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcher.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionMetricDispatcher.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/FakeInternalLogger.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/RumSessionEndedMetricTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcherTest.kt
* [ADD] Add `SessionEndedMetric` class to record the 
* [ADD] SessionEndedMetricDispatcher to coordinates multiple `SessionEndedMetric` and send telemetry when session is ended
Ticket: https://datadoghq.atlassian.net/browse/RUM-1662
This is the first step of this task, only implementation of two classes with unit test assuring that the data structure and json format matches the specification. In next PR, these two classes will be used inside `RumSessionScope` or `RumApplicatioScope` to track the session.
=> RUM-1662: Create SessionEndedMetric and SessionEndedMetricDispatcher with unit test

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/metrics/MethodCallSamplingRate.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/DefaultOnDrawListenerProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversalTest.kt
Have more granular telemetry sampling for mappers, using three levels - default, reduced and rare, with each level reducing the number of events by a factor of 10.
At the moment the default sampling rate is producing far too many events for some mappers.
=> RUM-4879: Granular telemetry sampling for mappers

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/Rum.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetric.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcher.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/RumSessionEndedIntegrationTelemetryTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/tests/assertj/TelemetryMetricAssert.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubInternalLogger.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubSDKCore.kt
* Integration of `SessionEndedMetricDispatcher` into core of SDK
* Add integration tests to test "was_stopped" and view counts can be calculate correctly
https://datadoghq.atlassian.net/browse/RUM-1662
* the way of tracking sdk error is modified, the session Id retrieved inside TelmetryEventHandler is always `NULL_UUID`, so now it relies on the last session id in `SessionEndedMetricDispatcher`
* `StubInternalLogger` is updated to send the event when `logMetric` is called, so that in integration test the event can be intercepted.
=> RUM-1662: Integration of SessionEndedMetric into sdk core

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/rum/resource-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/resource/RumResourceInputStream.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/resource/RumResourceInputStreamTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/security/EncryptionTest.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutTracesTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/ManualTrackingRumTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/RumConfigurationTest.kt
Add the `upload_size` to RUM Resources (among other to track the `POST` OkHttp requests)
> [!NOTE]
=> RUM-4822 Report upload_size for RUM Resources

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/GzipRequestInterceptor.kt, detekt_custom.yml
Ensure gzipped requests report their actual content length and not -1
> [!NOTE]
=> RUM-4822 Let GZipped requests report an accurate upoad size

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetric.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcher.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionMetricDispatcher.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/RumSessionEndedMetricTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcherTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/RumSessionEndedIntegrationTelemetryTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/tests/assertj/TelemetryMetricAssert.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubSDKCore.kt
Add following attributes into "Rum Session Ended Metric"
```
“rse” : {
“views_count”: { 
“with_has_replay”: <int>,
},
“no_view_events_count”: { “actions”: <int>, “resources”: <int>, “errors”: <int>, “long_tasks”: <int> },
“has_background_events_tracking_enabled”: <bool>,
“ntp_offset”: { “at_start”: <int>, “at_end”: <int> }
}
}
```
As Required in RUM-4592
* Following attribute is not added on Android,
```
“by_instrumentation”: { “<instrumentation type>”: <int> },
```
* Long task count is skipped in integration test since it's not possible to simulate with unit test env.
=> RUM-4592: Add diagnostic attributes to "RUM Session Ended" metric

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/ConnectionPoolInfo.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploader.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumResourceAttributesProvider.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
Adds a way for our customer to know the number of connections used by the internal OkHttpClient
> [!NOTE]
=> RUM-4822 Allow monitoring internal connection pool

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt
We're sending ns instead of ms in the error msg for dropped nodes, but still write "ms" in the message itself. This pr fixes the units in the message. 
Wrong units in the dropped nodes error.
=> RUM-5077: Fix units for dropped nodes

.gitlab-ci.yml, build.gradle.kts, buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/CheckTransitiveDependenciesTask.kt, buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/GenerateTransitiveDependenciesTask.kt, buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/TransitiveDependenciesPlugin.kt, integrations/dd-sdk-android-okhttp-otel/transitiveDependencies
Some dependency changes were not committed meaning that locally the `transitiveDependencies` for the `dd-sdk-android-okhttp-otel` is changed all the time in unrelated commits.
=> Update our CI around Generated files

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/InternalLogger.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/logger/SdkInternalLogger.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/MethodCalledTelemetry.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/metrics/MethodCallSamplingRate.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/logger/SdkInternalLoggerTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/MethodCalledTelemetryTest.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcher.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/FakeInternalLogger.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubInternalLogger.kt
> [!NOTE]
> This metric will be applied in addition to the telemetry sampling rate, so if a logMetric is created with a sampling rate of 10%, with the global telemetry sampling rate being sampled at 20%, it has a 2% chance of being kept.
=> Add sampling rate to internal metrics

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/storage/datastore/DataStoreHandler.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/datastore/DataStoreFileHandler.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/datastore/DataStoreFileHelper.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/datastore/DatastoreFileWriter.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/datastore/NoOpDataStoreHandler.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/FileExt.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/file/datastore/DataStoreFileWriterTest.kt
Adds an api to delete all saved datastore entries. 
The core's clearAllData api should return the sdk to a fresh state and therefore requires removal of datastore information.
=> RUM-4098: Add api to clear all datastore data

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt
Uses the BackpressureExecutor for session replay event processing. 
The session replay event loop can experience backpressure, especially in applications with an endless feed.
=> RUM-3741: Use BackpressureExecutor for SessionReplay event processing

detekt_custom.yml, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableTextViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableWireframeMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseSwitchCompatMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapperTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/DropDownSwitchersFragment.kt, sample/kotlin/src/main/res/layout/fragment_drop_down_switchers_components.xml, sample/kotlin/src/main/res/values/strings.xml
Improve the `SwitchCompatMapper` to make `SwitchCompat` have similar replay with the real UI.
* Same as previous PR, the `SwitchCompatMapper` doesn't create `ShapeWireframe` any more for checked or unchecked state, instead, we extract the track drawable and thumb drawable to show the real graphic of the component.
* Sample application is updated to demonstrate more state of switch buttons 
* RUM-4715
https://mobile-integration.datadoghq.com/rum/replay/sessions/128703cf-1202-45c6-a34a-8a8a2df7275d?applicationId=38030dde-f9f9-4e52-9443-b9804a030080&seed=bd9e3c7b-fbbf-4a75-89b7-a323624f0cd2&ts=1719931750249
Since the new implementation of `SwitchCompatMapper` create `ImageWireframe` other than `ShapeWireframe`, some overhead is in the …
=> RUM-4715:SwitchCompat mapper improvement

build.gradle.kts, buildSrc/build.gradle.kts, gradle/libs.versions.toml
Tiny change: Nexus publishing plugin actually shouldn't be in the `buildSrc` classpath and so we can move it out and use it via plugin reference.
=> Remove Nexus publishing plugin from buildSrc

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/ComposeWireframeMapper.kt
Adds MethodCall telemetry for compose mapper, so that we can know the duration of each compose mapper execution.
RUM-4731
=> RUM-4731: Add MethodCall telemetry for compose mapper

detekt_custom.yml, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/data/UiContext.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/ButtonCompositionGroupMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/ComposeWireframeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/TextCompositionGroupMapper.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/AbstractCompositionGroupMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/TextCompositionGroupMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/test/elmyr/UIContextForgeryFactory.kt, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/obfuscator/StringObfuscator.kt
Apply the privacy settings to `TextCompositionGroupMapper` for compose, the text masking strategy keeps same as `TextViewMapper` in Android View
* RUM-3634
| USER_INPUT | MASK | 
|---|---|
|https://mobile-integration.datadoghq.com/rum/replay/sessions/e55f5ad0-145d-4c2c-bc5b-1c4bbcd35ba9?applicationId=38030dde-f9f9-4e52-9443-b9804a030080&seed=70a2b95d-ba66-4083-ad43-81134787c57b&ts=1720118965911 | https://mobile-integration.datadoghq.com/rum/replay/sessions/5b0a74de-9928-4fb6-a273-e5d2a4f7ded3?applicationId=38030dde-f9f9-4e52-9443-b9804a030080&seed=49b1537e-3107-4da9-b7a6-49c24ed46145&ts=1720119348991|
* `StringObfuscator` is changed from `internal` class to `@InternalApi`, so the class can be shared between module.
- [ ] Make sure you discussed the feature or bugfix with the maintaining …
=> RUM-3634: Apply privacy settings to TextCompositionGroupMapper for compose

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/RotatingDnsResolver.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/RotatingDnsResolverTest.kt, detekt_custom.yml
In this PR we are fixing the race condition problem that was caused by a concurrent access to an unprotected list in the `RotatingDnsResolver` class. This was raised by the Support team in this ticket: https://datadog.zendesk.com/agent/tickets/1761693
=> RUM-5447 Fix the racing condition in the RotatingDnsResolver logic

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedNetworkRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/resource/ResourceId.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/resource/ResourceIdTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tests/elmyr/ResourceIdForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/Configurator.kt, integrations/dd-sdk-android-okhttp/build.gradle.kts, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogEventListener.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/internal/rum/RequestExt.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogEventListenerFactoryTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogEventListenerTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutTracesTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/test/elmyr/OkHttpIntegrationForgeConfigurator.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/test/elmyr/ResourceIdForgeryFactory.kt
This PR adds a better way to track OkHttp requests as resources avoiding key collisions. Our keys used to only take into account the url, now we generate a UUID attached to the request to have a more accurate resource representation.
=> RUM-648 Add request id in okhttp request

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/ImagePrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseCheckableTextViewMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelperTest.kt
Changes MASK_CONTENT to MASK_LARGE_ONLY, to make the ImagePrivacy api clearer about what is actually happening.
Clearer api for the users.
=> RUM-5524: Make ImagePrivacy clearer

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt
There are some ideas for renaming the masking levels in fine grained masking. Until we have this finalized, we shouldn't expose setImagePrivacy as a public api, since if we decide to change the values again after releasing the feature we'll have an issue. Therefore, temporarily, I want to make this api internal. This will also give us an opportunity to perform more rigorous performance testing of the implications of recording all images.
=> Make setImagePrivacy internal temporarily

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploader.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadStatus.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploaderTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadStatusTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/DNSErrorStatusForgeryFactory.kt
When a DNS issue prevents the SDK from reaching our intake hosts, we increase the delay to avoid an infinite loop. 
By default our retry loop can be quite frequent, but DNS issues often take some time to be fixed. Although an actual issue in our DNS registration is unlikely, there seems to also be some issues on some networks preventing the devices from resolving the intake host address. 
Relates to #2131
=> RUM-5564 increase retry delay on DNS error

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt
Reduce the amount we send batch telemetry rate to 10% of it's original value.
=> [RUM-4986] Decrease Batch Metrics sample rate by 10%

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelperTest.kt
Fixes a regression of session replay while image placeholder doesn't have the correct position and bounds.
in this [PR](https://github.com/DataDog/dd-sdk-android/commit/1f40138d99a4593a5ba412fa1892ee9d9ab6cac8#diff-f77bd930d8d3012f1393ff8ed0db17f7aa1f67d69e487f31feffeb0ec87d85eaL215), placeholder is using the content image bounds instead of image view bounds, which make the placeholder go beyond the image view.
rollback the related function to the version prior to this PR
here is the screenshot after the fix:
Session replay link:
https://mobile-integration.datadoghq.com/rum/replay/sessions/dc4868a1-f572-4c66-b598-e140f777f126?applicationId=8e378128-92c4-433c-bfce-0957f8abee1a&seed=a9049579-5c24-47b6-b15c-856b3317dd02&ts=1722252089784
Issue found before the sdk release:
Anything else we …
=> Fix content placeholder wireframe using wrong image bound

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelperTest.kt
=> Merge develop into release 2 12 0

tools/benchmark/src/main/java/com/datadog/benchmark/DatadogMeter.kt, tools/benchmark/src/main/java/com/datadog/benchmark/exporter/DatadogMetricExporter.kt, tools/benchmark/src/main/java/com/datadog/benchmark/exporter/LogsMetricExporter.kt, tools/benchmark/src/main/java/com/datadog/benchmark/ext/FileExt.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/DatadogMetricProfiler.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/reader/CPUVitalReader.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/reader/FpsVitalReader.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/reader/MemoryVitalReader.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/reader/VitalReader.kt, tools/benchmark/src/main/java/com/datadog/benchmark/noop/NoOpObservableDoubleGauge.kt, tools/benchmark/src/main/java/com/datadog/benchmark/noop/NoOpObservableLongGauge.kt, tools/benchmark/src/test/java/internal/CPUVitalReaderTest.kt, tools/benchmark/src/test/java/internal/MemoryVitalReaderTest.kt
Add DatadogMeter to read vital data for benchmark.
With this commit, the sample application can activate the `DatadogMeter` by adding this:
```
val datadogExporterConfiguration = com.datadog.benchmark.DatadogExporterConfiguration
.Builder(apiKey = "xxxxxx")
.setApplicationName("Sample Application")
.setApplicationId(BuildConfig.APPLICATION_ID)
.setApplicationVersion(BuildConfig.VERSION_NAME)
.setIntervalInSeconds(20L)
.setRun("baseline")
.build()
val meter = DatadogMeter.create(datadogExporterConfiguration)
meter.startGauges()
meter.stopGauges()
```
RUM-5553
Some vital readers classes and unit tests are copied from feature modules for following reasons:
* This module should depend or use as less as possible the functionalities from SDK to get better result.
* We might have different …
=> RUM-5553: Add DatadogMeter to read vital data for benchmark

.gitlab-ci.yml, buildSrc/build.gradle.kts, gradle.properties
Adds instrumented test support to our Gitlab CI pipeline
=> RUM-483 use macos runner

tools/benchmark/src/main/java/com/datadog/benchmark/DatadogExporterConfiguration.kt, tools/benchmark/src/main/java/com/datadog/benchmark/DatadogMeter.kt, tools/benchmark/src/main/java/com/datadog/benchmark/exporter/DatadogMetricExporter.kt, tools/benchmark/src/main/java/com/datadog/benchmark/exporter/LogsMetricExporter.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/MetricRequestBodyBuilder.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/model/MetricContext.kt, tools/benchmark/src/test/java/forge/MetricContextForgeryFactory.kt, tools/benchmark/src/test/java/internal/MetricRequestBodyBuilderTest.kt
Add "scenario" attribute in metrics payload.
According to the RFC of benchmark, we should have "scenario" in tags of metrics to indicate which scenario the benchmark is running with.
=> Add scenario attribute in benchmark metrics

README.md
This PR fixes a broken link to the Android SDK troubleshooting documentation.
Fixes issue:  #2163 
I was working through setting up a mobile device using the SDK and ran into issues. I clicked the link for troubleshooting assistance, and was met with a 404 error.
=> [#2163] Update link to troubleshooting documentation

sample/benchmark/src/main/java/com/datadog/benchmark/sample/BenchmarkApplication.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/MainActivity.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/benchmark/DatadogBenchmark.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/benchmark/SyntheticsRun.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/benchmark/SyntheticsScenario.kt
Add `DatadogBenchmark` class to be able to parse the Synthethics variables in order to control the benchmark test scenario.
1. define two local variables in synthetics test
2. define Optional Intent Arguments by using the local variables
3.On the app side, the class is able to parse the parameters in bundle, to switch the scenario in the code.
RUM-5550
=> RUM-5550: Parse synthetics variables to control benchmark test scenario

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/AbstractCompositionGroupMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/ComposeWireframeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/TabCompositionGroupMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/TabRowCompositionGroupMapper.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/AbstractCompositionGroupMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/TabCompositionGroupMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/TabRowCompositionGroupMapperTest.kt
Add "Tab" and "TabRow" Composable groups mappers, so that "Tab" & "TabRow" can have:
* correct position in SR
* correct color in SR
* correct size in SR
RUM-4738
(The other components in the screen is a bit glitchy, but `Tab` and `TabRow` is working)
https://mobile-integration.datadoghq.com/rum/replay/sessions/0d175d4a-4087-4cc9-8abc-fe22ee7d3c0e?applicationId=38030dde-f9f9-4e52-9443-b9804a030080&seed=e05a16d0-ea37-4f5b-b4fd-2ff7f27fe3fb&ts=1723037890870
=> RUM-4738: Add "Tab" and "TabRow" Composable groups mappers

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/DatadogCore.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt
=> Reset developerMode status when Datadog stop

.gitlab-ci.yml
Small improvement to the Gitlab CI file: common calls to pull credentials are extracted into a dedicated snippet.
=> Extract logic to pull publishing credentials into a dedicated snippet

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/receiver/ThreadSafeReceiver.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/receiver/ThreadSafeReceiverTest.kt
This issue was reported by a customer. Their security check tool detected this issue in our SDK where we do not register a receiver with NO_EXPORT_FLAG in API 33 to 26. This method actually exists also below API 33 up to API 26 but the flag Context.NO_EXPORT_FLAG was not available so that's the reason we skipped it. 
I chose not to use the `ContextCompat.NO_EXPORT_FLAG` just to not have to introduce this new dependency just for this case and added a `0x4` local flag myself (same value as the one in Context and ContextCompat). The worse thing it could happen is that this flag to change later but I checked and the SDK is not crashing it is just ignoring it. On the other side if the flag value (logic will change under the hood) we might end up with a different access rights for this receiver …
=> RUM-5750 Use NO_EXPORT_FLAG for BroadcastReceiver on API above 26

.gitlab-ci.yml
macOS runners are not using Docker, so `image` property is meaningless.
=> Remove image property from macOS-based jobs

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/CheckApiSurfaceTask.kt, buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/CheckTransitiveDependenciesTask.kt, dd-sdk-android-core/transitiveDependencies, features/dd-sdk-android-ndk/transitiveDependencies, features/dd-sdk-android-rum/transitiveDependencies, features/dd-sdk-android-session-replay/transitiveDependencies, gradle/libs.versions.toml, integrations/dd-sdk-android-coil/transitiveDependencies, integrations/dd-sdk-android-fresco/transitiveDependencies, integrations/dd-sdk-android-glide/transitiveDependencies, integrations/dd-sdk-android-okhttp-otel/transitiveDependencies, integrations/dd-sdk-android-okhttp/transitiveDependencies, integrations/dd-sdk-android-rx/transitiveDependencies, integrations/dd-sdk-android-sqldelight/transitiveDependencies
This PR updates OkHttp version to 4.12.0, changelog is here https://square.github.io/okhttp/changelogs/changelog_4x/
=> Update OkHttp to 4.12.0

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/GlobalRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/GlobalRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt
Fixes https://github.com/DataDog/dd-sdk-android/issues/2183. 
https://github.com/DataDog/dd-sdk-android/pull/2126 introduced some changes and now we need to have an instance of `AdvancedRumMonitor` for OkHttp instrumentation.
=> RUM-5830: Make no-op RUM monitor implementation returned by default to be `NoOpAdvancedRumMonitor`

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/ComposeWireframeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/SurfaceCompositionGroupMapper.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/SurfaceCompositionGroupMapperTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/JetpackComposeActivity.kt
* Convert `TabRowCompositionGroupMapper` to `SurfaceCompoitionGroupMapper`, because the way it maps the wireframe can be reused in a lot of Jetpack compose container components such as BottomNavigation, TopAppBar, TabRow.
RUM-5780
=> RUM-5780:Use SurfaceCompoitionGroupMapper to support container components in SR

features/dd-sdk-android-trace/src/test/kotlin/com/datadog/trace/api/IdGenerationStrategyTest.kt
`M generate id with strategyName and tIdSize bits` test was taking almost 1 minute to run on my machine (takes even more on CI), so speeding it up by lowering down the number of trace IDs being generated.
=> Speed up `IdGenerationStrategy` test

reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/InternalSdkCoreContextTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/SdkCoreContextTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/utils/ConfigurationExt.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/utils/MutableMapExt.kt, reliability/core-it/src/main/assets/datadog.buildId
=> RUM-5527 Add integration tests for internal sdk core

sample/kotlin/src/main/AndroidManifest.xml, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/DimensionExt.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/JetpackComposeActivity.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/LegacyComposeActivity.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/SampleSelectionScreen.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/TypographySample.kt, sample/kotlin/src/main/res/values/themes.xml
* Add a selection screen for Jetpack Compose session replay
* Add a Typography screen to demo the text as Jetpack Compose
* Move to the current demo screen to `LegacyActivity`.
Prepare to demonstrate the Jetpack compose session replay improvement on text mapper.
| selection screen | typography screen|
| ----- | ----- |
|![Screenshot_20240813_133607](https://github.com/user-attachments/assets/3ecd9ad2-3b35-4fc9-85df-c78b27940036)|![Screenshot_20240813_133626](https://github.com/user-attachments/assets/1336337f-e288-413d-863c-74cd3142607a)|
=> Add Typography screen in sample application for Jetpack Compose SR

build.gradle.kts, gradle/libs.versions.toml
`generated-files-check` job takes 30+ minutes on the CI ([link](https://gitlab.ddbuild.io/DataDog/dd-sdk-android/-/jobs/602898072)). It is essentially a gradle task `checkGeneratedFiles` in our case which runs licenses check, API surface check and transitive dependencies check. The main bottleneck is the task to check licenses.
With https://github.com/DataDog/gradle-dependency-license-plugin/pull/19 merged and released the job now takes only 8 minutes, so it is 4 times faster.
It is essentially possible to improve the change in the PR mentioned above by sharing the cache between the projects, but the current gain is already good enough for our needs (Detekt run with custom rules in the same stage takes 7+ minutes).
- [ ] Make sure you discussed the feature or bugfix with the maintaining …
=> RUM-5831: Speed up generated files/licenses checks

.gitlab-ci.yml
It doesn't work with Android below 23, giving `Error: Unknown option: -g` and resulting in the installation failure.
=> Use adb install `-g` flag only for Android API above 23

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryConfigurationEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/SessionReplayConfigurationForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
• Adds apis to manually start and stop session replay
SessionReplay.stopRecording()
SessionReplay.startRecording
• Adds an option to SessionReplayConfiguration so that users can choose to not start recording automatically
SessionReplayConfiguration..
.startRecordingImmediately(false)
- webviews will not be recorded when SR is stopped
- has_replay will be sent as 'false' to the backend when SR is stopped
- startRecordingImmediately will be sent to the backend in the config telemetry
Give users the option to stop and start recordings manually.
=> RUM-5540: Add stop and start apis for session replay

integrations/dd-sdk-android-timber/src/main/kotlin/com/datadog/android/timber/DatadogTree.kt, integrations/dd-sdk-android-timber/src/test/kotlin/com/datadog/android/timber/DatadogTreeTest.kt
Resolves #2195. If Timber tag is present, it will be logged as `timber.tag` attribute.
=> RUM-673: Log Timber tag

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt
• Expose Image Privacy as a public api on the feature branch as part of fine grained masking (in develop it's still an internal api). 
• Also change the default masking level to MASK_ALL as per the RFC.
=> Make Image Privacy a public api

.gitlab-ci.yml, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/KioskTrackingTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTest.kt, reliability/core-it/build.gradle.kts, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/FeatureSdkCoreContextTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/InternalSdkCoreContextTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/MockServerTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/SdkCoreContextTest.kt
This PR add the Gitlab steps for running the core-it instrumented tests in Gitlab using the Sonoma Mac OS runners.
We are also fixing the legacy instrumented tests Gitlab execution scripts which were not failing the job if the tests were failing.
Mainly the issue with the Gitlab scripts was that Gitlab runs them through `bash` and Sonoma forces to `zsh` therefore it runs each line in isolation meaning that the `exit code` values is being reset from one line to another.
=> RUM-5877 run core-it integration tests in Gitlab

tools/benchmark/src/main/java/com/datadog/benchmark/internal/SpanEventSerializer.kt
Add SpanEvent serializer in benchmark module
* `DatadogDataConstraints` constructor is assigned with default value of `internalLogger`, so that in benchmark module, it doesn't have to provide an implementation of `InternalLogger`
=> Add SpanEvent serializer in benchmark module

dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/user/DatadogUserInfoProviderTest.kt
Increases the max bound of `forge.anInt` to avoid that `min` and `max` are equal.
Following error is thrown by the test:
```
The ‘min’ boundary (1) of the range should be less than the ‘max’ boundary (1)
java.lang.IllegalArgumentException: The ‘min’ boundary (1) of the range should be less than the ‘max’ boundary (1)
at fr.xgouchet.elmyr.Forge.anInt(Forge.kt:124)
at com.datadog.android.core.internal.user.DatadogUserInfoProviderTest.M use immutable values W setUserInfo { removing properties }()(DatadogUserInfoProviderTest.kt:244)
```
=> Fix UserInfoProvider flaky test

dd-sdk-android-internal/api/apiSurface, dd-sdk-android-internal/api/dd-sdk-android-internal.api, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/profiler/BenchmarkProfiler.kt, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/profiler/BenchmarkSpan.kt, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/profiler/BenchmarkTracer.kt, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/profiler/GlobalBenchmark.kt
Adds following interface into SDK core:
* BenchmarkCounter
* BenchmarkGauge
* BenchmarkProfiler
* BenchmarkSpan
* BenchmarkTracer
Adds an object class to for BenchmarkProfiler
* GlobalBenchmark
RUM-5754
=> RUM-5754: Add profiling interface to internal module

tools/benchmark/src/main/java/com/datadog/benchmark/EndPoint.kt, tools/benchmark/src/main/java/com/datadog/benchmark/exporter/DatadogSpanExporter.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/BenchmarkSpanToSpanEventMapper.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/DatadogHttpClient.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/SpanEventSerializer.kt
* Fix the base url for `AP1` Endpoint
* Remove the logs for spans exporter
* Fix the trace id of the span event
* Fix some attributes for the span
* Fix the post request url of trace
* Fix the content type of request, which led to the failure of combined json request body.
* Fix `SpanEventSerializer`, the request body should be like this:
```
// span 1
{
"spans": [
{
...
}
],
"env": "debug"
}
// span 2
{
"spans": [
{
...
}
],
"env": "debug"
}
```
instead of 
```
{
"spans": [
// span 1
{
...
},
// span 2
{
...
}
],
"env": "debug"
}
``` …
=> Fix Benchmark Span request issue

dd-sdk-android-internal/api/apiSurface, dd-sdk-android-internal/api/dd-sdk-android-internal.api, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/profiler/BenchmarkSpanBuilder.kt, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/profiler/BenchmarkSpanExt.kt, tools/benchmark/src/main/java/com/datadog/benchmark/DatadogMeter.kt, tools/benchmark/src/main/java/com/datadog/benchmark/profiler/DDBenchmarkProfiler.kt, tools/benchmark/src/main/java/com/datadog/benchmark/profiler/DDBenchmarkSpan.kt, tools/benchmark/src/main/java/com/datadog/benchmark/profiler/DDBenchmarkSpanBuilder.kt, tools/benchmark/src/main/java/com/datadog/benchmark/profiler/DDBenchmarkTracer.kt
* Update `BenchmarkTracer` API
* Add implementations for following interfaces:
* BenchmarkSpanBuilder
* BenchmarkProfiler
* BenchmarkSpan
* BenchmarkTracer
* Add convenient static function to measure the span.
=> Add implementations of benchmark profiling api

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploader.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadStatus.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploaderTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadStatusTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/DNSErrorStatusForgeryFactory.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/NetworkErrorStatusForgeryFactory.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/UnknownExceptionStatusForgeryFactory.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/UnknownHttpErrorStatusForgeryFactory.kt, detekt_custom.yml
Small improvement in our `UploadStatus` type to keep track of exceptions when those happen, and a refactoring to make the logging method easier to read. 
This is step one to create a customisable retry scheduling strategy.
=> RUM-5977 include optional exception in Upload Status

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/UploadSchedulerStrategy.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadScheduler.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DefaultUploadSchedulerStrategy.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadSchedulerTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DefaultUploadSchedulerStrategyTest.kt, detekt_custom.yml
Creates a basic interface to let customers decide how long to wait after an upload before trying again, based on the number of upload attempts, status code and exceptions.
=> RUM-5977 create UploadSchedulerStrategy interface and default implementation

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt
Benchmark spans measurements are put in two places of session replay:
* Span with name "SnapshotProducer" when `snapshotProducer.produce` is called
* Span with name view class name when mapping the view.
=> Integrate benchmark span measurements in session replay

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/TouchPrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowCallbackInterceptor.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallback.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorderTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/SessionReplayConfigurationForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowCallbackInterceptorTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallbackTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelperTest.kt
Adds a public TouchPrivacy api
Possible values for touch:
`SHOW` - record all touch interactions
`HIDE` - do not record touch interactions
Default value will be HIDE.
Usage example:
```
SessionReplayConfiguration.Builder() 
.setTouchPrivacy(TouchPrivacy.SHOW)
```
Note: At the moment this will not hide the change in a button background that occurs as a result of a click (or other view hierarchy side effects). 
Part of the move to fine grained privacy options.
=> RUM-5763: Add TouchPrivacy to Session Replay

gradle/libs.versions.toml, integrations/dd-sdk-android-timber/api/dd-sdk-android-timber.api
Old version cannot be found on JitPack, causing the build failure.
=> Update `kotlinx.ast` dependency

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationCoreForgeryFactory.kt
Let customer chose their UploadSchedulerStrategy
=> RUM-5977 add configuration to set uploadSchedulerStrategy

tools/benchmark/src/main/java/com/datadog/benchmark/internal/DatadogHttpClient.kt
Fix metrics data upload due to the modification of request body media type, 
Actually "Metrics" and "Span" require different media type as intake.
"Span" API requires plain text so several span json can be combined in the same request, while "Metrics" API requires Json format, otherwise it refuses the request with 400 Bad request response.
=> Fix benchmarking metrics data upload request issue

dd-sdk-android-internal/api/apiSurface, dd-sdk-android-internal/api/dd-sdk-android-internal.api, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/profiler/BenchmarkSpanExt.kt, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/profiler/BenchmarkTracer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/BenchmarkExt.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt, tools/benchmark/src/main/java/com/datadog/benchmark/internal/BenchmarkSpanToSpanEventMapper.kt, tools/benchmark/src/main/java/com/datadog/benchmark/profiler/DDBenchmarkTracer.kt
Add a "isContainer" attribute into session replay span request to differentiate the components and containers view.
In the benchmark dashboard, we want to have a top list graph to see which components take the leads of the time consumption in SR. here is the current graph:
As we can see the top list is occupied by the containers, which doesn't what we expect. Because containers' spans contain the children view, so we want to have only real components here.
After adding this attributes, we can differentiate them by adding filter `@attribute.container:false `
Add we got pure components span in the list …
=> RUM-5985: Add isContainer attribute to session replay span

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelperTest.kt
Fix placeholder dimensions, which at the moment could cover the entire dimensions of the view in cases where there are compound drawables. This issue became noticeable with fine grained masking when users can mask all images. 
Before fix:
After fix:
=> RUM-6096: Fix placeholder dimensions

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/Debouncer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/RecordingTimeBank.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TimeBank.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/DebouncerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/RecordingTimeBankTest.kt
Add TimeBank in session replay recorder for dynamic optimisation.
The main idea is to have a time balance in this `TimeBank`, every execution of session replay recording will consume this balance, and the balance will be recharged during the time passing until a maximum balance is reached.
Before every execution of recording, if the balance is negative, the execution will skipped until the balance is recharged to positive.
RUM-6093
=> RUM-6093:Add TimeBank in session replay recorder for dynamic optimisation

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/DatadogCore.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallback.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtils.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallbackTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt, detekt_custom.yml
When the UploadWorker is woken by the system, it reads the SDK Instance name from the WorkRequest input data, and tries to get the instance with that name. 
However, the instance name was never sent meaning that for applications specifying an instance name would never find a relevant SDK. 
Fixes #2252
=> RUM-6104 ensure UploadWorker uses the sdk instance name

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetric.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcher.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionMetricDispatcher.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/RumSessionEndedMetricTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcherTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/Debouncer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/DefaultOnDrawListenerProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/DebouncerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListenerTest.kt
Add session replay skipped frames count in session ended metrics, so that we can have a visibility in RUM telemetry how many frames are optimised by the time bank.
RUM-5188
=> RUM-5188: Add session replay skipped frames count in session ended metrics

buildSrc/build.gradle.kts, gradle/libs.versions.toml
The transitive version used `com.github.drieks.antlr-kotlin:antlr-kotlin-runtime:d4384e4d90` cannot be found on Jitpack anymore, causing the build to fail. So specifying the version explicitly, with the one which can be found.
=> Explicitly set `antlr-runtime` transitive dependency version

sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
Apply the same logic that we have in Shopist, so that the android sample application will also randomize privacy for session replay. 10% of sessions will be fine grained masking sessions.
This pr includes a small cleanup of the sampleApplication class.
Part of dogfooding fine grained masking.
=> RUM-6136: Randomize privacy levels to support Fine Grained Masking in E2E

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/InternalLogger.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/InternalLoggerUtils.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/assertj/InternalAddViewLoadingTimeEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/assertj/InternalApiUsageEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryUsageEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/ViewLoadingTimeEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
Following the [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3951001790/RFC+View+loading+time+manual+API) in this PR we are adding the logs and telemetry related with usage of the `RumMonitor#addViewLoadingTime` newly introduced API. The telemetry and log configuration will be configured accordingly with the current RUM context state and will help us understand what is the pattern for this API usage on the client side.
=> RUM-6033 Add telemetry and logs related with RumMonitor#addViewLoadigTime API

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/InternalLogger.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/InternalLoggerUtils.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/assertj/InternalAddViewLoadingTimeEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/assertj/InternalApiUsageEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/ManualTrackingRumTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/tests/assertj/RumEventAssert.kt
=> RUM-6035 Add the integration tests related with RumMonitor#addViewLoadingTime API

detekt_custom.yml, gradle/libs.versions.toml, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt, sample/kotlin/build.gradle.kts, sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesFragment.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt, sample/kotlin/src/main/res/layout/fragment_traces.xml, sample/kotlin/src/main/res/values/strings.xml, sample/vendor-lib/build.gradle.kts, sample/vendor-lib/src/main/kotlin/com/datadog/android/vendor/sample/LocalServer.kt, sample/vendor-lib/src/main/kotlin/com/datadog/android/vendor/sample/SseEvent.kt
This PR Handles properly SSE (Server Sent Event) network request instrumented with our OkHttp interceptor. 
In order to report the size of a downloaded resource, we use the `peekBody()` method which tries to read the whole content of the network request. In case of a SSE request, it would wait until the end of the stream to eventually complete the interception and forward the content to the receiver, blocking the server messages. 
ServerSent events should have the `text/server-event` Mime Type, which we can use to detect such use case. 
Fixes #2266
=> RUM-6235 Handle sse request

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/InternalLogger.kt
=> Do not use magic numbers in InternalLogger API

dd-sdk-android-internal/api/apiSurface, dd-sdk-android-internal/api/dd-sdk-android-internal.api, dd-sdk-android-internal/build.gradle.kts, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/utils/ByteArrayExt.kt, dd-sdk-android-internal/src/test/java/com/datadog/internal/utils/ByteArrayExtTest.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/MD5HashGenerator.kt
This PR changes the way to convert MD5 bytes to HEX string.
When we broke down the steps of generating image wireframe, we noticed that `joinToString` function takes a huge amount of time when generating the MD5 resource id:
* String Concatenation Overhead:
joinToString internally uses StringBuilder, but string concatenation inside the lambda (using `"%02x".format(it)`) could be inefficient. If format() is invoked for each byte, it involves repeated function calls, which adds to overhead.
* Repeated Memory Allocations:
`"%02x".format(it)` creates a new string for each byte, which leads to multiple temporary objects being created. This puts pressure on the garbage collector.
After using the new function to convert the byte arrays, we can see the duration optimisation rate is up to **99%** …
=> RUM-6256: Optimize MD5 byte array to hex string conversion

integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt
Fix DatadogInterceptor flaky test
=> Fix DatadogInterceptor flaky test

CONTRIBUTING.md
Minor changes: update of the templates links and Detekt/Ktlint versions used.
=> `CONTRIBUTING` doc changes

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextViewMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ButtonMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextViewMapperTest.kt
Fix the Session Replay issue that text view overflow could not be displayed properly
RUM-6314
| App screen | Before | After |
|<img width="600" alt="image" src="https://github.com/user-attachments/assets/80b85cec-dff1-40cd-8392-4b06c760bea2"> |![image](https://github.com/user-attachments/assets/a165b4db-94e0-42a8-a7d0-7a5659dc659f)|![image](https://github.com/user-attachments/assets/59b068e5-7382-44ae-b074-6b041ad4635f)|
=> RUM-6314: Use layout text to display textview overflow correctly

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ButtonMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ButtonMapperTest.kt
Remove Session Replay button mapper border.
The logic before was adding a black border to every text view inside which doesn't have a shape or border, But text view mapper always return a wireframe without them, so the black border will always be applied, which doesn't correspond to the real UI.
RUM-6316
| App Screen | Before | After |
| <img width="299" alt="Screenshot 2024-09-24 at 14 21 10" src="https://github.com/user-attachments/assets/c7e30db7-433c-4ee7-8f56-4e7bb1fed734">|<img width="288" alt="image" src="https://github.com/user-attachments/assets/ccf03b39-f1ed-4192-ad9d-d1bbae3298aa"> |<img width="284" alt="image" src="https://github.com/user-attachments/assets/5b079ce4-1829-4406-9595-a2b4c4c3100d">     |
|<img width="290" alt="Screenshot 2024-09-24 at 14 22 …
=> RUM-6316: Remove Session Replay button mapper border

sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/SessionReplayFragment.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/ViewGroupComponentsFragment.kt, sample/kotlin/src/main/res/layout/fragment_session_replay.xml, sample/kotlin/src/main/res/layout/fragment_view_group_components.xml, sample/kotlin/src/main/res/navigation/nav_graph.xml, sample/kotlin/src/main/res/values/strings.xml
When testing SR with some other applications, we noticed that the card view is not correctly display in the player, before fixing the issue, we need to add an showcase screen for this kind of view groups.
RUM-6324
| Sample App| Player |
| --- | --- |
| ![Screenshot_20240925_135133](https://github.com/user-attachments/assets/c5c28505-b570-4a40-ba7e-34e58e49b79e)|![image](https://github.com/user-attachments/assets/821b059b-7afe-4f7e-b502-d40173a96105)|
=> RUM-6324: Add View Groups Session Replay demo screen in sample app

.gitlab-ci.yml, Dockerfile.gitlab
This PR fixes the issue of missing CI Visibility data coming from our Gitlab CI. The issue comes from the following PR https://github.com/DataDog/dd-sdk-android/pull/2192 which brought upgrade to Gradle 8.9.
Apparently, Datadog Agent wasn't supporting it and it was fixed in https://github.com/DataDog/dd-trace-java/pull/7319.
=> Update Datadog Agent to 1.39.0

features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaterialExtensionSupport.kt, features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/internal/CardWireframeMapper.kt, features/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/CardWireframeMapperTest.kt, sample/kotlin/src/main/res/layout/fragment_session_replay.xml, sample/kotlin/src/main/res/layout/fragment_view_group_components.xml, sample/kotlin/src/main/res/values/strings.xml
`MaterialCardView` is a widely used material component, this PR adds `MaterialCardView` support in Material SR extension
RUM-6324
| Sample | Before | After |
| <img width="400" alt="image" src="https://github.com/user-attachments/assets/6e7b1d4d-7066-4daa-8305-c34b9194eb0c">| <img width="400" alt="image" src="https://github.com/user-attachments/assets/27add180-e272-40d9-93af-c8b54beebf1f"> | <img width="400" alt="image" src="https://github.com/user-attachments/assets/5f8fb2ca-87aa-44c1-b284-7fbbfa4993c8">|
=> RUM-6324: Add MaterialCardView support in Material SR extension

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/BatchesToSegmentsMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/SegmentRequestFactory.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/MobileSegmentExt.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/BatchesToSegmentsMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/SegmentRequestFactoryTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/MobileSegmentExtTest.kt
This is to align with what iOS SDK has https://github.com/DataDog/dd-sdk-ios/blob/4dbdf4a10991ba65a02b02bf1fe87e4aa2765b38/DatadogSessionReplay/Sources/Feature/RequestBuilders/SegmentRequestBuilder.swift#L48
=> Use SDK source value in Session Replay `MobileSegment.source` property

detekt_custom.yml, features/dd-sdk-android-session-replay-compose/consumer-rules.pro, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SemanticsWireframeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapperTest.kt
Add Semantics Mapper for Button role
RUM-6194
|Sample App | Session Replay |
| --- | --- |
| <img width="800" alt="image" src="https://github.com/user-attachments/assets/38288175-da52-40ca-ad43-2fe2088ee842">| <img width="800" alt="image" src="https://github.com/user-attachments/assets/ff878818-2a16-44de-94df-59a27ddc78b2">|
=> RUM-6194: Add Semantics Mapper for Button role

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploader.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploaderTest.kt
Initially I thought that given the fact that the `DataOkHttpUploader` is being executed sequentially there is no need for thread safety in it. After a team discussion we stumbled upon this corner case where the executor could actually kill that thread and spawn a new one therefor we need to make sure these states are Volatile and kept in the Heap.
=> Make the DataOkHttpUploader state volatile

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SystemRequirementsConfiguration.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/prerequisite/CPURequirementChecker.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/prerequisite/MemoryRequirementChecker.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
Asynchronous enabling the session replay feature after checking the system requirement causes the dysfunction of touch recorder.
This commit fixes it by reading the files on the original thread synchronously with allowance of strict mode.
=> Read SR system requirement synchronously with strict mode allowance

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/SessionReplayTestRule.kt, instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/ProcessImportanceExt.kt
In integration test, the process is always treated as foreground service instead of foreground.
So when initialising the feature, `DatadogRumMonitor` consider the app is not in foreground,
which causes different test result in Rum feature.
In this case we need to force the importance of the process to have the same result of user environment.
Fix flaky test
=> Override process importance for Session Replay integration tests

sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
I noticed a problem in the sampleApplication - we had a line there setting the legacy privacy. This is overwriting the value from the useLegacyConfiguration method.
=> Remove unnecessary legacy privacy line from the sampleApplication

dd-sdk-android-internal/build.gradle.kts, tools/benchmark/build.gradle.kts
I noticed that some public modules were inconsistent in terms of the Java bytecode version produced, they had Java 17. Fixing it to align with other modules, to use Java 11.
=> Fix: use Java 11 bytecode for public modules

.gitlab-ci.yml, buildSrc/src/main/kotlin/com/datadog/gradle/config/TestPyramidConfig.kt, detekt_test_pyramid.yml, tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/pyramid/ApiSurface.kt, tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/pyramid/ApiUsage.kt
This updates how we compute our API coverage through Integration tests, by ignoring methods flagged with `@Internal` and Extension methods we use for non Datadog classes. 
Improve our visibility on integration test coverage
=> Detekt the api coverage in Integration tests

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/LegacyDrawableToColorMapper.kt
In lower version of Android, the color information is stored in `paint.colorFilter` instead of `paint`,
So we need to retrieve it from `colorFilter.mColor` attribute to have the correct color for drawable.
RUM-3469
=> RUM-3469: Resolve PorterDuffColorFilter case in drawable to color mapper

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/PrivacyOverrideExtensions.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/HiddenViewMapper.kt, features/dd-sdk-android-session-replay/src/main/res/values/ids.xml, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/PrivacyOverrideExtensionsTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversalTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/HiddenViewMapperTest.kt
Sets up the common mechanism for privacy overrides and implements overriding view privacy to `hidden` in the hierarchy. 
Views will be able to set hidden override privacy using the api:
```[view].setSessionReplayHidden(hide = true/false)```
where true will register the view to be replaced with a placeholder with the label "Hidden", and false will remove the hidden override from the view. The children of hidden views will not be traversed.
This is part of the third stage of Fine Grained Masking. The first stage was the start/stop api, and the second was global fine grained masking levels for the app.
- [ ] Make sure each commit and the PR mention the Issue …
=> RUM-6218: Add privacy override for hidden views

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/PrivacyOverrideExtensions.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt, features/dd-sdk-android-session-replay/src/main/res/values/ids.xml, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/PrivacyOverrideExtensionsTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducerTest.kt
Adds privacy overrides for images and textAndInput.
Api example:
`view.setSessionReplayImagePrivacy(privacy: ImagePrivacy?)`
`view.setSessionReplayTextAndInputPrivacy(privacy: TextAndInputPrivacy?)`
These privacy overrides work on nearest parent - so if you override the privacy on a viewgroup, it should be propagated to the children unless they have their own override.
Part of the fine grained masking effort. 
=> RUM-6219: Add Image and TextAndInput privacy overrides

gradle/libs.versions.toml, sample/kotlin/build.gradle.kts, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/ImageSample.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/SampleSelectionScreen.kt
Add sample screen for jetpack compose to demostrate images components:
* Image
* Icon
* Icon Button
* AsyncImage (coil)
To test jetpack compose session replay support for all types of images.
=> Add image sample screen for jetpack compose session replay

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/consumer-rules.pro, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/ImagePrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/PrivacyLevel.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/TextAndInputPrivacy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/TouchPrivacy.kt
Adds a proguard rule to prevent the fine grained masking enums from being obfuscated. 
Because we [resolve](https://github.com/DataDog/dd-sdk-android/blob/develop/features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt#L112) `String` --> `Enum` with `valueOf`.
=> Prevent obfuscation of Fine Grained Masking enums

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/AbstractStorage.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorage.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileOrchestrator.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/AbstractStorageTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorageTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/PendingToGrantedAsyncTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/PendingToGrantedCustomPersistenceAsyncTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/utils/HeapBasedPersistenceStrategy.kt
- **Issue Identified**:
- Our storage logic has a race condition issue affecting event processing.
- This problem is visible only in a specific use case involving concurrent operations and tracking consent management.
- **Specific Use Case**:
- The system is operating under "PENDING" tracking consent mode.
- Events are being written via a `featureScope` by one thread.
- At the same time, tracking consent is being changed by another thread.
- **Underlying Process**:
- For each event written:
- The system first resolves the `DatadogContext` to determine the current environment and configuration.
- It then uses the `DatadogContext` to resolve the `FileOrchestrator`, which decides where events should be stored.
- Subsequently, a task is added to the Executor queue to handle the actual writing …
=> RUM-6307 Make sure ConsentAwareFileOrchestrator is thread safe

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt
Add a default sample rate of 100% for Session Replay (sample rate is now optional when creating the configuration).
Align with the other features. 
=> RUM-6385: Default sample rate for session replay

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/FragmentTrackingTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt, instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/FragmentTrackingPlaygroundActivity.kt, instrumented/integration/src/main/kotlin/com/datadog/android/sdk/utils/ProcessImportanceExt.kt, instrumented/integration/src/main/res/layout/fragment_tracking_layout.xml
There are two integration tests failing for very long time,
* `ConsentPendingGrantedFragmentTrackingTest.verifyViewEventsOnSwipe`
* `ConsentGrantedFragmentTrackingTest.verifyViewEventsOnSwipe`
This is due to the action we perform on the test activity never works:
```
onView(ViewMatchers.withId(R.id.tab_layout)).perform(ViewActions.swipeLeft())
```
It's a known issue of  Espresso that swipe is not working on a view pager, so we can never perform the action that we want,
to fix it, I added two buttons on the layout to go to next or last page, and replace the swipe action by clicking the buttons.
Another issue is that in integration test we need to override the importance of the process otherwise we don't receive the event of application start
RUM-6570
Anything else we should know when …
=> RUM-6570: Fix Rum integration test verifyViewEventsOnSwipe

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt
The whole context please check the ticket: RUM-6293
TL,DR;
The sample rate should be decreased by 10 times but wrongly decreased by 1000 times,
Since we have add sample rate option on `logMetric` method, now it doesn't make sense to have another sampler inside `BatchMetricsDispatcher`. By removing it, the sample rate is simply controlled by the parameter passed into `logMetric` and the total sample rate will be increased by (1/0.015f) = 66.6 times.
RUM-6293
=> RUM-6293: Remove Batch metrics inner sampler to increase sample rate

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/data/SemanticsWireframe.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ImageSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SemanticsWireframeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapperTest.kt
A small update on the return value of each semantics node mapper,
since one semantic node can return several wireframes such as image, shape for background, we need a wrapper to contain the list of the wireframes.
=> Add SemanticsWireframe to wrap the collection of the wireframes

reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/LoggerTest.kt
Add a missing test in the SFIT/Logs module to improve our coverage.
=> Add missing integration test for Logs

.gitlab-ci.yml, Dockerfile.gitlab
This PR updates the version of Datadog Agent used for Test Visibility from 1.39.0 to 1.41.0.
Updating the agent is a pre-requisite for enabling ITR, and the recent version contains related fixes and improvements.
=> Update Datadog Agent to 1.41.0

detekt_custom.yml, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/test/elmyr/GlobalBoundsForgeryFactory.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/test/elmyr/SessionReplayComposeForgeConfigurator.kt
The main updates is that we stop using `semanticsNode.boundsInRoot` to calculate the global bounds of the component, instead, we need to use the `positionInRoot` to have the top-left coordinates, and get the size of the component to have the correct global bounds, here is the explanation:
The main reason is that `semanticsNode.boundsInRoot` represents the visible bounds of the component, when it is fully visible in the screen, it is equal to the bounds that we want, but if we scroll the screen and it becomes half visible, the bounds will shrink to the visible area, which is not useful for our wireframes: …
=> Update the resolveBounds logic for semantics node

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/SdkCore.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/DatadogCore.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/NoOpInternalSdkCore.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt, detekt_custom.yml, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayTest.kt
Allow session replay to run on only one core at a time. Attempting to start sr on more cores will send telemetry.
It probably doesn't make sense for session replay to run on multiple cores.
=> RUM-6375: Force single core for session replay

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/BaseSessionReplayTest.kt
In our SR instrumented tests we need to decompress the segments intercepted through the `MockServer` in order to be able to assess them with the expected payloads.
The segments are previously compressed with a `deflate` alg and we are using an `Inflater` instance in the SR tests to deflate them.
The `Inflater` class logic is buggy in the Android API 21 JVM. For some reason the `inflater.finished` method always returns `false` having our decompression logic running in an endless loop.
=> Fix the decompression in SR instrumented tests for API 21

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/LegacyDrawableToColorMapper.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentGrantedSrTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/chekboxandradio/SrCheckBoxAndRadioFieldsAllowTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/chekboxandradio/SrCheckBoxAndRadioFieldsMaskTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/chekboxandradio/SrCheckBoxAndRadioFieldsMaskUserInputTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/imagebuttons/SrImageButtonsAllowTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/imagebuttons/SrImageButtonsMaskTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/imagebuttons/SrImageButtonsMaskUserInputTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/images/SrImagesAllowTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/images/SrImagesMaskTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/images/SrImagesMaskUserInputTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/sensitivefields/SrSensitiveFieldsAllowTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/sensitivefields/SrSensitiveFieldsMaskTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/sensitivefields/SrSensitiveFieldsMaskUserInputTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/textfields/SrTextFieldsAllowTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/textfields/SrTextFieldsMaskTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/textfields/SrTextFieldsMaskUserInputTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/textfields/SrTextFieldsWithInputMaskUserInputTest.kt
Reactive Session Replay instrumented test for API 21, 
Fix a drawable resolving issue due to the different behavior on lower API.
RUM-5873
=> RUM-5873: Reactivate Session Replay instrumented test for API 21

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableTextViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableWireframeMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseCheckableTextViewMapperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapperTest.kt
Before, checkable mapper was using image privacy to mask the components, `Checkbox`, `CheckedTextView`, `Switch` are affected.
We actually need to use Text & input privacy to mask them.
=> Fix checkable mapper privacy issue

sample/kotlin/build.gradle.kts, sample/kotlin/proguard-rules.pro
* Use debug signing configs for local release build of sample app
* Add missing proguard rules for sample app
For the convenience of local release build test
=> Use debug signing configs for local release build & missing proguard rules

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolver.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseAsyncBackgroundWireframeMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelperTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolverTest.kt
Part of fixing the frozen scrolling when MASK_NONE is selected for image privacy. We were using the copy of the drawable as the key in the resource cache and this resulted in cache misses. This pr changes the behavior to use the original drawable to generate the key.
=> RUM-6897: Fix scrolling issue

.gitlab-ci.yml
This is needed for the cloudops -> cloud-inventory migration (see https://github.com/DataDog/cloudops/pull/40254 and https://github.com/DataDog/cloud-inventory/pull/24220), which in turn is needed in order to pick Android SDK-specific macOS Sonoma runners (see https://github.com/DataDog/ci-platform-machine-images/pull/138).
=> Update link to the CI Docker image

detekt_custom.yml, features/dd-sdk-android-session-replay-compose/consumer-rules.pro, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ImageSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/BackgroundInfo.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapperTest.kt
This PR manages to resolve the background information added by `Modifier` to shape wireframes.
For example, if an icon is defined like this:
```
Icon(modifier = Modifier
.padding(16.dp)
.clip(Circle(16.dp))
.background(Color.Green)
.padding(32.dp)
.size(128.dp)
.clip(RoundedCornerShape(8.dp))
.background(Color.DarkGray)
.padding(4.dp),
painter = painterResource(R.drawable.ic_dd_icon_red),
tint = Color.Red,
contentDescription = "red dog" )
```
then it will be resolved to three wireframes, one shape wire frame of green circle, one shape wire frame of black rectangle , one image wireframe with icon image.
| Sample App | Session Replay |
| --- | --- |
| <img width="400" alt="image" src="https://github.com/user-attachments/assets/7801c3c1-12c0-4c71-b213-6643e5bc0da4">) | <img width="400" …
=> Resolve Semantics modifier info to background wireframes

detekt_custom.yml, features/dd-sdk-android-session-replay-material/api/apiSurface, features/dd-sdk-android-session-replay-material/api/dd-sdk-android-session-replay-material.api, features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaterialExtensionSupport.kt, features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/internal/MaterialDrawableToColorMapper.kt, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/ExtensionSupport.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/NoOpExtensionSupport.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/AndroidMDrawableToColorMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/AndroidQDrawableToColorMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/DrawableToColorMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/LegacyDrawableToColorMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/SessionReplayConfigurationForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
In Session Replay, we noticed that there are some components have transparent background in player, which make the content not visible.
After investigation, we see that it's due to the background drawable that we currently can not parse.
According to Telemetry, here is a top list of the drawable that we don't support:
On top of that, it's `MaterialShapeDrawable`, which belongs to material components, in this case we need to inject a custom mapper from `dd-sdk-android-session-replay-material` to `dd-sdk-android-session-replay`, so that when user add the extension of material, it can parse the drawable.
RUM-6896:
| Before | After  |
| --- | --- |
|<img width="282" alt="Screenshot 2024-10-29 at 13 44 00" src="https://github.com/user-attachments/assets/85f31b0c-19e1-4c63-b57f-bc138adffacb"> | …
=> RUM-6896: Add custom drawable mappers to resolve extension drawable

features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
This PR does a bit of the optimization for the methods in `RumEventExt`: when random RUM raw event needs to be created, we are avoiding creating all of them and then selecting only one, but instead selecting the type and then creating only the selected one.
This gives a benefit for the tests where a lot of events are created. For example, for the `RumViewScopeTest#M produce event safe for serialization W handleEvent()` where there is a 1000 iterations loop to call `RumMonitor#handleEvent` this change is reducing execution time from 15s to 2s (and it will be much less redundant objects created, less work for GC). …
=> Lazy RUM raw event creation in event generator methods

detekt_custom.yml, features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaterialExtensionSupport.kt, features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/internal/ChipWireframeMapper.kt, features/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/ChipWireframeMapperTest.kt, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableCompoundButtonMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextViewMapper.kt, sample/kotlin/src/main/res/layout/fragment_text_view_components.xml, sample/kotlin/src/main/res/values/strings.xml
The telemetry in `CompoundButton` was not clear enough to understand why we can't resolve `buttonDrawable` of the view prior to this PR, so one of the task is to append the view information in the telemetry so that we can know the view type.
`ChipWireframeMapper` is added to support Material Chip component since it's a widely used one on customer side.
RUM-6871
| Sample App | Session Replay Allow| Session Replay Mask |
|<img width="234" alt="image" src="https://github.com/user-attachments/assets/5505a2f3-f540-4c5b-b2e0-c65fa06b7af3">| <img width="234" alt="image" src="https://github.com/user-attachments/assets/460b3d23-bf42-4d41-a2ab-f0c18e31f6a5">  | <img width="234" alt="image" src="https://github.com/user-attachments/assets/ce49fa81-3ee8-47c5-973c-d0a530b74120">|
- …
=> RUM-6871: Add Material Chip mapper and improve CompoundButton telemetry

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolver.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolverTest.kt
Snapshot item is never processed due to the fix in this [PR](https://github.com/DataDog/dd-sdk-android/pull/2351), 
this is because we call `job.started` callback but never call `job.finished` , so the snapshot is always in pending state.
=> Fix resolveResourceId not correctly calling job finished when drawable cloning failed

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableCompoundButtonMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableTextViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckedTextViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DrawableCopier.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseCheckableTextViewMapperTest.kt
This PR is a follow-up of this [PR](https://github.com/DataDog/dd-sdk-android/pull/2354).
There were still some mapper copying their drawable before retrieving the cache, especially in `CompoundButton` mappers,
So this PR cleans up the related issue.
RUM-6897
=> Fix CompoundButton mapper drawable clone issue

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageViewMapper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelper.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/ImageViewUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/ImageViewUtilsTest.kt, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_image_buttons_allow_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_image_buttons_mask_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_image_buttons_mask_user_input_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_allow_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_user_input_payload.json, sample/kotlin/src/main/res/layout/fragment_image_components.xml
In app development, clients usually use paddings to resize the content drawable in a given size image view, prior to this PR we didn't taken into account these paddings to resize our image wireframe, which leads some images/icons bigger than real.
So the updates in this PR:
* Add paddings for a demo image view in sample app
* Add paddings calculation in `resolveParentRectAbsPosition` function
* Fix the issue that  `GradientDrawable` didn't take into account the width&height after resizing.
RUM-3460
=> RUM-3460: Fix padding and resizing issue for image view mapper

features/dd-sdk-android-session-replay-compose/api/apiSurface, features/dd-sdk-android-session-replay-compose/api/dd-sdk-android-session-replay-compose.api, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/ComposeExtensionSupport.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/ExperimentalSessionReplayApi.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/ComposeExtensionSupportTest.kt
Add experimental annotation for Session Replay and Add it for Compose extension so that clients will be aware of the functionality is not stable.
Preparation for merging the feature/sr_compose into develop
=> Add experimental annotation for Session Replay and Add it for Compose

sample/benchmark/build.gradle.kts, sample/benchmark/src/main/java/com/datadog/benchmark/sample/MainActivity.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/benchmark/DatadogBenchmark.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/benchmark/SyntheticsScenario.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/compose/MainView.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/fragment/SessionReplayAppcompatFragment.kt, sample/benchmark/src/main/java/com/datadog/benchmark/sample/fragment/SessionReplayMaterialFragment.kt, sample/benchmark/src/test/java/com/datadog/benchmark/sample/benchmark/DatadogBenchmarkTest.kt
Add session replay compose scenario, so that the application can switch to compose view when receive the bundle argument, and also in metrics we can filter with `scenario:sr_compose` for compose session replay.
RUM-7085
=> RUM-7085:Add compose session replay scenario for benchmark sample application

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SemanticsWireframeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TabSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TabSemanticsNodeMapperTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/SampleSelectionScreen.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/TabsSample.kt
Add Tab semantics mapper to resolve tab component to wireframe for Session Replay
Known issue:
We are not able to have the correct color for the image in the tab bar, because we retrieve directly Bitmap, not a tintable drawable.
RUM-6200
| Sample App | Session Replay |
| --- | --- | 
| <img width="374" alt="image" src="https://github.com/user-attachments/assets/a54dd0fc-ffd4-440b-8e5c-d1794aacc910"> | <img width="374" alt="image" src="https://github.com/user-attachments/assets/f6c54cbf-b2e3-4023-8dd3-d7d3c0d55ed5"> |
=> RUM-6200: Add Tab semantics mapper

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
During our escalation sessions with our clients we encountered several situations where the SDK was not initialised outside the main process. Unless the application is using 2 different processes and has 2 SDK instances (one in each process) this scenario will lead to a non - functional SDK as the data will no be uploaded as we are not initialising our schedulers in a secondary process. 
In this PR we are adding a warning log for our users when the SDK is initialised in a secondary process just to better debug this situations and avoid long escalation back and forth. 
- [ ] Make sure each commit and the PR …
=> RUM-6400 Add warning log when initializing the SDK outside of main process

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RadioButtonSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SemanticsWireframeMapper.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RadioButtonSemanticsNodeMapperTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/SampleSelectionScreen.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/ToggleSample.kt
Add RadioButton Semantics Node Mapper. 
Since we are not able to retrieve the image of button, we use shape to simulate the radio button. 
And color of the button needs to be retrieved by reflection, here is a follow up tickets: RUM-7116
RUM-6198
| Sample App | Session Replay |
| --- | --- |
|<img width="289" alt="image" src="https://github.com/user-attachments/assets/2ca83506-51bf-4fc9-8c49-1e03e9c7adca">    |<img width="289" alt="image" src="https://github.com/user-attachments/assets/03e84d31-eabf-48c7-aee6-82312ce8a490">|
=> RUM-6198: Add RadioButton Semantics Node Mapper

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ContainerSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SemanticsWireframeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ContainerSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RadioButtonSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SemanticsWireframeMapperTest.kt
* Add ContainerSemanticsNodeMapper to handle container in compose
* Fix the bug of resolving the id
* Now use the parent color in the Ui context for tab semantics node
RUM-7082
For this PR, I tested with 3rd party application "NowInAndroid", it has dark mode so we can easily see that the background color of all the containers can be correctly resolved as dark due to the update:
Here is the session replay link:
* [Before](https://mobile-integration.datadoghq.com/rum/replay/sessions/df5838e3-b56c-44c0-99ab-d9883d00081b?applicationId=3fb301d4-d556-4e75-a4f5-72c9a11d6137&seed=6bae7b6e-c365-4feb-aa19-da51c2619530&ts=1731083470073)
* [After](https://mobile-integration.datadoghq.com/rum/replay/sessions/f538c44e-1bf7-4f81-8174-594071de945a?applicationId=3fb301d4-d556-4e75-a4f5-72c9a11d6137&seed=92 …
=> RUM-7082: Use dedicated semantics node mapper to resolve container frame

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/ImageViewUtils.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ImageViewMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/ImageViewUtilsTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ImageViewMapperTest.kt
Exposes `ImageViewMapper` so that it can be used by cross-platform frameworks. 
=> RUM-7024: Make ImageViewMapper public

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/logger/SdkInternalLogger.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/sampling/RateBasedSampler.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/sampling/Sampler.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/sampling/RateBasedSamplerTest.kt, features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt, features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/log/WebViewLogEventConsumer.kt, integrations/dd-sdk-android-okhttp/api/apiSurface, integrations/dd-sdk-android-okhttp/api/dd-sdk-android-okhttp.api, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorBuilderTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutTracesTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/TracingInterceptorBuilderTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorContextInjectionSampledTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt
Preparing for a new implementation of a sampler for the TracingInterceptor, add a type to the sampler to allow adapting the sampling decision to the event being sampled.
=> RUM-6866 Allow typed Sampler

sample/benchmark/src/main/java/com/datadog/benchmark/sample/benchmark/DatadogBenchmark.kt
Add compose extension in benchmark app
Benchmark can have Compose SR right now:
https://mobile-integration.datadoghq.com/rum/replay/sessions/6bad66b1-bd36-40e0-88a7-0b3b5bf5da36?applicationId=63e67473-c075-4f15-8891-04e96212f22e&seed=873a3613-936f-4040-8d5f-0c420ee7cb48&ts=1731598391352
=> RUM-7085: Add compose extension in benchmark app

sample/benchmark/build.gradle.kts, sample/benchmark/src/main/java/com/datadog/benchmark/sample/compose/MainView.kt
In Benchmark application, prior to this PR we don't send any `view` type Rum event when navigating between compose view, this leads to Rum session `has_replay` is always false even if in local it's already true. And on the player side we don't have a replay for the session for very long time.
Adding Navigation view tracking for compose can make the Rum view event sent correctly, and `has_replay` attribute will be earlier refreshed to true.
| Before | After |
| --- | --- |
|<img width="773" alt="image" src="https://github.com/user-attachments/assets/d5e5984f-3108-41ba-b60c-ab87aed8e45d"> |.<img width="779" alt="image" src="https://github.com/user-attachments/assets/27709771-27d4-4a0a-a635-be011df14255">|
- [ ] Make sure you discussed the feature …
=> Add Navigation view tracking in benchmark Compose application

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/ComposeExtensionSupport.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AndroidComposeViewMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ComposeViewMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/ComposeExtensionSupportTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AndroidComposeViewMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ComposeViewMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapperTest.kt
In Jetpack compose, if the composable content is added by `setContent{  }` in the activity, then the wrapper view is `ComposeView`, but for the pop up like bottom sheet dialog or Drop down menu, they use `AndroidComposeView` as the wrapper in a separated `DecorView`.
So we need to support `AndroidComposeView` mapping otherwise the Session Replay can not resolve any content in the popup decor view.
In this PR, a small refactor is done in order to share the common logic between `ComposeViewMapper` and `AndroidComposeViewMapper`, here is the structure change:
RUM-7215
Known issue in demo:
Drop down menu doesn't have the correct position in replay
https://mobile-integration.datadoghq.com/rum/replay/sessions/26a23f05-aa91-427e-9f77-4b3457ac4ba2?applicationId=38030dde-f9f9-4e52-9443-b9804a030080 …
=> RUM-7215: Add AndroidComposeViewMapper to support popup

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/wrappers/BitmapWrapper.kt
A client reported SDK crash with stack trace:
```
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@cad0e02
at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:83)
at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:174)
at android.graphics.Canvas.drawBitmap(Canvas.java:1580)
at android.graphics.Bitmap.createBitmap(Bitmap.java:1008)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:841)
at com.datadog.android.sessionreplay.internal.recorder.wrappers.BitmapWrapper.createScaledBitmap$dd_sdk_android_session_replay_release(BitmapWrapper.java:46)
at com.datadog.android.sessionreplay.internal.utils.DrawableUtils.createScaledBitmap$dd_sdk_android_session_replay_release(DrawableUtils.java:93)
at …
```
=> Fix crash while using recycled bitmap in Session Replay

features/dd-sdk-android-session-replay-compose/build.gradle.kts, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/BenchmarkExt.kt
Integrate benchmark profiler to measure the span of Compose Session Replay
RUM-7291
Compose part start from `RootNode` span, each component span is name with its mapper:
=> RUM-7291: Integrate benchmark profiler in compose mapper

features/dd-sdk-android-session-replay-compose/consumer-rules.pro, sample/benchmark/build.gradle.kts
`keepclassmembers` can not keep the class itself, which leads to class not found exception during the release mode runtime, so we need to change it to `keep`
Images are missing in the session replay of release benchmark app
https://mobile-integration.datadoghq.com/rum/replay/sessions/baff0c73-9b05-4dd6-8fb2-512b5c8d2a36?applicationId=63e67473-c075-4f15-8891-04e96212f22e&seed=c459ac50-a643-4203-abc3-2e550084b1f0&ts=1731925605609
=> Fix consumer-rules pro for Compose Session Replay

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayTest.kt
Aligns the log levels with iOS for the error we output when a user tries to enable session replay twice (either on the same core or on different cores) - "Session Replay is already enabled"
On iOS they output an error to the user and debug to the telemetry. 
=> RUM-7302: Align log levels for sr already enabled

features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/replay/WebViewReplayFeature.kt, features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/replay/WebViewReplayFeatureTest.kt
`WebviewReplayFeature` was using the default storage configuration. As a result, events sent by the browser sdk that were larger than 512kb were being rejected rather than written to batch files. This pr adjusts the size limits to align with session replay - 10mb per item and 10mb per batch. 
I also added unit tests for `WebviewReplayFeature` as there didn't seem to be any.
Support ticket where the customer couldn't see their webviews.
=> RUM-7337: Adjust Webview Replay storage configuration limits

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextLayoutInfo.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/StringUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AbstractSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ButtonSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ContainerSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RadioButtonSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TabSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/StringUtilsTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/test/elmyr/SessionReplayComposeForgeConfigurator.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/test/elmyr/TextLayoutInfoForgeryFactory.kt
For the other semantics node mapper, we are probably going to reuse the part of the logic of resolving the text in current `TextSemanticsNodeMapper`, so in this PR, some functions are moved to `AbstractSemanticsNodeMapper` or `SemanticUtils` so it can be directly used by others.
=> Refactor TextSemanticsNodeMapper to commonize the text wireframe logic

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextFieldSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextFieldSemanticsNodeMapperTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/InputSample.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/SampleSelectionScreen.kt
Add TextField semantics mapper for Session Replay Compose, with this PR, following compose components can be supported:
* TextField
* OutlineTextField
Known issue of this mapper:
* TextField hint text color might not be correct,
* OutlineTextField can have the correct outline
RUM-7091
| Sample App |.  Session Replay |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/b0cea05b-6216-45a7-a709-0fe76312264d" alt="Screenshot_20241121_095512" width="600">| ![ezgif-7-7d88bddb00](https://github.com/user-attachments/assets/4c2b81ad-3875-4ae9-b2f8-a3fe753881b6) |
=> RUM-7091: Add TextField semantics mapper for Session Replay Compose

features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextFieldSemanticsNodeMapperTest.kt
Fix TextFieldSemanticsNodeMapper flaky test, it's possible that the random font family in `fakeTextLayoutInfo` is not GenericFontFamily, so this PR covers the corner case.
=> Fix TextFieldSemanticsNodeMapper flaky test

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadStatus.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadStatusTest.kt
Improve the log message when exception happen during Upload. Right now we only print the error message but not the error type which makes it harder to investigate when an unknown error appears
=> Improve the log message when exception happen during Upload

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/data/UiContext.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AndroidComposeViewMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ComposeViewMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ImageSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextFieldSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/StringUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AndroidComposeViewMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ComposeViewMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextFieldSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/test/elmyr/UIContextForgeryFactory.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DefaultImageWireframeHelper.kt, gradle/libs.versions.toml, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/InputSample.kt
Apply Global privacy level to semantics node mapper, there are following major changes:
* Remove legacy privacy in UiContext, replace it by input privacy and image privacy
* Text and TextField semantics node mapper applied with input privacy
* Image semantics node mapper applied with image privacy
Besides, in sample app, material3 lib version is downgraded to align with compose bom version
RUM-7342
| | Selection screen| Typography screen | Input screen| 
| --- | --- | --- | --- |
| MASK_ALL | <img width="282" alt="Screenshot 2024-11-22 at 09 33 05" src="https://github.com/user-attachments/assets/2560489c-c3f5-4e6a-91d2-93e5353d907a"> | <img width="282" alt="Screenshot 2024-11-22 at 09 33 27" src="https://github.com/user-attachments/assets/05b26efc-21f4-4c0f-aec1-db1fc7fe1a45"> | <img …
=> RUM-7342: Apply Global privacy level to semantics node mapper

detekt_custom.yml, features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/rum/_common-schema.json, features/dd-sdk-android-rum/src/main/json/rum/error-schema.json, features/dd-sdk-android-rum/src/main/json/rum/long_task-schema.json, features/dd-sdk-android-rum/src/main/json/rum/resource-schema.json, features/dd-sdk-android-rum/src/main/json/rum/view-schema.json, features/dd-sdk-android-rum/src/main/json/rum/vital-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/InitialResourceIdentifier.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/InternalResourceContext.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/NetworkSettledMetricResolver.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/NetworkSettledResourceContext.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/TimeBasedInitialResourceIdentifier.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/networksettled/NetworkSettledMetricResolverTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/networksettled/TimeRequestBasedValidatorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/Configurator.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/InternalResourceContextFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/NetworkSettledResourceContextFactory.kt
In this PR we are adding the logic for resolving the newly introduced `Time To Network Settled` out-of-the-box view loading metric.
**Start**: Begins with RUM ViewScope initialization.
**End**: Tied to the end of the last resource load that commenced in the initial 100ms window or defined by the given strategy in the configuration. In case the application went into background or a new view started by the time the initial resources finished loading we will not report this metric for that specific view. In general this could be phrased as:
in case the view was stopped before all the resources were loaded we will not report this metric.
```mermaid
gantt
title Timeline for Time-to-Network-Settled
dateFormat  HH:mm:ss
section Time-to-Network-Settled
View Becomes Visible: des1, 00:00:00, …
```
=> RUM-7191 Implemented the basic logic for time-to-network-settle view metric

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/ReflectionUtils.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtilsTest.kt
* Decouple Compose reflection functions from `SemanticsUtils` to `ReflectionUtils`.
* Add Unit test to `SemanticsUtils`
* Clean up `ComposeReflection` so they can have unified logs and report to Telemetry.
* 
RUM-7081
RUM Telemetry result:
=> RUM-7081: Decouple Compose reflection functions and report to Telemetry

features/dd-sdk-android-session-replay-compose/api/apiSurface, features/dd-sdk-android-session-replay-compose/api/dd-sdk-android-session-replay-compose.api, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/ModifierExt.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ContainerSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ImageSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextFieldSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ContainerSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextFieldSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/TextSemanticsNodeMapperTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/FineGrainedMaskingSample.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/SampleSelectionScreen.kt
* Add Session Replay FGM override APIs for 
* ImagePrivacy
* TextAndInputPrivacy
* TouchPrivacy
* Implement `ImagePrivacy` and `TextAndInputPrivacy` in the semantics mapper.
RUM-7341
Touch Privacy will be applied in following commit
In each grid, the title of the grid means the override privacy of the content:
| Sampe App| Global configuration is Mask all | Global configuration is Mask none|
|<img width="283" alt="Screenshot 2024-11-27 at 13 01 32" src="https://github.com/user-attachments/assets/4101394b-af8b-4235-bc64-ba0f6f87b323">  |<img width="280" alt="Screenshot 2024-11-27 at 10 48 17" src="https://github.com/user-attachments/assets/2bfc63a1-6724-457c-b964-eb60568eeb45">   |<img width="282" alt="Screenshot 2024-11-27 at 10 51 12" …
=> RUM-7341: Add Compose FGM override API

features/dd-sdk-android-session-replay-compose/api/dd-sdk-android-session-replay-compose.api, features/dd-sdk-android-session-replay-compose/consumer-rules.pro, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/data/BitmapInfo.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ImageSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/ReflectionUtils.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtilsTest.kt
This is a follow up commit of this [PR](https://github.com/DataDog/dd-sdk-android/pull/2415) 
Move ImageSemanticsMapper reflection functions into ReflectionUtils
=> Move ImageSemanticsMapper reflection functions into ReflectionUtils

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/telemetry/configuration-schema.json, features/dd-sdk-android-rum/src/main/json/telemetry/usage/browser-features-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/TelemetryConfigurationEventForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryConfigurationEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
Adding `isMainProcess` property into telemetry configuration
We are trying to understand how are our customers using the SDK and if they are tracking their applications in the main process only
=> RUM-7070: supporting is_main_process property in telemetry configuration

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/Rum.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumConfiguration.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/InitialResourceIdentifier.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/NetworkSettledMetricResolver.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/NetworkSettledResourceContext.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/networksettled/TimeBasedInitialResourceIdentifier.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/metric/networksettled/InitialResourceIdentifier.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/metric/networksettled/NetworkSettledResourceContext.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/metric/networksettled/TimeBasedInitialResourceIdentifier.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumConfigurationBuilderTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/networksettled/TimeBasedInitialResourceIdentifierTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/metric/networksettled/NetworkSettledMetricResolverTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/metric/networksettled/TimeBasedInitialResourceIdentifierTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ConfigurationRumForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/NetworkSettledResourceContextFactory.kt
Following the RFC we are introducing the `setNetworkSettledInitialResourceIdentifier` API as part of the `RumConfiguration#Builder` in order to provide external control on which resource started in a view will be take part
in the `time-to-network-settled` metric computation. The default identifier being used is a `TimeBasedResourceIdentifier` with a default threshold set to `100ms`. This could be re - used by our users in the Configuration `Builder` by changing the `time interval` to their internal needs.
In addition to this this PR contain a small but very important fix in the `RumViewScope` where we make sure the `NetworkSettledMetricResolver` is notified for the `view stopped` only if the event was sent for the current view and only once. …
=> RUM-7174 Introduce the setNetworkSettledInitialResourceIdentifier API

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/test/elmyr/MappingContextForgeryFactory.kt, features/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/forge/MappingContextForgeryFactory.kt, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/TouchPrivacyManager.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/MappingContext.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/MappingContextForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducerTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversalTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/FineGrainedMaskingSample.kt
* Apply touch privacy override in `RootSemanticsMapper`
* Move `TouchPrivacyManger` into `MappingContext` so that RootSemanticsMapper can have access
RUM-7476
=> RUM-7476: Apply touch privacy override in RootSemanticsMapper

integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogEventListener.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogEventListenerTest.kt
In this PR we are trying to get rid of `Thread.sleep `instructions inside `DatadogEventListenerTest.kt`.
To do so we use `sdkCore.time.deviceTimeNs` at DatadogEventListener.kt instead of `System.nanoTime()` method which let us mock time values 
This approach makes this test independent from CI machine time and should increase test stability
This is a WIP PR so changes could be non-final. 
=> [RUM-3845] Trying to get from Thread.sleep(SHORT_SLEEP_MS) in unit tests at DatadogEventListenerTest

features/dd-sdk-android-session-replay-compose/consumer-rules.pro, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/ReflectionUtils.kt
`Coil` has done a migration on the painter class in this [PR](https://github.com/coil-kt/coil/commit/f0aa7aa2163f1221355b8cadb97411badd620794), which causes our reflection not able to retrieve the bitmap painter, This PR is to add the support before the migration.
RUM-6535
=> RUM-6535: Add backwards compatibility for Coil AsyncImage

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/net/DefaultFirstPartyHostHeaderTypeResolver.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/net/DefaultFirstPartyHostHeaderTypeResolverTest.kt, detekt_custom.yml
Changing logic with subdomain lookups. Now algorithm follows next logic : 
* first search the exact match
* if not found, check match for subdomain pattern
* if not found search for the * entry
This change puts matching logic into valid order: from strict to lenient one
=> RUM-6454: fixing potential issues with subdomain host lookup

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/interactiontonextview/ActionTypeInteractionValidator.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/interactiontonextview/InternalInteractionContext.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/StorageEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/metric/interactiontonextview/PreviousViewLastInteractionContext.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/interactiontonextview/ActionTypeInteractionValidatorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ActionSentForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/Configurator.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/PreviousViewLastActionContextFactory.kt
The interval we consider for the interaction-to-next-view metric is the moment the last action finished on the previous view until the moment the new view was created. Based on the last discussion we decided to completely rely on the RUM ActionEvents that were sent as potential last interactions meaning that we had to do several changes in the `RumActionScope` by reporting more information in the `ActionSent` event to the `RumViewScope`.
=> Fix the way we are recording the last interaction for ITNV metric

features/dd-sdk-android-trace/src/main/java/com/datadog/trace/api/GlobalTracer.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/api/profiling/Profiling.java, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt
Remove unused Datadog `GlobalTracer` class to avoid confusion with opentracing `GlobalTracer`
RUM-7527
=> RUM-7527: Remove unused Datadog GlobalTracer class

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/ModifierExt.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ComposeHiddenMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ComposeHiddenNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapperTest.kt
Show hide placeholder wireframe when user calls `.sessionReplayHide(hide = true) ` on the composable modifier.
RUM-7567
A demo about how it looks like:
=> RUM-7567: Apply hide view override on semantics node

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/StorageEvent.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
Currently if a resource was stopped with an error we are computing the TTNS metric no matter if the error event was persisted or not. To align with the the approach we took for the normal resource stop we will have to make sure that the TTNS metric will only be computed when the error event was persisted.
=> RUM-7643 Correctly handle TTNS when resource was stopped with error

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/AndroidComposeViewMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ComposeViewMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/ReflectionUtils.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/test/elmyr/MappingContextForgeryFactory.kt, features/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/forge/MappingContextForgeryFactory.kt, features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/DefaultInteropViewCallback.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/InteropViewCallback.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/MappingContext.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/MappingContextForgeryFactory.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/SampleSelectionScreen.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/WebViewSample.kt
A callback `InteropViewCallback` is added inside `mappingContext` so that in semantics tree, whenever an interop view is seen in the semantics node, this callback can be called to map in the way of how we are doing in the `TreeViewTraversal`.
with this PR, `AndroidView` can be seen in Session Replay, WebView embedded with `AndroidView` can be seen as well.
RUM-7195
o
=> RUM-7195: Support interop view from Compose

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
PerformanceMetric events are triggered automatically by some of the cross platform frameworks, and can result in log spam as views transition or if no view is active.  Fix it so that the performance metric event is considered a silent orphaned event type.
refs: RUM-6138
=> fix: Don't warn about missing view on PerformanceMetric events

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolver.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolverTest.kt
Fixes an issue where the `ResourcesLruCache` was being missed due to the wrong drawable being used. 
We are copying the drawable before creating the bitmap, and were using the copied drawable as the cache key for the new resourceId. However we query the cache with the original drawable. In this pr the original drawable is passed in to use as the basis for the key when writing to the cache.
=> Fix cache misses due to wrong drawable

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/service/LogsForegroundService.kt, sample/kotlin/src/main/res/drawable/ic_baseline_action_24.xml, sample/kotlin/src/main/res/drawable/ic_baseline_end_res_24.xml, sample/kotlin/src/main/res/drawable/ic_baseline_start_res_24.xml
In order to get a better signal from our telemetry, we update the logs when a view ends with a duration less than or equal to zero: 
- We distinguish negative and nul duration
- We add additional attributes to get more insights
- We exclude legitimate nul duration cases for background crashes.
=> Improve telemetry on invalid view duration

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
The way our telemetry was set up, we could send warnings when there shouldn't have been : 
- if a previous RumViewScope was stopped but kept to wait for children event to be sent, it would always send a warning saying there's no active view, even if an actual active view would actually handle the event.
=> Fix internal telemetry on invalid loading time usage

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SliderSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SliderSemanticsNodeMapperNodeMapperTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/SelectorSample.kt
=> RUM-7216: Add Slider semantics node mapper

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt
In Compose Session Replay, we setup some telemetry to monitor if the reflection is broken on client side, in the current version we noticed that some telemetries are false alert, so we need to remove them.
In this PR, we remove following reflection telemetry:
* paragraphInfoList
* ContentPainterModifier
* AsyncImagePainter
* ContentPainterElement
* layout
* paragraph
RUM-7870
=> RUM-7870: Remove non-critical Compose reflection error from telemetry

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SwitchSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RootSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SwitchSemanticsNodeMapperTest.kt
Adds support for the Compose Switch component. For the masked state returns an empty track, for the off state returns a white thumb on a white track, for the on state returns a black thumb on a black track. These colors are temporary until we can find a way to get the actual colors for the thumb and track.
Masked
Off
On
Additional mapper to support Compose. 
=> RUM-6199: Add Semantics mapper for Switch

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
Tiny change to use KDoc-specific syntax to properly reference existing code symbols.
=> Fix KDoc for `RumMonitor#stopSession`

features/dd-sdk-android-session-replay-compose/build.gradle.kts, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RadioButtonSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SwitchSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/ColorUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/ColorUtilsTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/JetpackComposeActivity.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/ToggleSample.kt
In semantics tree we are not able to retrieve the complex color of some components including:
* Checkbox
* Switch
* RadioButton.
Therefore we need to assume a contrasting color based on the background color to make them as much visible as possible.
The core function judges if the background is a bright one or dark one by [ Luma forumla ](https://en.wikipedia.org/wiki/Luma_(video)), based on that, we can give the content a black color or white color.
The components turn white in dark mode:
=> RUM-7467: Apply contrasting color to semantics component

dd-sdk-android-internal/api/apiSurface, dd-sdk-android-internal/api/dd-sdk-android-internal.api, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/utils/ImageViewUtils.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ImageViewMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ImageViewMapperTest.kt, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_allow_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_payload.json, instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_user_input_payload.json
The bug is introduced by this [PR](https://github.com/DataDog/dd-sdk-android/pull/2372), it fixed the padding issue when cropping the image, but it broke the clip for center crop image when it has cropToPadding as false.
This PR is to fix the problem by differentiate the parent content size by `cropToPadding` attribute, so the clip wireframe can be applied anyway.
| Before | After |
| --- | --- |
|<img width="365" alt="image" src="https://github.com/user-attachments/assets/22bd80a8-0938-4073-ae79-1ea2c0475c73" />  |<img width="382" alt="image" src="https://github.com/user-attachments/assets/3835a650-1622-4d5b-8298-ded23f02ebbb" />|
- [ ] Make sure each commit and the PR mention the Issue number (cf …
=> RUM-7472: Fix center crop image is not cropped in wireframe

features/dd-sdk-android-session-replay-compose/consumer-rules.pro, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/CheckboxSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RadioButtonSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SwitchSemanticsNodeMapper.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/ReflectionUtils.kt, features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/CheckboxSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/RadioButtonSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/SwitchSemanticsNodeMapperTest.kt, features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtilsTest.kt
Adds the correct Jetpack Compose RadioButton color to the mapper. Also adds masking support for RadioButton since it was not part of the original pr that added RadioButton support. 
Part of the support for Jetpack Compose.
=> RUM-7116: Add RadioButton color

integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt
This attribute should be in the range `[0;1]`, but [Sampler#getSampleRate](https://github.com/DataDog/dd-sdk-android/blob/54a38b64e366225767d1dad95b5e0271b329e9a9/dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/sampling/Sampler.kt#L23-L28) returns a value in the range `[0;100]`, so we need to normalize.
=> Fix `_dd.rule_psr` attribute calculation for RUM

.gitlab-ci.yml, features/dd-sdk-android-trace/src/main/java/com/datadog/legacy/trace/common/sampling/RateByServiceSampler.java, features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/propagation/DatadogHttpCodec.java, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/data/OtelTraceWriter.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/data/TraceWriter.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/data/OtelTraceWriterTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/data/TraceWriterTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/CoreDDSpanForgeryFactory.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/DDSpanContextForgeryFactory.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/SpanForgeryFactory.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/propagation/DatadogHttpCodecTest.kt, integrations/dd-sdk-android-okhttp-otel/src/main/kotlin/com/datadog/android/okhttp/otel/OkHttpExt.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutTracesTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorContextInjectionSampledTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt, reliability/single-fit/okhttp/build.gradle.kts, reliability/single-fit/okhttp/src/test/kotlin/com/datadog/android/okhttp/HeadBasedSamplingTest.kt, reliability/single-fit/okhttp/src/test/kotlin/com/datadog/android/okhttp/tests/assertj/SpansPayloadAssert.kt, reliability/single-fit/okhttp/src/test/kotlin/com/datadog/android/okhttp/tests/elmyr/OkHttpConfigurator.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/otel/OtelTracerProviderTest.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubSDKCore.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/tests/ktx/JsonObjectExt.kt, sample/kotlin/src/main/res/layout/fragment_traces.xml, settings.gradle.kts
This PR implements [Head-based sampling](https://docs.datadoghq.com/tracing/trace_pipeline/ingestion_mechanisms/?tab=java#head-based-sampling) for the network instrumentation to align with default sampling existing in other Datadog tracers.
In short, Head-based sampling (HBS) allows to have a single sampling decision for the whole trace: it is kept or dropped, instead of the individual spans.
This also aligns with the following changes in iOS SDK done in the past:
* https://github.com/DataDog/dd-sdk-ios/pull/1783
* https://github.com/DataDog/dd-sdk-ios/pull/1793
* https://github.com/DataDog/dd-sdk-ios/pull/1794
Now, if there is a parent span (propagated through the headers or via request tag; OpenTracing or OpenTelemetry), then its sampling decision will be taken into account instead of …
=> RUM-8051: Implement Head-based sampling for network instrumentation

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcher.kt
Adjust the metrics sampling rate, to ensure we have consistent data across platforms, and don't overwhelm our intake.
=> Adjust telemetry metrics sampling rates

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/rum/_common-schema.json, features/dd-sdk-android-rum/src/main/json/rum/action-schema.json, features/dd-sdk-android-rum/src/main/json/rum/resource-schema.json, features/dd-sdk-android-rum/src/main/json/rum/view-schema.json, features/dd-sdk-android-rum/src/main/json/telemetry/configuration-schema.json, features/dd-sdk-android-rum/src/main/json/telemetry/usage/common-features-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/DatadogLateCrashReporter.kt
Updates RUM schema to the most recent version.
It was done by using gradle tasks in the RUM target. I also checked SR, but there were no changes.
=> Update RUM Schema

integrations/dd-sdk-android-okhttp/api/apiSurface, integrations/dd-sdk-android-okhttp/api/dd-sdk-android-okhttp.api, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutRumTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutTracesTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/TracingInterceptorBuilderTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorContextInjectionSampledTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt
Adds an option to keep the resource name for network requests ending in `404` as original, instead of having them redacted to `"404"`.
=> RUM-8314 allow disabling 404 span redaction

features/dd-sdk-android-trace/api/dd-sdk-android-trace.api, features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/propagation/DatadogHttpCodec.java, features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/propagation/W3CHttpCodec.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/propagation/HttpCodec.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/propagation/PropagationTags.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/propagation/ptags/PTagsCodec.java, features/dd-sdk-android-trace/src/main/java/com/datadog/trace/core/propagation/ptags/PTagsFactory.java, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/propagation/DatadogHttpCodecTest.kt
As part of our Joint Sampling project, we forward the RUM session ID as tag in the tracing headers (DD and W3C style).
=> RUM-8366 Forward RUM Session ID in trace headers

docs/sdk_performance.md
=> RUM-7809: Update SDK performance doc with Session Replay measurements

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/attributes/LocalAttribute.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/attributes/ViewScopeInstrumentationType.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/logger/SdkInternalLogger.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/logger/SdkInternalLoggerTest.kt, dd-sdk-android-internal/api/apiSurface, dd-sdk-android-internal/api/dd-sdk-android-internal.api, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/telemetry/InternalTelemetryEvent.kt, features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/rum/_rect-schema.json, features/dd-sdk-android-rum/src/main/json/rum/_view-performance-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/ViewEndedMetricDispatcher.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/BundleExt.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/metric/ViewEndedMetricDispatcherTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, integrations/dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/internal/ComposeNavigationObserver.kt, integrations/dd-sdk-android-compose/src/test/kotlin/com/datadog/android/compose/internal/ComposeNavigationObserverTest.kt
Adds support for optional instrumentation_type attributes into view ended telemetry metric.
[Spec](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/4534173727/RUM+View+Ended+Telemetry+-+Spec)
[Previous](https://github.com/DataDog/dd-sdk-android/pull/2495) PR was too big to add this logic, I'd decided to split them into two separate ones 
I noticed that we were using the additionalAttributes map as a container for some local values that shouldn't be passed 
directly to the backend, but used to determine some values just before the actual events are sent, so as a side effect of this PR the local attributes logic has been refactored: Added a single place for such attributes and their cleanup.
- …
=> [RUM-8375]  View ended instrumentation type attribute support

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/attributes/LocalAttribute.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/attributes/ViewScopeInstrumentationType.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/logger/SdkInternalLoggerTest.kt, features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/json/telemetry/configuration-schema.json, features/dd-sdk-android-rum/src/main/json/telemetry/usage/common-features-schema.json, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/metric/interactiontonextview/TimeBasedInteractionIdentifier.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/metric/networksettled/TimeBasedInitialResourceIdentifier.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/metric/ViewEndedMetricDispatcherTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ConfigurationRumForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryConfigurationEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, integrations/dd-sdk-android-compose/src/test/kotlin/com/datadog/android/compose/internal/ComposeNavigationObserverTest.kt
Adds support for INV and TNS time-based thresholds if they used for metric collection
Small side effect on LocalAttribute - making `string` field private
=> [RUM-8098] Support for configuration schema updates for time based strategy of TNS and INV metrics

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/UploadWorker.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtils.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallbackTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
* change UploadWorker from internal to public
* Add doc to warn client that it should only be used in custom workfactory case
Fixes #2508
RUM-8705
=> RUM-8705: Change UploadWorker visibility from internal to public

features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/handlers/AndroidSpanLogsHandler.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/handlers/AndroidSpanLogsHandlerTest.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/opentracing/UtilitiesTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt
Ensures that the logs created from a `DDSpan.log()` behave the same way as the ones created from our `Logger` with `bundleWithTrace=true`.
=> RUM-8729 ensure span logs use 128 bits trace id as hex string

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
This PR aims to fix and match the behaviour of the first call made to `addViewLoadingTime`, so it properly logs the newLoadingTime that it has just calculated and that it will use to set viewLoadingTime to just a few lines after this log is registered.
The change is as simple as changing the log call to use `newLoadingTime` instead of `viewLoadingTime`.
This change is done so both Android and iOS SDKs behave in the same way, and also so the SDK avoids logging the initial null value of `viewLoadingTime`, which may confuse users into thinking that there's something wrong by logging a message like:
`[_dd.sdk_core.default]: View loading time nullns added to the view Main`
instead of:
`[_dd.sdk_core.default]: View loading time 525.0829529762268ns added to the view Main`
Found this while …
=> Avoid logging initial null viewLoadingTime on first call to addViewLoadingTime

dd-sdk-android-core/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnable.kt
It seems the Kotlin Coroutines machinery can throw `Error` sometimes while getting all threads stacktraces. In this PR we will catch them, so that we don't interrupt the flow.
=> Catch Coroutines errors while getting all threads stacktraces

.github/workflows/codeql-analysis.yml
Upgrade the CodeQL action to use `ubuntu-latest` over the deprecated `ubuntu-20.04` image
Github will be disabling `ubuntu-20.04` at the end of March.
=> chore: Upgrade github action to use ubuntu-latest

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/_RumInternalProxy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumInternalProxyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListenerTest.kt
Add a method to `AdvancedRumMonitor` to manually add an activity to JankStats tracking so that we can get framerate information.
Unity's main activity is started prior to initializing Datadog, so it misses adding the Activity to JankStats tracking. 
=> [RUM-8875] Add ability to manually add an activity to JankStats

features/dd-sdk-android-session-replay/api/apiSurface, features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayInternalCallback.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/_SessionReplayInternalProxy.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayLifecycleCallback.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayInternalProxyTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorderTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/SessionReplayConfigurationForgeryFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
- Exposes a new SessionReplayConfigutation option to allow clients to pass their own implementations of specific methods used in the Session Replay SDK. 
- Updates the SDK code to use the overriden function if provided and falling back to the original implementation otherwise. 
( Currently only `getCurrentActivity` is allowed to be redefined, but there's a high likelihood that more will be needed ) 
Certain parts of the session replay SDK don't  work as intended when ran in a react-native environment, leading to broken replays. In order to keep platform specific code out of the android SDK, the goal is to allow each client to add their own implementations of the parts that don't work.
We keep the `setInternalCallback` only accessible through …
=> [RUM-8652] Allow definition of custom implementations of specific SR methods

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
Allow the Flutter First Build Complete vital to be any numeric type, then convert it to long when creating the Performance structure.
Flutter will truncate Longs down to Ints if they are below a certain value, which was causing the `as? Long` cast to fail
=> fix: Allow first build complete to be any number format

CHANGELOG.md
The following commit https://github.com/DataDog/dd-sdk-android/commit/eddf6d89cc06d7b5e5c6912278d3815a99c10de3 shipped with release `2.11.0` moved existing `com.datadog.trace` package to the `com.datadog.legacy.trace` and as a result `com.datadog.trace` had new members.
This can leads to the following, as an example:
`com.datadog.trace.api.interceptor.MutableSpan` got renamed to `com.datadog.legacy.trace.api.interceptor.MutableSpan`, but also a new `com.datadog.trace.api.interceptor.MutableSpan` was added, so the following code written by the customer:
```
import com.datadog.trace.api.interceptor.MutableSpan
// some resourceName configurations here
(span as? MutableSpan)?.resourceName = resourceName
```
will do nothing, because `span` instance now implements …
=> Update 2.11.0 changelog with a note about `com.datadog.trace` package move

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/net/RumRequestFactory.kt
With https://github.com/DataDog/dd-sdk-android/pull/2298/files#diff-f064e155f59f2de7bfba9d1771f4f6721c48ba34cc1247e8cca065129dedf51b the double computation of the RUM upload body was added, but in fact `MessageDigest.digest` (-> `MessageDigest.update` under the hood) doesn't mutate input data, so it is safe to use it even after calling this method.
=> Remove double computation of the RUM payload

local_ci.sh
Makes `./local-ci.sh --setup` check for a specific version of KTLint instead of just outputting your current version. Also ask if you want to upgrade detekt after printing the current version.
Older / incorrect versions of KTLint will clash with what's on CI, giving fewer or more errors than what CI.
=> chore: Set the local-ci script to check for specific version of KTLint

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/LegacyDrawableToColorMapper.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/LegacyDrawableToColorMapperTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/ImageComponentsFragment.kt, sample/kotlin/src/main/res/drawable/selector_statelist_images_no_default.xml, sample/kotlin/src/main/res/layout/fragment_image_components.xml
`LegacyDrawableToColorMapper.mapDrawableToColor` can crash with NPE when invoked on a `StateListDrawable`, whose `getCurrent()` method returns `null`. This can happen when `<selector>` doesn't contain the default item.
demo [internal]
https://mobile-integration.datadoghq.com/rum/replay/sessions/de3b1c36-f346-4733-abdf-d295f21b99e4?seed=31a96bad-0d88-4292-8e2f-9dd615cadab4&ts=1741884288920
=> Fix NPE when Drawable.getCurrent returns null

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableExt.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableExtTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtilsTest.kt
Sometimes `Drawable.draw(canvas)` can throw an `AndroidRuntimeException` when called not on the main thread. We catch this exception.
[internal]
For full investigation see the jira ticket https://datadoghq.atlassian.net/browse/RUM-7664?focusedCommentId=2227218
=> RUM-7664: Add try-catch in drawOnCanvas in order to catch exceptions from draw(canvas) method

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/MetricsDispatcher.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorage.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/FileOrchestrator.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileOrchestrator.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/single/SingleFileOrchestrator.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorageTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestratorTest.kt, detekt_custom.yml
Adds to `batch deleted` events the number of pending batch files in the directory at the time the metric was sent.
Additional telemetry to increase transparency.
=> RUM-8041: Add telemetry for pending batch files

detekt_custom.yml, features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumConfiguration.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/configuration/SlowFramesConfiguration.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/state/ViewUIPerformanceReport.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/slowframes/SlowFramesListener.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/FrameStatesAggregator.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumConfigurationBuilderTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/slowframes/DefaultSlowFramesListenerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/FPSVitalListenerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/FrameStatesAggregatorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ConfigurationRumForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/Configurator.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/SlowFrameListenerConfigurationForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/SlowFramesListenerConfigurationForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ViewUIPerformanceReportForgeryFactory.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
In this PR I made several changes, mostly targeted to make implementation bit cleaner:
1.  Aligned threshold constants for `SlowFrameListener` with iOS.
2. `JankStatsActivityLifecycleListener`  renamed into FrameStatesAggregator as this name better represents responsibility of this class 
3. Initialization logic of `FrameStatesAggregator` refactored in `RumFeature` in order to avoid unpredictable behavior: `JankStatsActivityLifecycleListener` was initialized only within vital monitor logic when `VitalsUpdateFrequency` != `NEVER`
4. Fixed discrepancies with freezeRate and slowRate computation
PR targets into RUM-8654  …
=> [RUM-9065] Bugfixes and platform alignment

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/slowframes/SlowFramesListener.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/slowframes/DefaultSlowFramesListenerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/AddCustomTimingEventForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/AddErrorEventForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/AddFeatureFlagEvaluationForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/AddFeatureFlagEvaluationsForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/Configurator.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/ErrorSentForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/KeepAliveForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/LongTaskSentForgeryFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/SlowFramesConfigurationForgeryFactory.kt
Changes logic for ui slowness report a bit: now report is removed only when view is complete
We have an issue with `resolveReport` method implementation: report was removed from the map when `resolveReport`  is called, so in case if there are several events within the view scope -  report will be sent only for the first update
These changes should be part of the [main feature branch PR](https://github.com/DataDog/dd-sdk-android/pull/2518) but it was too big so I've decided to merge them separately
=> [RUM-9151]: fix issue with missing freeze rate and slow frames rate

features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListener.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListenerTest.kt
* Reverting SDK constraints for  `registerMetricsListener` and `unregisterMetricsListener` to S
* Add tests  and comments to prevent this issue from happening in the future 
[Issue](https://github.com/DataDog/dd-sdk-android/issues/2556)
=> [RUM-9154]: reverting back os version constraints to S for registerMetricsListener and unregisterMetricsListener

features/dd-sdk-android-trace/src/main/java/com/datadog/legacy/trace/api/Config.java
This PR removes the functionality of reading Tracer config from env variables and config file: both are options are not possible on Android.
It gives saves quite a good time during the Tracer initialization:
* before the change
* after the change
In theory, we can also remove config read from system properties (`System.getProperties`), but these ones can be set from the process (unlike env variables). Unlikely that it is used by any customer, but anyway removal of this block won't give a significant gain.
=> Remove the possibility to read Tracer config from env and from config file

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/DatadogCore.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreInitializationTest.kt, dd-sdk-android-internal/api/apiSurface, dd-sdk-android-internal/api/dd-sdk-android-internal.api, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/telemetry/InternalTelemetryEvent.kt, dd-sdk-android-internal/src/testFixtures/kotlin/com/datadog/android/internal/tests/elmyr/InternalTelemetryConfigurationForgeryFactory.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryConfigurationEventAssert.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutTracesTest.kt, integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt, sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
It adds a sampling rate from OkHttp interceptor to the telemetry configuration event. In the `init` block of `TracingInterceptor` we put the sampling rate into the feature context of the tracing feature. And then extract it in `DatadogCore.sendCoreConfigurationTelemetryEvent` when we send the event to the Rum feature.
Problems that remain unsolved:
1. If `TracingInterceptor` is created before `DatadogCore` then we will not send the sampling rate, because there is no way to submit the feature context without having an instance of `DatadogCore`. It happened in the sample app. I fixed it by making necessary things lazy.
2. There can be multiple instances of `TracingInterceptor` in the app and we don't know which one's sampling rate will be sent.
But for our purposes it looks like that these …
=> RUM-593: [Android] - Add traceSampleRate to Telemetry Configuration Event

integrations/dd-sdk-android-compose/api/apiSurface, integrations/dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/DatadogModifier.kt, integrations/dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/RecordImages.kt, integrations/dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/TrackViews.kt
* Add `datadog` function to be instrumented by Kotlin Compiler plugin for image recordings in Jetpack Compose
* Add annotations `RecordImages` and `TrackViews` for instrumentation annotation mode.
=> Add Compose instrumentation API for view tracking and image recording

detekt_custom.yml, features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/AndroidActionTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActionTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ViewTarget.kt
Prior to this PR, `GesturesListener` is coupled with Android View framework to find a target view of user interaction, making it difficult to extend to Jetpack Compose.
To make the Jetpack compose view finding possible within `GesturesListener`, this PR adds an interface called `ActionTrackingStrategy`, and move all the Android View framework logic from `GestureListener` into the `AndroidActionTrackingStrategy` implementation.  This change makes `GesturesListener` agnostic about the view framework, prepares for the Compose actions tracking integration
RUM-9309
=> RUM-9309: Add `ActionTrackingStrategy` Interface to decouple find view logic

features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/data/OtelTraceWriter.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/data/OtelTraceWriterTest.kt
Alignment with the change made in https://github.com/DataDog/dd-sdk-android/pull/2568.
Incoming collection is not supposed to be mutable.
=> Change `OtelTraceWriter#write type` from `MutableList` to `List`

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
A very minor 🤏 optimization for the features context read in the `TelemetryEventHandler`: it is already available in the `DatadogContext` object, so there is no need to do additional queries.
=> Optimize features context reads in `TelemetryEventHandler`

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/slowframes/SlowFramesListener.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/slowframes/UISlownessMetricDispatcher.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/slowframes/DefaultSlowFramesListenerTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/slowframes/DefaultUISlownessMetricDispatcherTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
* Fixes negative value for `start` variable for slow frames record
* Adds `missed_count` for ui slowness telemetry to see how often such events occurs 
* Adds `view_duration` value to align with iOS implementation
=> [RUM-9361] fixing negative values in slow frames, adjusting telemetry

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesDetectorWrapper.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesDetectorWrapperTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt
Prior to this PR, `RumMonitor.addActions(RumActionType.Tap)` will always be called twice for a single tap action, this is because that in `GestureListener` both `onSingleTapUp` and `onUp` are called by `GesturesDetectorWrapper` when a ACTION_UP is received. both functions will call `addActions` for this tap.
The fix is to make `onSingleTapUp` return true, indicating that the tap is already consumed and should not be handled it again.
RUM-9340
=> RUM-9340: Fix RumAction Tap is added twice for every ACTION_UP

features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/scopemanager/ContextualScopeManager.java, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/AndroidTracerTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/utils/TracerExtensionsTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/scopemanager/ScopeTestHelper.kt
This reverts commit 32afc41a21d49d505fc7dc1fadabbfd6676d8096.
The original commit attempted to allow using the tracer in a kotlin coroutine context, but ended up leading to possible memory leaks. Before we write a better integration with couroutines, we revert this to prevent the memory leak
=> Revert "Remove shared ThreadLocal scopes"

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/AndroidActionTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtils.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ViewTarget.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/ViewTargetTest.kt, integrations/dd-sdk-android-compose/src/test/kotlin/ComposeActionTrackingStrategyTest.kt
Prior to this PR, we were using `WeakReference` on `ViewTarget`, since `ViewTarget` is a local variable only in the scope of `findTarget` function, after execution, there will be zero reference of it, and if GC occurs, the object in  `WeakReference` will be cleaned. 
The correct way is that we should use strong reference of `ViewTarget`, but inside `ViewTarget` we hold weakReference of `View`. 
Also a dedicated GC unit test is added to cover this case.
=> Fix ViewTarget is garbage collected during actions tracking

features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/IdentityKeyTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/SpanCleanerTest.kt
After analysing the borrowed code from the deprecated APM java tracer following some internal investigations `PendingTrace` was actually leaking in 2 places:
1. In one place when using `dropSpan` the cleaner could not actually clean the `PendingTrace` reference and this was persisted forever in the `pendingTraces` set. Basically when the cleaner was trying to `clean` that method was doing nothing as there was no pending Span to write and the reference was not removed. 
2. Because of using a mutable `LinkedList` as an entry key to a `Set<PendingTrace>`. Basically because the key is resolved from the `LinkedList#hashCode()` method which is dependent on the values contained in the list first time a `PendingTrace` is created the `hashCode()` is always `1` and when later we're trying to remove …
=> RUMS-4305 Fix the memory leak in the `PendingTrace#cleaner`

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/interactiontonextview/InteractionToNextViewMetricResolver.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/interactiontonextview/InteractionToNextViewMetricResolverTest.kt
…not have itv metric
I performed a thorough functionality check on the way we resolve the ITV metric and everything seems to work fine. I chose to remove the noisy log when the metric could not be resolved as for some views (especially the first ones that are loaded automatically without any user interaction) this behaviour is normal.
=> RUM-9410 Remove the noisy warning log as for some views is normal to not have itv

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/DrawableUtils.kt
We have a SDK crash reported:
```
2025-04-15 15:52:34.448 27880-28415 Datadog com.carvana.carvanaTest E java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.shape.ShapePath$PathOperation.applyToPath(android.graphics.Matrix, android.graphics.Path)' on a null object reference
at com.google.android.material.shape.ShapePath.applyToPath(ShapePath.java:244)
at com.google.android.material.shape.ShapeAppearancePathProvider.appendEdgePath(ShapeAppearancePathProvider.java:202)
at com.google.android.material.shape.ShapeAppearancePathProvider.calculatePath(ShapeAppearancePathProvider.java:135)
at com.google.android.material.shape.MaterialShapeDrawable.calculatePathForSize(MaterialShapeDrawable.java:1165)
at …
```
=> RUM-9537: Catch NPE when drawing cloned drawable in Session Replay

.gitignore, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/GenerateTransitiveDependenciesTask.kt, features/dd-sdk-android-trace-otel/transitiveDependencies, gradle/libs.versions.toml, integrations/dd-sdk-android-glide/transitiveDependencies, integrations/dd-sdk-android-okhttp-otel/transitiveDependencies, integrations/dd-sdk-android-okhttp/transitiveDependencies, integrations/dd-sdk-android-sqldelight/transitiveDependencies, integrations/dd-sdk-android-trace-coroutines/transitiveDependencies, sample/vendor-lib/build.gradle.kts, tools/unit/build.gradle.kts
This PR does the following:
* Updates `unMock` plugin version mainly to benefit from the following change https://github.com/bjoernQ/unmock-plugin/pull/83
* Removes unused `me.xdrop:fuzzywuzzy` dependency
* Removes deprecated Gradle APIs to be better compatible with Gradle 9.0
* `Configuration.files` -> `Configuration.incoming.artifactView` brings a visibility on the lib dependencies used in the project dependencies.
=> Update `unMock` plugin version, remove `me.xdrop:fuzzywuzzy` dependency, remove deprecated Gradle APIs

.github/workflows/codeql-analysis.yml, .gitlab-ci.yml, features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java
Replace addFirst usage in PendingTrace, since it can have clash with Android API 35.
It contains some additional pipeline fix to pass CI
=> RUM-9894: Replace `addFirst` usage in PendingTrace

features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java
Replace addFirst usage in PendingTrace, since it can have clash with Android API 35.
RUM-9894
=> RUM-9894: Replace addFirst usage in PendingTrace

dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/BaseTest.kt, reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/FeatureScopeTest.kt
Some instrumented tests in the `FeatureScopeTest` are using unconditional `Thread.sleep` with a wait time of 30 seconds.
This PR brings some improvement in the execution time by introducing more precise waiting (but not eliminating it completely): now we will wait for the all write operations to complete before jumping to the assertion section and the only unconditional wait to use is the wait for the next upload cycle.
This is just a **quick improvement**, there is a TODO item to make it even better in the future.
=> Speed up some tests in `FeatureScopeTest` by reducing unconditional wait time

sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/DatadogActivityModule.kt
Unfortunately in my previous [pr](https://github.com/DataDog/dd-sdk-android/pull/2647) I made a mistake. All baseline benchmark runs started crashing (except session replay ones).
For example for LogsCustom scenario we still use `Logger` in baseline run [link](https://github.com/DataDog/dd-sdk-android/blob/develop/sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logscustom/LogsScreenViewModel.kt#L77), but it should be the no-op one. When it gets created [here](https://github.com/DataDog/dd-sdk-android/blob/develop/sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/DatadogActivityModule.kt#L83), it requires `sdkCore`, that tries to get created but crashes [here](https://github.com/DataDog/dd-sdk-android/blob/develop/sample/benchmark/src/main/java/com/datad …
=> RUM-9958: Fix datadog core creation in baseline benchmark run

integrations/dd-sdk-android-compose/build.gradle.kts, integrations/dd-sdk-android-compose/consumer-rules.pro, integrations/dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/internal/utils/LayoutNodeUtils.kt
Using internal field `collapsedSemantics` of `LayoutNode` may not work in all the build types, so this PR replaces it with classic reflection to retrieve the additional semantics information for the node.
Also fix the catch `Throwable` instead of `Exception`.
RUM-9345
=> RUM-9345: Use reflection to retrieve semantics information in modifier

buildSrc/src/main/kotlin/com/datadog/gradle/config/DetektCustomConfig.kt, features/dd-sdk-android-logs/build.gradle.kts, features/dd-sdk-android-ndk/build.gradle.kts, features/dd-sdk-android-rum/build.gradle.kts, features/dd-sdk-android-session-replay-compose/build.gradle.kts, features/dd-sdk-android-session-replay-material/build.gradle.kts, features/dd-sdk-android-session-replay/build.gradle.kts, features/dd-sdk-android-trace-otel/build.gradle.kts, features/dd-sdk-android-trace/build.gradle.kts, features/dd-sdk-android-webview/build.gradle.kts, integrations/dd-sdk-android-coil/build.gradle.kts, integrations/dd-sdk-android-compose/build.gradle.kts, integrations/dd-sdk-android-fresco/build.gradle.kts, integrations/dd-sdk-android-glide/build.gradle.kts, integrations/dd-sdk-android-okhttp-otel/build.gradle.kts, integrations/dd-sdk-android-okhttp/build.gradle.kts, integrations/dd-sdk-android-rum-coroutines/build.gradle.kts, integrations/dd-sdk-android-rx/build.gradle.kts, integrations/dd-sdk-android-sqldelight/build.gradle.kts, integrations/dd-sdk-android-timber/build.gradle.kts, integrations/dd-sdk-android-trace-coroutines/build.gradle.kts, integrations/dd-sdk-android-tv/build.gradle.kts
I noticed that during custom Detekt rules job execution there were some warnings regarding the types that cannot be resolved.
This PR removes (mostly) the need to specify project dependencies for Detekt run, although there is a pitfall: `api` configuration cannot be resolved, so we cannot know transitive project dependencies. Maybe this can be solved with detached configuration, but for now let's just specify most common modules `:dd-sdk-android-core` and `:dd-sdk-android-internal` by default for everything.
=> RUM-10120: Better project-type dependency resolution for Detekt custom rules execution

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/Datadog.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/SdkCore.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/DatadogCore.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/NoOpInternalSdkCore.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/user/DatadogUserInfoProvider.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/user/MutableUserInfoProvider.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/user/DatadogUserInfoProviderTest.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt, reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/LoggerTest.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/opentracing/AndroidTracerTest.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/otel/OtelTracerProviderTest.kt, reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubSDKCore.kt
Remove the option to set a null userId
=> RUM-9514 remove deprecated userInfo methods

features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/LogsConfiguration.kt, features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/internal/net/LogsRequestFactory.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/LogsConfigurationBuilderTest.kt, features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/net/LogsRequestFactoryTest.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumConfiguration.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/net/RumRequestFactory.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumConfigurationBuilderTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/net/RumRequestFactoryTest.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/ResourcesRequestFactory.kt, features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/SegmentRequestFactory.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/ResourcesRequestFactoryTest.kt, features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/SegmentRequestFactoryTest.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/TraceConfiguration.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/net/TracesRequestFactory.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/TraceConfigurationBuilderTest.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/net/TracesRequestFactoryTest.kt, instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/utils/StringExtensions.kt, instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt, reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/LoggerTest.kt, reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/RumConfigurationTest.kt, reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/opentracing/TraceConfigurationTest.kt
Align setting custom endpoint URL behavior with other platforms
Originally, on Android, we would only set the host, expecting the custom endpoint to have a path matching our own intake path (usually in the form `{host}/api/v2/{track}`. 
We now aim to have the same behaviour across platforms, so we take the provided url as is.
=> RUM-9923 Custom endpoint URL are taken as is

dd-sdk-android-core/api/apiSurface, dd-sdk-android-core/api/dd-sdk-android-core.api, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/logger/SdkInternalLogger.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/logger/SdkInternalLoggerTest.kt, dd-sdk-android-internal/api/apiSurface, dd-sdk-android-internal/api/dd-sdk-android-internal.api, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/attributes/LocalAttribute.kt, dd-sdk-android-internal/src/main/java/com/datadog/android/internal/attributes/ViewScopeInstrumentationType.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/ViewEndedMetricDispatcher.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/metric/ViewEndedMetricDispatcherTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt, integrations/dd-sdk-android-compose/build.gradle.kts, integrations/dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/internal/ComposeNavigationObserver.kt, integrations/dd-sdk-android-compose/src/test/kotlin/com/datadog/android/compose/internal/ComposeNavigationObserverTest.kt
I noticed that we have `LocalAttribute` class and related extension methods in the `core` module and thus extension modules can be leaked into user's space.
This PR moves them to the `internal` module which is always used as `implementation`, so no leak is possible.
=> Move `LocalAttribute` class and related extension methods to the `internal` module

features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/gson/GsonExtTest.kt
`forge.aString()` can generate numerical string like: "1", "23", etc, which make test fail,
change to `anAlphabeticalString` which doesn't contain any number.
=> Fix GsonExt flaky test

.github/workflows/changelog-to-confluence.yaml
- Updates secrets names on the Github Workflow
- Easier maintanenaince in the future
- Remove previous github Secrets from the repo  
- `CONFLUENCE_BASE_URL`  
- `ATLASSIAN_USERNAME`
- `ATLASSIAN_API_TOKEN`
=> Update changelog-to-confluence: Update secret names

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/system/DefaultAppVersionProvider.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/config/CoreFeatureTestConfiguration.kt
We need to mark some properties of `CoreFeature` as volatile: they are set from one thread and will be read from another thread - context processing thread.
=> RUM-10413: Mark `CoreFeature` properties used to create `DatadogContext` as volatile

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
There is an edge case when calling `withWriteContext`/`withContext`/... if we are in the process of SDK deinitialization.
When starting the task submitted to the context processing queue we would like to check if `CoreFeature` is still alive.
Normally, in the `CoreFeature.stop` we are calling `shutdownNow` for the executors which interrupts the threads, but just in case if the stop approach is different in the future we just put one more check.
=> RUM-10422: Handle the case when `DatadogContext` is requested when SDK is getting deinitialized

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/thread/BackPressuredBlockingQueue.kt, dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/thread/ObservableLinkedBlockingQueue.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/thread/IgnoreNewestBackPressuredBlockingQueueTest.kt, dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/thread/NotifyOnlyUnboundedBackPressuredBlockingQueueTest.kt
We need to monitor if the queue behind context executor is becoming big, so this PR modifies `BackPressuredBlockingQueue` a bit to:
* add constructor to create unbounded queue
* notify only if a given threshold is reached, separating this value from the `capacity` value which is basically `Int.MAX_VALUE` for unbounded queue.
=> RUM-9851: Monitor backpressure of context executor

ci/pipelines/default-pipeline.yml
I forgot to add `DDOCTOSTS_ID_TOKEN` to these jobs. I already added it to `dogfood-gradle-plugin` from the beginning and it [works now](https://gitlab.ddbuild.io/DataDog/dd-sdk-android/-/jobs/993672689). 
It is needed according to the [docs](https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts#%3Agitlab%3A-Via-Gitlab-CI-job).
=> RUM-10224: Add DDOCTOSTS_ID_TOKEN to dogfood-app and dogfood-demo

features/dd-sdk-android-rum/api/apiSurface, features/dd-sdk-android-rum/api/dd-sdk-android-rum.api, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/_RumInternalProxy.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt, features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumInternalProxyTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt, features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
refs: RUM-8875
This PR adds a new `updateExternalRefreshRate` function to the internal `AdvancedRumMonitor` interface, then updates `RumViewScope` so that it will populate `refresh_rate_average` and related properties based on the data received via this API function, if any such calls have been made.
If no calls have been made to `updateExternalRefreshRate` in the context of the current view, `RumViewScope` will continue to use the data collected from `frameRateVitalListener` as before.
Regardless of whether any calls are made to `updateExternalRefreshRate`, the vitals monitoring system within `com.datadog.android.rum.internal.vitals` will continue operating exactly as it does now. We make no attempt to disable or otherwise interfere with the `frameRateVitalListener`.
Per …
=> RUM-8875 Add `updateExternalRefreshRate` to internal RUM API

features/dd-sdk-android-trace-otel/transitiveDependencies, gradle/libs.versions.toml, integrations/dd-sdk-android-okhttp-otel/transitiveDependencies, tools/benchmark/build.gradle.kts
- Updating opentelemetry version up to 1.40.0
- Removing separate opentelemetry for benchmark module
1. We was pretty behind (40+ versions) from the latest opentelemetry version. 
2. On the other hand SDK v3 gonna bring many changes and upgrading to 1.40.0 feels bit safer than to the most recent opentelemetry version as we already tested it in benchmark modules. 
3. And last point - we want to reduce the amount of dependencies used in project making benchmarking closer to what we ship to production, so from this moment there will be only one opentelemetry verison for whole project 
This branch targets to opentracing-opentelemetry migration branch to be sure that all test passed for the the most recent changes 
- [ ] Make sure you discussed the feature or bugfix with the maintaining team …
=> [RUM 9903] Updating opentelemetry version

CONTRIBUTING.md
This PR updates `CONTRIBUTING` doc with new modules.
=> Update `CONTRIBUTING` doc with new modules

features/dd-sdk-android-trace-internal/api/dd-sdk-android-trace-internal.api, features/dd-sdk-android-trace-internal/src/main/java/com/datadog/trace/core/propagation/HttpCodec.java, features/dd-sdk-android-trace-internal/src/test/kotlin/com/datadog/trace/core/propagation/DatadogHttpCodecTest.kt, features/dd-sdk-android-trace-internal/src/test/kotlin/com/datadog/trace/core/propagation/HttpCodecTest.kt, features/dd-sdk-android-trace-internal/src/test/kotlin/com/datadog/trace/core/propagation/W3CHttpCodecTest.kt, features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/RumContextPropagator.kt, features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/RumContextPropagatorTest.kt, features/dd-sdk-android-trace/src/testFixtures/kotlin/com/datadog/android/trace/api/DatadogTracingTestExt.kt, features/dd-sdk-android-trace/src/testFixtures/kotlin/com/datadog/android/trace/utils/RumContextTestsUtils.kt, reliability/single-fit/okhttp/src/test/kotlin/com/datadog/android/okhttp/RumContextPropagationTest.kt, reliability/single-fit/okhttp/src/test/kotlin/com/datadog/android/okhttp/SpanExtIntegrationTest.kt
Adds support for `accountId` and `userId` propagation through `baggage` header.
Add and refactor tests that is related to rum context propagation
=> [RUM-11854]: Account id  and User id propagated in baggage header
