DataDog/dd-sdk-android

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/DatadogExt.kt

Fix a bug about having a null package version name (shouldn't probably happen in the wild, but you never know)

🐛RUMM-154 Handle null package version

---

instrumented/integration/build.gradle.kts
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/profiling/BatteryProfileForLogs.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/profiling/CpuProfileForLogs.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/profiling/LightMemoryProfileForLogs.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/profiling/MemoryProfileForLogs.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/utils/AbstractProfilingRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/utils/BatteryProfilingRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/utils/CpuProfilingRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/utils/SystemUtils.kt

Following the approach for the CPU and Memory profiling I added a new TestRule for the profiling the battery.
To provide a profiling test for the battery consumption scenario in the OKRs
There is an additional commit to the main goal where I took the chance and fixed the measurement/assertion logic for the CpuProfilingRule.

RUMM-129 Battery Profiling TestRule

---

dd-sdk-android/src/androidTest/kotlin/com/datadog/android/internal/utils/utils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/GzipRequestInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/GzipRequestInterceptorTest.kt
sample/java/src/main/java/com/datadog/android/sample/webview/WebFragment.java
sample/kotlin-timber/build.gradle.kts
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebFragment.kt

Use GZip compression to send the requests
Better performances when sending logs.

⚡️RUMM-48 gzip

---

bitrise.yml
instrumented/integration/build.gradle.kts
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/utils/CpuProfilingRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/utils/MockServerRule.kt

Add a test on Bitrise to run instrumented test against lowest and highest supported APIs
Unseen bugs on API < 24

Run instrumented test on lowest and highest APIs

---

docs/log_collection.md

Add logger creation in documentation

---

docs/log_collection.md

Wording update as it's not automated for now

Wording update

---

dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/time/DatadogTimeProviderTest.kt

Fix some flaky tests
Prevent having to restart CI jobs

RUMM-168 Fix flaky test for DatadogTimeProvider

---

.gitlab-ci.yml

Ensure the Timber artifact is published when we do a release
Resolves #90

RUMM-176 Publish Timber artifact along with SDK

---

.github/labeler.yml
.github/workflows/labels.yml
.gitlab-ci.yml
LICENSE-3rdparty.csv
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/ApiSurfacePlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/CheckApiSurfaceChangesTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/GenerateApiSurfaceTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/KotlinFileVisitor.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/gitdiff/GitConditionalDependencyTask.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/apisurface/KotlinFileVisitorTest.kt
dd-sdk-android-timber/apiSurface
dd-sdk-android-timber/build.gradle.kts
dd-sdk-android/apiSurface
dd-sdk-android/build.gradle.kts
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/GzipRequestInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/constraints/DatadogLogConstraints.kt

Have a way to detect early breaking changes for users

RUMM-155 API Surface plugin

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/ApiSurfacePlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/CheckApiSurfaceTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/BenchmarkJsonFileVisitor.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/ReviewBenchmarkExtension.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/ReviewBenchmarkPlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/ReviewBenchmarkResultsTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/model/Benchmark.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/model/BenchmarkContext.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/model/BenchmarkMetrics.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/model/BenchmarkResult.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/model/BenchmarkTargetBuild.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/model/BenchmarkTimeMetrics.kt
instrumented/benchmark/build.gradle.kts
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/profiling/CpuProfileForLogs.kt

It creates a task that will run the benchmark tests and analyse the output, making sure the median value stays under the defined thresholds.
Ensure we don't break the library performances

RUMM-178 Run Benchmark tests on Pull Requests

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/LogFileStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/JsonArrayForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/JsonObjectForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/JsonPrimitiveForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/LogForgeryFactory.kt
sample/java/build.gradle
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/MainActivity.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/assertj/JsonObjectAssert.kt

Allow users to add a `JsonObject` or `JsonArray` attribute to a Logger
Allow more complex data embedded in logs.

RUMM-198 allow json attribute

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/EndToEndTraceTest.kt
instrumented/integration/src/main/AndroidManifest.xml
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/trace/ActivityLifecycleTrace.kt
instrumented/integration/src/main/res/values/strings.xml

This PR adds the integration tests for the Tracing API.
The additional benchmark tests will be added in a different PR.

RUMM-195 Add tracing integration test

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/DeferredWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/LogFileStrategyTest.kt
instrumented/benchmark/build.gradle.kts
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/log/LogApiBenchmark.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/log/LogIOBenchmark.kt
tools/unit/build.gradle.kts
tools/unit/src/main/kotlin/com/datadog/tools/unit/ReflectUtils.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/forge/Throwable.kt

Add benchmark test on File I/O
More test is always good :)

RUMM-189 add benchmark test on File I/O

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/Log.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/utils/TracerExtensions.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/LogAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/utils/TracerExtensionsTest.kt
docs/log_collection.md

This PR bundles(links) the logs with the the active Trace in the application. Having this relation between the log and the current active span(trace) we will be able to see the logs sent for a specific trace. For now the **spanId** parameter is not used but probably will be used later so we added it anyway.

RUMM-186 Bundle the Log with the current active Trace

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallback.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracingFileStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallbackTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/utils/TracerExtensionsTest.kt
instrumented/integration/build.gradle.kts
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/kotlin-timber/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

This adds an `env` information on Logs, Traces and Crash Reports
Let user filter by env on the app.

RUMM-203 use env name

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracingFileStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/TracingFileStrategyTest.kt
sample/java/src/main/java/com/datadog/android/sample/MainActivity.java
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/java/src/main/java/com/datadog/android/sample/user/UserFragment.java
sample/java/src/main/res/drawable/ic_account_circle_black_24dp.xml
sample/java/src/main/res/layout/fragment_user.xml
sample/java/src/main/res/menu/navigation.xml
sample/java/src/main/res/values/strings.xml

Automatically add attributes in traces

RUMM-213 traces auto attributes

---

instrumented/benchmark/build.gradle.kts
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/Utils.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/log/LogApiBenchmark.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/trace/TraceApiBenchmark.kt

This PR adds some benchmarks scenarios related with the newly added **Trace** Api.

RUMM-206 Add the benchmarks for Tracing API

---

docs/log_collection.md

update setVerbosity doc

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt
sample/java/build.gradle
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/java/src/main/java/com/datadog/android/sample/traces/TracesFragment.java
sample/java/src/main/java/com/datadog/android/sample/traces/TracesViewModel.java
sample/java/src/main/res/drawable/ic_cancel_red_24dp.xml
sample/java/src/main/res/drawable/ic_check_circle_green_24dp.xml
sample/java/src/main/res/drawable/ic_error_red_24dp.xml
sample/java/src/main/res/drawable/ic_unknown_grey_24dp.xml
sample/java/src/main/res/layout/fragment_traces.xml
sample/java/src/main/res/values/strings.xml

RUMM-76 okhttp

---

instrumented/benchmark/build.gradle.kts

Tweak the tracing benchmarks thresholds

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadWorker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/UploadStatus.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/UploadStatusTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt

- Add logs on batch upload status
- Also adds a warning if a dev try to use the TracingInterceptor but didn't register a GlobalTracer
Developers who don't see anything in their dashboard need some way to know if batches are sent correctly or not.

RUMM-227 Log Failed upload status 

---

.github/CODEOWNERS

Changes code owner strategy to be notified only when doc is changed

fixing code owners strat

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/DetektConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/PublishingConfig.kt

Fixes the publication steps to keep the proper version number between `dd-sdk-android-timber` and `dd-sdk-android`
Bug report #138

Hotfix 1.2.1

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/PublishingConfig.kt

Fixes the publication steps to keep the proper groupId between dd-sdk-android-timber and dd-sdk-android

Hotfix 1.2.2

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
docs/log_collection.md

This PR exposes the **isInitialized** method which we are currently using internally to the Public API.
This was a request coming from our SDK users.

RUMM-234 Expose the isInitialized method to Public API

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt

Adds a `_dd.source` meta data to spans

RUMM-263 _dd.source

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumInterceptorTest.kt
sample/java/src/main/java/com/datadog/android/sample/MainActivity.java
sample/java/src/main/java/com/datadog/android/sample/traces/TracesViewModel.java

Create an Interceptor to log RUM Resources loading

RUMM-247 RUM Resource Interceptor

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumResourceKind.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventData.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/NoOpRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumResourceKindTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventDataResourceAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventDataResourceForgeryFactory.kt
sample/java/src/main/java/com/datadog/android/sample/MainActivity.java
sample/java/src/main/java/com/datadog/android/sample/traces/TracesViewModel.java

Add method to detect the Resource Kind automatically from the Mime Type

RUMM-248 resource kind

---

dd-sdk-android-timber/src/test/kotlin/com/datadog/android/timber/DatadogTreeTest.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/RuntimeUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt
dd-sdk-android/src/test/java/com/datadog/android/log/LoggerBuilderJavaTest.java
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/DeferredWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/FileReaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/RuntimeUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/domain/FilePersistenceStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/constraints/DatadogLogConstraintsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/FileOrchestratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/DatadogExt.kt
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/java/src/main/java/com/datadog/android/sample/logs/LogsFragment.java
sample/java/src/main/java/com/datadog/android/sample/webview/WebFragment.java
tools/unit/src/main/kotlin/com/datadog/tools/unit/annotations/SystemErrorStream.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/annotations/SystemOutStream.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/assertj/ByteArrayOutputStreamAssert.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/assertj/JsonObjectAssert.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/extensions/SystemStreamExtension.kt
tools/unit/src/test/kotlin/com/datadog/tools/unit/extensions/SystemStreamExtensionTest.kt

Add a link to the source line in logcat logs
Make devs' life easier

RUMM-262 logcat link

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Use Weak References to avoid leaking keys used in the RUM monitor

RUMM-276 avoid leaking RUM keys

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/TrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTracker.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/GesturesTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/TrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesListenerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTrackerTest.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/rum/RumGesturesTrackerBenchmark.kt
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/kotlin-timber/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/ReflectUtils.kt

This PR will adapt and merge the previously implemented GesturesTracker into the recently added GesturesTrackingStrategy.

RUMM-242 Merge the GesturesTracker into the GesturesTrackingStrategy

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventData.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventDataViewAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventDataViewMeasuresAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventDataTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventDataViewMeasureForgeryFactory.kt

Update the View model in the backend with the number of resources, errors and user actions.
Allow filtering views per actions / errors / resource counts.

RUMM-244 View measures

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Prevent sending closed views twice

:bug: (RUMM-244): Prevent sending closed view twice

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/RuntimeUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/Log.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/NoOpLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/LogAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/log/LogIOBenchmark.kt

Adds the current RUM view info in Logs and Traces
Link all features together

Add RUM info in Logs and Traces

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/NetworkTimeInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt

Prevent crashing when using SimpleDateFormat
**This is not tested as there's no way to consistently reproduce this error in a test**

:bug: (RUMM-285): Prevent concurrent access to SimpleDateFormat

---

.github/CODEOWNERS

Documentation team is real (yes, yes)  updating the code owners to reflect that.

Changing baklava to documentation

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/GlobalRumTest.kt

Automatically create and renew session ID

:sparkles: (RUMM-257): Renew SessionId automatically

---

docs/README.md

RUMM-275 Fix the docs links

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventData.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/GlobalRumTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventDataActionAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventDataUserActionForgeryFactory.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumActivityTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumGesturesTrackingTests.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/ReflectUtils.kt

Make User action have duration + link errors and resources with those actions

RUMM-261 user action duration

---

docs/log_collection.md
docs/trace_collection.md

Update Documentation for Tracing Features

RUMM-210 Update tracing documentation

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventForgeryFactory.kt

Add user information for RUM events

RUMM-314 Add user information in RUM events

---

docs/log_collection.md

Fixes bullet list indentation in the Android doc, to fix the display in the public doc.

Fixing bullet list indentation

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumWebChromeClient.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumWebViewClient.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventData.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/NoOpRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumWebChromeClientTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumWebViewClientTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
sample/java/build.gradle
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/java/src/main/java/com/datadog/android/sample/webview/WebFragment.java
sample/kotlin-timber/src/main/kotlin/com/datadog/android/sample/webview/WebFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebFragment.kt

Provide RUM/Logs Webview Integrations

RUMM-221 Webview Integrations

---

dd-sdk-android-androidx-fragment/src/main/kotlin/com/datadog/android/androidx/fragment/CompatFragmentLifecycleCallbacks.kt
dd-sdk-android-androidx-fragment/src/main/kotlin/com/datadog/android/androidx/fragment/OreoFragmentLifecycleCallbacks.kt
dd-sdk-android-support-fragment/src/main/kotlin/com/datadog/android/support/fragment/CompatFragmentLifecycleCallbacks.kt
dd-sdk-android-support-fragment/src/main/kotlin/com/datadog/android/support/fragment/OreoFragmentLifecycleCallbacks.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategy.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/DatadogProvider.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/UnsafeCallOnNullableType.kt
tools/detekt/src/test/kotlin/com/datadog/tools/detekt/rules/UnsafeCallOnNullableTypeTest.kt

Fix the detekt rule to prevent using `!!` in Kotlin code.
Let's avoid crashing our customer's applications

Detekt unsafe null

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/log/LogAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumWebViewClient.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventData.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/NoOpRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/LogFileStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumWebViewClientTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventDataResourceAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventDataResourceForgeryFactory.kt
sample/java/src/main/java/com/datadog/android/sample/traces/TracesViewModel.java

RUMM-335 Create constants for Attributes

---

README.md
docs/TROUBLESHOOTING.md

Add a Troubleshooting document for common issues

RUMM-306 Create Troublshooting document

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/GlobalRumTest.kt

Fix GlobalRumTest

---

dd-sdk-android-ktx/apiSurface
dd-sdk-android-ktx/build.gradle.kts
dd-sdk-android-ktx/src/main/AndroidManifest.xml
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/tracing/SpanExt.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/tracing/SpanExtTest.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/utils/Configurator.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/utils/ThrowableForgeryFactory.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ThrowableForgeryFactory.kt
settings.gradle.kts

RUMM-322 Add Ktx module

---

dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt

RUMM-321 Duplicate Crash as Rum Error

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt

RUMM-328 duplicate log error as rum error

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/ThrowableExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/ThrowableExtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/LogFileStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandlerTest.kt
instrumented/benchmark/gradle.properties
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/EndToEndTraceTest.kt

RUMM-358 open tracing fields

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

RUMM-378 resources reported on the incorrect view

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt

RUMM-382 Detect correct tap target when ViewGroup and child are both clickable

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/NoOpActionTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/NoOpViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/ViewTreeChangeTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/TrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventDataActionAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/datalist/DataListFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/datalist/DataListViewModel.kt
sample/kotlin/src/main/res/drawable/ic_add_24dp.xml
sample/kotlin/src/main/res/layout/fragment_data_list.xml
sample/kotlin/src/main/res/layout/item_layout.xml

RUMM-365 Detect ViewTree changes

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/GesturesTrackingStrategyApi29.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/NoOpActionTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/UserActionTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumConfigAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/GesturesTrackingStrategyApi29Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTrackerTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumGesturesTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumGesturesTrackingActivityTestRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumMockServerActivityTestRule.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumGesturesTrackingPlaygroundActivity.kt

RUMM-380 TrackingStrategy - set Window callback on the onCreate/onPreCreate

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/GesturesTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/Gesture.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/GesturesTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/AbstractGesturesListenerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTrackerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ExpectedEvents.kt

RUMM-394 Intercept gestures in ActionBar drop down menus

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumActivityTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumFragmentTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ExpectedEvents.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTestUtils.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumMockServerActivityTestRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/utils/BundleExtensions.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/utils/IntentExtensions.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumFragmentTrackingPlaygroundActivity.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/assertj/JsonObjectAssert.kt

RUMM-363 Update View tracking end to end tests

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt

Propagate the Menu selection event to the wrapped Window.Callback

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumGesturesTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ExpectedEvents.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTestUtils.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumGesturesTrackingActivityTestRule.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumGesturesTrackingPlaygroundActivity.kt
instrumented/integration/src/main/res/layout/gestures_tracking_layout.xml
instrumented/integration/src/main/res/layout/item_layout.xml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/datalist/DataListFragment.kt

RUMM-362 Assert Swipe events in the EndToEndRumGesturesTrackingTests

---

tools/noopfactory/src/main/kotlin/com/datadog/tools/noopfactory/NoOpFactoryAnnotationProcessor.kt
tools/noopfactory/src/main/resources/META-INF/gradle/incremental.annotation.processors

Incremental kapt

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/net/LogsOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt

RUMM-406 Change source value for Logs, Traces and RUM events

---

.idea/codeStyles/Project.xml
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt

RUMM-426 Change RUM "user" attribute name to "usr"

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/ViewTreeChangeTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumGesturesTrackingTests.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumGesturesTrackingPlaygroundActivity.kt
instrumented/integration/src/main/res/layout/gestures_tracking_layout.xml

RUMM-364 Discard actions without resource or ViewTree changes

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt

Fix application Id

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumRequestInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumRequestInterceptorTest.kt

Duplicate Http error status (4xx, 5xx) as RUM errors

RUMM-429 resource Http error

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/JetpackViewAttributesProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumConfigAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumGestureTrackerAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/JetpackViewAttributesProviderTest.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/log/LogApiBenchmark.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/rum/RumGesturesTrackerBenchmark.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumGesturesTrackingActivityTestRule.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

RUMM-415 Use the JetpackViewAttributesProvider by default in the GesturesTracker

---

dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/tracing/SpanExt.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/tracing/SpanExtTest.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracingFileStrategy.kt

Also fix the withinSpan extension

RUMM-398 Force one single span per batch file

---

docs/log_collection.md
docs/rum_collection.md
docs/trace_collection.md

Prepare the RUM Android Getting started documentation

RUMM-397 RUM Documentation

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt

RUMM-435 reset session

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/log/LogAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/net/LogsOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderTest.kt

RUMM-412 Send "version" as application version for all features

---

.gitlab-ci.yml
buildSrc/src/main/kotlin/com/datadog/gradle/config/PublishingConfig.kt

Ensure ktx artifact is built and published to bintray on tags

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderTest.kt

RUMM-425 Add sdk version as RUM event tag

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/AsyncWriterFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/FilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/PayloadDecoration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashLogFileStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogFileStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracingFileStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/domain/FilePersistenceStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/LogFileStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/TracingFileStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/BatchExt.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/EndToEndLogTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/EndToEndTraceTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/utils/StringExtensions.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt

RUMM-436 fix span intake

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/MixedViewTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/MixedViewTrackingStrategyTest.kt

RUMM-418 Introduce the MixedViewTrackingStrategy

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

RUMM-439 Add View url information in all rum events

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventForgeryFactory.kt

RUMM-434 Add Network info on RUM resources and errors

---

.idea/codeStyles/Project.xml
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEventListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventData.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumRequestInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventDataResourceAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumRequestInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventDataResourceForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventDataResourceTimingForgeryFactory.kt
docs/rum_collection.md
sample/java/src/main/java/com/datadog/android/sample/traces/TracesViewModel.java

RUMM-433 resource timing

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
docs/rum_collection.md
docs/trace_collection.md

RUMM-441 Update the APM and RUM features docs

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracingRequestInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracingRequestInterceptorTest.kt
sample/java/src/main/java/com/datadog/android/sample/traces/TracesViewModel.java

RUMM-440 Condition the OkHttp APM tracing on provided domains list

---

sample/kotlin/src/main/AndroidManifest.xml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/logs/LogsFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/service/LogsForegroundService.kt
sample/kotlin/src/main/res/layout/fragment_logs.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-354 Add a ForegroundLogsService into the Sample app

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracingRequestInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifierTest.kt

RUMM-438 Use request identifier to track ongoing request spans

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/FileLockExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/DatadogExt.kt

RUMM-446 Make the data persistence layer safe for multiprocess usage

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/service/LogsForegroundService.kt

RUMM-450 Keep session alive every 5 minutes

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/ReviewBenchmarkResultsTask.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumContextAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumContextForgeryFactory.kt
instrumented/benchmark/build.gradle.kts
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/core/CoreInitBenchmark.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/log/LogApiBenchmark.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/log/LogIOBenchmark.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/rum/RumGesturesTrackerBenchmark.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/rum/RumManualApiBenchmark.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/trace/TraceApiBenchmark.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ExpectedEvents.kt

RUMM-384 Fix/Update the benchmarks and optimise the code base

---

docs/TROUBLESHOOTING.md
sample/kotlin/src/main/AndroidManifest.xml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/ViewPagerActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/viewpager/FragmentA.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/viewpager/FragmentB.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/viewpager/FragmentC.kt
sample/kotlin/src/main/res/drawable/ic_view_array_black_24dp.xml
sample/kotlin/src/main/res/layout/activity_view_pager.xml
sample/kotlin/src/main/res/layout/view_pager_child_fragment_layout.xml
sample/kotlin/src/main/res/menu/navigation.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-447 Add troubleshooting for tracking view events in FragmentViewPager

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
docs/rum_collection.md

RUMM-454 Update docs - outline manual view tracking mode as default mode

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/KotlinFileVisitor.kt
dd-sdk-android-timber/apiSurface
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEventListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/ViewTreeChangeTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogEventListenerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

RUMM-466 resource timing

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumRequestInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumRequestInterceptorTest.kt

RUMM-451 Provide the bytes_read in the Resource event attributes

---

CONTRIBUTING.md
dd-sdk-android-timber/README.md
dd-sdk-android/README.md
docs/TROUBLESHOOTING.md
docs/log_collection.md
docs/rum_collection.md
docs/trace_collection.md

RUMM-464 update documentation

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/Gesture.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt
sample/kotlin/src/main/res/drawable/ic_message_black_24dp.xml
sample/kotlin/src/main/res/menu/navigation.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-449 Intercept Back actions and track them as RUM action events

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/log/LogAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/EndToEndLogTest.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt

RUMM-476 Send application version as tag for Log events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/DatadogTimeProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/time/DatadogTimeProviderTest.kt

RUMM-480 Ignore time correction if offset is too small

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEventListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogEventListenerTest.kt

RUMM-483 Fix timing on failing requests

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/LogFileStrategyTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/EndToEndLogTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/EndToEndTraceTest.kt

RUMM-488 Fix status case for logs

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
docs/rum_collection.md
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/core/CoreInitBenchmark.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumGesturesTrackingActivityTestRule.kt
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/kotlin-timber/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

RUMM-487 DatadogConfig change trackGestures to trackInteractions method name

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadWorker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/UploadStatus.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/UploadStatusTest.kt

RUMM-490 Add batch byteSize information into Dev logs

---

dd-sdk-android-ktx/apiSurface
dd-sdk-android-ktx/build.gradle.kts
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/tracing/OkHttpRequestExt.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/tracing/OkHttpRequestExtTest.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracingRequestInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracingRequestInterceptorTest.kt
docs/trace_collection.md
sample/java/src/main/java/com/datadog/android/sample/traces/TracesFragment.java
sample/java/src/main/java/com/datadog/android/sample/traces/TracesViewModel.java

RUMM-491 TracingRequestInterceptor - resolve parent span from tags 

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriter.kt

RUMM-510 Prevent malformed payload if writing data fails

---

docs/trace_collection.md

Removes the beta note for the trace GA
We're GA now! 

[documentation] removing a beta note

---

.gitignore
buildSrc/src/main/kotlin/com/datadog/gradle/config/FlavorBuildConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/SampleAppConfig.kt
sample/README.md
sample/java/build.gradle
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/kotlin-timber/build.gradle.kts
sample/kotlin-timber/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt

RUMM-536 Provide staging/production config flavours for sample apps

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt

RUMM-531 Add error count in actions

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt

RUMM-561 Set source to Android

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracedRequestListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracingRequestInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracingRequestInterceptorTest.kt

RUMM-532 TracingRequestInterceptor - provide ability to modify created Span

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/view-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/AndroidXFragmentLifecycleCallbacks.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/FragmentLifecycleCallbacks.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/OreoFragmentLifecycleCallbacks.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/ViewLoadingTimer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/ActivityLifecycleTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/AndroidXFragmentLifecycleCallbacksTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/OreoFragmentLifecycleCallbacksTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/ViewLoadingTimerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumActivityTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumFragmentTrackingTests.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumActivityTrackingPlaygroundActivity.kt
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
tools/unit/src/main/kotlin/com/datadog/tools/unit/ReflectUtils.kt

RUMM-527 Track view loading time in ViewTrackingStrategies

---

dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracingRequestInterceptorTest.kt

TracingRequestInterceptor - fix the testing mutation

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

RUMM-540 Update viewId with parent sessionId

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumActivityTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumFragmentTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumGesturesTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTestUtils.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/assertj/JsonObjectAssert.kt

RUMM-574 Use the context namespace for custom RUM attributes

---

dd-sdk-android/src/main/json/action-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumActivityTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumFragmentTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumGesturesTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ExpectedEvents.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTestUtils.kt

RUMM-528 Track Application startup time

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/error-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumErrorSource.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/RumWebChromeClient.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/RumWebViewClient.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumWebChromeClientTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumWebViewClientTest.kt
sample/java/src/main/java/com/datadog/android/sample/BaseFragment.java
sample/java/src/main/java/com/datadog/android/sample/MainActivity.java
sample/java/src/main/java/com/datadog/android/sample/webview/WebFragment.java

RUMM-547 Add webview error source

---

build.gradle.kts
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/tracing/OkHttpRequestExt.kt
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/tracing/SpanExt.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/tracing/SpanExtTest.kt

RUMM-579 Fix and setup CI analysers for dd-sdk-android-ktx module

---

LICENSE-3rdparty.csv
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-ndk/CMakeLists.txt
dd-sdk-android-ndk/build.gradle.kts
dd-sdk-android-ndk/src/androidTest/kotlin/com/datadog/android/ndk/AndroidManifest.xml
dd-sdk-android-ndk/src/androidTest/kotlin/com/datadog/android/ndk/NdkTests.kt
dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.cpp
dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.cpp
dd-sdk-android-ndk/src/test/cpp/CMakeLists.txt
dd-sdk-android-ndk/src/test/cpp/integration-tests.cpp
dd-sdk-android-ndk/src/test/cpp/test_datetime_utils.cpp
dd-sdk-android-ndk/src/test/cpp/test_generate_backtrace.cpp
dd-sdk-android-ndk/src/test/cpp/test_utils.cpp
dd-sdk-android-ndk/src/test/cpp/test_utils.h
dd-sdk-android-ndk/src/test/cpp/utils/greatest/greatest.h
instrumented/integration/build.gradle.kts

RUM-587 Add the NDK integration tests

---

build.gradle.kts

RUMM-592 Add NDK integration tests artifacts gradle task

---

build.gradle.kts
dd-sdk-android-ndk/src/test/cpp/integration-tests.cpp
dd-sdk-android-ndk/src/test/cpp/test_generate_backtrace.cpp

Fix C++ generate backtrace unit tests

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java

RUMM-570 Let users add global tags on Tracer

---

dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c
sample/kotlin/src/main/cpp/datadog-native-sample-lib.cpp
sample/kotlin/src/main/kotlin/com/datadog/android/sample/logs/LogsFragment.kt
sample/kotlin/src/main/res/layout/fragment_logs.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-583 Add use cases for SIGILL and SIGABRT signals in sample app

---

dd-sdk-android-ndk/src/test/cpp/integration-tests.cpp
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/BroadcastReceiverNetworkInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/receiver/ThreadSafeReceiver.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/info/BroadcastReceiverNetworkInfoProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProviderTest.kt

RUMM-593 Make the BroadcastReceivers thread safe

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/DefinitionRef.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/GenerateJsonSchemaTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/JsonDefinition.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/JsonSchemaReader.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/JsonType.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/TypeDefinition.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/TypeProperty.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/JsonSchemaReaderTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGeneratorTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/TestDefinitions.kt
buildSrc/src/test/kotlin/com/example/model/Opus.kt
buildSrc/src/test/kotlin/com/example/model/UserMerged.kt
buildSrc/src/test/resources/input/all_of_merged.json
buildSrc/src/test/resources/input/description.json

RUMM-539 Improve the Json Schema to Kotlin generator

---

docs/README.md
docs/kotlin_extensions.md
docs/native_crash_collection.md
docs/timber_integration.md

RUMM-581 Add doc file for each extension package

---

Dockerfile.gitlab

RUMM-618 Update docker image

---

dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.cpp
dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c
dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.h
dd-sdk-android-ndk/src/test/cpp/CMakeLists.txt
dd-sdk-android-ndk/src/test/cpp/integration-tests.cpp
dd-sdk-android-ndk/src/test/cpp/test_signal_monitor.cpp
sample/kotlin/src/main/kotlin/com/datadog/android/sample/logs/LogsFragment.kt
sample/kotlin/src/main/res/layout/fragment_logs.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-593 NDKCrashReporter - handle SIGQUIT (ANR) signals

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/ViewLoadingTimer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/ViewLoadingTimerTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumActivityTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumFragmentTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ExpectedEvents.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTestUtils.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumMockServerActivityTestRule.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumActivityTrackingPlaygroundActivity.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/assertj/JsonObjectAssert.kt

RUMM-560 Update integration tests for view loading time

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumActivityTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumFragmentTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumGesturesTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTestUtils.kt

RUMM-617 Fix application start event

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/LogAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/RumWebChromeClient.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/RumWebViewClient.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumWebChromeClientTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumWebViewClientTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumRequestInterceptorTest.kt
docs/rum_collection.md

RUMM-628 Update Interceptors documentation

---

dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/LogAssert.kt

Bundle RUM and Trace attribute in crash logs
Crash logs need to have the relevant TraceID/SpanId (if any) and the RUM context (application/session/view ids) to be able to link that with the relevant product un the dashboard.

RUMM-627 Bundle RUM and Trace attribute in crash logs

---

dd-sdk-android-ndk/apiSurface
dd-sdk-android-ndk/src/androidTest/kotlin/com/datadog/android/ndk/NdkTests.kt
dd-sdk-android-ndk/src/main/cpp/CMakeLists.txt
dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.cpp
dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.h
dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.cpp
dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.h
dd-sdk-android-ndk/src/main/cpp/utils/datetime.cpp
dd-sdk-android-ndk/src/main/cpp/utils/stringutils.cpp
dd-sdk-android-ndk/src/main/cpp/utils/stringutils.h
dd-sdk-android-ndk/src/main/kotlin/com/datadog/android/ndk/NdkCrashReportsPlugin.kt
dd-sdk-android-ndk/src/test/cpp/integration-tests.cpp
dd-sdk-android-ndk/src/test/cpp/test_generate_backtrace.cpp
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/plugin/DatadogContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/plugin/DatadogPlugin.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/plugin/DatadogRumContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/GlobalRumTest.kt

RUMM-608 Add RUM context data to NDK crash logs

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutTracesTest.kt
docs/trace_collection.md
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/AndroidManifest.xml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/server/LocalServer.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebViewModel.kt
sample/kotlin/src/main/res/layout/fragment_traces.xml
sample/kotlin/src/main/res/xml/network_security_config.xml

Ensure that we can handle redirection when tracing requests. A sample was made to test this use case. By default redirections won't appear but the documentation was updated to let users know how to get that information if needed.

RUMM-625 Handle Redirection with Tracing

---

docs/rum_collection.md

This page is going to be pulled into the public documentation for Dash. I am removing the beta notices, updating some grammar nits and fixing one formatting thing that looks odd when you pull it into the docs, but shouldn't change the display at all when you are looking at the md.
Better docs for a better world!

[documentation] 

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Allow users to sample their RUM sessions
Customers are billed per session, and might want to only track a percentage of those. 
Because we need each scope state to still evolve, we updated the context to know whether events should be sent or not.

RUMM-589 sample RUM events

---

README.md
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/ViewModelFactory.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt
sample/kotlin/src/picasso/kotlin/com/datadog/android/sample/picture/PictureViewModel.kt

The goal was to provide a Picasso integration, but Picasso's API is very scarce, and doesn't provide any useful callback.
This PR simply provide a sample flavor that uses Picasso, and some doc in the README explaining how to add the okHttpClient with our intercepters to Picasso.

RUMM-550 Picasso integration

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/sampling/RateBasedSampler.kt

RUMM-667 RateBasedSampler - switch to SecureRandom generator

---

.gitlab-ci.yml

Add a CI job to publish the Glide artifact (cf #342)

RUMM-666 Publish dd-sdk-android-glide artifact

---

.gitlab-ci.yml
LICENSE-3rdparty.csv
README.md
build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-fresco/.gitignore
dd-sdk-android-fresco/README.md
dd-sdk-android-fresco/apiSurface
dd-sdk-android-fresco/build.gradle.kts
dd-sdk-android-fresco/src/main/AndroidManifest.xml
dd-sdk-android-fresco/src/main/kotlin/com/datadog/android/fresco/DatadogFrescoCacheListener.kt
dd-sdk-android-fresco/src/test/kotlin/com/datadog/android/fresco/DatadogFrescoCacheListenerTest.kt
dd-sdk-android-fresco/src/test/kotlin/com/datadog/android/fresco/utils/Configurator.kt
dd-sdk-android-fresco/src/test/kotlin/com/datadog/android/fresco/utils/ThrowableForgeryFactory.kt
dd-sdk-android-fresco/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt
docs/fresco_integration.md
docs/rum_collection.md
sample/kotlin/build.gradle.kts
sample/kotlin/src/fresco/kotlin/com/datadog/android/sample/picture/PictureViewModel.kt
sample/kotlin/src/fresco/res/layout/fragment_picture.xml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/picture/PictureFragment.kt
settings.gradle.kts

RUMM-553 Fresco integration with Datadog SDK

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/data/TraceWriter.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/data/TraceWriterTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt
sample/kotlin/src/main/res/layout/fragment_traces.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-661 Send equivalent RUM event for Spans tagged with errors

---

.gitlab-ci.yml
README.md
build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-coil/.gitignore
dd-sdk-android-coil/README.md
dd-sdk-android-coil/apiSurface
dd-sdk-android-coil/build.gradle.kts
dd-sdk-android-coil/src/main/AndroidManifest.xml
dd-sdk-android-coil/src/main/kotlin/com/datadog/android/coil/DatadogCoilRequestListener.kt
dd-sdk-android-coil/src/test/kotlin/com/datadog/android/fresco/DatadogCoilRequestListenerTest.kt
dd-sdk-android-coil/src/test/kotlin/com/datadog/android/fresco/utils/Configurator.kt
dd-sdk-android-coil/src/test/kotlin/com/datadog/android/fresco/utils/ThrowableForgeryFactory.kt
dd-sdk-android-coil/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
docs/coil_integration.md
sample/kotlin/build.gradle.kts
sample/kotlin/src/coil/kotlin/com/datadog/android/sample/picture/PictureViewModel.kt
settings.gradle.kts

This PR provide integration support for Coil ImageLoading API 
[Coil][(https://coil-kt.github.io/coil/getting_started/)

RUMM-664 Coil integration with Datadog

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/FlavorBuildConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/SampleAppConfig.kt
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/ViewModelFactory.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/DataRepository.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/RemoteDataSource.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/Result.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/model/Log.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/model/LogAttributes.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/model/LogsCollection.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/datalist/DataListFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/datalist/DataListViewModel.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt
sample/kotlin/src/main/res/drawable/ic_baseline_refresh_24.xml
sample/kotlin/src/main/res/layout/fragment_data_list.xml
sample/kotlin/src/main/res/layout/item_layout.xml

The purpose of this PR was to provide support for Retrofit integration. As we could easily plugin our own OkHttpClient to be used with Retrofit we only had to update the docs and provide an use - case for Retrofit in our sample application.

RUMM-548 Retrofit integration with Datadog

---

README.md

RUMM-688 Add docs warning note for Roku devices

---

README.md
docs/rum_collection.md

RUMM-554 Update Docs for integration with Apollo

---

dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

This PR reinforces the unit tests for the RumViewScope following the next 2 rules:
- If during the lifetime of the View event the Global attributes are changed (if we change the value of any attribute there) this will be taken into account in the View event updates (for example when the View is closed) and the backend will take the last value of the attribute for the final Event
- If during the lifetime of the View event we remove a Global attribute (by calling the Public API GlobalRum.removeAttribute(key) method, this change will not be taken into account for this Event.
- [ ] Make sure each commit and the PR …

RUMM-690 RumViewScope - reinforce tests on Global attributes update

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

RUMM-684 Add global attributes to AppStart event

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt

RUMM-702 validate the env name at initialisation time

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEventListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileReader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogEventListenerFactoryTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogEventListenerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/FileReaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/GlobalRumTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Fix a couple of flaky test, and add a couple of tests to improve our coverage.
Make the codebase more stable ;)

Fix flaky test and improve coverage

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt

Add a message in logcat when RUM event are detected but no View is started
Some calls with customers showed that people assume Views are tracked automatically. They didn't use one of the `ViewTrackingStrategy`, and didn't start the view manually either. Because no action / resource can be sent if no view is active, they didn't get any single data , and had to call in for our support.
Adding this message is a simple and efficient way to let them know that they need to start a view to see those events.

RUMM-724 Add message when no RUM view is active

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileReader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/FileReaderTest.kt

Prevent crashing on FileNotFoundException
Issue #377

:bug: (RUMM-729): Fix crash in FileReader

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-coil/README.md
dd-sdk-android-fresco/README.md
dd-sdk-android-glide/README.md
dd-sdk-android-ktx/README.md
dd-sdk-android-ktx/apiSurface
dd-sdk-android-ktx/build.gradle.kts
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/coroutine/CoroutineExt.kt
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/coroutine/CoroutineScopeSpan.kt
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/coroutine/CoroutineScopeSpanImpl.kt
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/coroutine/FlowExt.kt
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/tracing/SpanExt.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/coroutine/CoroutineExtTest.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/coroutine/FlowExtTest.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/tracing/SpanExtTest.kt
dd-sdk-android-rx/README.md
dd-sdk-android-timber/README.md
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt
sample/kotlin/src/main/res/layout/fragment_traces.xml
sample/kotlin/src/main/res/values/strings.xml

Add Flow and Coroutines extensions.
Allow Kotlin/Coroutine developers easily add Trace/RUM support to their code.

RUMM-569 Kotlin coroutines / Flow extension

---

dd-sdk-android-ktx/README.md
dd-sdk-android-ktx/apiSurface
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/sqlite/SqliteDatabaseExt.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/sqlite/SqliteDatabaseExtTest.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/tracing/CloseableExtTest.kt
sample/kotlin/src/sqlite/kotlin/com/datadog/android/sample/data/contentprovider/DatadogContentProvider.kt

RUMM-741 Provide SQLiteDatabase#transactionTraced extension function

---

dd-sdk-android-sqldelight/README.md
dd-sdk-android-sqldelight/apiSurface
dd-sdk-android-sqldelight/src/main/kotlin/com/datadog/android/sqldelight/SqlDelightExt.kt
dd-sdk-android-sqldelight/src/main/kotlin/com/datadog/android/sqldelight/TransactionWithSpanAndWithReturn.kt
dd-sdk-android-sqldelight/src/main/kotlin/com/datadog/android/sqldelight/TransactionWithSpanAndWithoutReturn.kt
dd-sdk-android-sqldelight/src/test/kotlin/com/datadog/android/sqldelight/SqlDelightExtTest.kt
dd-sdk-android-sqldelight/src/test/kotlin/com/datadog/android/sqldelight/utils/Configurator.kt
dd-sdk-android-sqldelight/src/test/kotlin/com/datadog/android/sqldelight/utils/ThrowableForgeryFactory.kt
sample/kotlin/src/sqldelight/kotlin/com/datadog/android/sample/data/db/LocalDataSource.kt

RUMM-752 Provide SQLDelight extensions for traced transactions

---

docs/README.md
docs/sdk_performance.md

RUMM-727 Provide docs for SDK performance metrics

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/TransitiveDependenciesPlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/TransitiveDependenciesTask.kt
dd-sdk-android-coil/build.gradle.kts
dd-sdk-android-coil/transitiveDependencies
dd-sdk-android-fresco/build.gradle.kts
dd-sdk-android-fresco/transitiveDependencies
dd-sdk-android-glide/build.gradle.kts
dd-sdk-android-glide/transitiveDependencies
dd-sdk-android-ktx/build.gradle.kts
dd-sdk-android-ktx/transitiveDependencies
dd-sdk-android-ndk/build.gradle.kts
dd-sdk-android-ndk/transitiveDependencies
dd-sdk-android-rx/build.gradle.kts
dd-sdk-android-rx/transitiveDependencies
dd-sdk-android-sqldelight/build.gradle.kts
dd-sdk-android-sqldelight/transitiveDependencies
dd-sdk-android-timber/build.gradle.kts
dd-sdk-android-timber/transitiveDependencies
dd-sdk-android/build.gradle.kts
dd-sdk-android/transitiveDependencies
sample/kotlin/build.gradle.kts

Cleanup Dependencies for the main artifact (as suggested in #396) and keep track of the transitive dependencies with a plugin.

RUMM-799 Cleanup dependencies

---

.idea/codeStyles/Project.xml
dd-sdk-android/src/main/java/datadog/opentracing/DDTracer.java
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/BigIntegerFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/opentracing/DDSpanContextTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/opentracing/assertj/DDSpanContextAssert.kt

I started this PR with the idea in mind to update the current OpenTracing java code with the latest changes added in the *dd-trace-java* repository. After some work and research I rapidly come to the conclusion that we will not be able to merge the *dd-trace-java* code into our sources as they added more dependencies and they made it more coupled with the Java Agent code. Having this in mind we decided that from now we will try to clean and unit test the current OpenTracing java implementation with the idea in mind to port it to Kotlin at some point.
This is one of the firsts PR in that scope and we will continue to add more work in there with time.
- [ ] Make sure you discussed the feature or …

RUMM-800 Some cleanup on the OpenTracing java source code

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProviderTest.kt

Graceully handles the SecurityException that can happen for some devices. The root cause is not known yet as we can't reproduce this issue locally.

RUMM-852 prevent crash with SecurityException

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt

Updates Coil to the 1.0.0 stable release.
Also I noticed you're using `ImageRequest.Listener` to listen for errors. I'd recommend converting to use [`EventListener`](https://coil-kt.github.io/coil/api/coil-base/coil/-event-listener/) since it allows you to listen to error events globally for an `ImageLoader`. `EventListener` will likely be marked as stable in the next release.

Update Coil to 1.0.0.

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/batching/DefaultMigratorFactory.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/batching/migrators/MoveDataMigrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/batching/migrators/WipeDataMigrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/MiscUtils.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/FileHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/domain/batching/DefaultMigratorFactoryTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/domain/batching/migrators/MoveDataMigratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/domain/batching/migrators/WipeDataMigratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/MiscUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/DatadogExt.kt

RUMM-838 Introduce the basic BatchedDataMigrator implementations

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/ConsentPendingGrantedLogsTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/LogsTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ActivityTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentGrantedActivityTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentGrantedFragmentTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentGrantedGesturesTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentPendingGrantedActivityTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentPendingGrantedFragmentTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentPendingGrantedGesturesTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/FragmentTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/GesturesTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/ConsentGrantedTracesTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/ConsentPendingGrantedTracesTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/TracesTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/GesturesTrackingActivityTestRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/HandledRequest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt
instrumented/integration/src/main/AndroidManifest.xml
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/ActivityTrackingPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/FragmentTrackingPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/GesturesTrackingPlaygroundActivity.kt

RUMM-876 Introduce the ConsentPendingToGranted End-to-End tests

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/ConsentPendingNotGrantedLogsTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/LogsTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentPendingNotGrantedActivityTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentPendingNotGrantedFragmentTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ConsentPendingNotGrantedGesturesTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/ConsentPendingNotGrantedTracesTest.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/trace/ActivityLifecycleTrace.kt

RUMM-784 Introduce the ConsentPendingToNotGranted End-to-End tests

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/FileHandlerTest.kt
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/Preferences.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/gdpr/GdprDialogFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/user/UserFragment.kt
sample/kotlin/src/main/res/drawable/ic_baseline_lock_open_24.xml
sample/kotlin/src/main/res/layout/fragment_gdpr.xml
sample/kotlin/src/main/res/menu/navigation.xml
sample/kotlin/src/main/res/navigation/nav_graph.xml
sample/kotlin/src/main/res/values/dimens.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-889 Add GDPR use case in the sample app

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/TracesTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/datalist/DataListFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/logs/LogsFragment.kt

RUMM-326 Let user register a custom timing event

---

dd-sdk-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeRum.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/Time.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/bridge/internal/BridgeRumTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/domain/TimeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Allow adding custom timestamp in RUM Events
Make the internal implementation work with the mobile bridge

RUMM-899 allow timestamp override

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/bridge/DdBridge.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/bridge/DdRum.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/bridge/DdSdk.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/bridge/DdSdkConfiguration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/bridge/DdBridgeTest.kt

Updates the Bridge following the renaming for the iOS Bridge implementation

RUMM-767 iOS Bridge

---

dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c

Report SIG Abort crashes from the ndk

---

docs/README.md
docs/sdk_benchmarks.md

RUMM-872 Provide SDK benchmarks report

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/FirstPartyHostDetector.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutTracesTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/FirstPartyHostDetectorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt

RUMM-916 Introduce the wild card host for the FirstPartyHostDetector

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt

Always send custom RUM actions, even with no side effects

RUMM-910 Keep all custom actions

---

.idea/codeStyles/Project.xml
dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/_common-schema.json
dd-sdk-android/src/main/json/action-schema.json
dd-sdk-android/src/main/json/error-schema.json
dd-sdk-android/src/main/json/long_task-schema.json
dd-sdk-android/src/main/json/resource-schema.json
dd-sdk-android/src/main/json/view-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

RUMM-88 Add provider for first party RUM Resource/Error events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

RUMM-906 Warn and allow usage of URLs for first party hosts

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt

 RUMM-930 Sanitise and verify first party hosts for valid host name or ip address (new config)

---

dd-sdk-android/src/main/json/_common-schema.json
dd-sdk-android/src/main/json/action-schema.json
dd-sdk-android/src/main/json/error-schema.json
dd-sdk-android/src/main/json/long_task-schema.json
dd-sdk-android/src/main/json/resource-schema.json
dd-sdk-android/src/main/json/view-schema.json

RUMM-938 Update RUM events json schemas

---

docs/rum_collection.md

RUMM-923 Provide docs for RUM data scrubbing feature

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

Fixes the timestamp used by RUM Errors

RUMM-947 rum error timestamp

---

README.md

Fix broken link to timber dedicated library

Fix the link to timber

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/UploadFrequency.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadScheduler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadSchedulerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationCoreForgeryFactory.kt

Allow the customer to set their preferred Upload Frequency strategy

RUMM-826 Allow configuration of upload frequency

---

.gitignore
docs/README.md
docs/gdpr.md
docs/log_collection.md
docs/rum_collection.md
docs/trace_collection.md

RUMM-944 Update the docs for GDPR Api

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoDeserializerGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoExtensions.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoSerializerGenerator.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelValidationTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGeneratorTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/TestDefinitions.kt
buildSrc/src/test/kotlin/com/example/forgery/ForgeryConfiguration.kt
buildSrc/src/test/kotlin/com/example/forgery/OrderForgeryFactory.kt
buildSrc/src/test/kotlin/com/example/model/Article.kt
buildSrc/src/test/kotlin/com/example/model/Book.kt
buildSrc/src/test/kotlin/com/example/model/Conflict.kt
buildSrc/src/test/kotlin/com/example/model/Customer.kt
buildSrc/src/test/kotlin/com/example/model/DateTime.kt
buildSrc/src/test/kotlin/com/example/model/Delivery.kt
buildSrc/src/test/kotlin/com/example/model/Demo.kt
buildSrc/src/test/kotlin/com/example/model/Foo.kt
buildSrc/src/test/kotlin/com/example/model/Location.kt
buildSrc/src/test/kotlin/com/example/model/Message.kt
buildSrc/src/test/kotlin/com/example/model/Opus.kt
buildSrc/src/test/kotlin/com/example/model/Order.kt
buildSrc/src/test/kotlin/com/example/model/Person.kt
buildSrc/src/test/kotlin/com/example/model/Product.kt
buildSrc/src/test/kotlin/com/example/model/Shipping.kt
buildSrc/src/test/kotlin/com/example/model/User.kt
buildSrc/src/test/kotlin/com/example/model/UserMerged.kt
buildSrc/src/test/kotlin/com/example/model/Version.kt
buildSrc/src/test/kotlin/com/example/model/Video.kt
buildSrc/src/test/resources/input/enum_array.json
dd-sdk-android/apiSurface

RUMM-979 PokoGenerator generate Type::fromJson deserializer method

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/KtLintConfig.kt

Fix Ktlint configuration for generated code

---

docs/README.md
docs/log_collection.md
docs/native_crash_collection.md
docs/rum_collection.md
docs/sdk_initialization.md
docs/trace_collection.md

RUMM-943 Update the docs following the new API for SDK initialisation

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt

RUMM-1007 Have the Log 'error.kind' attribute resolved from canonical class name

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt

 RUMM-1014 Tracing - do not add RUM context if RumFeature is disabled

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt

RUMM-996 Send related RUM ErrorEvent when resource request fails

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt

Use a more reliable way to compute the Application Start Time

RUMM-1027 Improve Application Start Time computing

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/data/TraceWriter.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/data/TraceWriterTest.kt

Remove duplication of APM Errors to RUM
Error tracking now ingest errors from APM directly, we don't need this duplication anymore

RUMM-1047 Remove duplication of APM Errors to RUM

---

.gitlab-ci.yml
dogfood.py

Whenever a Tag is created and the SDK is published successfully, the CI will create a PR on the Datadog Android App project to update it to the latest version.
The goal is to make dogfooding systematic when a new version is available

RUMM-1031 Create tool to update SDK for Datadog

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/AndroidXFragmentLifecycleCallbacks.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/OreoFragmentLifecycleCallbacks.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/AcceptAllActivities.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/AcceptAllDefaultFragment.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/AcceptAllSupportFragments.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ComponentPredicate.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/AndroidXFragmentLifecycleCallbacksTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/OreoFragmentLifecycleCallbacksTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/ComponentPredicateTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java

Let customers define a custom RUM View name

RUMM-983 Custom RUM View Name

---

docs/log_collection.md

Lint headings for Log collection to comply with [Documentation style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#headers)
Implementation of Vale Linter in the documentation repo
N/A

Lint headings for Log collection

---

dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt

When we create a RUM Crash report, we lose the throwable message, and replace it with the “standard” Application crash detected.
We need to actually embed the original message, e.g.: `Application crash detected: Unable to parse { "error": "invalid client" }`
This change add the necessary information.

RUMM-1166: Add exception message to RUM and Logs crash messages

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/FlavorBuildConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/SampleAppConfig.kt
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/RuntimeUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/user/UserInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/monitoring/internal/InternalLogFileStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/RuntimeUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/monitoring/internal/InternalLogFileStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationInternalLogsForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

Provide a mecanism to send internal logs to our own datadog org.

RUMM-1133 δ internal monitoring

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt

RUMM-1171 Use class simpleName as default for gesture targetName

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/DatadogExt.kt

RUMM-1177 Suppress deprecation warning for PackageInfo#getVersionCode

---

dd-sdk-android-glide/apiSurface

Follow-up on #533, `apiSurface` should be updated accordingly.

Update API surface for Glide integration

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadWorker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/UploadStatus.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/BroadcastReceiverNetworkInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileMigrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/LoggingSyncListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/UploadStatusTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/net/LogsOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderTest.kt

Cleanup Internal logs to avoid noise and spam : only keep relevant logs

RUMM-1244 Cleanup internal logs

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/core/network_info.json
dd-sdk-android/src/main/json/trace/span-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/BroadcastReceiverNetworkInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/event/SpanEventMapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracesFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/event/DdSpanToSpanEventMapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/info/BroadcastReceiverNetworkInfoProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/NetworkInfoAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/assertj/SpanEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/event/DdSpanToSpanEventMapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/event/SpanEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/NetworkInfoForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/SpanEventForgeryFactory.kt
tools/noopfactory/src/main/kotlin/com/datadog/tools/noopfactory/NoOpFactoryAnnotationProcessor.kt
tools/noopfactory/src/test/resources/gen/NoOpAnyGenericInterface.kt
tools/noopfactory/src/test/resources/gen/NoOpGenericInterface.kt
tools/noopfactory/src/test/resources/gen/NoOpInheritedInterface.kt
tools/noopfactory/src/test/resources/gen/NoOpSimpleInterface.kt
tools/noopfactory/src/test/resources/src/AnyGenericInterface.kt

Use the new SpanEvent in the traces pipeline

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracesFilePersistenceStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationTracingForgeryFactory.kt
docs/trace_collection.md

RUMM-1242 Add public api for spans data scrubbing

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/KtLintConfig.kt
dd-sdk-android/.gitignore
dd-sdk-android/apiSurface
dd-sdk-android/build.gradle.kts
dd-sdk-android/generate_log_models.gradle.kts
dd-sdk-android/src/main/json/log/log-schema.json

This is the first PR in a much bigger task for providing data scrubbing API for Log events.
We are going to first generate a new `LogEvent` poko from the json schema to replace the old `Log` poko.

RUMM-1281 Generate the LogEvent from the json schema

---

dd-sdk-android-coil/README.md
dd-sdk-android-fresco/README.md
dd-sdk-android-glide/README.md
dd-sdk-android-ktx/README.md
dd-sdk-android-rx/README.md
dd-sdk-android-sqldelight/README.md
dd-sdk-android-timber/README.md
dd-sdk-android/README.md
docs/README.md
docs/kotlin_extensions.md
docs/log_collection.md
docs/mobile_data_collected.md
docs/native_crash_collection.md
docs/rum_getting_started.md
docs/trace_collection.md

Cleanups reference to the Bintray repository and cleans up the docs' Readme

Cleanup doc

---

docs/configure_rum_android_sdk.md
docs/integrated_libraries_android.md
docs/mobile_data_collected.md
docs/rum_getting_started.md
docs/troubleshooting_android.md

docs_review_2

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/RuntimeUtils.kt

InternalLogger: enable the network information

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtils.kt

RUMM-1295 Update the content for some internal logs

---

dogfood.py

Update mobile app SDK dependency source path

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt

RUMM-1316 Make all methods in Datadog JvmStatic

---

build.gradle.kts
instrumented/nightly-tests/build.gradle.kts
instrumented/nightly-tests/src/androidTest/AndroidManifest.xml
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/ForgeExtensions.kt
instrumented/nightly-tests/src/main/AndroidManifest.xml
instrumented/nightly-tests/src/main/res/values/strings.xml
settings.gradle.kts

In this PR we setup the new `nightly-tests` module which will contain the E2E tests covering all our SDK Manual and Automatic features. More details you can find in the [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/1608190199/RFC+-+List+native+SDK+features+Project)

RUMM-1143 Setup the nightly-tests module

---

.gitlab-ci.yml
Dockerfile.gitlab
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt
tools/unit/src/test/kotlin/com/datadog/tools/unit/ConditionWatcherTest.kt

This PR adds a static analysis to ensure we don't use any non-inclusive language.

Add language check for diversity and inclusion

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt

DataUploader: add error stack trace information in error log

---

CONTRIBUTING.md

Add Nightly tests docs in the CONTRIBUTING page

---

docs/README.md
docs/advanced_troubleshooting.md
docs/configure_rum_android_sdk.md
docs/integrated_libraries_android.md
docs/kotlin_extensions.md
docs/log_collection.md
docs/native_crash_collection.md
docs/rum_getting_started.md
docs/trace_collection.md

This change updates code samples in docs to make it up-to-date and match the actual API.

RUMM-1091: Update code samples in docs to make it up-to-date, fix formatting

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalInfo.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalMonitorTest.kt

Create a `VitalMonitor` class following our RFC.

RUMM-1271 Create VitalMonitor class

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/CPUVitalReader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/MemoryVitalReader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalObserver.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalReader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalReaderRunnable.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/CPUVitalReaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/MemoryVitalReaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalReaderRunnableTest.kt

Add readers to track CPU and memory usage

Track mobile vitals

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandler.kt

Found this during code inspection. Luckily it doesn't affect functionality, because conversion ratio is still the same. Decided to target release branch instead of master just to avoid possible confusion for the people who may debug DD SDK.

Fix for wrong time conversion API usage

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerBuilderE2ETests.kt

We need to give time to the started `View` event to be propagated as it is handled by a different thread otherwise the test gets flaky.

Fixes on the LoggerBuilder nightly tests

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanE2ETests.kt

This change add performance monitoring for `Span` class related APIs.

RUMM-1381: Add performance monitoring for Span class related APIs

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/AndroidManifest.xml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/service/LogsForegroundService.kt
sample/kotlin/src/main/res/drawable/ic_baseline_error_24.xml

RUMM-1263 Record  RUM events while in background

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/GdprSpanE2ETests.kt

This change is pretty much similar to the #591, just for the Trace feature.

RUMM-1388: Add GDPR related tests for the Trace feature

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/GdprRumE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt

RUMM-1406 Add RUM GDPR nightly-tests

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/ExternalResourceTimings.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/ExternalResourceTimingsKtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/ResourceTimingExt.kt

Cherry pick of #581 to the `1.9.0` branch. Changes to the existing functionality is very small and isolated, so should be safe to merge.
Will be followed by another PR, which will bump version to `1.9.1`.

RUMM-1313: Support external resource timings

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Bump to version 1.9.1. There is nothing added to the Changelog, because there is nothing customer-facing compared to 1.9.0.

Bump to version 1.9.1

---

build.gradle.kts
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rules/NightlyTestRule.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt

RUMM-1433 Fix the RumMonitor flaky nightly tests

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt

We had some flaky nightly test cases in the `Background Action` section. This PR fixes those instrumentation scenarios and also adds more comments to explain the very complex logic behind those test cases.

RUMM-1438 Fix the nightly test cases for background actions

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt

RUMM-1441 NightlyTests - fix the sdkInitialize computation logic

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/anr/ANRException.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnableTest.kt

Add a tool to detect ANRs before the application is killed by the system

RUMM-1363 Add a tool to detect ANRs

---

dd-sdk-android-coil/README.md
dd-sdk-android-fresco/README.md
dd-sdk-android-ktx/README.md
dd-sdk-android-rx/README.md
dd-sdk-android-sqldelight/README.md
dd-sdk-android-timber/README.md
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt

This change removes all references to `DatadogConfig` class, which was removed from codebase before.

Remove DatadogConfig class references

---

sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/crash/CrashFragment.kt
sample/kotlin/src/main/res/layout/fragment_crash.xml
sample/kotlin/src/main/res/values/strings.xml

In order to test OOM reporting in the app, add a way to trigger it in the sample app

Add a button to trigger OOM in Sample app

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/UploadStatus.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderV2.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/UploadStatusTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderV2Test.kt

Make sure response body is always closed when uploading data through OkHttp.

RUMM-1382 Prevent OkHttp leaks

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/constraints/DataConstraints.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraints.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/event/SpanEventSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/event/SpanEventSerializerTest.kt

RUMM-1299 Correctly sanitize SpanEvent attributes keys

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/UploadStatus.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderV2.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/UploadStatusTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderV2Test.kt

Add changes to data uploaders to support API v2

RUMM-1491 API v2

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationCoreForgeryFactory.kt

Enable proxy configuration for tracked data upload to Datadog intake.
Fixes #592

RUMM-1349 Data upload Proxy

---

.gitlab-ci.yml
dogfood.py

Create a PR automatically to update `dd-sdk-bridge` when a new version is released

Create a PR to update dd-sdk-bridge when a new version is released

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/FlavorBuildConfig.kt
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEndpoint.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogSite.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogSiteTest.kt
sample/README.md
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

Add support to the US5 endpoints

RUMM-1488 US5 endpoints

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/FlavorBuildConfig.kt
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEndpoint.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogSite.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogSiteTest.kt
sample/README.md
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

RUMM-1488 Support US5 endpoints

---

instrumented/nightly-tests/proguard-rules.pro

RUMM-1654 Fix the crash in nightly tests for NetworkInterceptor

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/MemoryVitalReader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/MemoryVitalReaderTest.kt

Fix memory vitals. Those were read as Kb, but sent as byte.

RUMM-1682 Fix memory vital unit

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/Serializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/single/SingleItemDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/NdkNetworkInfoDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/NdkUserInfoDataWriter.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/single/SingleItemDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumDataWriterTest.kt

Add internal logs for serialization errors
A customer faced is issue in this section, and internal logs didn't provide any value there. Ended up losing 1 hour looking for the issue.

RUMM-1683 Add internal logs for serialization errors

---

docs/troubleshooting_android.md

Typo in the documentation.
This PR consists in correcting a typo in the documentation.
To improve our public documentation.
No. 

eh_updating troubleshooting_android.md

---

build.gradle.kts
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/HostsSanitizer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/HostsSanitizerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationCoreForgeryFactory.kt

RUMM-1722 Introduce the Configuration#setWebViewTrackingHosts Public API

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/Serializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/single/SingleItemDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/NdkNetworkInfoDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/NdkUserInfoDataWriter.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/single/SingleItemDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/forge/BaseConfigurator.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/forge/ErrorForgeryFactory.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/forge/ExceptionForgeryFactory.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/forge/Throwable.kt

This is a merge PR: content of `release/1.11.0` into `master`.

Merge release/1.11.0 into master

---

dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt

There are 2 tests which have the same body. This change fixes that by adding the necessary test setup.

Fix WindowCallbackWrapper tests

---

dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestratorTest.kt

Similar to https://github.com/DataDog/dd-sdk-ios/pull/644/commits/48b3d01b8ad2471784da1aaa779b4e2e3a26e1fd, this change improves the test to make sure that new files can be written and data can be read back.

RUMM-1714: Ensure new events can be written when event limit per file is reached

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt
sample/kotlin/src/main/res/menu/navigation.xml
sample/kotlin/src/main/res/values/strings.xml

Adds an option to clear all data from Sample app
Check that this feature works with both pending and granted data. Spoiler alert… it does.

RUMM-1715 add an option to clear all data from Sample app

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

Read `error.is_crash` info from cross platform attributes

RUMM-1762 Read is_crash info from cross platform attributes

---

docs/rum_getting_started.md

Referenced https://developer.android.com/studio/releases/platforms to correct versions for OS and SDK API level.
Corrected versioning numbers to have correct Android OS and Android SDK level.
Inaccurate information, was going to send this to customer for reference.
Discussed with Product Manager.

Corrected Android OS and SDK API level level

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/HostsSanitizer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/WebRumEventConsumer.kt
detekt.yml

Fix detekt warnings

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/log/log-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/DatadogEventBridge.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/WebEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/WebLogEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/WebRumEventConsumer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/LogEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/event/LogEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/webview/WebEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/webview/WebLogEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/assertj/DeserializedLogEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/LogEventForgeryFactory.kt

RUMM-1727 Introduce the WebLogsEventConsumer

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/DatadogEventBridge.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/WebEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/WebLogEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/WebRumEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/WebRumEventContextProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/WebRumEventMapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/DatadogEventBridgeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/WebEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/WebLogEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/WebRumEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/WebRumEventContextProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/WebRumEventMapperTest.kt

Im just cleaning up some things in this PR and basically I am moving the WebView tracking classes into a separated WebView tracking feature dedicated package.

Move WebView tracking into a separated feature package

---

dd-sdk-android/src/main/java/com/datadog/opentracing/propagation/DatadogHttpCodec.java

We are adding the missing header in the traced request: `x-datadog-sampled: 1` which indicates that this request is selected for sampling.

RUMM-1810 Add missing header in traced request

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/rum/_common-schema.json

Update RUM Json schemas

---

docs/log_collection.md
docs/rum_getting_started.md

Add region specific info and fix broken link in documentation
DOCS-2897

[DOCS-2897] Add site region specific info

---

build.gradle.kts
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/utils/LogUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/DatadogEventBridge.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/log/WebLogEventDateCorrector.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/log/WebViewLogEventConsumer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/utils/LogUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ForgeExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/WebViewEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/log/WebLogEventDateCorrectorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/log/WebViewLogEventConsumerTest.kt
detekt.yml

RUMM-1831 Apply timestamp correction for web log events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/GesturesTrackingTest.kt

Distinguish view-less event's happening early during the app's lifetime as `AppLaunch` instead of just `Background`

RUMM-1807 Handle App launch events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraintsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/info/BroadcastReceiverNetworkInfoProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/event/LogEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumResourceKindTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/ExternalResourceTimingsKtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/AndroidXFragmentLifecycleCallbacksTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/JetpackViewAttributesProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/tracking/OreoFragmentLifecycleCallbacksTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalReaderRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/event/DdSpanToSpanEventMapperTest.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/ObjectTest.kt

This change reduces flakiness in test coverage by making some tests more predictable in terms of the branches they cover.
It is still possible to have some flakiness though, but it will be less often and will have less impact on the overall test coverage for PRs.

RUMM-1228: Reduce flakiness in tests coverage

---

dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/info/BroadcastReceiverNetworkInfoProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExtTest.kt

One more round to reduce flakiness is some most noisy tests. Mostly switching to `ParametrizedTest` for tests, where set of input parameters is finite.

RUMM-1228: Reduce test coverage flakiness

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/rum/_common-schema.json
dd-sdk-android/src/main/json/rum/error-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumErrorSourceType.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt

Completes RUMM-1899 To adds Flutter as an error source type

Update RUM Schema

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebFragment.kt

Cleanup the sample application

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/config/CoreFeatureTestConfiguration.kt
detekt.yml

This change explicitly define supported TLS versions and cipher suites. The precise change list is the following:
* Dropped completely support of TLS 1.0 and 1.1 (which was enabled for API 19), because they are generally not supported (they are supported in EU1 only, but it has support of TLS 1.2 as well). It is ok to use TLS 1.2 on API 19, because it exists there, although it should be enabled explicitly, but OkHttp does that (see https://github.com/square/okhttp/blob/okhttp_3.12.x/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java#L452).
* TLS 1.3 cipher suites are kept (even though `TLS_CHACHA20_POLY1305_SHA256`, for example, is not yet confirmed with FIPS 140-2), because US5 supports it (it is only DC which supports it so far). We will state exact requirements for the …

RUMM-1868: Explicitly define supported TLS versions and cipher suites

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/ActivityViewTrackingStrategyTest.kt

Track the Intent's action and data URI, only if the "track extra" option is enabled.

RUMM-1326 track Activity Intent action and data URI

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/RumWebChromeClient.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/RumWebViewClient.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/JetpackComposeActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/NavigationSample.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebViewModel.kt

RUMM-1937 Provide WebView tracking code snippets

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt

Prepare release of `1.12.0-alpha1`

Bump to version 1.12.0-alpha1

---

README.md

Fix a broken link to troubleshooting doc in README

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/AbstractGesturesListenerTest.kt
detekt.yml

Use the location within the window boundaries to ensure we track the relevant view when user interacts with the app

RUMM-1801 Use location relative to window

---

build.gradle.kts
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/DatadogEventBridge.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/MixedWebViewEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/WebViewEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/log/WebViewLogEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventConsumer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/DatadogEventBridgeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/MixedWebViewEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/log/WebViewLogEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventConsumerTest.kt

Allow setting the hosts for webview tracking upon creating of the `DatadogEventBridge`

RUMM-1953 Lazy webview hosts

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/DatadogEventBridge.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/DatadogEventBridgeTest.kt
detekt.yml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebFragment.kt

We are introducing a new utility API to enable auto - instrumentation for a specific `WebView`. 

RUMM-1959 Add DatadogEventBridge#setup utility api for web view tracking

---

LICENSE-3rdparty.csv
build.gradle.kts
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
gradle/libs.versions.toml
instrumentation-tools/nightly_tests_code_coverage.py
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/webview/WebViewTrackingE2ETests.kt
instrumented/nightly-tests/src/main/AndroidManifest.xml
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/WebViewTrackingActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/WebViewTrackingBridgeHostsActivity.kt
instrumented/nightly-tests/src/main/res/layout/webview_tracking_activity.xml
instrumented/nightly-tests/src/main/res/xml/network_security_config.xml

Add the required nightly tests for the WebView tracking feature. Complementary monitors were added to assess each scenario.

RUMM-1958 Add nightly-tests for WebView tracking feature

---

.gitlab-ci.yml
dogfood.py

Create a PR on Flutter SDK repo whenever a new version is released

RUMM-1963 Automatic update Flutter SDK

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt

Prevent printing warning about dropped event for internal events

RUMM-1968 don't warn for silent orphan events

---

docs/README.md
docs/log_collection.md
docs/mobile_data_collected.md

Update the documentation to explain the lack of encryption by default.

RUMM-1938 Add mention of encryption (or lack thereof)

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/crash/JvmCrashHandlerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/crash/NdkCrashHandlerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanE2ETests.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/WebViewTrackingActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/WebViewTrackingBridgeHostsActivity.kt

RUMM-1960 Fix performance nightly tests and apply detekt custom rules to nightly-test module

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/KtLintConfig.kt
dd-sdk-android/.gitignore
dd-sdk-android/apiSurface
dd-sdk-android/build.gradle.kts
dd-sdk-android/clone_telemetry_schema.gradle.kts
dd-sdk-android/generate_telemetry_models.gradle.kts
dd-sdk-android/src/main/json/rum/error-schema.json
dd-sdk-android/src/main/json/telemetry/_common-schema.json
dd-sdk-android/src/main/json/telemetry/debug-schema.json
dd-sdk-android/src/main/json/telemetry/error-schema.json
instrumentation-tools/src/constants.py

This change brings support of new telemetry events added in https://github.com/DataDog/rum-events-format/pull/54.

RUMM-2019: Update schemas with new telemetry events

---

.gitlab-ci.yml

This change removes redundant `git fetch` calls for all the steps in `.gitlab-ci.yml`.

Remove redundant git fetch calls from CI pipeline steps

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
detekt.yml

Fixes #849 
Some orphan events were not counted as orphans

Handle missed orphans

---

dogfood.py

When a new version of the SDK is deployed, update the README for the package to have the correct version.
Make sure documentation is always up to date with the truth

Update version in documentation when updating the Flutter SDK

---

dd-sdk-android-tv/src/test/kotlin/com/datadog/android/tv/LeanbackViewAttributesProviderTest.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalReaderRunnable.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalReaderRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumContextForgeryFactory.kt

RUMM-2061 Disable RUM vitals monitor if no active foreground view

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/transitiveDependencies

RUMM-2078 Prevent sending negative View durations

---

docs/rum_getting_started.md

Updated the docs.
Clarified that the build.gradle file that needs to be modified is the one in the app directory.
Modified the code snipped to reorder the blocks, added the android block, added //(...) to make it obvious where these lines should be added.
Clarification for less experienced users. 

app/build.gradle clarification + code snippet

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt

RUMM-2104 Prevent negative RUM resource durations

---

README.md
docs/README.md
docs/rum_getting_started.md

Updates READMEs and public docs to mention Android TV support.
DOCS-3269

DOCS-3269 Android TV and Android Support in READMEs and Documentation

---

docs/web_view_tracking.md

To enable the documentation preview link again before we merge, will need to change to develop.
DOCS-3019

Stage Branch --> Master

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPersister.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/model/Records.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/model/Segments.kt
sample/RedReader/build.gradle

RUMM-2160 Explote the web events format

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsUtils.kt

Follow-up for #920. Apparently numbers used in branches of `sendRandomLog` were not the same as actual values of `Log` priorities.

RUMM-2042: Fix E2E test

---

docs/mobile_data_collected.md

Removes the `country_subdivision_iso_code` facet.
RUM Docs Slack

DOCS-3465 Android Data Collected Edit

---

docs/configure_rum_android_sdk.md

Provide a documentation with samples for the `RumResourceAttributesProvider`.

Android Advanced Configuration Edits

---

docs/rum_getting_started.md

DOCS-3301 add documentation to track background events

---

dogfood.py

This updates the dogfooding python script to support UTF-8 encoding on READMEs. I looks like gitlab for some reason was attempting to read the file as ASCII, which broke when we added a warning Emoji to the README in the Flutter SDK.
I also added `--dry-run` which does everything but push and create the PR.

Update dogfood.py ot support UFT-8 for READMEs

---

.github/CODEOWNERS

Tags me as a secondary reviewer on doc-related pull requests, hopefully leading to faster approvals.

 Adds Secondary Doc Reviewer

---

docs/mobile_data_collected.md

Removes the `view.loading_time` metric.
#rum-docs, #support-rum Slack

Android Monitoring Doc Edit

---

.gitlab-ci.yml
build.gradle.kts

Use a defined gitlab template for all generated files status check
Successful run: https://gitlab.ddbuild.io/datadog/dd-sdk-android/builds/164093339

Use a gitlab template for analysis generated files check

---

docs/configure_rum_android_sdk.md
docs/mobile_data_collected.md
docs/rum_getting_started.md

Merge the latest doc changes made in `master` branch into `develop` branch.

Merge master branch into develop

---

docs/configure_rum_android_sdk.md

Add setVitalsUpdateFrequency function to the advanced configuration doc.
Adds setVitalsUpdateFrequency function and description to the advanced configuration doc.
Parity with iOS doc. 

Add setVitalsUpdateFrequency to the doc

---

docs/configure_rum_android_sdk.md
docs/mobile_data_collected.md

Sync updates made to `master` branch.
Default branches on GitHub~

Sync Doc Changes From Master to Develop

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepares `1.14.0-beta2` release.

Prepare 1.14.0-beta2 release

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/LogAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogGeneratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dogfood.py

This change merges the head (`1.14.0-beta2`) of `release/1.14.0` branch into `develop` branch.

Merge the head (1.14.0-beta2) of release/1.14.0 branch into develop branch

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ConfigurationRumAssert.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt

This PR cherry-pick https://github.com/DataDog/dd-sdk-android/pull/1023 into 1.14 release.

Cherry-pick "disable action tracking" into 1.14.0

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares the final release of `1.14.0`.

Prepare final release of 1.14.0

---

docs/mobile_data_collected.md

Hotjar
Addresses some copy nits flagged by translators.

Android Data Collected Edits

---

dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt

This change makes commented tests in `DatadogCoreInitializationTest.kt` working again.
It was already done #1055, but since that PR is closed, taking it from there.

Update DatadogCore initialization tests

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepare 1.14.1 release. The only difference with 1.14.0 is #1057.

Prepare 1.14.1 release

---

build.gradle.kts

An update to ktlint has caused this file to fail on analysis because of import ordering. This re-orders the imports to fix the build.

Fix import ordering

---

gradle/libs.versions.toml

This change bumps the version of Android Gradle Plugin to 7.3.1.

Android Gradle Plugin 7.3.1

---

library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtilsTest.kt

Fix flaky tests in WireframeUtilsTest

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This change bumps SDK version to 1.16.0 for the development.

Next dev cycle

---

dd-sdk-android/README.md

Updates the sample in Readme file to reflect the current API

Fix sample in README

---

instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/CrashService.kt

Cherry-pick work from https://github.com/DataDog/dd-sdk-android/pull/1137, it is needed because "Nightly tests for Web" job is running for the code from the `master` branch.

Suppress the deprecation of Bundle#get in nightly test

---

docs/configure_rum_android_sdk.md

Fix sample code in addAction API

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEndpoint.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogSite.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/plugin/Feature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/security/EncryptionTest.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/crash/NdkCrashHandlerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/JvmCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/NdkCrashService.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

This reverts commit 76d290f5f8747d6a8e576745d01a03832e607c36.

Revert "Remove Session Replay from public API"

---

.gitlab-ci.yml

This PR adds publish task for the Session Replay module, otherwise SNAPSHOT builds are broken currently.

Add publish task for the Session Replay module

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt

Cherry-pick of https://github.com/DataDog/dd-sdk-android/pull/1171 for the `develop` branch.

Cherry-pick: Make a local copy of tags before creating LogEvent

---

docs/configure_rum_android_sdk.md

Fix broken link in documentation.

Fix link to setup facets and measures

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This change bumps the version in `develop` branch.

Next dev version 1.17.0

---

.gitlab-ci.yml

MTG-8 upgrade detekt pipeline version

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Promote to version 1-17-0-sr-alpha2-SNAPSHOT

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/UploadStatus.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/RequestFactory.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/UploadStatusTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/net/DataOkHttpUploaderTest.kt

RUMM-2796 RequestFactory can throw exceptions

---

dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/RequestBodyFactory.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactory.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/exception/InvalidPayloadFormatException.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/domain/RequestBodyFactoryTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactoryTest.kt

RUMM-2797 SR RequestFactory allow to throw exceptions

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/DatadogLogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/FeatureScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/DatadogContextProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/DatadogLogGeneratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/DatadogContextProviderTest.kt
docs/mobile_data_collected.md

This change cherry-picks some important fixes from `develop` and `feature/sdkv2` branches into `release/1.16.0` branch.

Cherry pick some fixes into 1.16.0 release

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt

This PR is a cherry-pick of https://github.com/DataDog/dd-sdk-android/pull/1222 into `release/1.16.0` branch.

Cherry-pick: RUMM-2868: Apply extra sampling rate to the configuration telemetry

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This change does the necessary update to make a final release of SDK version `1.16.0`.

RUMM-2893: Make final release of 1.16.0

---

CHANGELOG.md
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/DatadogLogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/FeatureScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/DatadogContextProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/DatadogLogGeneratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/DatadogContextProviderTest.kt

This PR does the merge of `release/1.16.0` branch into `develop` branch with all the conflicts resolved.

Merge release 1.16.0 branch into develop

---

.github/workflows/codeql-analysis.yml
CHANGELOG.md
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
docs/mobile_data_collected.md
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/ext/ReceiverExt.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/InvalidStringFormat.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/ThreadSafety.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/UnsafeThirdPartyFunctionCall.kt

This PR makes a merge of `develop` branch into `feature/sdkv2` branch with all the conflicts resolved.

Merge develop into SDK v2 branch

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Promote to 1.17.0-sr-beta1-snapshot

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEndpoint.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogSite.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/plugin/Feature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/security/EncryptionTest.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/crash/NdkCrashHandlerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/JvmCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/NdkCrashService.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

Temporary commit to remove Session Replay from the public API. It will be reverted shortly after, needed to do the SDK v2 content merge into `develop` branch.

Remove Session Replay from public API

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Promote to 1.17.1-sr-beta1-snapshot

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracingFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/Feature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/FeatureStorageConfiguration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/StorageBackedFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/log/WebViewLogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracingFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/log/WebViewLogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFeatureTest.kt

This PR creates interfaces for the simple feature (just `name` property + initialization method) and for the feature which requires some storage (it should provide storage and upload configurations). The latter is the extension of the former.
Also this PR makes existing features to use these interfaces.

RUMM-2916: Create interfaces for simple feature and storage-backed feature

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/NodeFlattener.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtils.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ForgeConfigurator.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ShapeBorderForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ShapeWireframeForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/NodeFlattenerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtilsTest.kt

RUMM-2933 Ignore Shape wireframes with not border and background

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactory.kt

This PR bumps dev version we are using, because we are going to make 1.17.0 release.

Next dev version

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallback.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallbackTest.kt

Ensure we detect the device's refresh rate with any ViewTrackingStrategy
The previous implementation didn't work with the NavigationViewTrackingStrategy

RUMM-2903 detect device's refresh rate from vital monitor

---

instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingFirstPartyHostsWithTracingHeaderTypeActivity.kt

Change resource name in order to receive valid data 

Update E2E tests with valid resource (as to not get 404)

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
library/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
library/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt

This PR makes Logs feature to use message bus to forward errors to RUM instead of having an explicit dependency on the RUM.

RUMM-3005: Logs feature is using message bus to forward errors to RUM

---

.gitlab-ci.yml
build.gradle.kts
dd-sdk-android-okhttp/.gitignore
dd-sdk-android-okhttp/README.md
dd-sdk-android-okhttp/apiSurface
dd-sdk-android-okhttp/build.gradle.kts
dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/Placeholder.kt
dd-sdk-android-okhttp/transitiveDependencies
library/dd-sdk-android-logs/build.gradle.kts
library/dd-sdk-android-logs/transitiveDependencies
settings.gradle.kts

This PR creates an empty module for the future OkHttp extraction.
Also it makes a minor change for Logs module, to align namespace with the name of the package (doesn't really impact anything).

RUMM-3022: Create an empty dedicated module for OkHttp instrumentation

---

.gitlab-ci.yml
build.gradle.kts
instrumentation-tools/src/constants.py
library/dd-sdk-android-session-replay/build.gradle.kts
library/dd-sdk-android-trace/.gitignore
library/dd-sdk-android-trace/README.md
library/dd-sdk-android-trace/apiSurface
library/dd-sdk-android-trace/build.gradle.kts
library/dd-sdk-android-trace/src/main/java/com/datadog/android/trace/Placeholder.kt
library/dd-sdk-android-trace/transitiveDependencies
settings.gradle.kts

This PR creates an empty module for the future tracing feature extraction.

RUMM-3037: Create empty module for Tracing feature

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracingFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/tracing/internal/net/TracesRequestFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracingFeatureBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracingFeatureTest.kt

This change creates a dedicated builder for `TracingFeature`. We will switch to its usage in the public API in the next PR.

RUMM-3038: Create a dedicated builder for Tracing feature

---

.gitlab-ci.yml
build.gradle.kts
library/dd-sdk-android-webview/.gitignore
library/dd-sdk-android-webview/README.md
library/dd-sdk-android-webview/apiSurface
library/dd-sdk-android-webview/build.gradle.kts
library/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/Placeholder.kt
library/dd-sdk-android-webview/transitiveDependencies
settings.gradle.kts

This PR creates a dedicated module for the WebView integration feature. For now it is empty.

RUMM-3059: Create empty module for WebView integration feature

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallback.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifierTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallbackTest.kt

This change prepares release 1.17.1 with some bugfix changes which were cherry-picked from `develop` + one revert of PR #1251.

Prepare release 1.17.1

---

dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallbackTest.kt

This is not a fix per se, but adding the assumption for the test to be considered valid.
It is possible to have too high or too low framerate in this test because of combination of frame duration and refresh rate scale. So we are going to allow this test to run only if expected fps is within the valid boundaries for the reporting.

Fix flaky VitalFrameCallback test

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/AllowAllWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckedTextViewMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CompoundButtonMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/GenericWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllCheckedTextViewMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllRadioButtonMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/RadioButtonMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/AllowAllWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseRadioButtonMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllRadioButtonMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/RadioButtonMapperTest.kt
sample/kotlin/src/main/res/layout/fragment_radio_checkbox_components.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-2962 SR - add capability to record RadioButton implementations

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ConfigurationLegacyRumAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationLegacyRumForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
library/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/LogsFeature.kt

This change copies the context of `Configuration.Feature.RUM` into its own class under the `RumFeature` and adds the related builder. PR may look big, but in the end it is a copy-paste of existing code into the new location.
Legacy code (`Configuration.Feature.RUM`) will be deleted in the next PRs.

RUMM-2926: RUM configuration is extracted into its own class with builder

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/DropDownSwitchersFragment.kt
sample/kotlin/src/main/res/layout/fragment_drop_down_switchers_components.xml
sample/kotlin/src/main/res/values/arrays.xml
sample/kotlin/src/main/res/values/strings.xml

This PR only adds the spinners case into the sample app as the ability to record Spinners was already added int the [REPLAY-1422](https://github.com/DataDog/dd-sdk-android/pull/1314/files) 
[REPLAY-1422]: https://datadoghq.atlassian.net/browse/REPLAY-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

REPLAY-1327 Add SR spinners scenario into the sample app

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This change prepares release 🏷️ `1.17.2`

Prepare release 1.17.2

---

.gitlab-ci.yml
build.gradle.kts
library/dd-sdk-android-rum/.gitignore
library/dd-sdk-android-rum/README.md
library/dd-sdk-android-rum/apiSurface
library/dd-sdk-android-rum/build.gradle.kts
library/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/Placeholder.kt
library/dd-sdk-android-rum/transitiveDependencies
settings.gradle.kts

This change create an empty module for the future RUM-related code extraction.

RUMM-3097: Create empty module for RUM feature

---

docs/mobile_data_collected.md

Two documentation changes were made on `develop` that need to be pulled into master. Cherry-picking them for @rtrieu 

Cherry pick documentation updates into master

---

dd-sdk-android-okhttp/build.gradle.kts
library/dd-sdk-android-logs/build.gradle.kts
library/dd-sdk-android-ndk/build.gradle.kts
library/dd-sdk-android-rum/build.gradle.kts
library/dd-sdk-android-session-replay-material/build.gradle.kts
library/dd-sdk-android-session-replay/build.gradle.kts
library/dd-sdk-android-trace/build.gradle.kts
library/dd-sdk-android-webview/build.gradle.kts

This change brings the consistency for the `packagingOptions` parameter among the new modules.

Align packaging options for new modules

---

.gitlab-ci.yml
CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This change does the merge of `develop` branch into SDK v2 branch with conflicts resolved.

Merge develop branch into SDK v2 branch

---

library/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaskAllTabWireframeMapper.kt
library/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/TabWireframeMapper.kt
library/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/MaskAllSliderWireframeMapperTest.kt
library/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/SliderWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllSeekBarWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SeekBarWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversalTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseSeekBarWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllSeekBarWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SeekBarWireframeMapperTest.kt
sample/kotlin/src/main/res/layout/fragment_sliders_steppers_components.xml

REPLAY-1454 SR - add capability to record SeekBars

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

`1.18.1` release with spammy telemetry removed.

Prepare release 1.18.1

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllNumberPickerMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/NumberPickerMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseNumberPickerMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllNumberPickerMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/NumberPickerMapperTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/SlidersSteppersFragment.kt
sample/kotlin/src/main/res/layout/fragment_sliders_steppers_components.xml

REPLAY-1478 SR - add capability to record Steppers

---

instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayPlaygroundActivity.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextViewWireframeMapperTest.kt

REPLAY-1378 Use Roboto as first option in font-family for sans-serif typeface

---

.gitlab-ci.yml
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

[REPLAY-1325](https://datadoghq.atlassian.net/browse/REPLAY-1325) Radio buttons are displayed in SR
[REPLAY-1327](https://datadoghq.atlassian.net/browse/REPLAY-1327) Pickers \(drop-down\) lists are displayed in SR
[REPLAY-1333](https://datadoghq.atlassian.net/browse/REPLAY-1333) Tabs are displayed in SR
[REPLAY-1334](https://datadoghq.atlassian.net/browse/REPLAY-1334) Sliders are displayed in SR
[REPLAY-1338](https://datadoghq.atlassian.net/browse/REPLAY-1338) Switches are displayed in SR
[REPLAY-1342](https://datadoghq.atlassian.net/browse/REPLAY-1342) Rich text elements are displayed in SR
[REPLAY-1387](https://datadoghq.atlassian.net/browse/REPLAY-1387) \[Android\] Send \`Roboto\` as first option in the fontFamily for TextWireframe …

Promote to 1.18.0 sr beta1 snapshot

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/DifferentFontsFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/SessionReplayFragment.kt
sample/kotlin/src/main/res/drawable/baseline_font_download_24.xml
sample/kotlin/src/main/res/layout/fragment_different_fonts.xml
sample/kotlin/src/main/res/layout/fragment_session_replay.xml
sample/kotlin/src/main/res/navigation/nav_graph.xml
sample/kotlin/src/main/res/values/strings.xml

RUMM-1388 Add different typefaces page in Sample app

---

library/dd-sdk-android-session-replay-material/transitiveDependencies
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllTextViewMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextViewWireframeMapperTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/PasswordEditTextComponentsFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/SessionReplayFragment.kt
sample/kotlin/src/main/res/drawable/baseline_password_24.xml
sample/kotlin/src/main/res/layout/fragment_password_edit_text_components.xml
sample/kotlin/src/main/res/layout/fragment_session_replay.xml
sample/kotlin/src/main/res/navigation/nav_graph.xml
sample/kotlin/src/main/res/values/strings.xml

REPLAY-1501 Make sure password like input fields are always masked

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/EditTextViewMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/EditTextViewMapperTest.kt

REPLAY-1522 Resolve EditText underline color from textColor by default

---

docs/log_collection.md

Adds a tab for the AP1 site region.
DOCS-5147
https://docs-staging.datadoghq.com/alai97/log-collection-small-ap1-doc-update/logs/log_collection/android

DOCS-5147 Android Log Collection Edit

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

[REPLAY-1522](https://datadoghq.atlassian.net/browse/REPLAY-1522) Use the textColor as default underline color in the EditTextViewWireframeMapper
[REPLAY-1540](https://datadoghq.atlassian.net/browse/REPLAY-1540) Make sure we don't use a semi - translucent background for DropDown windows
[REPLAY-1557](https://datadoghq.atlassian.net/browse/REPLAY-1557) Mask all the passwords, emails, phone numbers, credit cards, etc, by default
[REPLAY-1522]: https://datadoghq.atlassian.net/browse/REPLAY-1522?atlOrigin=ey …

Release version 1.18.1-sr-beta1-snapshot

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This change prepares release 1.19.0 of Android SDK.

Prepare release 1.19.0

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Bumping the dev version as we are doing 1.19.0 release.

Next dev cycle: 1.20.0

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BasePickerMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllNumberPickerMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/NumberPickerMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseNumberPickerMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllNumberPickerMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/NumberPickerMapperTest.kt

REPLAY-1611 Do not show prev-next value in number pickers for MASK_USER_INPUT

---

library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/obfuscator/FixedLengthStringObfuscatorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/obfuscator/NoOpStringObfuscatorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/obfuscator/rules/TextValueResolverTest.kt

Add missing unit tests for TextValueResolver, and also for StringObfuscator implementations

Add missing unit tests

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/InternalSdkCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt
library/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumFeature.kt
library/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumFeatureTest.kt

This small PR makes RUM feature read developer mode flag from the SDK core and adjust RUM session sampling rate accordingly.

Support developer mode in RUM

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/SrSnapshotTest.kt

Fix Bitrise flakiness

---

library/dd-sdk-android-session-replay-material/apiSurface
library/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaterialExtensionSupport.kt
library/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaterialOptionSelectorDetector.kt
library/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/MaterialExtensionSupportTest.kt
library/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/MaterialOptionSelectorDetectorTest.kt
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/ExtensionSupport.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/NoOpExtensionSupport.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayFeature.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayLifecycleCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/ComposedOptionSelectorDetector.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/DefaultOptionSelectorDetector.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/OptionSelectorDetector.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/ComposedOptionSelectorDetectorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/DefaultOptionSelectorDetectorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducerTest.kt

REPLAY-1614 Mask calendar header for MASK_ALL or MASK_USER_INPUT

---

sample/wear/build.gradle.kts
sample/wear/src/main/java/com/datadog/android/wear/sample/WearApplication.kt

This PR aligns SDK setup in the `sample:wear` app with SDK v2 public API changes.

Align SDK setup in the Wear app sample with SDK v2 public API

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentGrantedSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/SrSnapshotTest.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayPlaygroundActivity.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewUtilsInternal.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/UnsupportedViewMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversalTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/UnsupportedViewMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/optionselectormocks/AppcompatToolbarCustomSubclass.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/optionselectormocks/ToolbarCustomSubclass.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/SessionReplayFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/UnsupportedViewsFragment.kt
sample/kotlin/src/main/res/layout/fragment_session_replay.xml
sample/kotlin/src/main/res/layout/fragment_unsupported_views.xml
sample/kotlin/src/main/res/navigation/nav_graph.xml
sample/kotlin/src/main/res/values/strings.xml

Unsupported view placeholder support
- Provide an unsupported view placeholder for android.widget.Toolbar and androidx.appcompat.widget.Toolbar
- Refactor unit tests for SessionReplayPrivacyTest

REPLAY-1301 Provide placeholder for Action Bar

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

[REPLAY-1556](https://datadoghq.atlassian.net/browse/REPLAY-1556) Do not mask Tab selection for MASK\_ALL
[REPLAY-1594](https://datadoghq.atlassian.net/browse/REPLAY-1594) Make sure the Dropdown, Calendar and Time Pickers values are masked in MASK\_USER\_INPUT mode
[REPLAY-1598](https://datadoghq.atlassian.net/browse/REPLAY-1598) Change SR text obfuscation code architecture following latest docs
[REPLAY-1599](https://datadoghq.atlassian.net/browse/REPLAY-1599) Add the unit tests for StringObfuscator and TextValueResolver
[REPLAY-1600](https://datadoghq.atlassian.net/browse/REPLAY-1600) \[Android\] Increase the Snapshot Debouncer to 64 ms
[REPLAY-1614](https://datadoghq.atlassian.net/browse/REPLAY-1614) Mask the Calendar header for MASK\_USER\_INPUT
What inspired you to submit this pull …

Promote to v1.19.0-sr-beta1-snapshot

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

This PR prepares patch release 1.19.1 by cherry-picking the necessary commits from `develop` branch and updating `CHANGELOG` file.

Prepare release 1.19.1

---

gradle/libs.versions.toml

Update Realm to 10.16.0, because it has a better compatibility with incremental compilation.

Update Realm to 10.16.0

---

sample/kotlin/build.gradle.kts
sample/wear/build.gradle.kts

This PR fixes compilation of the Wear app and make `kotlin` sample app to use Java 17 bytecode.

Fix compilation of the Wear sample app

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

This PR reverts changes made with following PRs:
* https://github.com/DataDog/dd-sdk-android/pull/1447
* https://github.com/DataDog/dd-sdk-android/pull/1399

Revert SdkInit command changes in develop branch

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This change bumps SDK version to `2.0.0` in the SDK v2 branch in order to better distinguish the events in the dashboard.

Bump SDK version to 2.0.0

---

build.gradle.kts
instrumentation-tools/src/constants.py
local_ci.sh

This PR fixes typos in some modules names.

Fix typos in some modules names

---

library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/image-wireframe-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/image-wireframe-update-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/segment-metadata-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/wireframe-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/wireframe-update-mutation-schema.json
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/MobileSegmentExt.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolver.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/WireframeUtils.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/WireframeExt.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolverTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/NodeFlattenerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/WireframeUtilsTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/WireframeExtTest.kt

Generate models for ImageWireframe, plus additional changes to support
Preparation for base64 image support

REPLAY-1723: Update models to support ImageWireframe

---

.gitlab-ci.yml
gradle.properties

I started to receive OOM errors more often recently when building SDK v2 branch, so giving additional 500 MB to the max heap for Gradle build.

Increase max heap used by Gradle to 3G

---

library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/NoOpRecorder.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/Recorder.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayFeature.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorder.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/LifecycleCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/NoOpLifecycleCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayLifecycleCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewOnDrawInterceptor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowCallbackInterceptor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/OnWindowRefreshedCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderFragmentLifecycleCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/MiscUtils.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayFeatureTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorderTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayLifecycleCallbackTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderFragmentLifecycleCallbackTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallbackTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListenerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/MiscUtilsTest.kt

REPLAY-1681 Introduce the SessionReplayRecorder logic

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/sampling/RateBasedSampler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/sampling/Sampler.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentNotGrantedSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentPendingSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/SampledOutSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/SrSnapshotTest.kt
instrumented/integration/src/main/AndroidManifest.xml
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplaySampledOutPlaygroundActivity.kt
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayFeature.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessor.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayFeatureTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/SessionReplayConfigurationForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/MiscUtilsTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

REPLAY-1681 Add the Sampling API

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Promote to 1.20.0-sr-beta2-snapshot

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/NoOpFeatureSdkCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumTest.kt

Small PR containing rename of `NoOpSdkCore` into `NoOpFeatureSdkCore` and a fix for the flaky test.

Minor improvements

---

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt

Tiny PR to align the terminology in the method description.

Replace "sampling rate" with "sample rate" in Session Replay Configuration for the consistency of terminology

---

instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayPlaygroundActivity.kt
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/placeholder-wireframe-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/placeholder-wireframe-update-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/wireframe-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/wireframe-update-mutation-schema.json
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/MobileSegmentExt.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolver.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/WireframeUtils.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/UnsupportedViewMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/utils/WireframeExt.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ForgeConfigurator.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ImageWireframeForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/PlaceholderWireframeForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/WireframeForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolverTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/NodeFlattenerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/WireframeUtilsTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/UnsupportedViewMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/utils/WireframeExtTest.kt

REPLAY-1771 Use the new Placeholder wireframe for unsupported views

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/generator/ClassGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/generator/Identifier.kt
dd-sdk-android-core/api/apiSurface
dd-sdk-android-core/api/dd-sdk-android-core.api
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/file/FileExt.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/ByteArrayExt.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/ConcurrencyExt.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/MiscUtils.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/NumberExt.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/utils/ThrowableExt.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/persistence/Serializer.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/v2/api/context/UserInfo.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/utils/MiscUtilsTest.kt
features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/assertj/JsonObjectAssertExt.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/utils/NumberExt.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/assertj/JsonElementAssert.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt

This PR does the following:
* annotates top-level internal functions with `InternalApi`
* moves `Any?.toJsonElement` to the dedicated class, so that it doesn't show up in the autocompletion dropdown on the user side (it has quite a wide scope).

RUMM-3362: Annotate top-level internal functions with `InternalApi`, move `toJsonElement` to the dedicated class

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/v2/core/internal/storage/ConsentAwareStorage.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/v2/core/internal/storage/ConsentAwareStorageTest.kt

The purpose of this change is to make write to metadata file sequential.
Imagine that we allow write operations to be executed in parallel and there is an operation which writes view event and also updates view count in metadata file. Let's say we have `Operation A` and `Operation B` and before executing them metadata file has `viewCount = 0`. If we allow parallel execution it is possible to have a situation when both operations get 0 as current view count, and both then set it to 1, meaning that once both operations are completed we have a value 1 stored in the metadata file, which is wrong.
By introducing the lock we are making sure that all write operations are sequential, meaning that for the example above the final value will always be 2.
It is not a fix for v1, because currently we …

Add synchronized lock to the write operations

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/storage/FeatureStorageConfiguration.kt

Fix default storage configuration in Core

---

local_ci.sh

Update the `local_ci.sh`script to allow link to custom path for the dd_source detekt rules

Make local_ci.sh script adaptable to each engineer

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release `2.0.0-beta1`.

RUMM-3406: Prepare release 2.0.0-beta1

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/FilePersistenceConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestratorTest.kt
detekt_custom.yml

This is a release with a single change to solve the issue described in https://github.com/DataDog/dd-sdk-android/issues/1469.

Prepare release 1.19.3

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataOkHttpUploader.kt

Don't report OkHttp errors to telemetry, because they can happen quite often (no internet connection) and not actionable.

Don't report OkHttp throwables to telemetry

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Next dev cycle 2.1.0

---

features/dd-sdk-android-rum/api/apiSurface
features/dd-sdk-android-rum/api/dd-sdk-android-rum.api
features/dd-sdk-android-rum/src/main/json/rum/_common-schema.json
features/dd-sdk-android-rum/src/main/json/rum/view-schema.json
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashEventHandler.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/LongTaskEventAssert.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

Adds the configured RUM sample rate to all reported RUM events. 

[RUMM-3449] Add sample rate to reported RUM events

---

features/dd-sdk-android-session-replay-material/README.md
features/dd-sdk-android-session-replay/README.md

REPLAY-1302 Add the README files for SR modules

---

.gitlab-ci.yml
dogfood.py

Removes the dogfooding step in CI and reference to bridge in the dogfooding script 
Bridge repository is archived and can't receive branches/PRs anymore

Remove the bridge dogfooding step, bridge repo is archived

---

detekt_custom.yml
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorder.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactory.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/gson/GsonExt.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/BatchesToSegmentsMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolver.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessor.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RumContextDataHandler.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowCallbackInterceptor.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowInspector.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallback.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorderTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/gson/GsonExtTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/BatchesToSegmentMapperTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolverTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RumContextDataHandlerTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowCallbackInterceptorTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowInspectorTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallbackTest.kt

REPLAY-1895 use internalLogger in SR modules

---

features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/gson/GsonExtTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/BatchesToSegmentMapperTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/MutationResolverTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RumContextDataHandlerTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallbackTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/utils/InternalLoggerUtils.kt

Two merges around the Internal Logger created failing tests on develop. 
This fixes that.

Fix tests around InternalLogger

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt

RUM-952 Provide the inBackground property for batch_delete metric

---

codecov.sh
ddcoverage.py

Update gitlab CI env variables for gitlab 16
Gitlab 16 upgrade will be coming soon

Update gitlab CI env variables for gitlab 16

---

features/dd-sdk-android-session-replay/api/apiSurface
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewUtilsInternal.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ButtonMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskInputTextViewMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskTextViewMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextViewMapper.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewUtilsInternalTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/ImageWireframeHelperTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseTextViewWireframeMapperTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskTextViewMapperTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/ImageComponentsFragment.kt
sample/kotlin/src/main/res/layout/fragment_image_components.xml

Implement serialization of TextViews and Buttons to base64.
Continuation of base64 support for different views.

RUM-936: Serialize TextViews/Buttons to base64

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release `2.1.0`.

RUM-1021: Prepare release 2.1.0

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR bumps development version to 2.2.0 after the release of version 2.1.0.

Next dev iteration 2.2.0

---

CHANGELOG.md

This PR does the merge of release 2.1.0 into develop branch with all the conflicts resolved (there was one conflict in `AndroidConfig.kt`).

Merge release 2.1.0 into develop branch

---

.gitlab-ci.yml
sample/kotlin/src/main/AndroidManifest.xml

Use a shared Android Lint check from dd-source 
Shared CI steps across all Android projects

MTG-7 Use shared Android Lint check

---

instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_checkbox_and_radio_fields_allow_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_checkbox_and_radio_fields_mask_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_checkbox_and_radio_fields_mask_user_input_payload.json
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/BaseSessionReplayTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentGrantedSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentNotGrantedSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentPendingSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/SampledOutSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/chekboxandradio/SrCheckBoxAndRadioFieldsAllowTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/chekboxandradio/SrCheckBoxAndRadioFieldsMaskTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/chekboxandradio/SrCheckBoxAndRadioFieldsMaskUserInputTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/sensitivefields/SrSensitiveFieldsMaskTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/sensitivefields/SrSensitiveFieldsMaskUserInputTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/textfields/SrTextFieldsAllowTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/textfields/SrTextFieldsMaskTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/textfields/SrTextFieldsMaskUserInputTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/textfields/SrTextFieldsWithInputMaskUserInputTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt
instrumented/integration/src/main/AndroidManifest.xml
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayRadioCheckboxFieldsActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplaySensitiveFieldsActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayTextFieldsActivity.kt
instrumented/integration/src/main/res/layout/sr_radio_checkbox_fields_layout.xml
instrumented/integration/src/main/res/values/strings.xml
local_ci.sh

RUM-1004 Add the SR functional tests for checkboxes and radiobuttons

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

Edit the sample to send RUM error on low memory callbacks

Add sample showing how to listen to memory events

---

features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/opentracing/PendingTraceTest.kt

Add some thread safe guards for PendingTrace, and prevent `ConcurrentModificationException`.
Fixes #1570 

RUM-790 Fix PendingTrace ConcurrentModificationException

---

build.gradle.kts
features/dd-sdk-android-webview/api/apiSurface
features/dd-sdk-android-webview/api/dd-sdk-android-webview.api
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/WebViewTracking.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/log/WebViewLogEventConsumer.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/WebViewTrackingTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/log/WebViewLogEventConsumerTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/webview/WebViewTrackingE2ETests.kt

Add a setting to set the logs sample rate for Webview Logs integration

RUM-985 Add sampler to WebViewLogEventConsumer

---

instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_allow_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_user_input_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_allow_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_mask_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_mask_user_input_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_allow_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_mask_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_mask_user_input_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_with_input_mask_user_input_payload.json

Fix SR functional tests payloads after develop roll - back

---

CONTRIBUTING.md

Follow up after today's meeting to improve our testing guidelines.

Update testing conventions

---

.github/workflows/codeql-analysis.yml
.gitlab-ci.yml
CONTRIBUTING.md
build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/config/TestPyramidConfig.kt
local_ci.sh
reliability/single-fit/logs/build.gradle.kts
reliability/single-fit/logs/src/main/AndroidManifest.xml
reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/ScaffoldingTest.kt
reliability/single-fit/logs/src/test/kotlin/com/datadog/android/logs/integration/tests/elmyr/LogsIntegrationForgeConfigurator.kt
reliability/single-fit/rum/build.gradle.kts
reliability/single-fit/rum/src/main/AndroidManifest.xml
reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/ScaffoldingTest.kt
reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/tests/elmyr/RumIntegrationForgeConfigurator.kt
reliability/single-fit/trace/build.gradle.kts
reliability/single-fit/trace/src/main/AndroidManifest.xml
reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/ScaffoldingTest.kt
reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/tests/elmyr/TraceIntegrationForgeConfigurator.kt
settings.gradle.kts

Creates the scaffolding for our Single Feature Integration Test level from our Test Pyramid strategy.

RUM-1517 Add test pyramid scaffolding

---

.github/CODEOWNERS

This PR includes the `rum-mobile-android` team as a code owning team in order to ensure we have at least 1 Android Engineer reviewing every merged PR.

Include rum-mobile-android as codeowner

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR bumps dev version to `2.4.0`.

Bump dev version to 2.4.0

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR bumps SDK version for development.

Next dev iteration: 2.5.0

---

features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/WebViewTracking.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/DatadogEventBridge.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/WebViewTrackingTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/DatadogEventBridgeTest.kt

RUM-2484 Provide the SR privacy level through the DatadogEventBridge

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/SessionReplayFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/WebViewRecordFragment.kt
sample/kotlin/src/main/res/layout/fragment_session_replay.xml
sample/kotlin/src/main/res/layout/fragment_webview_with_replay_support.xml
sample/kotlin/src/main/res/navigation/nav_graph.xml
sample/kotlin/src/main/res/values/strings.xml

RUM-2590 Add recorded WebView scenario into the sample app

---

.gitlab-ci.yml

Prevent gitlab Jobs from crashing with OOM

Fix OOM in CI jobs

---

detekt_custom.yml
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
features/dd-sdk-android-webview/api/apiSurface
features/dd-sdk-android-webview/api/dd-sdk-android-webview.api
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/WebViewTracking.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/MixedWebViewEventConsumer.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/replay/WebViewReplayEventConsumer.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/replay/WebViewReplayEventMapper.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/replay/WebViewReplayFeature.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/rum/TimestampOffsetProvider.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/WebViewTrackingTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/MixedWebViewEventConsumerTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/replay/WebViewReplayEventConsumerTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/replay/WebViewReplayEventMapperTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/rum/TimestampOffsetProviderTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventConsumerTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/webview/WebViewTrackingE2ETests.kt

RUM-2487 Provide the WebViewRecordConsumer for the JS bridge

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt

This PR updates `dd-java-agent` used to version 1.26.1.

Use Datadog Agent 1.26.1

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Since we are going to release version 2.5.0, we need to bump the dev version.

Next dev iteration 2.6.0

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release 2.5.0.

Prepare release 2.5.0

---

CHANGELOG.md

This PR does the merge of `release/2.5.0` into `develop` branch with conflicts resolved.

Merge `release/2.5.0` branch into `develop` branch

---

detekt_custom.yml
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt

Cherry Pick from #1830 
Create a 2.5.1 hotfix with this commit

Make a copy of attributes before passing them to RUM event

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepare 2.5.1

---

detekt_custom.yml
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/RumContext.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/WebViewTracking.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventConsumer.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventMapper.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFeature.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/rum/domain/NativeRumViewsCache.kt
features/dd-sdk-android-webview/src/main/kotlin/com/datadog/android/webview/internal/rum/domain/WebViewNativeRumViewsCache.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/WebViewTrackingTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventMapperTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFeatureTest.kt
features/dd-sdk-android-webview/src/test/kotlin/com/datadog/android/webview/internal/rum/domain/WebViewNativeRumViewsCacheTest.kt

RUM-2485 Provide the parent container information for browser rum events

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR bumps dev version to 2.7.0.

Next dev iteration

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release 2.6.0.

Prepare release 2.6.0

---

CHANGELOG.md

This PR does the merge of `release/2.6.0` branch into `develop` branch with conflicts resolved.

Merge `release/2.6.0` in `develop`

---

features/dd-sdk-android-rum/api/apiSurface
features/dd-sdk-android-rum/api/dd-sdk-android-rum.api
features/dd-sdk-android-rum/src/main/json/telemetry/_common-schema.json

When updating the `source` property, the RUM schema was updated, but not the telemetry one. This updates the telemetry schema.

Fix missing source in telemetry json schema

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release 2.6.1.

Prepare release 2.6.1

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepare hotfix 2.6.2

---

LICENSE-3rdparty.csv
build.gradle.kts
detekt_custom.yml
features/dd-sdk-android-trace/api/apiSurface
features/dd-sdk-android-trace/api/dd-sdk-android-trace.api
features/dd-sdk-android-trace/build.gradle.kts
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/context/propagation/TraceStateHelper.java
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelConventions.java
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelExtractedContext.java
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelSpan.java
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelSpanBuilder.java
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelSpanContext.java
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelSpanLink.java
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelTracer.java
features/dd-sdk-android-trace/src/main/java/com/datadog/opentelemetry/trace/OtelTracerBuilder.java
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/OtelTracerProvider.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/data/NoOpOtelWriter.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/OtelTracerBuilderProviderTest.kt
features/dd-trace-core/src/main/java/com/datadog/trace/api/Config.java

RUM-3247 Port the Otel Java implementation and provide OtelTracerProvider Builder

---

sample/kotlin/build.gradle.kts
sample/kotlin/proguard-rules.pro

Sometimes it is useful to enable the minification to test the things. This PR adds the missing rules for that.

Update ProGuard configuration

---

features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/OtelTracerProvider.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/TracingFeature.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/data/OtelTraceWriter.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/domain/event/OtelDdSpanToSpanEventMapper.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/OtelTracerBuilderProviderTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/TracingFeatureTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/data/OtelTraceWriterTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/domain/event/OtelDdSpanToSpanEventMapperTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/CoreDDSpanForgeryFactory.kt

RUM-3394 Provide the OtelDataWriter to be used in the OtelTracer

---

detekt_custom.yml
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/BatchesToSegmentsMapper.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/net/BatchesToSegmentsMapperTest.kt

Sends the `hasFullSnapshot` properly when forwarding Webview session replay segments

RUM-3302 detect full snapshot from webview sr

---

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/data/ComposeFields.kt
features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/reflection/ComposeReflection.kt
features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/internal/data/ComposeFieldsTest.kt

RUM-2895 Read composition group data parameter fields

(4/10) RUM-2895 Read composition group data parameter fields

---

detekt_custom.yml
features/dd-sdk-android-session-replay-compose/api/apiSurface
features/dd-sdk-android-session-replay-compose/api/dd-sdk-android-session-replay-compose.api
features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/ComposeExtensionSupport.kt
features/dd-sdk-android-session-replay-compose/src/test/kotlin/com/datadog/android/sessionreplay/compose/ComposeExtensionSupportTest.kt

RUM-2895 Create the ComposeExtensionSupport

(7/10) RUM-2895 Create the ComposeExtensionSupport

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release `2.7.0`.

Prepare release 2.7.0

---

detekt_custom.yml
features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/ComposeWireframeMapper.kt
features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/TextCompositionGroupMapper.kt

RUM-2895 Create the TextCompositionGroupMapper

(8/10) RUM-2895 Create the TextCompositionGroupMapper

---

CHANGELOG.md

This PR merges release 2.7.0 into `develop` branch.

Merge release 2.7.0 into `develop` branch

---

dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/system/DefaultAndroidInfoProviderTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/thread/ThreadPoolExecutorExtTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/JankStatsActivityLifecycleListenerTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/WireframeUtilsTest.kt

This PR fixes some flaky tests.

Address some flaky tests

---

instrumented/integration/src/androidTest/assets/session_replay_payloads/consent_granted_sr_test_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_image_buttons_allow_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_image_buttons_mask_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_allow_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_images_mask_user_input_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_allow_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_mask_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_sensitive_fields_mask_user_input_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_allow_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_mask_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_mask_user_input_payload.json
instrumented/integration/src/androidTest/assets/session_replay_payloads/sr_text_fields_with_input_mask_user_input_payload.json

The mimetype was removed in the refactor pr and this is breaking the nightly tests. This pr removes the mimetype from the payload jsons

Fix mime type for nightly tests

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/ConsentGrantedSrTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/sessionreplay/imagebuttons/SrImageButtonsMaskTest.kt

Temporarily disable some SR integration tests due to CI flakiness

Disable some sr integration tests temporarily due to flakiness

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/thread/BackPressuredBlockingQueue.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/vitals/VitalsFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/vitals/VitalsViewModel.kt
sample/kotlin/src/main/res/layout/fragment_vitals.xml
sample/kotlin/src/main/res/values/strings.xml

Ensure the configuration uses the customer provided backpressureStrategy
Add some tests in the sample app

RUM-3668 update sample and fix configuration

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepare 2.7.1

---

detekt_custom.yml
features/dd-sdk-android-session-replay-compose/consumer-rules.pro
features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/ButtonCompositionGroupMapper.kt
features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/ComposeWireframeMapper.kt

RUM-2895 Create the ButtonCompositionGroupMappers

(9/10) RUM-2895 Create the ButtonCompositionGroupMappers

---

sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/NavigationSample.kt

RUM-2895 Update sample compose screen

(10/10) RUM-2895 Update sample compose screen

---

features/dd-sdk-android-trace/src/main/java/com/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/AndroidTracer.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/FeatureSdkCoreExt.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/OtelTracerProvider.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/FeatureSdkCoreExtTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/OtelTracerBuilderProviderTest.kt

RUM-3250 Provide Otel bundle with logs feature

---

.gitlab-ci.yml
Dockerfile.gitlab

This PR makes use of Golden Base Image (GBI) for the Docker containers we are using. These images are owned by Datadog.

Switch to the Golden Base Image for Docker

---

reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/opentracing/AndroidTracerTest.kt
reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/opentracing/SpanExt.kt
reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/opentracing/TraceConfigurationTest.kt
reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/opentracing/UtilitiesTest.kt
reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/tests/assertj/SpansPayloadAssert.kt

RUM-4030 Setup the trace end tests environment for Otel API

---

buildSrc/build.gradle.kts
gradle/libs.versions.toml

This dependency is not used anymore, so removing it.

Remove unused Maven Model dependency

---

.gitlab-ci.yml

Publish a version of the sample app to the RUM Playground to generate Mobile+Webview SR from synthetics to help test the SR player

RUM-3120 upload sample app to rum playground

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares SDK release version `2.9.0`.

Prepare release 2.9.0

---

CHANGELOG.md
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/constraints/DatadogDataConstraints.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadStatus.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/constraints/DatadogDataConstraintsTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadStatusTest.kt

This PR merges release `2.9.0` into `develop` branch.

Merge release `2.9.0` into `develop` branch

---

local_ci.sh

The relevant version on CI according to the pipeline version is 0.50.0, so fixing it.

Fix KtLint version in `local_ci` script

---

.gitlab-ci.yml
build.gradle.kts

Adding the gitlab step for publishing the `dd-sdk-android-trace-otel` module
Removing the `dd-sdk-android-trace` unit tests exception, this was a leftover from a previous PR which I forgot to remove.

RUM-4372 Setup the CI and gradle tests for the new dd-sdk-android-trace-otel module

---

.gitlab-ci.yml

This PR updates static analysis pipeline version. It includes at least https://github.com/DataDog/dd-source/pull/96112 and https://github.com/DataDog/dd-source/pull/95612.

Update static analysis pipeline version

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR bumps SDK version, because we are going to release 2.10.0 (see https://github.com/DataDog/dd-sdk-android/pull/2049).

Next dev iteration 2.11.0

---

.gitlab-ci.yml
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/utils/Version.kt

Configure the relase snapshot version

---

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt

Reduce method call sample rate from 5f to 0.1f

Reduce Method Call Sample Rate

---

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt

Limit the total number of telemetry events sent per session

Limit total telemetry events sent per session

---

features/dd-sdk-android-trace/consumer-rules.pro

Fix the jctools proguard rules

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release `2.10.1`.

Prepare release 2.10.1

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/TreeViewTraversal.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt

This PR merges release `2.10.1` into `master` branch.

Merge release `2.10.1` into `master` branch

---

sample/kotlin/build.gradle.kts
sample/kotlin/proguard-rules.pro

Even though minification is not enabled for the sample app, it is still useful to have Proguard rules attached for the cases when we need to test sample app with minification enabled.

Add ProGuard rules to sample app

---

sample/vendor-lib/build.gradle.kts
sample/vendor-lib/src/main/kotlin/com/datadog/android/vendor/sample/LocalServer.kt
sample/wear/proguard-rules.pro

RUM-4508 Add OpenTelemetry use case into the vendor-lib sample

---

integrations/dd-sdk-android-okhttp-otel/src/main/kotlin/com/datadog/android/okhttp/otel/OkHttpExt.kt
integrations/dd-sdk-android-okhttp-otel/src/test/kotlin/com/datadog/android/okhttp/otel/OkHttpExtTest.kt

Fix the Okhttp Otel parent span feature when not using RUM

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/service/LogsForegroundService.kt

Adapt the sample app to showcase the specifics of this change
> [!NOTE]

RUM-4822 adapt sample app

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

Prepare a "debug" build specifically for this incident 
> [!NOTE]

RUM-4822 Prepare debug build

---

features/dd-sdk-android-rum/api/apiSurface
features/dd-sdk-android-rum/api/dd-sdk-android-rum.api
features/dd-sdk-android-rum/src/main/json/rum/_common-schema.json
features/dd-sdk-android-rum/src/main/json/rum/_view-container-schema.json
features/dd-sdk-android-rum/src/main/json/telemetry/_common-schema.json

Follow-up https://github.com/DataDog/rum-events-format/pull/214: update RUM and telemetry schema.
No code/tests changes needed.

RUM-5110: Update models with KMP SDK source

---

dd-sdk-android-core/api/apiSurface
dd-sdk-android-core/api/dd-sdk-android-core.api
dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/InternalLogger.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/logger/SdkInternalLogger.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcher.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/metrics/MethodCalledTelemetry.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/metrics/MethodCallSamplingRate.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/logger/SdkInternalLoggerTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/BatchMetricsDispatcherTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/metrics/MethodCalledTelemetryTest.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/SessionEndedMetricDispatcher.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/FakeInternalLogger.kt
reliability/stub-core/src/main/kotlin/com/datadog/android/core/stub/StubInternalLogger.kt

Reverts DataDog/dd-sdk-android#2108

Revert "Add sampling rate to internal metrics"

---

features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/metric/RumSessionEndedMetricTest.kt

Fix the min boundary of generating the int for unit test.

Fix RumSessionEnded metric flaky test

---

sample/kotlin/build.gradle.kts

Add session replay compose module dependency in sample app
The sample app can not be compiled due to the lack of the dependency

Add session replay compose module dependency in sample app

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ResourceTrackingTest.kt
integrations/dd-sdk-android-glide/src/main/kotlin/com/datadog/android/glide/DatadogGlideModule.kt
integrations/dd-sdk-android-okhttp/api/apiSurface
integrations/dd-sdk-android-okhttp/api/dd-sdk-android-okhttp.api
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/TraceContextInjection.kt
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorBuilderTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutRumTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/DatadogInterceptorWithoutTracesTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/TracingInterceptorBuilderTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorContextInjectionSampledTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerNotSendingSpanTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

Following the requirements specified in this [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3529509193/RUM+SDKs+Trace+Context+Injection+control) we are adding this new API and fixing the traces propagation in our `TracingInterceptor`.
This also fixes the issue: #2124

RUM-3536 Introduce the TraceContextInjection to handle sampling in distributed traces

---

.gitlab-ci.yml

This publishes a version of the Sample App targeting staging into the staging Synthetics org for Backend E2E tests

Publish sample app on staging org for e2e testing

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorage.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorageTest.kt

Adds a telemetry to measure the delay between the moment data is planned to be written, and the moment it's actually written.
This delay is expected, and will drive the backpressure experienced by the executors on the persistence layer.

RUM-3826 Add telemetry on batch writing operation

---

detekt_custom.yml
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorContextInjectionSampledTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerNotSendingSpanTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNonDdTracerTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorNotSendingSpanTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt

RUM-4710 Make sure network local spans have kind:client tag

---

reliability/stub-feature/build.gradle.kts
settings.gradle.kts

RUM-5531 Introduce the stub-feature module for testing pyramid

---

reliability/core-it/build.gradle.kts
reliability/core-it/src/main/AndroidManifest.xml
reliability/core-it/src/main/res/values/strings.xml
settings.gradle.kts

RUM-5530 Add the core-it module in the test pyramid

---

gradle/libs.versions.toml
sample/kotlin/build.gradle.kts
tools/benchmark/build.gradle.kts
tools/benchmark/src/main/java/com/datadog/benchmark/DatadogExporterConfiguration.kt
tools/benchmark/src/main/java/com/datadog/benchmark/EndPoint.kt
tools/benchmark/src/main/java/com/datadog/benchmark/internal/DatadogHttpClient.kt
tools/benchmark/src/main/java/com/datadog/benchmark/internal/MetricRequestBodyBuilder.kt
tools/benchmark/src/main/java/com/datadog/benchmark/internal/RequestBodyBuilder.kt
tools/benchmark/src/main/java/com/datadog/benchmark/internal/model/MetricContext.kt
tools/benchmark/src/main/java/com/datadog/benchmark/internal/model/MetricType.kt
tools/benchmark/src/test/java/forge/ForgeConfigurator.kt
tools/benchmark/src/test/java/forge/GaugeDataForgeryFactory.kt
tools/benchmark/src/test/java/forge/MetricContextForgeryFactory.kt
tools/benchmark/src/test/java/forge/MetricDataForgeryFactory.kt
tools/benchmark/src/test/java/forge/PointDataForgeryFactory.kt
tools/benchmark/src/test/java/internal/MetricDataAssert.kt
tools/benchmark/src/test/java/internal/MetricRequestAssert.kt
tools/benchmark/src/test/java/internal/MetricRequestBodyBuilderTest.kt
tools/benchmark/src/test/java/internal/PointAssert.kt

Implement MetricHttpClient and RequestBodyBuilder,
The request corresponds to the spec: 
https://docs.datadoghq.com/api/latest/metrics/#submit-metrics
RUM-5553

RUM-5553: Implement MetricHttpClient and RequestBodyBuilder

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Bump develop to 2.13.0

---

.gitlab-ci.yml
sample/benchmark/build.gradle.kts

* Setup benchmark sample app synthetics gitlab configuration
RUM-5550

RUM-5550: Setup Benchmark sample app synthetics gitlab configuration

---

.gitlab-ci.yml
buildSrc/src/main/kotlin/com/datadog/gradle/config/FlavorBuildConfig.kt
sample/benchmark/build.gradle.kts
sample/benchmark/proguard-rules.pro
sample/benchmark/src/main/AndroidManifest.xml
sample/benchmark/src/main/java/com/datadog/benchmark/sample/BenchmarkApplication.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/BenchmarkNavigationPredicate.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/MainActivity.kt
tools/benchmark/src/main/java/com/datadog/benchmark/internal/DatadogHttpClient.kt

Setup datadog sdk and session replay in benchmark application
RUM-5550

RUM-5550: Add datadog config and enable SR in benchmark sample app

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/JsonSchemaReader.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/TypeDefinition.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/generator/ClassGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/generator/ClassJsonElementDeserializerGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/generator/ClassStringDeserializerGenerator.kt
buildSrc/src/test/kotlin/com/datadog/android/core/internal/utils/JsonSerializer.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/JsonSchemaReaderTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelValidationTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/TestDefinitions.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/generator/FileGeneratorTest.kt
buildSrc/src/test/kotlin/com/example/forgery/ForgeryConfiguration.kt
buildSrc/src/test/kotlin/com/example/forgery/WeirdComboForgeryFactory.kt
buildSrc/src/test/kotlin/com/example/model/Animal.kt
buildSrc/src/test/kotlin/com/example/model/Company.kt
buildSrc/src/test/kotlin/com/example/model/Location.kt
buildSrc/src/test/kotlin/com/example/model/Version.kt
buildSrc/src/test/kotlin/com/example/model/WeirdCombo.kt
buildSrc/src/test/resources/input/one_of_nested.json
features/dd-sdk-android-rum/api/apiSurface
features/dd-sdk-android-rum/api/dd-sdk-android-rum.api
features/dd-sdk-android-rum/src/main/json/telemetry/configuration-schema.json
features/dd-sdk-android-rum/src/main/json/telemetry/usage-schema.json
features/dd-sdk-android-rum/src/main/json/telemetry/usage/browser-features-schema.json
features/dd-sdk-android-rum/src/main/json/telemetry/usage/common-features-schema.json
features/dd-sdk-android-trace/api/apiSurface
features/dd-sdk-android-trace/api/dd-sdk-android-trace.api

This updates our Kotlin data class generation from JsonSchema
- Handle nested `one_of` descriptions
- Better handling of `constant` properties: we now check the constant has the expected value

Json schema update

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/DatadogCore.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/user/DatadogUserInfoProvider.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/user/MutableUserInfoProvider.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/user/DatadogUserInfoProviderTest.kt

Make sure user properties are immutable when setUserInfo

---

README.md

Merges the external PR request to develop.

Merge README external fix to develop

---

sample/benchmark/build.gradle.kts
sample/benchmark/src/main/java/com/datadog/benchmark/sample/benchmark/DatadogBenchmark.kt
sample/benchmark/src/test/java/com/datadog/benchmark/sample/benchmark/DatadogBenchmarkTest.kt
tools/benchmark/src/main/java/com/datadog/benchmark/exporter/DatadogMetricExporter.kt

The session replay was wrongly enabled when the "run" is "baseline",
The PR fixes it by checking the "run" condition.
Unit test is added to protect it.

Fix Benchmark baseline run bug and add unit test

---

sample/benchmark/README.md
tools/benchmark/README.md

Add README for benchmark module and benchmark sample application
[RUM:5553]
[RUM:5550]

Add README for benchmark module and benchmark sample application

---

CHANGELOG.md

2.12.0 release was missing `CHANGELOG` file update, fixing that.

Add changelog for 2.12.0 release (in release branch)

---

reliability/core-it/build.gradle.kts
reliability/stub-feature/build.gradle.kts

Removing things that are not used/already declared to speed up build configuration.

Remove redundant build configuration in new reliability modules

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares a hotfix 2.12.1 release.

Prepare release 2.12.1

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/GlobalRumMonitor.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/GlobalRumMonitorTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt

This PR does the merge release `2.12.1` into `master` branch.

Merge release `2.12.1` into `master` branch

---

CHANGELOG.md
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/GlobalRumMonitor.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/GlobalRumMonitorTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogInterceptor.kt

This PR does the merge release `2.12.1` into `develop` branch.

Merge release `2.12.1` into `develop` branch

---

reliability/single-fit/trace/src/test/kotlin/com/datadog/android/trace/integration/opentracing/AndroidTracerTest.kt

This test takes almost 1 minute to do 16 repetitions. Cutting it down to 4 repetitions.

Speed up Send sampled Spans test

---

instrumented/integration/build.gradle.kts
local_ci.sh
reliability/core-it/build.gradle.kts
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/FeatureSdkCoreContextTest.kt
reliability/stub-feature/src/main/kotlin/com/datadog/android/api/feature/stub/StubContextUpdateReceiver.kt
reliability/stub-feature/src/main/kotlin/com/datadog/android/api/feature/stub/StubFeatureEventReceiver.kt

RUM-5526 Add the integration tests for FeatureSdkCore public API

---

tools/benchmark/build.gradle.kts
tools/benchmark/generate_trace_models.gradle.kts
tools/benchmark/src/main/json/span-schema.json
tools/benchmark/src/test/java/forge/SpanEventForgeryFactory.kt

* Copy `span-schema.json` into `tools/benchmark` module
* Copy gradle task to generate `SpanEvent` class into `tools/benchmark`
* Copy Forge factory into `tools/benchmark` for span event
RUM-5846

Add Datadog span event schema in benchmark module

---

.gitlab-ci.yml
tools/benchmark/build.gradle.kts
tools/benchmark/generate_trace_models.gradle.kts

Publish benchmark module to sonatype
To use benchmark module in some external demo applications

Publish benchmark module to sonatype

---

tools/benchmark/src/main/java/com/datadog/benchmark/internal/reader/MemoryVitalReader.kt
tools/benchmark/src/test/java/internal/MemoryVitalReaderTest.kt

Update benchmark metrics memory reader probe interval
Logic changes:
* Before: Memory reader reads the stats file directly for the memory data when `readVitalData()` is called every 10 seconds.
* After: Memory reader keeps reading the stats file every 500ms internally and keeps the max memory data until `readVitalData` is called to output this result.

Update benchmark metrics memory reader probe interval

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/KioskTrackingTest.kt

RUM-5919 Fix the flakiness in the KioskTrackingTest

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepare `2.13.1-debug` release

Prepare 2.13.1-debug

---

features/dd-sdk-android-rum/api/apiSurface
features/dd-sdk-android-rum/api/dd-sdk-android-rum.api
features/dd-sdk-android-rum/src/main/json/rum/error-schema.json

These properties are iOS-specific, but it is better still to have them to simplify mapping on the cross-platform side.

Update RUM Error event schema

---

features/dd-sdk-android-session-replay/api/apiSurface
features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplay.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/DefaultRecorderProvider.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/Debouncer.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/DefaultOnDrawListenerProducer.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SessionReplayRecorder.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/SessionReplayConfigurationForgeryFactory.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/DebouncerTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListenerTest.kt

[Adding API changes] Add dynamic optimization field in SessionReplayConfiguration
RUM-5184

RUM-5184: Add dynamic optimization field in SessionReplayConfiguration

---

.gitignore
.gitlab-ci.yml
build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/config/DetektCustomConfig.kt
dd-sdk-android-core/build.gradle.kts
dd-sdk-android-internal/build.gradle.kts
features/dd-sdk-android-logs/build.gradle.kts
features/dd-sdk-android-ndk/build.gradle.kts
features/dd-sdk-android-rum/build.gradle.kts
features/dd-sdk-android-session-replay-material/build.gradle.kts
features/dd-sdk-android-session-replay/build.gradle.kts
features/dd-sdk-android-trace-otel/build.gradle.kts
features/dd-sdk-android-trace/build.gradle.kts
features/dd-sdk-android-webview/build.gradle.kts
integrations/dd-sdk-android-coil/build.gradle.kts
integrations/dd-sdk-android-compose/build.gradle.kts
integrations/dd-sdk-android-fresco/build.gradle.kts
integrations/dd-sdk-android-glide/build.gradle.kts
integrations/dd-sdk-android-okhttp-otel/build.gradle.kts
integrations/dd-sdk-android-okhttp/build.gradle.kts
integrations/dd-sdk-android-rum-coroutines/build.gradle.kts
integrations/dd-sdk-android-rx/build.gradle.kts
integrations/dd-sdk-android-sqldelight/build.gradle.kts
integrations/dd-sdk-android-timber/build.gradle.kts
integrations/dd-sdk-android-trace-coroutines/build.gradle.kts
integrations/dd-sdk-android-tv/build.gradle.kts
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/sdk/PackageNameVisibility.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/sdk/ThreadSafety.kt

This  task splits the detekt custom job to limit the RAM usage in CI

Update custom detekt CI Job

---

tools/benchmark/src/main/java/com/datadog/benchmark/internal/MetricRequestBodyBuilder.kt
tools/benchmark/src/test/java/internal/MetricRequestBodyBuilderTest.kt

Add env tag in benchmark metrics
To separate debug test metrics and release metrics

Add env tag in benchmark metrics

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Bump develop to 2.15.0-snapshot

Bump next dev iteration

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

• Promote 2.14.0 to release
• Update changelog

Add changelog for 2.14.0 release

---

CHANGELOG.md

Merge 2.14.0 into develop

---

reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/FeatureSdkCoreTest.kt
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/InternalSdkCoreTest.kt

These tests had concurrency issues. Updating them a bit by removing `CountdownLatch` and making more stable.

Fix flaky feature context integration tests

---

features/dd-sdk-android-session-replay/api/apiSurface
features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api
features/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/segment-metadata-schema.json

Change is coming from https://github.com/DataDog/rum-events-format/pull/223.

Update Session Replay schema with a Kotlin Multiplatform source for Mobile segment

---

features/dd-sdk-android-session-replay-compose/consumer-rules.pro
features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/mappers/semantics/ImageSemanticsNodeMapper.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/ImageSample.kt

* Changes some proguard rules in order to make the code work in release build.
* Changes some reflection logic for image mapper in order to make it work in higher version of `Coil`
* Change the bitmap copy config in order to make it work for Bitmap ALPHA config.
* Update the sample app image showcase screen.

Fix Image reflection issue and proguard rules

---

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableTextViewMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableWireframeMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapper.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseCheckableTextViewMapperTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapperTest.kt

Fix checkable mapper privacy issue

---

features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/domain/event/CoreTracerSpanToSpanEventMapper.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/domain/event/DdSpanToSpanEventMapper.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/domain/event/MetaKeys.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/assertj/SpanEventAssert.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/domain/event/CoreTracerSpanToSpanEventMapperTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/domain/event/DdSpanToSpanEventMapperTest.kt

Requested by several customers we are adding the application variant as part of the local span `metadata` property.

RUM-6893 Add application variant into the local Span metadata

---

.gitlab-ci.yml

This PR makes use of macOS Sonoma runners with the Android SDK repo dedicated AMI.

Use repository-specific AMI with macOS Sonoma runners

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Update version to 2.15.1 to make a hot fix

Update version to 2.15.1

---

detekt_custom.yml
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaterialExtensionSupport.kt
features/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/internal/ChipWireframeMapper.kt
features/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/ChipWireframeMapperTest.kt
features/dd-sdk-android-session-replay/api/apiSurface
features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableCompoundButtonMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableTextViewMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckedTextViewMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/SwitchCompatMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/DrawableCopier.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextViewMapper.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseCheckableTextViewMapperTest.kt
sample/kotlin/src/main/res/layout/fragment_text_view_components.xml
sample/kotlin/src/main/res/values/strings.xml

Merge develop into feature/sr_compose

Merge develop into feature/sr_compose

---

CHANGELOG.md
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolver.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/resources/ResourceResolverTest.kt

Merge 2.15.1 into develop

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Bump version from Snapshot to Release for 2.16.0

Bump version from Snapshot to Release for 2.16.0

---

.gitlab-ci.yml

Add publish sonatype task for Session Replay Compose module

---

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/ViewLoadingTimeMetricsTests.kt
reliability/single-fit/rum/src/test/kotlin/com/datadog/android/rum/integration/tests/assertj/RumEventAssert.kt

RUM-7623 Add integration tests for TTNS metric

---

features/dd-sdk-android-rum/build.gradle.kts
gradle/libs.versions.toml

Explicit the direct dependency to AndroidX Fragment library
Fixes #2440

RUM-7620 Explicit Fragment dependency

---

CHANGELOG.md

Update develop with 2.16.1. Since everything already exists in develop this means just updating the changelog.

Merge 2.16.1 to develop

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Bump version on develop to 2.18.0-SNAPSHOT.

Bump develop version to 2.18.0 snapshot

---

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

Use a more accurate view duration : do not update the view duration after the view has been stopped.

RUM-7806 improve the view duration accuracy

---

gradle/libs.versions.toml

This PR updates AGP to version 8.7.3 (not to the latest 8.8.0, this is on purpose).

Update AGP to version 8.7.3

---

integrations/dd-sdk-android-okhttp/build.gradle.kts
integrations/dd-sdk-android-okhttp/transitiveDependencies

Fixes #2486, check for more details there.

RUM-8141: Add OpenTracing API as exported dependency to OkHttp instrumentation

---

LICENSE-3rdparty.csv
buildSrc/src/main/kotlin/com/datadog/gradle/config/JavadocConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/ApiSurfacePlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/CheckApiSurfaceTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/GenerateJsonSchemaTask.kt
gradle/libs.versions.toml

We were checking only Kotlin API surface file for the missing changes, this PR adds Java API surface file.

Include Java API surface file in the API changes check

---

.github/workflows/codeql-analysis.yml

Pin Github actions to exact hashes for repo security.

Pin github actions to exact commit hash

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR bumps dev version to 2.19.0.

Next dev iteration 2.19.0

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release 2.18.0.

Prepare release 2.18.0

---

CHANGELOG.md

This PR merges `release/2.18.0` branch into `develop` branch.

Merge `release/2.18.0` branch into `develop` branch

---

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/metric/ViewEndedMetricDispatcher.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/metric/ViewEndedMetricDispatcherTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/metric/interactiontonextview/TimeBasedInteractionIdentifierTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/metric/networksettled/TimeBasedInitialResourceIdentifierTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/utils/forge/TelemetryViewInitializationMetricsStateForgeryFactory.kt

Wrong sampling rate for INV and TNS telemetry was introduced in https://github.com/DataDog/dd-sdk-android/pull/2495
Fixing in this ticket. 
Also fixing some missing review comments

[RUM 8449] Fixing sampling rate

---

gradle/libs.versions.toml

Small update of AGP version to 8.8.2.

Update AGP version to 8.8.2

---

features/dd-sdk-android-rum/api/apiSurface
features/dd-sdk-android-rum/api/dd-sdk-android-rum.api
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumConfiguration.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumConfigurationBuilderTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

Follow up on https://github.com/DataDog/dd-sdk-android/pull/2487
Adds missing builder function that allows opting-out from this feature.

Add missing builder function for anonymous user tracking

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepare release 2.19.1

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/LegacyDrawableToColorMapper.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/LegacyDrawableToColorMapperTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/sessionreplay/ImageComponentsFragment.kt
sample/kotlin/src/main/res/drawable/selector_statelist_images_no_default.xml
sample/kotlin/src/main/res/layout/fragment_image_components.xml

Merge Release/2.19.0 into master

Merge Release/2.19.0 into master

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepare release 2.19.2

---

CHANGELOG.md
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/vitals/FrameStatesAggregator.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/vitals/FrameStatesAggregatorTest.kt

Merge hotfix `2.19.2` onto develop

Merge 2.19.2

---

features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/data/TraceWriter.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/data/TraceWriterTest.kt

`MutableList` is not really needed there, we are not supposed to modify incoming collection.

Change `TraceWriter#write` type from `MutableList` to `List`

---

features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/internal/data/TraceWriter.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/data/TraceWriterTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/SpanForgeryFactory.kt

Fixed a flaky test. Had to parametrize `SpanForgeryFactory` in order to control forging the `samplingPriority` field. I am not sure it is a canonical way of doing things so feel free to criticize.

RUM-9130: Fix flaky TraceWriterTest M log error and proceed W write() { serialization failed }

---

features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/internal/data/OtelTraceWriterTest.kt

Some tests in the OtelTraceWriter are flaky because of the method used to generate lists of DDSpans. In some cases, all the elements of the list can be filtered out leaving empty lists, and this causes the tests to fail. 
Solution: ensure the list of spans generated by the tests is not empty.
Flakiness noticed in the tests.

Fix flaky tests in OtelTraceWriter

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/DatadogCore.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreInitializationTest.kt
dd-sdk-android-internal/api/apiSurface
dd-sdk-android-internal/api/dd-sdk-android-internal.api
dd-sdk-android-internal/src/main/java/com/datadog/android/internal/telemetry/InternalTelemetryEvent.kt
dd-sdk-android-internal/src/testFixtures/kotlin/com/datadog/android/internal/tests/elmyr/InternalTelemetryConfigurationForgeryFactory.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/internal/trace/TracingHeaderTypeUtils.kt
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingHeaderTypeMapperTest.kt
integrations/dd-sdk-android-okhttp/src/test/kotlin/com/datadog/android/okhttp/trace/TracingInterceptorTest.kt

We can optimize a big logic of sending OkHttp configuration telemetry by reading values directly in `TelemetryEventHandler` instead.

Optimize OkHttp configuration telemetry

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Bump develop version to 2.21.0 snapshot

Bump version to 2.21.0 snapshot

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Add a changelog for 2.20.0 and bump the version.

Update 2.20.0 changelog and version

---

.github/workflows/changelog-to-confluence.yaml

Adds a workflow changelog-to-confluence.yaml to import the Changelog release notes to confluence.
The release notes are disperced by products which makes difficult to find the release notes information.
- TEEP-319

Add workflow: Changelog update to Confluence

---

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt

Implement a 1% sampling rate on recordedDataQueueHandler telemetry messages
Reduce the frequency of these messages

RUM-8879: Sample telemetry for RecordedDataQueueHandler

---

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt

This is a bug fix based on a support ticket saying they don't see session replay for some of their sessions, after investigating there some key points which lead to the issue.
* All the sessions missing replay are created after the expiration of previous sessions
* Client set `backgroundTrackingEnabled` to false in `RumConfiguration`
* Client have sampleRate 100% and never call start/stop recording manually.
After looking into code, it turns out that the expiration of the session will make `keepSession` false, and stop recording in `SessionReplayFeature`, when `keepSession` becomes true due to new user interactions, session replay will not be able to resume.
This PR fixes this case and add a unit test to protect against this corner case. To achieve that, there are some import flag changes …

RUM-7924: Fix Session Replay is not resumed after the session has expired before

---

gradle/libs.versions.toml
sample/benchmark/build.gradle.kts
sample/benchmark/src/main/java/com/datadog/benchmark/sample/BenchmarkApplication.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/compose/ImageScreen.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/compose/MainView.kt

Use 1.17.0-rc1 Datadog Plugin in Benchmark application for Compose auto-instrumentation

Integrate Datadog Plugin in benchmark application

---

sample/benchmark/src/main/java/com/datadog/benchmark/sample/MainActivity.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/MainActivityViewModel.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/BenchmarkActivityComponent.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/DatadogActivityModule.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/ViewModelsModule.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/common/DispatchersModule.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/navigation/FragmentsNavigationManagerImpl.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/LogPayloadUtils.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/common/DropDownMenuView.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/common/ExpandedItemView.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/common/ValueChooserItemView.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logscustom/LogsScreen.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logscustom/LogsScreenViewModel.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logsheavytraffic/LogsHeavyTrafficFragment.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logsheavytraffic/LogsHeavyTrafficHostFragment.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logsheavytraffic/LogsHeavyTrafficNavigationManager.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logsheavytraffic/LogsHeavyTrafficScreen.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logsheavytraffic/LogsHeavyTrafficSettingsFragment.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logsheavytraffic/LogsHeavyTrafficSettingsScreen.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logsheavytraffic/LogsHeavyTrafficViewModel.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/logsheavytraffic/di/LogsHeavyTrafficComponent.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/utils/ComponentHolderViewModel.kt
sample/benchmark/src/main/res/layout/fragment_logs_heavy_traffic_host.xml

1. Implemented LogsHeavyTraffic scenario for Android Benchmarking app that is described [here](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3981476482/Benchmarks+iOS#Logs-Heavy-Traffic-Scenario). demo: [link](https://drive.google.com/file/d/1VR9hNh4YV9VYYL_gRSLOfw9xdD0uqxat/view?usp=sharing)
2. created a synthetics test described [here](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3981476482/Benchmarks+iOS#Proposed-Test-Scenario.1). [Link](https://mobile-integration.datadoghq.com/synthetics/details/2jm-bt3-uri?tab=details&from_ts=1746441189544&to_ts=1746455589544&live=true). I checked that is works for my local build.
- [ ] Make sure you discussed the feature or bugfix with the …

RUM-9508: LogsHeavyTraffic scenario for android benchmarks

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Prepare release 2.15.2

---

sample/benchmark/src/main/java/com/datadog/benchmark/sample/DatadogFeaturesInitializer.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/BenchmarkActivityComponent.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/OpenTelemetryModule.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/ViewModelsModule.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/navigation/FragmentsNavigationManagerImpl.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/trace/TraceScenarioFragment.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/trace/TraceScenarioScreen.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/trace/TraceScenarioViewModel.kt

1. Implemented Traces scenario for Android Benchmarking app that is described [here](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3981476482/Benchmarks+iOS#Traces). demo: [link](https://drive.google.com/file/d/10oBCtQE4sKpqpadTPnQHfNt8FUfkpJng/view?usp=sharing)
2. created a synthetics test described [here](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3981476482/Benchmarks+iOS#Proposed-Test-Scenario.2). [Link](https://mobile-integration.datadoghq.com/synthetics/details/rza-v3y-xtx?from_ts=1746757706461&to_ts=1746772106461&live=true). I checked that is works for my local build.
3. One of the traces from the synthetic test [link](https://mobile-integration.datadoghq.com/apm/trace/1146575803547414911?graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=88058937838808 …

RUM-9509: Trace scenario for android benchmark app

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProviderTest.kt

It seems exceptions may be thrown (although **very** rarely) by the system during the Power or Battery intents processing, so this PR aims to catch and log them instead of crashing the host app.

Catch exceptions during the Power or Battery broadcast intents processing

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProviderTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
features/dd-sdk-android-trace/src/main/java/com/datadog/opentracing/PendingTrace.java
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/BaseTest.kt
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/FeatureScopeTest.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/DatadogFeaturesInitializer.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/MainActivityViewModel.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/config/SyntheticsScenario.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/BenchmarkActivityComponent.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/DatadogActivityModule.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/OpenTelemetryModule.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/di/activity/ViewModelsModule.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/navigation/FragmentsNavigationManagerImpl.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/rummanual/RumManualScenarioFragment.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/rummanual/RumManualScenarioScreen.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/rummanual/RumManualScenarioViewModel.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/trace/TraceScenarioFragment.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/trace/TraceScenarioScreen.kt
sample/benchmark/src/main/java/com/datadog/benchmark/sample/ui/trace/TraceScenarioViewModel.kt

This is a merge PR: `develop` branch into feature context synchronization branch.

Merge `develop` branch into feature context synchronization branch

---

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt

Add Jetpack Compose specific log in gesture listener if target not found

---

dd-sdk-android-core/api/apiSurface
dd-sdk-android-core/api/dd-sdk-android-core.api
dd-sdk-android-core/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/SdkCore.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/DatadogCore.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/NoOpInternalSdkCore.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/DatadogTest.kt

RUM-10240: Add public APIs for set account information

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/Preferences.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/account/AccountFragment.kt
sample/kotlin/src/main/res/layout/fragment_account.xml
sample/kotlin/src/main/res/menu/navigation.xml
sample/kotlin/src/main/res/navigation/nav_graph.xml
sample/kotlin/src/main/res/values/strings.xml

Add Account Info fragment for sample app
RUM-10274

RUM-10274: Add Account Info fragment for sample app

---

reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/BaseTest.kt
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/FeatureScopeTest.kt
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/InternalSdkCoreTest.kt
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/PendingToGrantedAsyncTest.kt
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/PendingToGrantedCustomPersistenceAsyncTest.kt
reliability/core-it/src/androidTest/kotlin/com/datadog/android/core/integration/tests/forge/factories/ConfigurationCoreForgeryFactory.kt

Speed up the `core-it` test suite and reduce the time spent in CI

RUM-9917 improve speed of running core-it suite

---

features/dd-sdk-android-session-replay-compose/src/main/kotlin/com/datadog/android/sessionreplay/compose/internal/utils/SemanticsUtils.kt

In Session Replay especially for Jetpack Compose, we are copying the original bitmap before compressing and transforming it into byte data on work thread in case that the original one is recycled. 
But copying [hardware bitmap](https://bumptech.github.io/glide/doc/hardwarebitmaps.html) can be very slow especially we are doing it on main thread. With some manual test we noticed that the average copy time of software bitmap is around 30\~60us, and for hardware bitmap it can be up to 10\~20ms. And it throws strict mode warning if client enables it in their app.
So in this PR we decide to skip hardware bitmap copying, passing the original instance until the byte data processing, if it is recycled during the time, then we skip it by reporting it to telemetry.
RUM-10346:
- [ ] Make sure you …

RUM-10346: Avoid copying hardware bitmap in Session Replay

---

.gitlab-ci.yml

Sorry about that, I wrote this comment in order to emulate change to retrigger CI.

Remove unnecessary comment

---

.github/chainguard/self.gitlab.read.sts.yaml

Fix octo-sts pattern

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

This PR prepares release 2.24.0.

Prepare release 2.24.0

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/config/CoreFeatureTestConfiguration.kt
detekt_custom.yml

This is a pull of contribution made by @Laimiux in https://github.com/DataDog/dd-sdk-android/pull/2824 into the repo directly from the fork to be able to run CI.
Check original PR for more details.

Move OkHttp client initialization to background thread

---

features/dd-sdk-android-rum/api/dd-sdk-android-rum.api
features/dd-sdk-android-rum/build.gradle.kts
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/startup/RumAppStartupDetectorImplTest.kt

Addressing [this](https://github.com/DataDog/dd-sdk-android/pull/2861#discussion_r2351405579) comment.

RUM-11555: Remove BuildConfig from public api of dd-sdk-android-rum

---

features/dd-sdk-android-profiling/api/apiSurface
features/dd-sdk-android-profiling/api/dd-sdk-android-profiling.api
features/dd-sdk-android-profiling/build.gradle.kts
features/dd-sdk-android-profiling/generate_profiling_models.gradle.kts
features/dd-sdk-android-profiling/src/main/java/com/datadog/android/profiling/internal/PerfettoProfiler.kt
features/dd-sdk-android-profiling/src/main/java/com/datadog/android/profiling/internal/PerfettoResult.kt
features/dd-sdk-android-profiling/src/main/json/profiling/profiling-schema.json
features/dd-sdk-android-profiling/src/test/kotlin/com/datadog/android/profiling/PerfettoProfilerTest.kt
features/dd-sdk-android-profiling/transitiveDependencies

* Add profiling event schema to generate `ProfilingEvent` 
* Add internal `PerefettoResult` to carry profiling result.

RUM-11948: Create Profiling Event schema
