dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/CallbackNetworkInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/NetworkInfo.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/NetworkInfoAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/forge/NetworkInfoForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/net/CallbackNetworkInfoProviderTest.kt

Include network speed and signal strength info into the `network.client` attributes
Get more information in logs
The new attributes are named: 
- `network.client.uplink_kbps`: the peak upload speed (in kbps)
- `network.client.downlink_kbps`: the peak download speed (in kbps)
- `network.client.signal_strength`: the strength of the signal (in dBm, only available on Android 10 or more, and apparently only on Wifi networks)

RUMM-150 network speed

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt

When calling `Datadog.initialize` more than once, all calls after the first one are ignored, and a warning message will be printed to the Logcat to warn the dev.
Resolves #86

RUMM-170 Allow Datadog.initialize() to be called more than once

---

.gitlab-ci.yml

Adds a slack step during CI builds to notify slack when the publication on Bintray succeeded or failed

RUMM-167 Add slack notification on publish task

---

build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android/build.gradle.kts
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/GzipRequestInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/GzipRequestInterceptorTest.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/log/LogApiBenchmark.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/utils/AbstractProfilingRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integrationtests/utils/MockServerRule.kt

Downgrade the OkHttp dependency from 4.* to 3.12
For customers writing apps with Kotlin+OkHttp3, our dependency breaks their Kotlin sources.
Mostly OkHttp4 is OkHttp3 with Kotlin sugar syntax.
Using OkHttp3 in our library is binary compatible with customers writing in either Kotlin or Java and using either OkHttp3 or OkHttp4.
We do miss on several fixes from later versions, but none that actually impact our limited use of OkHttp.

RUMM-185 downgrade ok http

---

dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/Log.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/LogFileStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/LogForgeryFactory.kt

Let Crash logs use the `EMERGENCY` status
Because users can log `ERROR` message themselves, we need a way for crash to appear out of the list of non fatal error logs.

RUMM-196 Let Crash logs use the EMERGENCY status

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/constraints/DatadogLogConstraints.kt

Fixes few typos I spotted while working on `RUMM-134`.
💡 I also noticed that `date` is not a reserved attribute in Android SDK. Is this correct @mariusc83 @xgouchet ? Means, users can now overwrite it.

RUMM-134 Fix typos and remove unused constant

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadWorker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt

Allow users to create Logger even if the SDK is not initialized. An error message will be logged if such a case occur. 
Avoid needless crashes on users' mistakes.

RUMM-165 Prevent crashing the app when the SDK is not Initialized

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/DatadogTimeProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/TimeProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracingFileStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/time/DatadogTimeProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/TracingFileStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/extension/BigIntegetExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/extension/JsonObjectExt.kt

Correct the timestamp used in Spans for local device time offset. 
Some device which don't use NTP to sync the device Time and Date with the network can report bogus timestamps, That will result in weird or inconsistent data. This is an attempt to prevent that.

RUMM-183 Correct traces timestamp

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt

We should only add the top level metrics for the root span in the trace. This will fix the way the traces are displayed on the dashboard by showing only the top level span that can be expanded on user action.

RUMM-208 Add top level metrics only for root span

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/Tracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracerTest.kt

By default the **dd-trace-ot** SDK delivers the closed spans to the writer every time a trace is complete (the root span was closed) or whenever the threshold for partial flushing is reached which is by default 100 closed spans. To avoid too much memory consumption we lowered that default threshold to 5 and made that option configurable from the **Tracer.Builder**.

RUMM-207 Tracer - Add a configurable partial flush threshold

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/net/LogsOkHttpUploaderTest.kt
sample/kotlin/build.gradle.kts

When I first tried to use the Tracing intake there were some weird errors reported by the **logs-processing** service related with the user agent parsing. To make sure these are not the cause for which our traces were dropped I remove the user agent from header for this endpoint. Now when everything is stable I added it back and everything seems to work as expected so probably the assumption I made that the user agent format was not supported was wrong.

RUMM-209 Add user agent into traces intake request

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/Writer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/DeferredWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/NoOpPersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/data/TraceWriter.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/DeferredWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/data/TraceWriterTest.kt

In this PR we are providing the support for handling a list of model to our current FileWriter. This feature was needed in order to optimize the code around the TraceWriter which was scheduling a Runnable in the DefferedWriter for each model (Span). Due to the newly added feature we are able to consume all the list in one Runnable.

RUMM-184 Give the Writer the capability to handle a list of models

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt

Not knowing exactly the *dd-trace-ot* Sampling mechanism under the hood we were adding the **_sampling_priority_v1:1** key - value property in all the spans metrics. Right now we are correcting this by following the *dd-trace-ot* logic which adds this only to the "parent" span as default. Furthermore once the sampling mechanism on their end will be validated we don't have to do anything on our end as this property is correctly managed on their end and we will only serialize it on our end.

RUMM-214 Correctly handle the trace sampling

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/Tracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/utils/TracerExtensionsTest.kt

Inject a random TraceId on top level spans
Android uses a zygote process, meaning that new instance of the same app will always have the same trace id, unless the device gets rebooted.

RUMM-233 Inject a random TraceId on top level spans

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt

The traces couldn't be sent on prod (and on staging it didn't work anymore) because the intake expects a `\n` separated list of json object sent with `Content-Type: text/plain;charset=UTF-8`.
Also the `type` field in a span is used to define the icon in the dashboard and can take the following values : `web`, `db`, `cache`, `custom`.

RUMM-255 traces content type

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/BenchmarkJsonFileVisitor.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/BenchmarkStrategy.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/ReviewBenchmarkExtension.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/ReviewBenchmarkResultsTask.kt
instrumented/benchmark/build.gradle.kts
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/rum/RumGesturesTrackerBenchmark.kt

This PR adds an extension to the current Benchmark Plugin to be able to add relative thresholds as a measurement criteria.
We define the relative threshold as the threshold for the execution time difference between 2 defined tests.

RUMM-240 Benchmark plugin - provide relative thresholds

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt
dd-sdk-android/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

For now the TraceInterceptor was doing nothing if there was no Global Tracer registered. With this PR we introduced the **localTracer** fallback in case there's was no Tracer registered yet by the user.

RUMM-258 TraceInterceptor - fallback to local tracer if no global

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileReader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/NetworkTimeInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/BroadcastReceiverNetworkInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/RuntimeUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/constraints/DatadogLogConstraints.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt
dd-sdk-android/src/test/java/com/datadog/android/log/LoggerBuilderJavaTest.java
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/FileReaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/ImmediateFileWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/RuntimeUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/domain/FilePersistenceStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/constraints/DatadogLogConstraintsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/DatadogExt.kt

This PR addresses the issue #133 and adds a new capability to our LogcatHandler to be able to resolve and use as a TAG  the caller class name whenever using either the *sdkLogger*, *devLogger* or a simple logger having the *logcatOptionEnabled*. 
Was requested by some of our users and also brings a lot of value in our logs.
Please note that we are using 2 STACK_INDEX values to detect the right stack trace element due to the different place in the stack hierarchy if we are using the *sdkLogger* or the *devLogger* (which has one extra layer).

RUMM-235 LogcatHandler - add caller classname as tag when in debug

---

.gitlab-ci.yml
build.gradle.kts
dd-sdk-android-timber/src/test/kotlin/com/datadog/android/timber/DatadogTreeTest.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/ReflectUtils.kt

Tries to prevent a crash happening on Runtime shutdown
Mostly motivated by issue #154: 
When the ART/JVM shuts down (either from a previous crash or when the app exits), new Thread are blocked from being spawned and will throw a `java.lang.InternalError`.
We add a shutdown hook to stop the Datadog SDK whenever the Runtime shuts down.
I wasn't able to reproduce this yet, but this fix should handle the issue.
@alparp27, if you can could you please build a local version of the Datadog library and see if this does indeed fix the issue?

Prevent crash on Runtime shutdown

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/TrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/NoOpWindowCallback.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/ActivityTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/TrackingStrategiesTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/TrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesListenerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTrackerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/rum/RumGesturesTrackerBenchmark.kt
sample/java/src/main/java/com/datadog/android/sample/MainActivity.java
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java
sample/kotlin-timber/build.gradle.kts
sample/kotlin-timber/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

This PR adds the Automatic ActivityScreenTracker as an optional feature to the SDK. By enabling this feature we will be able to detect activity changes and start/stop RumView events whenever on the Activity onResume/onPause lifecycle events.

RUMM-219 Add activity screen tracker

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileReader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/FileReaderTest.kt

Prevent SDK from crashing when an OOM Error occurs. (#164)
This doesn't fix the root cause of the OOM of course, but will avoid crashing on our side.

RUMM-278 Prevent OutOfMemory crash

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumActivityTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumMockServerActivityTestRule.kt
instrumented/integration/src/main/AndroidManifest.xml
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumActivityTrackingPlaygroundActivity.kt
instrumented/integration/src/main/res/values/strings.xml

Adds the end - to - end tests for the Rum  Activity based view tracking strategy. It will assert the dispatched rum View events between the onPause and onResume Activity lifecycle events.

RUMM-273 Add End - to - End tests for ActivityViewTrackingStrategy

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ListenableFutureFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/WorkerParametersForgeryFactory.kt
detekt.yml
gradle.properties

Please not that in this PR I added also a fix for the IllegalStateException that was thrown by the `Datadog#stop` method when being called without initialising the SDK upfront. This was not a problem before as this method was only meant for tests but recently we added a fix and we are calling this method from the **Runtime ShutdownHook Thread** which can introduce unwanted Crashes in our clients applications.

RUMM-270 Build tools and SDK dependencies update

---

dd-sdk-androidx-fragment/apiSurface
instrumented/integration/build.gradle.kts
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/EndToEndRumFragmentTrackingTests.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/RumMockServerActivityTestRule.kt
instrumented/integration/src/main/AndroidManifest.xml
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/FragmentA.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/FragmentB.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/FragmentC.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumActivityTrackingPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/RumFragmentTrackingPlaygroundActivity.kt
instrumented/integration/src/main/res/layout/fragment_b_layout.xml
instrumented/integration/src/main/res/layout/fragment_c_layout.xml
instrumented/integration/src/main/res/layout/fragment_layout.xml
instrumented/integration/src/main/res/layout/fragment_tracking_layout.xml
instrumented/integration/src/main/res/values/strings.xml

Adds the end - to - end tests for FragmentViewTrackingStrategy. We are using a Fragments based ViewPager which we instrument (using swipe actions) and we assert the view events after each page change. 
We are not covering in this PR the corner case where the ViewPager is using same Fragment for displaying each page.

RUMM-274 Add end - to - end tests for FragmentViewTrackingStrategy

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/NoOpDataUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/net/LogsOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderTest.kt

In this PR we add the UTC timestamp in milliseconds as a query parameter to each batch intake request:
*http://url?batch_time=System.currentTimeInMillis()*
This new query parameter will be needed to normalise the events timestamps on server side by computing the offset between the device UTC time and the server UTC time.

RUMM-256 Add the UTC timestamp as query parameter

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/AsyncWriterFilePersistenceStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/domain/FilePersistenceStrategyTest.kt

In this PR we make sure we're only creating and sharing one single Writer instance per feature inside fir the persistence layer.

RUMM-304 Share one single writer per feature

---

buildSrc/src/main/kotlin/com/datadog/gradle/utils/Version.kt
buildSrc/src/test/kotlin/com/datadog/gradle/utils/VersionTest.kt

Avoids typo when releasing an `aphla` or `beat` version.

Update the versioning model

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/MapUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/file/LogFileStrategyTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/EndToEndLogTest.kt

In this PR we are fixing the Logger **remove/add** methods for tags or attributes by making them Thread safe. To achieve this we are switching from regular HashMap and HashSet implementations to a ConcurrentHashMap and a CopyOnWriteArraySet implementations.
Please note that the problem was also present in Android as I was able to reproduce the **ConcurrentModificationException** in my tests.

RUMM-308 Make Logger methods Thread safe

---

instrumented/benchmark/build.gradle.kts
instrumented/benchmark/src/androidTest/kotlin/com/datadog/android/sdk/benchmark/core/CoreInitBenchmark.kt

Write a simple benchmark test to ensure the initialize method doesn't slow an application's startup time
**Note** benchmark are not run on each PR, but it's still important to have this one in the lot.

RUMM-315 Add a benchmark on the SDK initialize

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
docs/trace_collection.md

In this PR we are adding 2 static helper methods for the AndroidTracer to be able to attach a Throwable or an error message to a specific Span.

RUMM-331 Tracer - add helper methods for logging an error

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorInternalMethodsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt

Provides 2 extra internal methods inside the Datadog RumMonitor implementation `startUserAction` and `stopUserAction(actionName, attributes)` needed by our Gestures instrumentation layer.

RUMM-360 RumMonitor - add start/update user action methods

---

dd-sdk-android-navigation/src/main/kotlin/com/datadog/android/androidx/navigation/NavigationViewTrackingStrategy.kt
dd-sdk-android-navigation/src/test/kotlin/com/datadog/android/androidx/navigation/NavigationViewTrackingStrategyTest.kt

In some applications the way the Navigation pattern is implemented creates problems with the way our NavigationViewTrackingStrategy is starting/stoping Views. More exactly the `currentDestination` attribute in the NavigationController component returns the wrong destination (usually is the destination before previous one) and therefore it will no be able to close the right view.

RUMM-388 NavigationViewTrackingStrategy - fix start/stop view behaviour

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileReader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/file/FileReaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/domain/FilePersistenceStrategyTest.kt

This PR fixes the concurrency issue we were experiencing in the FileReader. In short this class was using 2 sets to mark files as *in progress* or *sent* and only one of these 2 collections was synchronised. Furthermore there was a multithreaded access to this file (from the WorkManager and from the default DataUploadScheduler) and the application was seldom crashing with a ConcurrentModificationAccess.
Opened issue #234  on our Github repository 

RUMM-416 FileReader - fix the concurrency issue

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumConfigAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/FeatureConfigForgeryFactory.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/EndToEndLogTest.kt

RUMM-407 Use app package name as default service name value

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/FilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/PersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracesFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt

Some users want/need to be able to clear any unsent data we gather. This PR implements this feature as a single method that will wipe any remaining file from the application folders.

RUMM-639 clear data

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/domain/TimeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

Resets the Application Start info when `resetSession` is called.
`resetSession` is called in our Ci environment to simulate multiple sessions in one single instrumented test run. To enhance the demo data, we want to reset the "application startup time" every time we simulate a new session.

RUMM-641 Reset application startup time on resetSession

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/ViewTreeChangeTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Ensure that continuous RUM Actions behave the same way as Actions
We had a bug, where a continuous action (e.g.: scroll) would be sent as soon as it ends, without waiting for side effects to happen.

RUMM-662 Continuous RUM Actions

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt

In this PR we update some logs following the latest changes in the SDK initialisation and we provide an additional Log for the case where the `setRumEnabled` option is used without correctly initialising the `DatadogConfig.Builder` instance.

RUMM-676 Log error messages for inconistent states of the SDK

---

dd-sdk-android-ndk/src/main/cpp/CMakeLists.txt
dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.cpp
dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.cpp
dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.h
dd-sdk-android-ndk/src/test/cpp/test_generate_backtrace.cpp
dd-sdk-android-ndk/src/test/cpp/test_utils.h

The goal was this task was to research over the way we are currently constructing the backtrace in our NDK crash reporting code and if our current approach is good enough or we should use `libunwind` or `corkscrew` as seen in other SDKs. 
The resolution of this task is that what we have it is simple enough and covers all the processors as with other approaches we would have to use different APIs for each processor type bringing bigger complexity in our code.
In theory I was able to keep what we had so far and add an improvement where I enrich the crash stacktrace with more information and format it in a more readable structure following iOS approach. Right now we will have also the `shared object` file from which the executed line address was coming and also the memory offset for the …

RUMM-684 Cleanup the NDK code

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/ResourceTiming.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/resource/RumResourceInputStream.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/resource/RumResourceInputStreamTest.kt
sample/README.md
sample/kotlin/src/main/res/layout/fragment_traces.xml

Fix the RUM events timing.
With each RUM raw event (start X, stop Y, …), we keep an `eventTime` value to know when the event occurred in the client's code. At some point, those raw events could be updated to include additional attributes, and since they are all immutable objects, we used the `copy()` method.
The main issue was that the `eventTime` attribute was part of the parent `sealed` class (`RumRawEvent`), and was not copied but recreated at the time of the copy, meaning that all our events' times were skewed by a few milliseconds, making each information slightly off.
This PR fixes that by making the parent `eventTime` attribute abstract, forcing implementations to have them (meaning that they are taken into account by the kotlin compiler, and indeed kept during a `copy()` call).

RUMM-692 Fix RUM events timing

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadScheduler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadSchedulerTest.kt

Increase the delay between batch uploads when an error is detected.
When an app using the SDK is ran behind some firewalls/proxy, the data intake request can fail. This means that the workers are going to retry up to every 2 seconds to send the same batch, leading in more CPU consumption. 

:bug: (RUMM-708): Prevent frequent retry on network layer error

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/gitclone/GitCloneDependenciesExtension.kt
dd-sdk-android/apiSurface
dd-sdk-android/clone_rum_schema.gradle.kts
dd-sdk-android/src/main/json/_common-schema.json
dd-sdk-android/src/main/json/action-schema.json
dd-sdk-android/src/main/json/resource-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

This is the first step into letting the backend generate spans for each RUM Resource: 
- add a UUID `resource.id` attribute on RUM Resource
- include the `_dd.trace_id` and `_dd.span_id` attributes to hold the identifiers of the span related to the request.
Step 2 will be performed once the backend can create the spans on our behalf

RUMM-650 Implement link between RUM Resources and APM spans

---

.gitlab-ci.yml
.idea/codeStyles/Project.xml
LICENSE-3rdparty.csv
build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-coil/src/main/kotlin/com/datadog/android/coil/DatadogCoilRequestListener.kt
dd-sdk-android-coil/src/test/kotlin/com/datadog/android/coil/DatadogCoilRequestListenerTest.kt
dd-sdk-android-coil/src/test/kotlin/com/datadog/android/coil/utils/Configurator.kt
dd-sdk-android-coil/src/test/kotlin/com/datadog/android/coil/utils/ThrowableForgeryFactory.kt
dd-sdk-android-fresco/src/main/kotlin/com/datadog/android/fresco/DatadogFrescoCacheListener.kt
dd-sdk-android-rx/.gitignore
dd-sdk-android-rx/README.md
dd-sdk-android-rx/apiSurface
dd-sdk-android-rx/build.gradle.kts
dd-sdk-android-rx/src/main/AndroidManifest.xml
dd-sdk-android-rx/src/main/kotlin/com/datadog/android/rx/DatadogRumErrorConsumer.kt
dd-sdk-android-rx/src/main/kotlin/com/datadog/android/rx/DatadogRxExt.kt
dd-sdk-android-rx/src/test/kotlin/com/datadog/android/rx/DatadogRumErrorConsumerTest.kt
dd-sdk-android-rx/src/test/kotlin/com/datadog/android/rx/DatadogRxExtTest.kt
dd-sdk-android-rx/src/test/kotlin/com/datadog/android/rx/utils/Configurator.kt
dd-sdk-android-rx/src/test/kotlin/com/datadog/android/rx/utils/ThrowableForgeryFactory.kt
dd-sdk-android-rx/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/DataRepository.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/RemoteDataSource.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/datalist/DataListFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/datalist/DataListViewModel.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/logs/LogsFragment.kt
settings.gradle.kts

This PR provides helper methods/consumers for RxJava streams to intercept and send the potential Exception as RUM error events to Datadog.
For **Kotlin** codebase we are also providing extensions methods to go along with the proposed `DatadogErrorConsumer`.

RUMM-475 Provide integration with RxJava 

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/LogAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogGeneratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt

The scope of this PR is to add the application version information as a tag into the **Crash** logs by complying with the default log creation rules. 
Getting to the bottom of the issue I realised that we had 2 sources of true regarding the rules we are using for a Log creation: 
1. From the DatadogExceptionHandler
2. From the DatadogLogHandler
To fix this problem and to avoid similar problems in the future I introduced the `LogGenerator` class which will handle the `Log` object creation through all the SDK and will contain all the required rules. 
- [ ] Make sure each commit and the PR mention the Issue …

RUMM-736 Add app version as tag into the Crash logs

---

dd-sdk-android-ktx/README.md
dd-sdk-android-ktx/apiSurface
dd-sdk-android-ktx/src/main/kotlin/com/datadog/android/ktx/sqlite/SqliteDatabaseExt.kt
dd-sdk-android-ktx/src/test/kotlin/com/datadog/android/ktx/sqlite/SqliteDatabaseExtTest.kt
sample/kotlin/src/sqlite/kotlin/com/datadog/android/sample/data/contentprovider/DatadogContentProvider.kt

The scope of this PR was to allow update the recently introduced SQLiteDatabase extension -> `transactionTraced` in order to allow the Span decoration from inside the provided lambda:
```
sqliteDabase.transactionTraced("<SPAN_NAME>", isExclusive) { database -> 
database.insert("<TABLE_NAME>", null, contentValues)
setTag("<TAG_KEY>", "<TAG_VALUE>")
}
```

RUMM-754 Allow Span decoration from the SQLiteDatabase#transactionTraced

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/AbstractGesturesListenerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTrackerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/res/values-v21/themes.xml
sample/kotlin/src/main/res/values/colors.xml
sample/kotlin/src/main/res/values/themes.xml

Fix a but preventing user to call the Activity's `setTheme()` method.
When the gesture tracking is enabled, we are calling the window's `getDecorView()` early, which forces the generation of the decorView state. This state is (partly) immutable, meaning that when a customer calls `setTheme()` from the Activity's `onCreate()` method, some style attributes can't be changed, meaning that the app's (or OS's) default style is applied.

RUMM-761  setTheme on activity

---

docs/log_collection.md

Adding reference to remove confusion around the APPLICATION_ID for getting logs set up with Android (whether it is the same as the APPLICATION_ID used to set up RUM for Android or it is the applicationId property defined in an Android application)
ticket: https://datadog.zendesk.com/agent/tickets/402817

Add reference to Application ID definition through RUM

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProviderTest.kt

Ensure we retrieve the current network status on start
One of our customer experiences a weird behavior on some (Samsung) devices : the inital value is never received, and only when turning the airplane mode on and off does the callback get triggered.

RUMM-870 Make sure we get the current network state on start

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt

Simple dependency version bump for `kronos-android`. Fixes #408 
alpha10 version removes `com.android.support` dependencies, which helps library consumers migrate off of the AndroidX Jetifier.
N/A

Update kronos-android to v0.0.1-alpha10

---

dd-sdk-android/src/test/kotlin/com/datadog/android/rum/resource/RumResourceInputStreamTest.kt

Use JUnit5's `Assumptions` class instead of JUnit4's
Because the java-agent expect all our tests to be running with JUnit5, JUnit4 exceptions are not recognized.

RUMM-884 Use JUnit5 assumptions

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/constraints/DataConstraints.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraints.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraintsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/user/UserFragment.kt
sample/kotlin/src/main/res/layout/fragment_user.xml

In this *PR* we are aligning the logic used for sanitising the keys for all the provided custom attributes (custom timings, custom user extra information, custom attributes) inside our events Serialisers. We are following the previously used rules for sanitising the Log custom attributes and we are applying these for each type of custom attribute.

RUMM-906 Sanitise the custom attributes keys for all the events

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/JsonDefinition.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/JsonSchemaReader.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/TypeProperty.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/JsonSchemaReaderTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelValidationTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGeneratorTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/TestDefinitions.kt
buildSrc/src/test/kotlin/com/example/forgery/ForgeryConfiguration.kt
buildSrc/src/test/kotlin/com/example/forgery/MessageForgeryFactory.kt
buildSrc/src/test/kotlin/com/example/model/Article.kt
buildSrc/src/test/kotlin/com/example/model/Book.kt
buildSrc/src/test/kotlin/com/example/model/Conflict.kt
buildSrc/src/test/kotlin/com/example/model/Customer.kt
buildSrc/src/test/kotlin/com/example/model/DateTime.kt
buildSrc/src/test/kotlin/com/example/model/Delivery.kt
buildSrc/src/test/kotlin/com/example/model/Demo.kt
buildSrc/src/test/kotlin/com/example/model/Foo.kt
buildSrc/src/test/kotlin/com/example/model/Message.kt
buildSrc/src/test/kotlin/com/example/model/Opus.kt
buildSrc/src/test/kotlin/com/example/model/Person.kt
buildSrc/src/test/kotlin/com/example/model/Style.kt
buildSrc/src/test/kotlin/com/example/model/User.kt
buildSrc/src/test/kotlin/com/example/model/UserMerged.kt
buildSrc/src/test/kotlin/com/example/model/Video.kt
buildSrc/src/test/resources/input/enum.json
buildSrc/src/test/resources/input/read_only.json

Add support to the JSON Schema `readOnly` property. When generated, non readOnly properties will be `var` properties, and readOnly will become `val`. This ensures that when the object is passed to the customer for data scrubbing, they can only modify a subset of properties.

RUMM-912 Json schema read only properties

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/info/CallbackNetworkInfoProviderTest.kt

Calling `registerNetworkCallback` can trigger a RuntimeException with message "Too many NetworkRequests filed" in some cases. This is a documented issue in the `ConnectivityManager` class that we need to address.

RUMM-918 Prevent crash callback network

---

.gitignore

Fixes the .gitignore configuration to exclude only the files in the `config` folder at the root level of the project. 

Fix .gitignore configuration for config folder

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/ApiSurfacePlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/JsonSchemaReader.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/TypeDefinition.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/TestDefinitions.kt
buildSrc/src/test/kotlin/com/example/forgery/ConflictForgeryFactory.kt
buildSrc/src/test/kotlin/com/example/model/Conflict.kt
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ActionEventForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ErrorEventForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ResourceEventForgeryFactory.kt

When generated RUM Event types from Json schema, ensure that types with conflicting names use a user friendly name.
Because those types are public, it was a bit weird to have `Type1` or `Type2` classes. Now those classes will be named more accurately (e.g.: `SessionType` or `ResourceType`).

Make generated names user friendly

---

dd-android-gradle-plugin/src/main/kotlin/com/datadog/gradle/plugin/DdAndroidGradlePlugin.kt

Prevent coupling between assemble and publishMapping tasks. 
Once uploaded, mapping files can't be overriden. Uncoupling those tasks ensure we don't block a release by mistake

RUMM-909 Prevent coupling between assemble and publishMapping tasks

---

dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.cpp
dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.h
dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.cpp
dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c
dd-sdk-android-ndk/src/main/kotlin/com/datadog/android/ndk/NdkCrashReportsPlugin.kt
dd-sdk-android-ndk/src/test/cpp/integration-tests.cpp
dd-sdk-android-ndk/src/test/cpp/test-generate-backtrace.cpp
dd-sdk-android-ndk/src/test/kotlin/NdkCrashReportsPluginTest.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/Deserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/data/file/RumFileWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumFileStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/NdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/NdkCrashLog.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/NdkCrashLogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/NdkCrashLogForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventForgeryFactory.kt

In this *PR* I am concluding the NDK crash reporting feature by adding the last missing piece: `DatadogNdkCrashHandler`
with the following responsibilities:
- check when the SDK is initialized if there is any crash report from previous session in the NDK crash reports folder.
- if a crash report is found the handler will send a related Crash Log based on the information found in the crash report
- if along with the crash report there is also a `last_view_event` stored in the NDK crash reports folder the handler will also increment the `error.count` attribute and update this `ViewEvent`. A RUM ErrorEvent will also be sent for this ViewEvent.
- to avoid data duplication the `DatadogNdkCrashHandler` will only be running in the Application main process.
- to avoid the duplication of the RUM …

RUMM-969 Increment RUM ViewEvent error count and send ErrorEvent when NDK crash detected

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/error-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/data/TraceWriter.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/data/TraceWriterTest.kt

Attaches the `error.type` attribute for the RUM ErrorEvent when available. The attribute value resolves from the `Throwable` by using the canonical name of the `Throwable` type.

RUMM-962 Send the 'error.type' attribute in the RUM ErrorEvent

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNotSendingSpanTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt

We want to allow customer to set known first party locally per interceptor

RUMM-953 Un-deprecate local known hosts

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt

This PR fixes wrong tag in the logcat output for Timber integration, when wrong call stack element was picked (closes #483)
Existing issue #483
This is not a universal solution and will fix only Timber integration case. Need to come up with better call site matching later.

RUMM-1048: Fix wrong logcat tag for Timber integration

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/JacocoConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/PublishingConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/CheckApiSurfaceTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/GenerateApiSurfaceTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/BenchmarkJsonFileVisitor.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/benchmark/BenchmarkStrategy.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/checklicenses/CheckThirdPartyLicensesTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/checklicenses/SPDXLicenceConverter.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/checklicenses/ThirdPartyLicensesPlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/gitclone/GitCloneDependenciesTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/GenerateJsonSchemaTask.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/JsonSchemaReader.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoDeserializerGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoExtensions.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoSerializerGenerator.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelValidationTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelWithAdditionalAttributesTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/TestDefinitions.kt
buildSrc/src/test/kotlin/com/example/forgery/CompanyForgeryFactory.kt
buildSrc/src/test/kotlin/com/example/forgery/ForgeryConfiguration.kt
buildSrc/src/test/kotlin/com/example/model/Company.kt
buildSrc/src/test/kotlin/com/example/model/MiscUtils.kt
buildSrc/src/test/resources/input/additional_props_any.json
dd-sdk-android/build.gradle.kts

This PR adds a new capability to the PokoGenerator to be able to use `Map<String,Any?>` types when declaring the `additionalAttributes` into the json schemas. 
We needed this new capability to be able to generate internal model like the `UserInfo` from the `PokoGenerator` and to rely on the generated methods for deserializing/serializing the model instances.
Please note that because `Any` is not a valid json schema type we could not validate the `TypeDefinition` (`Company`) generated from the `additonal_props_any.json` schema but another test class was provided were we test the serialization/deserialization methods. …

PokoGenerator - support Any type for additionalProperties values 

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

Additional help to investigate #490 
Issue #490
N/A

RUMM-1061: Add a warning when RUM action is dropped while another action is still active for the same view

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/event/ViewEventMapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt
sample/java/src/main/java/com/datadog/android/sample/SampleApplication.java

In this PR we introduce the `ViewEventMapper` interface and will enforce the argument of the Public API method which provides the mapper for the View events to extend from this new interface. By doing this we will prevent the View events from being discarded from the mapper.

RUMM-1079 EventMapper - prevent discarding View events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/constraints/DataConstraints.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraints.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraintsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializerTest.kt

Follow up on changes described [here](https://github.com/DataDog/rum-events-format/pull/28/files): `ViewEvent.CustomTimings` attributes allows limited set of characters. This change does the necessary sanitization (unsupported characters are replaced with `_`) and logs the warning when key is changed.
Changed introduced in https://github.com/DataDog/rum-events-format/pull/28/files
N/A

RUMM-1060: Sanitize `custom_timings` attribute keys

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/data/file/RumFileWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/EventType.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/data/file/RumFileWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/LongTaskEventForgeryFactory.kt
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt
sample/kotlin/src/main/res/layout/activity_nav.xml

Ensure that the count of Resources, Actions, Errors and Long Tasks is valid when data scrubbing is used. 
When user discard events, the previous implementation could create views with invalid `view.<type>.count` values. This could lead to invalid dashboards, and filtering would bring a lot of false positives.

RUMM-1080 validate event count

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/FirstPartyHostDetector.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNotSendingSpanTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt

Ensure the local first party hosts provided in the OkHttp Interceptors are actually used. 
Fixes  #513
We also removed the `warnDeprecated` calls that existed and weren't not removed in the un-deprecation of the related constructors

RUMM-1151 Use the Local first-party host detector

---

dd-sdk-android/build.gradle.kts
dd-sdk-android/consumer-rules.pro

This change add proguard rule to keep code attributes needed for the Error Tracking feature, namely line number and source file name. This is achieved by adding special file with consumer configuration which will be used nor for the SDK build, but will be shipped with AAR and used in the application build (merged proguard configs).
Proguard docs on the possible attributes can be found here: https://www.guardsquare.com/en/products/proguard/manual/usage/attributes
Android docs on the consumer proguard rules: https://developer.android.com/studio/projects/android-library#Considerations
The feature itself is available at least since `AGP 3.0` (mentioned here https://google.github.io/android-gradle-dsl/3.0/com.android.build.gradle.internal.dsl.DefaultConfig.html#com.android.build.gradle.internal …

RUMM-1068: Keep line and filename information in the user builds to make Error Tracking feature work reliably

---

tools/noopfactory/src/main/kotlin/com/datadog/tools/noopfactory/NoOpFactoryAnnotationProcessor.kt

Very tiny change which adds a line break to the messages, otherwise all of them are in a single line like that:
```
Note: Generated NoOpTracedRequestListenerNote: Generated NoOpNetworkInfoProviderNote: Generated NoOpDataUploaderNote: Generated NoOpConsentProviderNote: Generated NoOpTimeProviderNote: Generated NoOpSystemInfoProviderNote: Generated NoOpWriterNote: Generated NoOpReaderNote: Generated NoOpUploadSchedulerNote: Generated NoOpPersistenceStrategyNote: Generated NoOpDataProcessorNote: Generated NoOpBatchedDataMigratorNote: Generated NoOpAdvancedRumMonitorNote: Generated NoOpNdkCrashHandlerNote: Generated NoOpGesturesTrackerNote: Generated NoOpFragmentLifecycleCallbacksNote: Generated NoOpUserActionTrackingStrategyNote: Generated NoOpRumScopeNote: Generated NoOpRumMonitorNote: …
```

Add newline after no-op classes generation messages

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumResourceAttributesProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/RumWebViewClient.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutRumTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutTracesTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNotSendingSpanTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ExpectedEvents.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ResourceTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTestUtils.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/utils/ForgeExtensions.kt
tools/noopfactory/src/main/kotlin/com/datadog/tools/noopfactory/NoOpFactoryAnnotationProcessor.kt
tools/noopfactory/src/test/resources/gen/NoOpGenericInterface.kt
tools/noopfactory/src/test/resources/gen/NoOpSimpleInterface.kt
tools/noopfactory/src/test/resources/src/GenericInterface.kt
tools/noopfactory/src/test/resources/src/SimpleInterface.kt

This change gives user a possibility to attach custom attributes to automatically collected RUM Resource events: either in the `OkHttp` flow, or in the `WebView` flow.
Attributes are collected after the resource call is completed (with either `success` or `error` outcome)
Resources are also automatically collected [here](https://github.com/DataDog/dd-sdk-android/blob/master/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/resource/RumResourceInputStream.kt), but this part is not covered by this PR, because this class is low level and not sure if it is needed. Can be addressed in another PR if needed though.

RUMM-1153: Possibility to attach custom attributes to automatically collected RUM Resource events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
instrumented/integration/build.gradle.kts
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/CPUProfileForLogs.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/MemoryProfileForLogs.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ActivityTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/AbstractProfilingRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/GesturesTrackingActivityTestRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/utils/ExtraIntentExtensions.kt
instrumented/integration/src/main/AndroidManifest.xml
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/ActivityProfiling.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/ActivityTrackingPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/FragmentTrackingPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/GesturesTrackingPlaygroundActivity.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/ObjectTest.kt

This PR addresses following things:
1. We had a bug in the `RumViewScope` that could not close the View when the `ApplicationStart` event was sent during the View lifetime.
2. Due to the new configuration defaults we were sending lots of `LongTask` events during our integration test cases and those were all failing. I had to add a very long threshold for the `LongTaskStrategy` to avoid that and I will open a new Jira task where we specifically add an Espresso test for it.
3. The `integration tests` project was using the `Proguard` based deprecated compiler and not R8.
- [ ] Make sure each commit and the PR …

RUMM-1174 Fix the integration tests

---

dd-sdk-android-sqldelight/src/main/kotlin/com/datadog/android/sqldelight/DatadogSqliteCallback.kt
dd-sdk-android-sqldelight/src/test/kotlin/com/datadog/android/sqldelight/DatadogSqliteCallbackTest.kt
dd-sdk-android/src/main/java/com/datadog/trace/api/Config.java
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraints.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/NetworkInfoDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/user/UserInfoDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sqlite/DatadogDatabaseErrorHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogConfigBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sqlite/DatadogDatabaseErrorHandlerTest.kt

The way we were using the `String.format(...` function was not consistent in our code (sometimes we specified the Locale and sometimes we didn't). 
Not specifying the `Locale` and using the default one is recommended when presenting information to the user but these messages need to be adapted for the specific country. Not specifying the `Locale` is not recommended for machine readable output (data sent to our endpoints) because it can produce weird interpretations and sometimes it can't even interpret an argument: floating-point numbers some locales will use ',' as the decimal point and '.' for digit grouping.
Because the only part were we are using the `String.format(...` function to send output to the UI/User is in our logs I do not see a reason why we should not apply this rule …

RUMM-1168 Make sure we specify the Locale for 'String.format'

---

dd-sdk-android-glide/README.md
dd-sdk-android-glide/src/main/kotlin/com/datadog/android/glide/DatadogGlideModule.kt

Un-deprecate the DatadogGlideModule constructor (make it consistent with the un-deprecation of the Interceptor's constructors).
#528

Undeprecate the DatadogGlideModule constructor

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-ktx/transitiveDependencies

Kotlin coroutines version 1.4.1 has a bug causing stack overflow which was fixed here https://github.com/Kotlin/kotlinx.coroutines/issues/2371 as part of 1.4.2 release.
This bug causes a crash in the sample app.
Changelog: https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md

Use Kotlin coroutines 1.4.2, because version 1.4.1 has StackOverflowError bug

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandlerTest.kt

Fixes #522 . Before this change `MESSAGE` field was removed from the collection if it also contains error fields as part of `extractError` method, and then for the logs default message was used (since original was removed). But it actually makes sense to propagate it to the logs as well.

RUMM-1180: Keep message for logs when it comes with error fields in OpenTracing format

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoDeserializerGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoExtensions.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGenerator.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelValidationTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/TestDefinitions.kt
buildSrc/src/test/kotlin/com/example/forgery/VersionForgeryFactory.kt
buildSrc/src/test/kotlin/com/example/model/Location.kt
buildSrc/src/test/kotlin/com/example/model/Version.kt
buildSrc/src/test/resources/input/constant_number.json
dd-sdk-android/apiSurface
sample/kotlin/src/main/kotlin/com/datadog/android/sample/server/LocalServer.kt

We removed the unnecessary code from the `toJson` method  generated for the `TypeDefinition.Constant` property.
We suppress the lint warning for the unused argument in the method signature. 

RUMM-1176 Constant TypeDefinition - refactor 'fromJson' method

---

dd-sdk-android/src/main/java/com/datadog/opentracing/DDSpan.java
dd-sdk-android/src/main/java/com/datadog/opentracing/PendingTrace.java
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/data/TraceWriter.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutTracesTest.kt
docs/trace_collection.md
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/DataRepository.kt

This PR contains some fixes and updated documentation to offer support for having a continuous Trace when using RxJava and Retrofit streams:
1. We make sure we are dropping the automatically generated requests spans in our `TracingInterceptor` when RUM feature is initialized. This will allow any active trace to be successfully closed and persisted as all of its children (spans) are finished.
2. Cleanup some code inside the `TraceWriter`
3. Provide documentations steps for tracing an RxJava + Retrofit stream
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) …

RUMM-1170 Continuous trace support when using RxJava and Retrofit

---

.gitlab-ci.yml

Add a CI Task to generate and store GPG keys
To publish our artefacts on Sonatype OSSR (and Maven Central), we need to sign our aar/jar with a GPG key.
For security reasons, this GPG key should never be generated on an engineer's work computer. We use this CI script to generate the key and store it as a secret in AWS SSM.
In a future PR, we will be able to read the same GPG key and use it to sign and upload our artefacts to Sonatype OSSR

RUMM-1081 (1/2) Generate GPG signing key in CI

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/ViewUtils.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/ViewUtilsTest.kt

When called from RN `RumMonitor#startView` uses only `java.lang.String` key type and because of that the `view.url_path_group` attribute name was always `java/lang/String` for RN View events. 
In this PR we are addressing this by using the actual key value in this case.

RUMM-1215 Return key value when resolving view url for type String

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt

This change gives user a possibility to provide additional free-form configuration values which can be used at the SDK initialization step on top of the existing pre-defined configuration fields.

RUMM-1212: Add additional free-form configuration to the Datadog configuration

---

dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ForgeExt.kt

This change fixes one issue causing flaky tests (although it happens pretty rare): Say there is `mapA` and `mapB` and there are some common keys in both, with different values. Obviously, `mapA`+`mapB` != `mapB`+`mapA` then, because things will be overwritten differently. Underlying code is doing `mapB+mapA`, but test code does `mapA+mapB` to make an assertion, so test fails.
So this changes introduces the necessary method which will make sure that generated map has unique keys.

RUMM-1223: Fix some flaky tests related to the map merging order when maps have common keys

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/net/LogsOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/SpanSerializerTest.kt

This change introduces a possibility to specify custom `Source` tag for Logs, Spans and RUM events instead of default `android`, this is done with a help of `additionalConfig` collection which was added earlier in #549. This is useful if we want to distinguish whenever SDK is used directly in the native app, or integrated via bridge (say in React Native).
This approach doesn't work well when user has mixed app (native + React Native), because `initialize` call from React Native will be ignored (since SDK would already be initialized). But even if it is not be ignored, it wouldn't work reliably, because it would override default `android` property, which is still valid for events coming from the native layer. But to fix that architecture re-work should be done then, because then `source` …

RUMM-1039: Add a possibility to specify custom Source tag for Spans, Logs and RUM events

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/event/LogEventMapperWrapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/event/LogEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/monitoring/internal/InternalLogFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracesFilePersistenceStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraintsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/event/LogEventMapperWrapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/event/LogEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracesFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationLogForgeryFactory.kt
docs/log_collection.md
docs/trace_collection.md

In this PR:
- we introduce the new `LogMapperSerializer`
- we add the public API method at the SDK configuration level to be able to set the log event mapper
- fixes a problem in the `TraceFilePersistenceStrategy` from previous PRs where the provided `SpanEventMapper` was not wrapped in our own `SpanEventMapperWrapper`
- fixes some flaky tests
- updates the docs related with the new public API method

RUMM-1303 Add public api for logs data scrubbing

---

dd-sdk-android/src/main/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeature.kt

The current key: application that we are using to send the application package name as an internal log attribute is clashing with the already existing facet application.version. We will not be able to create a facet from it and make it queryable so we decided to use a new key instead: application.name

InternalLogger: use application.version as package name key

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploader.kt

In order to have more visibility on the repeated issue regarding the `Timeout` exception in the `OkHttp` request when uploading our log batches we will add information about the current active threads in the `DataUploadScheduledExecutor`.

DataOkHttpUploader: add Executor active threads info to the error log

---

dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt

Cleanup the  crash error message.
The Error Tracking is working on making visible which errors come from  a crash (uncaught errors) and which are just logged errors (caught errors). We need to use the raw message if possible, with the prefix.

RUMM-1325 cleanup crash message

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadWorker.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/constraints/DatadogDataConstraintsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/resource/RumResourceInputStreamTest.kt

Fix tests reported as Flaky in CI App
Avoid noise in the CI App. Most of the tests are not flaky, but are just "not ran" because an assumption fails. By updating the way the fixtures are generated, we can avoid those assumptions. 
Fixed a bug in the Upload worker not sending RUM data.

RUMM-1293 Fix flaky tests

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt

This change solves quite a specific issue: it removes the need of having GPG keys for signing local artifacts (they are useful when development of the bridge is done). Thus condition is quite specific: requirement is lifted only when `publishToMavenLocal` is executed (which is enough to reach the goal). Official documentation proposes to use [taskGraph](https://docs.gradle.org/current/userguide/signing_plugin.html#sec:conditional_signing), but I feel that without project flag (which is too much to introduce) it may become error-prone in case if `taskGraph` also has remote publishing tasks in addition to local publishing. …

Skip artifact signing for local publishing

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/ExternalResourceTimings.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/ExternalResourceTimingsKtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/ResourceTimingExt.kt

This PR brings support of external resource timings which may come with `stopResource` call via free-form `attributes` map.
This is needed to support resource timings coming from any consumer of Android Bridge. Code may have a lot of `if`-checks, but this is because we need to read the free-form map, so we don't have advantage of the type system here.
This PR supports the following timings: `ssl`, `connect`, `dns`, `firstByte`, `download`, even though not all may come (like in case of React Native we can only provide `firstByte` and `download`, but this may not be the same for other users of the bridge).

RUMM-1313: Support external resource timings

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoDeserializerGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoSerializerGenerator.kt
buildSrc/src/test/kotlin/com/example/model/Comment.kt

In this PR we align the code generation for the deserializer and serializer methods in the PokoGenerator in order to prevent overriding the reserved properties when `additionalProperties` provided. 

RUMM-1298 PokoGenerator#toJson do not override the reserved properties

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt

This change makes code to wait for the executors termination, otherwise there is a flakiness in the tests: like test code fails, because expected state is not yet there.

RUMM-1345: Wait for the executors termination to remove flakiness from the tests

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/apisurface/KotlinFileVisitorTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelValidationTest.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelWithAdditionalAttributesTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/privacy/TrackingConsentProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/user/UserInfoDeserializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/user/UserInfoSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/ExternalResourceTimingsKtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/log/LogsTest.kt
tools/unit/src/test/kotlin/com/datadog/tools/unit/ConditionWatcherTest.kt

Recent Android Studio 4.2 comes with Java 11 by default and it turns out our codebase wasn't able to be compiled under it. The issue comes with the old version of `AssertJ` (`3.7.0`, year 2017) which was used in the classpath. Switching to a newer issue helped.

RUMM-1347: Support building with Java 11

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt

To align the data with the browser SDK, and make the infos more consistent, we keep all the usr custom attributes in the root `usr` object.

RUMM-1321 Let all user info be in the usr root

---

docs/configure_rum_android_sdk.md

Converts tables that had hard-to-read columns into Description Lists so that they're more readable.
This page is pulled into the official Datadog public docs (here: https://docs.datadoghq.com/real_user_monitoring/android/advanced_configuration/). The docs team is restructuring some Markdown tables into Description Lists so that they are more readable on the docs site. These changes don't look that impressive here on the rendered github page, but they look a LOT better on the docs site.
Preview the changes here: https://docs-staging.datadoghq.com/kari/test-remote-updates/real_user_monitoring/android/advanced_configuration/#initialization-parameters
No content change (one typo fixed), just structural
- …

Docs: Restructure tables in docs page for improved readability

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataFlusher.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/Flusher.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/PersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/FileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/single/SingleFileOrchestrator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataFlusherTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileOrchestratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/advanced/SingleFileOrchestratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestratorTest.kt

In our instrumentation tests we often need to stop the SDK from one tests case to another for using different configurations. For making sure that all the data was sent we were using a `Thread.sleep()` mechanism which was not very efficient and was introducing a lot of dead time in our CI tasks. To mitigate this  issue we are introducing the `Datadog#flushStoredData` which is making sure that all the executors queues are drained and that the stored granted data for each feature is being sent before stopping the SDK. …

RUMM-1348 Add Datadog#flushStoredData method

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEventListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogEventListenerTest.kt

The instrumented RUM Resource event is started in the `intercept` method in the `DatadogInterceptor`. In case we want to report also the request metrics for this resource we will use a `NetworkInterceptor` -> `DatadogEventListener` which previously was asking the active resource to `WaitForResourceEvent` before sending it. The problem is that the `WaitForResourceTimingEvent` was sent during the `callStart` callback method which for some reason is being called before the `DatadogInterceptor#intercept` in the new version of OkHttp and as it is not active resource event at this time this event will be dropped. 
To fix this issue and to make the active resource to wait for the resource timing event before sending it we will send the `WaitForResourceTimingEvent` on each `start*` callback …

RUM Resource - fix network timings reports feature

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt

In this PR we are adding the nightly test cases for the `Logger#Builder` options and also for the `Datadog#initialize` configuration settings related with the Logs feature.

RUMM-1346 Add nightly tests for Logger.Builder and Datadog.initialize

---

.gitlab-ci.yml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
instrumented/benchmark/build.gradle.kts
tools/detekt/build.gradle.kts

Use a plugin to enforce a `stagingRepositoryId` when uploading the artifacts to Sonatype
The outbound requests from gitlab use a Load Balancer, which means that different files for the same artifact publication can end up in different automatic StagingRepository (cf: https://issues.sonatype.org/browse/OSSRH-19485).

RUMM-1361 Add nexus stagingRepositoryId 

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt

When a `RumActionScope` was dropped without being sent we were not notifying the parent scope (`RumViewScope`) in order to decrement the `pendingActionCount`. This was creating a bad side effect by not allowing to stop a `View` in case there was any action started during the its lifetime that was dropped due to the `no - side - effects` rule. In this *PR* we are fixing this issue by notifying the `parentScope` through an `ActionDropped` event whenever this case arrives.

RUMM-1372 RumViewScope - decrement pendingAction when Action was dropped

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

This change adds support of keeping instant (ones recorded using `.addUserAction`) custom actions even if there is another action ongoing. Before such actions would be dropped.
Here they would be instantly sent, because they don't have any dependencies, so they are not lost.
This change also deprecates variant of `stopUserAction` method which doesn't have `name` parameter in order to:
* be consistent with other methods of the interface
* prevent users from calling it to allow better internal API changes in future
This change doesn't solve however the problem of custom action which may be recorded using `startUserAction/stopUserAction` API, since in this case it cannot be instant, so can have dependencies.

RUMM-1338: Keep instant custom actions even if there is active action ongoing

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt

This change adds all the necessary tests for the observability of the Trace feature configuration APIs.

RUMM-1389: Add tests for the APIs of configuration of the Trace feature

---

docs/rum_getting_started.md

This changes adds the statement about minimum supported OS version. It is added at the similar place as for the Browser SDK https://docs.datadoghq.com/real_user_monitoring/browser/, right after initial Setup block.

RUMM-1384: Add statement about minimum supported version to the official docs

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Credentials.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/CredentialsForgeryFactory.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt

This change prevents sending empty `variant` tag (which is the case when app doesn't declare flavors), because having it leads to the weird display in UI.

RUMM-1370: Don't send empty variant tag

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt

For some reason using only the `yyyy-MM-dd` format in the `SimpleDateFormat` generates different timestamps from one process to another. In this PR we are trying to add a more granular format which will allow us to set the time to the number of milliseconds and see the monitor output in the following days.

Fix the flakiness in the 'logs_logger_add_date_attribute' nightly test

---

instrumentation-tools/nightly_tests_code_coverage.py
instrumentation-tools/src/api_surface.py
instrumentation-tools/src/constants.py
instrumentation-tools/src/feature.py

A first version of the python script tool that will compute the coverage of our nightly tests based on the generated `apiSurface` file. This script will be running as a CI step in our project.
Please note that for now the default threshold is set to a very small value as a consequence of the current amount of tests we have in our `nightly-tests` module. This parameter will be adjusted along the time.

RUMM-1375 Nightly tests coverage computation script

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConstants.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/ForgeExtensions.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt

In this **PR** we are adding the test cases for the `RumMonitor` API in the `nightly-tests` module. Have in mind that those test cases are running based on a basic SDK initialization. All the RUM related options in the SDK `Configuration` and `RumMonitor#Builder` will be covered in upcoming PRs.
Please add comments if you can think to a different test case scenario than the ones I added here in order to update the PR.

RUMM-1392 Add nightly-tests for RumMonitor API

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumContextForgeryFactory.kt

This change add support of `view.name` for the resource, action, error, long task events. Now name of the view will be displayed in the dashboard instead of its id.
Before:
After:
Minor UI thing spotted as well: when dashboard shows `view.id` popup still proposes to filter by `view.name`.

RUMM-1414: Use view name in the children events

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoGenerator.kt
buildSrc/src/test/kotlin/com/example/model/Comment.kt
buildSrc/src/test/kotlin/com/example/model/Company.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/event/LogEventSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/event/LogEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

This PR fixes 2 flaky tests:
* The problem is that if we received tick only once, then it is not enough to calculate a metric `number of ticks on a view`, because we need at least 2 points per this code https://github.com/DataDog/dd-sdk-android/blob/0e9ac1420b70390b58b923902638e57ffc25af1c/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt#L85-L90
* There is a possibility to have `LogEvent.Usr.additionalProperties` with keys which are reserved and dropped during the serialization, but assertion was missing this drop part. Solved by making `RESERVED_PROPERTIES` as `internal` in generated models and by adding a link to it in the assertion.

Fix flaky tests: test which checks a number of ticks on a view, and log event with reserved properties test

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConstants.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt

Adding the nightly test cases for the RUM Feature Configuration options :
- RUM feature enabled
- RUM feature disabled
- RUM feature with sampled RUM sessions
- LongTaskEvent mapper
- ViewEvent mapper
- ErrorEvent mapper
- ResourceEvent mapper
- ActionEvent mapper
Please note that for all the test cases added in this PR we are re-using the performance monitor dedicated for the SDK initialisation execution time. This is already computing the average duration / day so it will work as expected.

RUMM-1425 Add nightly tests for RUM feature config options

---

docs/configure_rum_android_sdk.md

Add documentation for Custom Timings.
**Note**: I copied mostly the corresponding [documentation](https://docs.datadoghq.com/real_user_monitoring/browser/monitoring_page_performance/#add-your-own-performance-timing) from the `browser-sdk`

RUMM-1390 Add documentation for Custom Timings

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/gdpr/GdprDialogFragment.kt

This change fixes refresh of the tracking consent label: it wasn't updated, because it is a part of hosting activity layout, so `onResume` is not called after fragments switch, because same activity is active all the time. Probably it would be cleaner to register some listener in the object responsible for preferences, but it would be more code, because each time `Preferences#defaultPreferences` is called new object is created.

Fix tracking consent label display, which wasn't updated after the change in the dialog

---

docs/log_collection.md
docs/rum_getting_started.md
docs/trace_collection.md

Fixes #627
Deobfuscation is only applied on RUM Errors stack trace, but the note in the Logs/Traces documentation
led some customers to believe deobfuscation would also be applied to Logs / Spans.
Also add a recommendation to use the `BuildConfig.FLAVOR` value to initialize the SDK.

Remove ambiguous statement about deobfuscation in docs.

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumResourceKind.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumResourceKindTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNotSendingSpanTest.kt

Use XHR by default instead of Unknown for RUM Resources
When we are unable to detect the resource type, we're going to use `XHR` by default instead of unknown to ensure the resource can have a backend trace attached to it.

RUMM-1422 Use XHR by default instead of Unknown for RUM Resources

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/trace/TracesTest.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/ReflectUtils.kt

In this PR was trying to identify and fix potential flaky tests in our integration tests module. I tried for more consecutive times to run our integration tests locally and was able to identify a potential flaky test: `ConsentPendingGrantedTracesTest`. After being able to reproduce it ones I was not able to reproduce it anymore and ran the test suite at least 50 times on my end. I guess once it will fail in Bitrise I will have more information on this matter and will able to jump back to it.
I took the chance and fixed also the code in `ReflectUtils.kt` which was throwing a `NoSuchFieldException` if executed in `AndroidJUnit` runtime [See here](https://stackoverflow.com/questions/13755117/android-changing-private-static-final-field-using-java-reflection).
What inspired you to submit this …

RUMM-1396 Fix flaky instrumented tests

---

dd-sdk-android/build.gradle.kts
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/AggregatingVitalMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/FrameRateVitalReader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallback.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/AggregatingVitalMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/FrameRateVitalReaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallbackTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt

Track the device's refresh rate and report it in RUM Views. The refresh rate uses the Choreographer's callback to know when each frame started and compute an accurate approximation of the device's frame rate.

RUMM-1277 Track refresh rate

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderTest.kt

When an application is configured with an invalid Client Token, discard the batch to avoid retrying endlessly with the same invalid token.

RUMM-1475 discard batches on invalid Client Token

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationRumForgeryFactory.kt

Let customers enable/disable tracking of background (view-less) events. This feature is turned off by default to avoid generating too many sessions and impact their billing.

RUMM-1268 let user enable/disable background RUM events

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ComponentPredicate.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/InteractionPredicate.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ConfigurationRumAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/RumGestureTrackerAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTrackerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt
instrumentation-tools/src/constants.py

In this PR we provide a new optional argument for the Public API method: `Configuration#Builder#trackInteractions` -> `InteractionPredicate`
The `InteractionPredicate` interface can be implemented to provide a custom name for the intercepted user interaction target. 
Please note that for the moment this feature will not produce any visible output on the Datadog dashboard because the `action.target.name` attribute is overridden by backend team at the intake level [See here](https://github.com/DataDog/logs-backend/blob/7a5da689f6c4f1ae62ef102033d67b1bf4da81fb/processing/src/main/java/com/dd/logs/processing/processors/AndroidRetraceProcessor.java#L174).
As a follow up, based on the resolution decided together with the Error Tracking team we will …

RUMM-1342 Add action target name predicate API

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumUtils.kt

There were several issues with our nightly tests for the RUM session sampling API :
- the test instrumentation was broken as we were sending the `test_method_name` parameter also for the `View` events that should only have bundled the actual (assertable) action or resource event.
- we were not sending enough events to have a lower deviation rate when sampling the sessions and therefore we were always reaching the limit in the monitors

RUMM-1493 Fix the RUM sampling nightly tests

---

instrumented/nightly-tests/.gitignore
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorBackgroundE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt

Following #652, update the nightly test to handle cases when background RUM events are tracked/not tracked.

RUMM-1498 update nightly tests for background RUM events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/EventType.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Write crash and view update immediately when a crash is detected. 
To avoid crashes being missed, make sure that a crash event is processed on the current thread and is processed immediately. Also we discard the event mapping process for crashes to ensure they're not lost.

RUMM-1504 handle Rum crash reports

---

docs/rum_getting_started.md

Standardize the use of italics documented in Writing Style (Docs4Docs).
Italics are used to introduce product names and features in product landing pages (the parent page in the TOC). Child pages underneath the parent page do not use italics to discuss product names and features.

Standardizing Italics in RUM Docs

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-coil/transitiveDependencies
dd-sdk-android-fresco/transitiveDependencies
dd-sdk-android-glide/transitiveDependencies
dd-sdk-android-ktx/transitiveDependencies
dd-sdk-android-ndk/transitiveDependencies
dd-sdk-android-rx/transitiveDependencies
dd-sdk-android-sqldelight/transitiveDependencies
dd-sdk-android/transitiveDependencies

This change fixes (or at least should fix, because I didn't manage to reproduce the crash in the sample app running Android API 30, but maybe it can depend on OEM) the issue reported at https://github.com/DataDog/dd-sdk-android/issues/658 by upgrading OkHttp version from `3.12.6` to the most recent `3.12.13`. Change is verified - I can see events in the Dashboard from sample app.
OkHttp 3.x changelog https://square.github.io/okhttp/changelog_3x/#version-31213
OkHttp `3.12.6` to `3.12.13` commits https://github.com/square/okhttp/compare/parent-3.12.6...parent-3.12.13 (there are only bugfixes there).

RUMM-1508: Update OkHttp version to 3.12.13 to prevent crashes on the recent Android versions

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/MiscUtils.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/MiscUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/JsonObjectAssertExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/assertj/JsonElementAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ForgeExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/JsonArrayForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/JsonPrimitiveForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumContextForgeryFactory.kt

This change fixes the the serialization issue for nested maps in custom attributes. Say we have a following map `"foo" to ("bar" to "foobar")`. Before this change final JSON would look like that:
```
{
"foo": "{bar = foobar}"
}
```
after the change:
```
{
"foo": {
"bar": "foobar"
}
}
```
This was happening because we were missing `Map` case when doing conversion to `JsonElement`, so default `else` branch was used, which just converted nested map to `String`.
Why it wasn't caught by the test: test also had mistake, so that it was always asserting `Map.Entry` object instead of the actual map value, which was handled by the `else` branch.
Second commit fixes flaky tests: character `.` was used in the regex without escaping, so it had a meaning of any character instead of the original …

RUMM-1515: Support proper serialization for nested maps in custom user attributes

---

dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.cpp
dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c
dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.h
dd-sdk-android-ndk/src/test/cpp/test-signal-monitor.cpp

There was a NPE crash in the `signal-monitor#handle-signal` function. 
The main issue was :
-  in the `handle-signal` function after serializing and persisting the `NDK crash log` we were delegating the intercepted `signal` to the original handler and before
- because we wanted to avoid a continuous loop we will first deregister our handlers 
- in the `uninstall_handlers` function we were also deallocating the memory but because the memory therefore deallocating also the memory which was holding the original handlers. The main reason this crash was not reproduced every time is that the memory is not deallocated synchronously therefore in most of the time the original handlers were were still there when calling the next method.
Also have in mind that this crash is not very dangerous for …

RUMM-1507 Fix NDK NPE crash in signal_monitor

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/KronosTimeProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/TimeProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/time/KronosTimeProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogGeneratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandlerTest.kt

To correct potentially corrupted system UTC time value we were using 2 different approaches for our features: for RUM and Logs we were using a server side time correction (when sending the batch we were sending also the `System.currentTimeInMillis` as a query parameter and the correction was done server side) and for Traces we were using the local `KronosTimeProvider` which is computing the time offset by using an NTP server.
To align on all features we are switching the time correction for RUM and Logs to Kronos and we are dropping the server side time correction.
- [ ] Make sure each commit and the PR …

RUMM-1519 Use Kronos time correction for Rum and Logs

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt

Currently the `source-code-integration` team is overriding the `action.target.name` attribute in case the attribute `action.target.classname` is set. 
The reason behind this is that we are automatically resolving the `action.target.name` from the `action.target.classname` locally and in most of the cases the `classname` is obfuscated. On their end they are able to de - obfuscate first the `action.target.name` in case the `mapping.txt` was provided by the client and use this to override the `action.target.name`.
This worked fine until now when we added the possibility for the client to add its own custom `action.target.name` for each intercepted user - interaction. In order to make these 2 feature working together we will only send the custom `action.target.name` from our end and on the …

RUMM-1516 RumActionEvent - send empty string as default target name

---

dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
instrumented/nightly-tests/build.gradle.kts
instrumented/nightly-tests/proguard-rules.pro
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/crash/JvmCrashHandlerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/crash/NdkCrashHandlerE2ETests.kt
instrumented/nightly-tests/src/main/AndroidManifest.xml
instrumented/nightly-tests/src/main/cpp/CMakeLists.txt
instrumented/nightly-tests/src/main/cpp/datadog-nightly-lib.cpp
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/exceptions/RumDisabledException.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/exceptions/RumEnabledException.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/CrashHandlerDisabledCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/CrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/JvmCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/NdkCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/NdkHandlerDisabledNdkCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/RumDisabledCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/RumEnabledCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/RumEnabledNdkCrashService.kt

In this PR we are adding the required nightly tests for the `JVM` and `NDK` crash reporters. We were able to cover all the scenarios for the `JVM` crash reporter but for the `NDK` one we are missing one scenario (when RUM is not enabled) which could not be yet solved. A separated [task](https://datadoghq.atlassian.net/browse/RUMM-1554) was opened in our JIRA board to try to tackle this later.
A bug was detected at the JVM crash reporter level. When `RUM` feature is not enabled the `onHandleException` method is not delayed enough to give time to the `Logs` `ScheduledWriter` to write the log event so in my tests this was always missing. This is the same for the `RUM` writer but for some reason this has the time to finish in time, I guess it was pure luck. I opened a …

RUMM-1514 Nightly tests for NDK and JVM crash reporters

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/thread/ThreadPoolExecutorExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/thread/ThreadPoolExecutorExtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt

The JVM intercepted crash is not always persisted as a log especially when `RUM` feature is disabled and the reason why is that in both cases : `RUM` and `Logs` we are using a `ScheduledWriter` to persist the event and the `Thread` does not have time to finish before the process is killed. In this *Pr* we are fixing this issue by having the `MainThread` waiting with a minimal timeout before delegating the caught `exception` to the original handler.

RUMM-1556 When intercepting crashes wait for events to be persisted

---

dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.cpp
dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.h
dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c
dd-sdk-android-ndk/src/test/cpp/test-generate-backtrace.cpp
sample/kotlin/src/main/kotlin/com/datadog/android/sample/crash/CrashFragment.kt

The generated NDK stacktrace was always containing the first 3 frames coming from our `libdatadog-native-lib.so` file as the as part of the stacktrace generation code. In order to not send false informations in the Crash reports we need to remove these 3 frames from our NDK reports stacktrace. 

RUMM-1538 Sanitize NDK stacktrace

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumSessionListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Adds an optional `RumSessionListener` to the `RumMonitor`, letting the customer know: 
- when a new Session is starting
- whether the session is kept/discarded (bases on the sampling rate)
- what Datadog's Session id is
Inspired by this feature request: [Datadog/dd-sdk-ios#526](https://github.com/DataDog/dd-sdk-ios/issues/526)

RUMM-1456 Session Listener

---

sample/java/build.gradle

This change makes the usage of common project-wise Android SDKs versions. Otherwise we have 2 Android SDKs linked currently: 29 and 30.

Use common Android SDKs versions in the Java Sample app buildscript

---

.gitlab-ci.yml

Currently we have the following warning when Java VM starts:
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
```
So this change removes `MaxPermSize` option, because it has no effect.

Remove MaxPermSize Java VM option, because it has no effect starting from Java 8

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallbackTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/extension/ChoreographerExt.kt

Fixes #678. Crash happens only on KitKat with minified build due to `DexVerfier` rejecting bytecode of the class `ActivityViewTrackingStrategy`, specifically bytecode of this line https://github.com/DataDog/dd-sdk-android/blob/34933826d3b36988dee8e9fa8a76b829b4a70314/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityViewTrackingStrategy.kt#L72
Error says:
```
I/dalvikvm: Could not find method android.app.Application$ActivityLifecycleCallbacks.onActivityPostResumed, referenced from method com.datadog.android.rum.tracking.ActivityViewTrackingStrategy.onActivityPostResumed
W/dalvikvm: VFY: unable to resolve virtual method 257: Landroid/app/Application$ActivityLifecycleCallbacks;.onActivityPostResumed (Landroid/app/Activity;)V
W/dalvikvm: VFY:  rejecting opcode 0x6f at …
```

RUMM-1580: Fix SDK initialization crash on KitKat for a minified build due to DexVerifier rejecting opcode

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt

This change adds a special handling of `null` argument of `WindowCallbackWrapper#dispatchTouchEvent` to prevent possible crash. Although it is not clear if `dispatchTouchEvent` can receive `null` (all Google code I've checked makes an assumption that argument is never `null`), at least we will have a visibility if it happens and if it happens indeed, it won't crash.

RUMM-1572: Handle null value in WindowCallbackWrapper#dispatchTouchEvent to prevent possible crash

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/GlobalRumE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConstants.kt

Adds coverage on `GlobalRum.addAttribute()` and `GlobalRum.removeAttribute()`
Added the following monitors : 
- Ensures that Views/Actions/Resources/Errors sent after `addAttribute` are received with the expected attributes
- Ensures that Views/Actions/Resources/Errors sent after `removeAttribute` are received without the attributes
- ensure both methods' performance is below the usual threshold

RUMM-1532 add nightly tests for RUM Global Attributes

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/rum/resource-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumResourceKind.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutTracesTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumResourceKindTest.kt

Replace `xhr` by `native` as default resource kind, as `XHR` is a browser technology and doesn't really make sense in a mobile App

RUMM-1606 replace XHR by Native as default resource kind

---

build.gradle.kts
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanConfigE2ETests.kt

In this PR we are adding the remaining nightly tests related with the non - instrumented part of the RUM Tracer feature.
The `AndroidTracer#Builder#setPartialFlushThreshold` configuration option lets the user specify when a pending trace can flush (persist) the already closed child spans and we added 2 use - cases here which assert both situations:
1. When the trace has a pending span (is pending) and a closed Span but the threshold was not reached
2. When the trace has a pending span (is pending) and 2 closed Spans and the threshold was reached
For each of these 2 use cases a monitor was created: 
`[RUM] [Android] Nightly - trace_config_flush_threshold_not_reached: number of spans is above expected value`
`[RUM] [Android] Nightly - trace_config_flush_threshold_reached: number of spans is …

RUMM-1535 Add remaining nightly tests on AndroidTracer.Builder

---

dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c
dd-sdk-android-ndk/src/test/cpp/test-signal-monitor.cpp

In this PR we are removing the ANR handling at the NDK level as it overrides the Google current implementation [more details here](https://github.com/bugsnag/bugsnag-android/blob/next/bugsnag-plugin-android-anr/src/main/jni/anr_google.c). Google is handling the ANRs adding its own signal catcher at [runtime](https://android.googlesource.com/platform/art/+/master/runtime/signal_catcher.h) . 
We are already covering the ANR error at the JVM level so there is no need for this here.

RUMM-1593 Remove SIGQUIT(ANR) signal handler from NDK plugin

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEventListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/plugin/DatadogContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/plugin/DatadogPluginConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/plugin/Feature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumResourceKind.kt
detekt.yml
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/TodoWithoutTask.kt

This change removes all JCenter repo references, because JFrog is sunsetting it and it had an outage on September 16th, causing the failure of our CI pipeline.
The following libs were updated, because they (or their transitive dependencies) were hosted on JCenter before:
* `Detekt`
* `Realm`
* `Dokka`
Update of `Detekt` required some code changes, because the following rules are changed in the new version:
* `LongParameterList` - the following PR https://github.com/detekt/detekt/pull/2410 added constructor validation, which wasn't there before. Solved by adding `constructorThreshold: 12` to the rule configuration, no code changes were made.
* `UndocumentedPublicProperty` - the following PR https://github.com/detekt/detekt/pull/2475 added constructor validation, which wasn't there before. …

RUMM-1621: Remove jcenter repo references

---

buildSrc/build.gradle.kts
tools/unit/src/main/kotlin/com/datadog/tools/unit/ReflectUtils.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/annotations/TestTargetApi.kt

It turns out that for a long time version of Detekt Gradle plugin wasn't in sync with lib version we are using, causing the miss in the scan of some files. This change aligns version of plugin with the version of the library.

Sync Detekt Gradle plugin version with lib version

---

dd-sdk-android-ndk/src/main/kotlin/com/datadog/android/ndk/NdkCrashReportsPlugin.kt

This change prevents a crash if during `updateTrackingConsent` call in the NDK plugin native library is not loaded.
No test for this change, because it seems spying/mocking native methods is not possible without `PowerMock`.

RUMM-1677: Prevent native updateTrackingConsent call if libdatadog-native-lib is not loaded

---

dd-sdk-android-ndk/src/main/cpp/utils/backtrace-handler.h
dd-sdk-android-ndk/src/main/cpp/utils/signal-monitor.c

In Android 11 and Android 12 it seems that the signal stack overhead memory is reduced so when trying to unwind the stack frames in the signal handler we were running out of memory and the process exited without serializing the crash log. In order to fix that we are increasing the amount of memory for our signal stack and in the same time we are decreasing the memory allocated in the stack for unwinding and constructing the stacktrace. 

RUMM-1652 Fix the problem with the signal stack memory in NDK handler

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

Copy the `throwable`‘s message into the RUM Error message field to get a better visibility for customers.

RUMM-1711 Enrich RUM error with throwable message

---

dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt

This change switches from API v1 to API v2 for the Crash Reports feature as it was done for other features in #671 before.
I validated this change in the sample app by triggering a crash - it was displayed in the Logs with stacktrace and `Emergency` level.

RUMM-1754: Use API v2 for Crash Reports feature

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt

This change fixes the issue reported here https://github.com/DataDog/dd-sdk-reactnative/issues/123: custom `source` tag wasn't applied after migration to API v2. This happens because after API v2 migration we apply `additionalConfig` too late.

RUMM-1753: Apply custom source tag for the API v2 uploaders setup

---

.gitlab-ci.yml
dogfood.py

This change updates dogfood script to target Gradle version catalogs, which are introduced with the recent Gradle 7 upgrades.

RUMM-1748: Update dogfood script to target Gradle version catalogs

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/rum/error-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumErrorSourceType.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ErrorEventForgeryFactory.kt

This change introduces the possibility for specify custom error source type, so that we can distinguish errors coming from native Android apps vs another layer calling Android SDK (like Browser or React Native SDK).
This is done by adding `_dd.error.source_type` key to the `attributes` which can be supplied to the `addError` or `addErrorWithStacktrace` calls (`stopResourceWithError` is out of scope, because it is not used currently by non-native SDKs). Provided value will override the default one `Android`. Supported values are `react-native` and `browser` for now, `iOS` is out of scope, because it is not technically possible to have it.

RUMM-1717: Read custom error source type value

---

.gitlab-ci.yml
dogfood.py

This change cherry-picks update to dogfood script (https://github.com/DataDog/dd-sdk-android/commit/2395df2c8d6b0a7433bfad230afb2a33919ac6d0) to target version catalogs in the dependent repos.

Cherry-pick: RUMM-1748: Update dogfood script to target Gradle version catalogs

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/thread/ThreadExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/thread/ThreadPoolExecutorExt.kt

Prevent app from crashing when calling the `DatadogExceptionHandler.uncaughtException()` method.
Fixes #749

RUMM-1759 Prevent crash on uncaught exception

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracingFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/event/DdSpanToSpanEventMapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderV2.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogGeneratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/event/DdSpanToSpanEventMapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderV2Test.kt

This change introduces a possibility to override native SDK version which is need for other SDKs using the native one, like React Native SDK.
This is achieved by having a new property `_dd.sdk_version` in the `additionalConfiguration` dictionary which is passed during the native SDK initialization.
We are going to use custom SDK version only for API v2 uploaders, API v1 uploaders are left untouched.

RUMM-1708: Allow to specify custom SDK version

---

dogfood.py

This change adds the missing `gradle-plugin` to the list of dogfood script targets.
This is a minor issue, no need to cherry pick into `1.11.0` release branch.

Fix missing value in the options of dogfood script

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

Only mark a view as not active when it's fully complete
The backend reducer marks the view as readonly after the first update where `is_active:false`, meaning that if we try to update it afterwards, it will be ignored and some data will be lost.

RUMM-1775 Ensure view is reported as active until it's fully complete

---

dd-sdk-android-compose/README.md
dd-sdk-android-compose/apiSurface
dd-sdk-android-compose/build.gradle.kts
dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/ExperimentalTrackingApi.kt
dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/InteractionTracking.kt
dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/Navigation.kt
dd-sdk-android-compose/src/test/kotlin/com/datadog/android/compose/TapActionTrackerTest.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/test/kotlin/androidx/compose/ui/platform/ComposeView.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerTapTest.kt
detekt.yml
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/ComposeFragment.kt

This change add a small utility function which may simplify click tracking with Jetpack Compose.
Unfortunately, it seems there is no good way to do auto-instrumentation by using public Compose API, so this change is about the manual instrumentation: user has to use it explicitly on the element.
It is worth mentioning that there is very small added value, because it can be just written as:
```
Button(onClick = {
GloralRum.get().addUserAction(...)
...rest of onClick logic...
})
```
But because we proxying original `() -> Unit` type with the help of class with `fun operator invoke()` overload and we have to capture the variables, to avoid new objects creation during the re-composition event, we have to add a bunch of `remember` calls.
~~Another pitfall is `RumActionType` usage. If we use …

RUMM-1611: Track clicks in Jetpack Compose

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/webview/WebRumEventContextProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/GlobalRumTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

In this PR we are introducing the `GlobalRum#notifyIngestedWebViewEvent` internal method. The purpose of this method is to trigger an asynchronous `EmptyEvent` at the `SessionScope` level which will check if the session needs to be updated or not. This should be triggered whenever a new RUM event is received through the JS bridge.

RUMM-1774 Add the GlobalRum#checkForSessionUpdate method

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt

This change aligns value of `action.gesture.direction` attribute with physical gesture (finger) direction.
It is done to remove the possible confusion: currently if finger is moved to the `right`, direction reported will be `left`, because we go to the beginning of the list in case of RTL layout (and vice versa). This makes sense for the scrollable list, but not for the swipe (element still goes to the `right`). Moreover, reporting logic for horizontal axis wasn't consistent with vertical axis in case of scroll.
Now the direction of the finger will be simply reported.

RUMM-1800: Use physical gesture direction definition

---

tools/detekt/src/main/kotlin/com/datadog/tools/detekt/DatadogProvider.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/ext/KotlinTypeExt.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/ext/ReceiverExt.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/InvalidStringFormat.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/UnsafeThirdPartyFunctionCall.kt
tools/detekt/src/test/kotlin/com/datadog/tools/detekt/rules/InvalidStringFormatTest.kt

Add a check to ensure `String.format()` calls are valid: 
- checks number of argument matches the provided specifiers
- checks the type of arguments matches the provided specifiers
Add checks on the code we ship

RUMM-1760 create rule to detekt invalid String.Format

---

LICENSE-3rdparty.csv
dd-sdk-android-compose/README.md
dd-sdk-android-compose/apiSurface
dd-sdk-android-compose/build.gradle.kts
dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/InteractionTracking.kt
dd-sdk-android-compose/src/test/kotlin/com/datadog/android/compose/SwipeAndScrollActionTrackerTest.kt
dd-sdk-android-compose/transitiveDependencies
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt
detekt.yml
gradle/libs.versions.toml
sample/kotlin/build.gradle.kts
sample/kotlin/src/main/AndroidManifest.xml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/ViewPagerActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/InteractionFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/JetpackComposeActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/NavigationFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/home/HomeFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/viewpager/FragmentA.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/viewpager/FragmentB.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/viewpager/FragmentC.kt
sample/kotlin/src/main/res/layout/activity_compose.xml
sample/kotlin/src/main/res/navigation/nav_graph.xml

This change brings support of manual instrumentation of Swipe and Scroll actions in Jetpack Compose.
It works by listening for the interactions happening with a help of [InteractionSource](https://developer.android.com/reference/kotlin/androidx/compose/foundation/interaction/InteractionSource) and then reading the current state of Swipe/Scroll when certain interaction happens.
Under the hood of Jetpack Compose both scroll and swipe rely on the generic `drag` operation, so code for their tracking have some similarities. However, there are also differences: 
* Direction: swiping down will **increase** offset from the base point, however scrolling down will **decrease** offset from the base point.
* Anchors: scroll doesn't have anchors, but swipe should have at least one anchor is …

RUMM-1776: Add swipe and scroll manual instrumentation to jetpack compose

---

dd-sdk-android-compose/README.md
dd-sdk-android-compose/apiSurface
dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/Navigation.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/compose/NavigationFragment.kt

This change renames `DatadogViewTrackingEffect` to `NavigationViewTrackingEffect` to better emphasize that this effect relies on navigation mechanism and to remove redundant `Datadog` mention (other public elements in `compose` module are not using it).

Rename DatadogViewTrackingEffect to NavigationViewTrackingEffect

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt

As discussed in #760, but without separate `LazyNavigationViewTrackingStrategy` - there's no need for a separate class, it will just confuse, especially since it would either need to re-implement all of the functionality of the base class, or need to be derived from it. Original implementation still works exactly the same as before, but exposes tracking functionality through public functions `startTracking` and `stopTracking`. This way, it's possible to use the strategy with programmatically created `NavHostFragment`.
In most cases, only a call to `startTracking` is needed, `stopTracking` is called automatically when activity stops. But we do call `stopTracking` in our custom implementation as well because we replace `NavHostFragment` multiple times during activity lifetime. Having it …

Improving `NavigationViewTrackingStrategy` to allow dynamic `NavHostFrament` setup [#760]

---

build.gradle.kts
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationCoreForgeryFactory.kt

The `verboseDebugInfo` flag will override any other user settings to increase upload frequency, disable sampling, and set logging to verbose, but only when the application is marked as `debuggable` in the manifest.
Implements RUMM-1773

Add a flag that allows increased info when debugging

---

build.gradle.kts
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt

This change brings the same logic in `ActionScope` when `StartView` event is received as for the `StopView`, because action lives in the boundaries of the parent view scope, and if another view starts without calling `stopView` for the previous view, we need to release current action, to be able to mark current view as complete.

RUMM-1833: Stop current action if another view starts

---

dd-sdk-android/apiSurface
dd-sdk-android/build.gradle.kts
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/MiscUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/MiscUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/JsonObjectAssertExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/assertj/JsonElementAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ForgeExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/GsonJsonArrayForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/GsonJsonObjectForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/GsonJsonPrimitiveForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/OrgJSONArrayForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/OrgJSONObjectForgeryFactory.kt
detekt.yml
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt

Closes #588. This change adds support of `org.json.JSONArray` and `org.json.JSONObject` classes (which come with Android SDK) in the `Logger#addAttribute` call.

RUMM-1837: Add org.json support for the event attributes

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/GdprRumE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumUtils.kt

This change affects nightly RUM E2E tests which are backed by multi-alert (by group) monitors: before monitors were failing because they expect events of all types to be received, so this change will send all the possible event types in such tests.

RUMM-1850: Remove flakiness in RUM E2E tests backed by multi-alert (by group) monitors

---

instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/CrashService.kt

Recent https://github.com/DataDog/dd-sdk-android/pull/791 changed the way `appLaunch` event is sent (so that now it cannot be send from background process) and it impacted E2E test `ndk_crash_reports_rum_enabled`.
The issue is that since this test spins a service in another process (so it has background status), and just start a view, by the time NDK crash happens there is no yet view written to the disk (it was written before because of `appLaunch` event, which is not triggered now for this setup).
So solution is just to add `addTiming` call which will cause view event dump to the disk (via `sendViewUpdate`). It could be done with actions as well, but actions are saved only when another action arrives, so it would be more code.

Fix NDK Crash E2E test failure caused by missing RUM view at the time of crash

---

detekt.yml
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/UnsafeThirdPartyFunctionCall.kt
tools/detekt/src/test/kotlin/com/datadog/tools/detekt/rules/UnsafeThirdPartyFunctionCallTest.kt

This change makes `UnsafeThirdPartyCall` check skip `invoke` calls, because this is essentially synthetic wrapper around lambda invocation.

RUMM-1797: Ignore kotlin.FunctionX.invoke calls in the UnsafeThirdPartyCall check

---

dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventConsumer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventContextProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventConsumerTest.kt

We were currently sending the dummy `WebViewEvent` to refresh the session in the `RumSessionScope` for all ingested JS events resulting from WebView tracking including the `log` events. This PR corrects this behaviour by sending the event only for RUM types ingested events.

RUMM-1877 Send dummy RUM WebViewEvent only for RUM JS ingested events

---

.gitlab-ci.yml
build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/GenerateJsonSchemaTask.kt

This change improves build pipeline speed by doing the following:
* Enables [Gitlab cache](https://docs.gitlab.com/ee/ci/caching/) between `analysis` and `test` stages.
* Makes `test:tools` to build only `US1` variant, because we don't have different source code sets for the flavors, so this will be enough.
Cache is **only produced** by `analysis:detekt` job (as it covers most of task graph among executions in the `analysis` stage), and **only consumed** by `test` group.
Cache is not consumed by the `publish` stage, because this stage is executed very rarely.
Cache is valid only inside the certain pipeline (because it has pipeline ID as a key, check [Gitlab predefined variables](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)), so we will monitor `test` stage execution …

RUMM-1873: Improve build pipeline speed

---

dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt

Mockito is using `Arrays.equal` to compare array arguments, so it is possible that test setup has 2 (or more) batches with the same content, this led to the tests failure (because non-successful upload should happen only for one batch).

RUMM-1423: Fix flaky UploadWorkerTest setup

---

docs/integrated_libraries_android.md
docs/log_collection.md
docs/native_crash_collection.md
docs/rum_getting_started.md
docs/trace_collection.md

This PR fixes the format for Java code snippets in the RUM docs pages:
[See here](https://docs.datadoghq.com/real_user_monitoring/android/?tab=java#initialize-the-library-with-application-context)

RUMM-1915 Fix the Java code snippets in the docs

---

dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandlerTest.kt

Kotlin 1.5 brought the following feature https://kotlinlang.org/docs/whatsnew15.html#sam-adapters-via-invokedynamic, which will skip wrapper class generation for SAM-compatible declarations. This made the referenced test to fail, because there is no anonymous class generated.
This change enables this test back by avoiding SAM-compatible declaration.

RUMM-1732: Enable back LogcatLogHandler#resolves_nested_stack_trace_element_from_caller test

---

dd-sdk-android/src/test/kotlin/com/datadog/android/utils/assertj/JsonElementAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ForgeExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/GsonJsonPrimitiveForgeryFactory.kt

When deserializing a json string to a RUM event we are using the `JsonParser` from Gson internal libraries. The `JsonParser` will bundle any property value in a `JsonPrimitive` and will force that value to a `String`. Now when trying to match a deserialized object with a serialized one `AssertJ` uses the `JsonPrimitive#equals` method under the hood which has a special case for `Double` and `Float`:
```
double a = getAsNumber().doubleValue();
double b = other.getAsNumber().doubleValue();
return a == b || (Double.isNaN(a) && Double.isNaN(b));
```
Problem is that when using a `Float` in the deserialized object we will get a `String` representation of that value and the `other.getAsNumber().doubleValue()` uses `Double.parseDouble(value)` under the hood which returns the float conversion but …

RUMM-1531 Support json float fields in test assertions

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventMapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventMapperTest.kt

We do not override anymore the `service` property in the RUM events received through the `JSBridge` with out own internal value. 

RUMM-1920 Do not override 'service' property for WebView tracked events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/event/DdSpanToSpanEventMapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/domain/event/DdSpanToSpanEventMapperTest.kt

Report the correct `_dd.source` for spans.
The `source` attribute can be changed by our cross platform SDKs (React Native, Flutter, …). We do take it into account for logs and RUM but didn't yet for spans.

RUMM-1853 Report the correct source for spans

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorBackgroundE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt

This PR introduces a new overloaded method in the `RumMonitor` interface:
```
fun stopResourceWithError(
key: String,
statusCode: Int?,
message: String,
source: RumErrorSource,
stackTrace: String,
errorType: String?,
attributes: Map<String, Any?> = emptyMap()
)
```
This method is mainly added for being used from hybrid apps/sdks.

RUMM-1898 RumMonitor#stopResourceWithError with stacktrace and errorType properties

---

dogfood.py

Since the dependency management changed in the Mobile App repo, we needed to update our dogfooding script to point to Gradle's `libs.versions.toml` instead of the previously used `Datadog.kt` class.

RUMM-1947 fix dogfooding script

---

dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/ThrowableExtTest.kt

Ensure that nested exception stack trace prints everything (including the `Caused by` parts).

RUMM-1933 Java Error nested stack trace

---

CONTRIBUTING.md
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorBackgroundE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt

In some of our perfs measurement methods we were also taking int account the time to forge the fake method parameters. 
This PR fixes this problem by generating all the parameters outside of the measurement block.

RUMM-1942 Improve the perfs measurements methods in nightly tests

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTrackerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt

This PR introduces adds a new capability to our RUM feature allowing it to track user interactions when running on Android TV or any other type of devices that are using a remote control to interact with the application.

RUMM-2040 Detect user actions on remote control actionable devices

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/SystemInfo.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataUploadRunnableTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/assertj/SystemInfoAssert.kt

We are currently conditioning the data upload on the device battery status but this creates a problem when the device has a different power supply than a battery. In that case the `BATTERY_STATUS` is usually unknown and the `BATTERY_LEVEL` usually 0 which means no data will ever be sent from that device. Such devices can be the Android TV or any other device using the Android OS and running on external power supply.
In this PR we are fixing this issue by taking into account also the `PLUGGED_STATUS` in the `BatteryManager` information Intent. This will usually return one of the values `BatteryManager.BATTERY_PLUGGED_AC`, `BatteryManager.BATTERY_PLUGGED_WIRELESS`, `BatteryManager.BATTERY_PLUGGED_USB` in case the device is running on external power source.
What inspired you to submit this …

RUMM-2039 Always send data when device has external power source

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/ReflectUtils.kt

Encryption tests in the night run were failing with error:
```
java.lang.NoSuchMethodError: No static method setSecurityConfig(Lcom/datadog/android/core/configuration/Configuration$Builder;Lcom/datadog/android/core/configuration/d;)Lcom/datadog/android/core/configuration/Configuration$Builder; in class Lcom/datadog/android/nightly/utils/ReflectUtilsKt; or its super classes (declaration of 'com.datadog.android.nightly.utils.ReflectUtilsKt'
```
This PR fixes that by adding the necessary method to the necessary location.

Fix nightly run for encryption tests

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt

Wrong name (from another test) was used.

Fix name used in rum_rummonitor_ignore_stop_background_resource_with_error_stacktrace test

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt

We currently have some internal attributes which are coming from cross-platform calls (ex. React Native SDK) and these attributes are needed only for the SDK (not for the backend). However, in the current sanitization logic these attributes are considered as reserved and dropped during event serialization with logging an error entry, which leads to the log pollution.
This change silently drops such attributes at the `RumEventSerializer` level, keeping current `ignoredAttributes` collection untouched (to avoid breaking the things on the server side and in case if at some point `ignoredAttributes` != `crossPlatformTransitAttributes`) and applies such logic only to the context attributes (not user-ones, because these internal attributes are coming only through events).

RUMM-2066: Silently drop cross-platform RUM attributes before event serialization

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/KotlinFileVisitor.kt
dd-sdk-android/apiSurface
dd-sdk-android/generate_telemetry_models.gradle.kts
dd-sdk-android/src/main/json/telemetry/_common-schema.json
dd-sdk-android/src/main/json/telemetry/debug-schema.json
dd-sdk-android/src/main/json/telemetry/error-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSourceProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryType.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSerializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventSourceProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryDebugEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/assertj/TelemetryErrorEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/model/TelemetryDebugEventTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/model/TelemetryErrorEventTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/TelemetryDebugEventForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/TelemetryErrorEventForgeryFactory.kt
gradle/libs.versions.toml
instrumentation-tools/src/constants.py

This PR adds support of sending telemetry events as a part of general RUM events processing pipeline (because these events go to the RUM intake).
The necessary private methods are added to the `AdvancedRumMonitor` (they are quite basic ones for now, without support of stack as a string, for example, for now).
Processing happens outside of any RUM scope (to not depend on the scope being created) and also outside of application and session scopes (to avoid the possible confusion with taking RUM context of those, which will miss info about current view and action).
Also this change updates the version of the Kotlin AST parsing lib, because I've hit a bug with existing version (also update solves the issue with wrong entries in the `apiSurface`).
The rest of work like replacing the existing …

RUMM-2021: Support telemetry events in the events processing pipeline

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/DefaultViewUpdatePredicate.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/ViewUpdatePredicate.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/DefaultViewPredicateTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ActivityTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/FragmentTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/GesturesTrackingTest.kt

During a `ViewScope` lifecycle we are sending too many `ViewEvent` updates which are significantly increasing the size of our payloads and also increasing the data traffic. Above all these extra `ViewEvents` are affecting our reducers performance in the backend. We are currently introducing a special `predicate` that will limit the `ViewEvent` updates to 1/30 seconds with a wildcard in case the scope `ViewScope` was finalized.

RUMM-2028 Reduce number of views updates in payloads

---

.gitlab-ci.yml
LICENSE-3rdparty.csv
build.gradle.kts
dd-sdk-android-tv/.gitignore
dd-sdk-android-tv/README.md
dd-sdk-android-tv/apiSurface
dd-sdk-android-tv/build.gradle.kts
dd-sdk-android-tv/src/main/AndroidManifest.xml
dd-sdk-android-tv/src/main/kotlin/com/datadog/android/tv/LeanbackViewAttributesProvider.kt
dd-sdk-android-tv/src/test/kotlin/com/datadog/android/tv/LeanbackViewAttributesProviderTest.kt
dd-sdk-android-tv/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
dd-sdk-android-tv/transitiveDependencies
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/DatadogGesturesTracker.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt
docs/integrated_libraries_android.md
docs/rum_getting_started.md
gradle/libs.versions.toml
settings.gradle.kts

We are currently missing some relevant information for the intercepted RUM Action events in the Android TV applications. 
In this PR we are adding 2 extra features to enrich that information:
1. We are using the existing `JetpackViewAttributesProvider` also for the DPAD (remote control) intercepted action events. By doing this we will provide additional information as the parent class name or the adapter position in case the target is rendered inside a `RecyclerView`
2. We are introducing the `dd-sdk-android-tv` module in which we provide the `LeanbackViewAttributesProvider`. The latter will add extra information as the `actionId` or `actionLabel` in case the target is an action item added through the default Leanback API.
Anything else we …

RUMM-2051 Android TV - get more information on action targets

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/config/DetektConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt
dd-sdk-android-ndk/build.gradle.kts
dd-sdk-android/build.gradle.kts
dd-sdk-android/src/main/java/com/datadog/trace/api/Config.java
instrumented/integration/build.gradle.kts
instrumented/nightly-tests/build.gradle.kts
sample/kotlin/build.gradle.kts

This change aligns JVM target for both Java and Kotlin compilation to 11 to avoid the following warning during the build:
> 'compileJava' task (current target is 11) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
This is completely safe change because AGP 7+ [supports de-sugaring Java 11 produced code](https://developer.android.com/studio/releases/gradle-plugin#java-11).
Also `Config.java` file requires adding `@Deprecated` annotation to the symbols having `deprecated` in their Javadoc to fix the warnings (some other symbols in this have this annotation already).

RUMM-2103: Set Java 11 compilation target

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/GlobalRumTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/config/CoreFeatureTestConfiguration.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/annotations/ProhibitLeavingStaticMocksIn.kt
tools/unit/src/main/kotlin/com/datadog/tools/unit/extensions/ProhibitLeavingStaticMocksExtension.kt
tools/unit/src/test/kotlin/com/datadog/tools/unit/extensions/JavaClassWithNestedStaticMock.java
tools/unit/src/test/kotlin/com/datadog/tools/unit/extensions/JavaClassWithStaticMock.java
tools/unit/src/test/kotlin/com/datadog/tools/unit/extensions/ProhibitLeavingStaticMocksExtensionTest.kt

This PR brings a `JUnit` extension, which will track mocks left in the static fields (Java) or fields of `object` of `companion object` (Kotlin), trying to search for me starting from the specified class roots.
This may help in tracking down issue when some static field has mock left and it is causing unexpected behavior in another test. It is mostly for the debugging than for the usage everywhere, because:
1) It is using the reflection and scan full reference hierarchy.
2) It requires you to respect extension declaration order (described in the annotation docs).
3) Most important: in case of `lateinit` properties there is no way to reset them, there is no API for that, so such properties may still have mocks - in such cases extension will just report violation in the log.

Track static mocks left

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt

In this PR we are aligning the error log messages displayed in the console when the `NoOp` implementation is used for `Logger`, `AndroidTracer` or `RumMonitor` due to the SDK not being initialized yet or the feature not being enabled.

RUMM-2090 Print logcat error message when using NoOp implementations

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

`setWebViewTrackingHosts` was called twice and second time it was called with a wrong host, so `DatadogEventBridge` wasn't receiving any events.

Fix tracked webview hosts in the sample app

---

dd-sdk-android-coil/build.gradle.kts
dd-sdk-android-compose/build.gradle.kts
dd-sdk-android-fresco/build.gradle.kts
dd-sdk-android-glide/build.gradle.kts
dd-sdk-android-ktx/build.gradle.kts
dd-sdk-android-rx/build.gradle.kts
dd-sdk-android-sqldelight/build.gradle.kts
dd-sdk-android-timber/build.gradle.kts
dd-sdk-android-tv/build.gradle.kts
tools/unit/build.gradle.kts

Follow-up for #890. It turns out some modules didn't specify `compileOptions` explicitly and default value for `source/targetCompatibility` was Java 8 (and I didn't noticed that because of task caching). This PR aligns that.
Note: it will be still a warning for `buildSrc` compilation because of the following issue https://github.com/gradle/gradle/issues/18935, which should be fixed in Gradle 7.5.

Specify android DSL compile options explicitly

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/UploadStatus.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/UploadStatusTest.kt

When a client token is unknown, the upload request receives a `403 FORBIDDEN` status code. We need to make it clearer and actionnable in the logcat message we provide the developers

RUMM-2128 update 403 FORBIDDEN logcat message

---

build.gradle.kts

This PR removes usage of `flatDir` in the Gradle script, because it was generating warnings during the builds. It wasn't useful anyway, because the only file in the `libs` folder is loaded as agent [here](https://github.com/DataDog/dd-sdk-android/blob/c19dd9e0eafd120d3707ee7fa71b7a484ee72d0a/buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt#L27) and there are no files there which are dependencies for the final build.

Remove flatDir usage in Gradle script

---

.gitlab-ci.yml
buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt

This PR bumps `dd-java-agent` version used from `0.67.0` to `0.98.1`, unlocking the possibility to use JUnit 5.8+, which wasn't possible because of the bug which was fixed only in `0.92.0`.
Test and pipeline runs are reported fine after this change.

RUMM-1897: Update DD Java Agent to 0.98.1

---

docs/web_view_tracking.md

Adds Android Web View Tracking beta documentation.
DOCS-3019
Preview link in Documentation PR: https://docs-staging.datadoghq.com/alai97/single-sourcing-web-view-tracking-docs/real_user_monitoring/android/web_view_tracking/.
Remember to update the branch back to `master` in the dependencies front matter before merging!

DOCS-3019 Adds Android Web View Tracking Documentation

---

dd-sdk-android-ndk/src/main/kotlin/com/datadog/android/ndk/NdkCrashReportsPlugin.kt
dd-sdk-android/build.gradle.kts
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/DataFlusher.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/EncryptedFileHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/EventMeta.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/FileHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/FilePersistenceConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/FeatureFileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataReader.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/single/SingleItemDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/ByteArrayExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/DataFlusherTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/EncryptedFileHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/EventMetaTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/advanced/FeatureFileOrchestratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataReaderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/single/SingleItemDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/ByteArrayExtTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandlerTest.kt
detekt.yml
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/security/EncryptionTest.kt

This PR brings a new event storage format. Now every event written to the disk will also have a header which contains metadata. Currently this metadata only includes event size in bytes, which makes possible to treat a storage as a binary file and read individual events back for the possible pre-processing before doing the upload, also removing the need to store the separator in the file.
This new format also dramatically improves the logic needed to support encryption, because knowing event binary size we don't need to rely on the separator anymore when reading it back.
Another benefit is that is file is partially corrupted we will be able to read back at least some events, instead of loosing all the data in the file.
While this PR adds metadata to each event, it is **not yet propagated …

RUMM-2139: New event storage format

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/LoggingSyncListener.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/time/LoggingSyncListenerTest.kt

This change widens the scope of the exceptions thrown by Kronos library to be reported with telemetry. Apparently it [can throw InvalidServerReplyException](https://github.com/lyft/Kronos-Android/blob/b2774ab9458ffd0202e2c4880e2a181134953beb/kronos-java/src/main/java/com/lyft/kronos/internal/ntp/SntpClient.java#L156) when server is not a valid state (like `leap` value is equal to `0b11`, meaning server is not synchronized, check [NTP RFC](https://datatracker.ietf.org/doc/html/rfc5905#page-20)).
We cannot address such issues anyway and if NTP servers are not healthy it will be caught by infra monitoring.
To avoid spammy telemetry entries this PR adds all `IOException` instances to the ignore list.

Ignore IO exceptions in Kronos for telemetry reporting

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestratorTest.kt

This PR fixes a race condition in the features folders creation logic. It may occur when one thread checks for the existence of the root dit for the feature, gets that folder doesn't exist and goes in the folder creation logic branch, and another thread does the same. This may lead to a situation when both threads will call `File#mkdirs` but only one of them will get a successful result, because another one will get a failure since folder is already created.
Not sure if this situation can happen often in the client setup, but it happens in our nightly test runs when we do a call to change a consent (so to migrate files from one dir to another) right after SDK initialization step, which impacts test outcome.

RUMM-2150: Fix race condition in the features folders creation logic

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

This change should fix having a telemetry entry saying that current view ID doesn't match view ID in the global RUM context. This may happen if we update the context when new session started - this means we also change view ID for the current view.
This PR fixes that allowing update of the global context in case of the session ID mismatch.

RUMM-2142: Allow global context update if view is stopped in a new session

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/LoggingSyncListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/time/LoggingSyncListenerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

This PR change pulls the latest fixes made in `develop` branch into `release/1.13.0` branch. Notably:
https://github.com/DataDog/dd-sdk-android/pull/913
https://github.com/DataDog/dd-sdk-android/pull/912
https://github.com/DataDog/dd-sdk-android/pull/910

Pull latest fixes into 1.13.0 release branch

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/MavenConfig.kt
gradle.properties

This change brings support of the new publishing model by explicitly specifying components for publishing (`release` in our case).
This new model landed [originally in AGP 7.1](https://developer.android.com/studio/releases/gradle-plugin#disable-component-creation) and automatic components creation for publishing will be disabled in AGP 8.0.
Docs for the new approach can be found [here](https://developer.android.com/studio/publish-library/configure-pub-variants).
Since new model can also attach `sources` and `javadoc` (by `Dokka`) artifacts to the published component, explicit tasks for the sources and docs are removed.
Change is verified by publishing to the local Maven, everything is fine and file set is complete (`aar` + `sources` + `javadoc` + `pom` + `module`) and has an expected …

RUMM-2095: Support new AGP publishing model

---

dd-sdk-android-timber/apiSurface
dd-sdk-android-timber/src/main/kotlin/com/datadog/android/timber/DatadogTree.kt
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsUtils.kt

Closes #847. This PR includes the following:
* Adds a possibility to set up default `logger` with min priority log level set in the `DatadogTree` (Timber integration module).
* Adds a possibility to define minimum log level sent to the Datadog servers in the `Logger.Builder` configuration (main SDK module). Note: `logcat` logs are not affected by this parameter.
This feature is useful when Datadog logger is used in the collaboration with other loggers and there is need for more granular control for Datadog logger to avoid sending unwanted log levels to avoid exploding log volume usage (can be the case of verbose or debug logs).

RUMM-2042: Filter Datadog logs per level

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/ByteArrayExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/ByteArrayExtTest.kt
detekt.yml

Fixes a silly bug: size taken by separators could be negative in case of empty collection (doesn't impact any data upload though).

Fix the logic of joining byte arrays when there is no items

---

dogfood.py

Add a link to the github tag diff page on PR opened by the CI on new version releases.
Need a fast and easy way to. know the diff between two intermediate release (as the changelog reflects major release but not alpha/beta release)
Not sure how to test it out of the release pipeline and on all repos using the script/CI PR generation

Add github diff link on PR generated by the CI on new versions

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/VitalsUpdateFrequency.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/thread/NoOpScheduledExecutorService.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationRumForgeryFactory.kt
detekt.yml

In this PR we are introduce a new API : `ConfigurationBuilder.setVitalsUpdateFrequency(frequency)` where the frequency is an enum :
```
/** Every 100 milliseconds. */
FREQUENT(100L),
/** Every 500 milliseconds. This is the default frequency. */
AVERAGE(500L),
/** Every 1000 milliseconds. */
RARE(1000L),
/** No data will be sent for mobile vitals. */
NEVER(0)
```
This will allow the client to customise the update frequency for mobile vitals reader or disable this feature.

RUMM-2076 Add the Configuration#setVitalsMonitorUpdateFrequency API

---

build.gradle.kts
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConfigE2ETests.kt

Adding the nightly tests for newly introduce API : `ConfigurationBuilder#setVitalsUpdateFrequency`
Increasing the nightly tests coverage to 0.94

RUMM-2183 Nightly tests for ConfigurationBuilder#setVitalsUpdateFrequency

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/EventMeta.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/EventMetaTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileHandlerTest.kt
detekt.yml

This change aligns the binary format used to write data to the disk with format implemented in https://github.com/DataDog/dd-sdk-ios/pull/841.
For every event received we are going to write `meta` + `event` in the TLV (Type-Length-Value) format, where the format itself for each block (`meta` or `event`) has the following structure:
```
+-  2 bytes -+-   4 bytes  -+- n bytes  -|
|  block type | data size (n) |    data   |
+------------+---------------+-----------+
```
It is safe to merge it without cleaning existing data, because this PR targets SDK v2 branch, where the change later will be done to use SDK instance ID in the feature folder naming, so data in the SDK v2 read/write paths won't overlap with data from existing SDK (but during the current development existing data should be …

RUMM-2177: Use TLV format for data storage

---

dd-sdk-android-glide/README.md
dd-sdk-android-glide/apiSurface
dd-sdk-android-glide/src/main/kotlin/com/datadog/android/glide/DatadogGlideModule.kt
dd-sdk-android/README.md
dd-sdk-android/apiSurface
dd-sdk-android/src/main/java/com/datadog/opentracing/propagation/DatadogHttpCodec.java
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracedRequestListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutRumTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutTracesTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNonDdTracerNotSendingSpanTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNonDdTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNotSendingSpanTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt
detekt.yml
docs/trace_collection.md
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumResourceTrackingE2ETests.kt
instrumented/nightly-tests/src/main/AndroidManifest.xml
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingCustomAttributesActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingCustomSpanAttributesActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingNetworkInterceptorActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingTraceSamplingActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/server/LocalServer.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/picture/SampleGlideModule.kt

This change adds the trace sampling for auto-instrumented network requests (instrumentation via `TracingInterceptor`, `RumInterceptor` and `DatadogInterceptor`) by adding `x-datadog-sampling-priority` header to the outgoing requests which may have a value of `1` (keep) or `0` (drop). This header will later be parsed on the backend side and sampling decision will be respected for the services downstream.
Sampler will make a decision if request should be traced (by injecting tracing headers) or not. This will allow customer to control amount of traces created directly (via `TracingInterceptor`) or indirectly (via RUM2APM integration in case of `DatadogInterceptor` or `RumInterceptor`), which is necessary to align with a new billing model. Default trace sampling is set to 20%.
The sampling …

RUMM-2165: Add trace sampling for instrumented network requests

---

dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/MixedWebViewEventConsumer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/MixedWebViewEventConsumerTest.kt

Remove telemetry reporting for unknown web events, because Browser SDK can be way ahead of Android SDK.

Don't report telemetry for unknown web events

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/utils/Version.kt
buildSrc/src/test/kotlin/com/datadog/gradle/utils/VersionTest.kt

Prepare the release version name for artefacts without navigation components
See #941

RUMM-2229 Prepare release version 1.13.0-no-name

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/LoggingSyncListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/time/LoggingSyncListenerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt

This change does the following:
* Makes telemetry events use `dd-sdk-android` as a `service` name value.
* Removes telemetry from Kronos sync listener, because all the errors we get are not actionable and just add noise, and if there is any issue with NTP server or Kronos itself we will see it in the sample app anyway.

Telemetry adjustments

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/upload/UploadWorker.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt

WebView RUM and Logs data upload was missing in the `UploadWorker`. Not a big issue, because we also do upload using another way as well while SDK is active, but this change adds the missing part for the consistency.

RUMM-2261: Handle WebView RUM and Logs data in the background upload worker

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

This PR improves the way we track session, and ensure the logic follows the expectation from our billing guidelines
We separate the `RumSessionScope` into two classes: 
- `RumSessionScope` which manages the session lifecycle (extending the life of a session, renewing or reseting a session)
- `RumViewManagerScope` which handles the different views and creates Background/AppLaunch views when necessary

RUMM-2231 Fix the session management rules

---

docs/trace_collection.md
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/DataRepository.kt

This change fixes the usage of span scope in the RxJava chain.
Documentation of `ScopeManager#activate` [says that](https://github.com/opentracing/opentracing-java/blob/a8557d7c7a56210cbcf6bc518fe24b32923aa66f/opentracing-api/src/main/java/io/opentracing/ScopeManager.java#L59-L60) "It is a programming error to neglect to call {@link Scope#close()} on the returned instance.". So to comply with that code now stores `Scope` returned by `ScopeManager#activate` call and calls `Scope#close` when related span is finished.
Without doing that the scope is always alive and further scopes created will get it as a parent (and new spans will have finished span as a parent).
Also examples in the docs are updated: code example for Java is slightly different from Kotlin, because Java allows having only …

RUMM-2226: Fix handling of span scope in RxJava chain

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumActionType.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/GesturesListenerScrollSwipeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt

This change does the following:
* `back` interaction are reported as `BACK` now instead `CUSTOM`.
* Prevents sending empty target name. It _seems_ it happens because we may start scroll/swipe action with empty target name and without attributes, but `onUp` is not called, because screen is closed while finger is still touching the screen. To avoid that we will report `targetId` and `targetName` for the `startUserAction` as well, so that once it completes due to timeout, it has the necessary data.
Fixes #964.

RUMM-2322: Report back interaction as back type, prevent reporting empty target name

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/_InternalProxy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/_RumInternalProxy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/Telemetry.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/InternalProxyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumInternalProxyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/telemetry/TelemetryPlaygroundActivity.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt

This exposes some internal Datadog classes and methods for use by cross platform frameworks.
We expose internal methods through the _InternalProxy class, which is documented for internal use, and the `_internal` static member on the Datadog object. We keep Telemetry and RUM as separate proxies, in case we have to split them as v2 takes shape.
As part of exposing telemetry I also needed a way to report errors that are not Throwable, so I modified the event to replace the `throwable` member with `stack` and `kind`, and moved the creation of those strings farther up the chain (they were created on event write prior).
Please double check all my logic on the switch from `throwable` to `stack` and `kind` …

Expose Telemetry and addLongTask for internal use

---

docs/rum_getting_started.md

Small spacing nits.
Batch edit for Error Tracking.

Android and Android TV Monitoring Formatting Edit

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/generator/ClassDeserializerGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/generator/ClassGenerator.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/generator/MultiClassGenerator.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/TestDefinitions.kt
buildSrc/src/test/kotlin/com/example/model/Animal.kt
buildSrc/src/test/kotlin/com/example/model/Company.kt
buildSrc/src/test/kotlin/com/example/model/Household.kt
buildSrc/src/test/kotlin/com/example/model/Location.kt
buildSrc/src/test/resources/input/constant.json

Small fix in the PokoGenerator tool

---

dogfood.py

Having a line break in the json data seems to break the upload leading in a 400 error. Escaping the `\n` seems to fix the issue.

Fix dogfooding script

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/config/BaseExtensionConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/DetektConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/JUnitConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/JavadocConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/NightlyTestsCoveragConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/apisurface/ApiSurfacePlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/checklicenses/ThirdPartyLicensesPlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/gitclone/GitCloneDependenciesPlugin.kt
buildSrc/src/main/kotlin/com/datadog/gradle/plugin/transdeps/TransitiveDependenciesPlugin.kt
dd-sdk-android/generate_core_models.gradle.kts
dd-sdk-android/generate_log_models.gradle.kts
dd-sdk-android/generate_rum_models.gradle.kts
dd-sdk-android/generate_telemetry_models.gradle.kts
dd-sdk-android/generate_trace_models.gradle.kts

Inspired by the similar PR in the mobile app repository, which in turn was inspired by http://melix.github.io/blog/2022/05/gradle-laziness.html.
Replaces some tasks creation APIs with the lazy variant.

Use Gradle lazy API more

---

sample/kotlin/src/main/res/layout/fragment_home.xml

This change fixes a minor UI glitch on the Home screen of the sample app: `Jetpack Compose` button was overlaying `Picture Loading` button.

Fix buttons overlap in the sample app

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/rum/_common-schema.json
dd-sdk-android/src/main/json/rum/action-schema.json
dd-sdk-android/src/main/json/rum/view-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumEventExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ActionEventForgeryFactory.kt
detekt.yml

Add the `error_tap` frustration signal when a Tap action leads to one or more errors

RUMM-2349 Add frustration signal 'Error Tap'

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/DataOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/net/LogsOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/net/RumOkHttpUploaderV2Test.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/net/TracesOkHttpUploaderV2Test.kt
detekt.yml

Sanitize our intake request headers to be complient with the HTTP specification
Before OkHttp version `4.9.2` (cf [okhttp#6551](https://github.com/square/okhttp/pull/6551)), if a header value contains illegal characters (any non ASCII or Control character), the header would be printed as is in the logcat. This could potentially leak secrets (especially our customer's client token). 
This is not a critical issue since: 
- Client Tokens are generated by us and all match `/pub[0-9a-f]+/`, so they never have any invalid characters
- Only the invalid header is printed to the logcat, so even if another header was invalid, it would not print the client token
We are still sanitizing every header that might contain value that we do not control.
- if the client token would lead to an error, we …

RUMM-2377 Add checks on intake request headers

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/tracking/AndroidXFragmentLifecycleCallbacks.kt
detekt.yml
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/build.gradle.kts
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/full-snapshot-record-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/incremental-snapshot-record-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/text-style-schema.json
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/LongExt.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/SnapshotProducer.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ButtonWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/GenericWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ViewScreenshotWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ViewWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/WireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/ForgeExt.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/LongExtTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/SnapshotProducerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ButtonWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/GenericWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ViewScreenshotWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/NodeForgeryFactory.kt

This PR introduces the basic logic in our `SnapshotProducer` as a part of the `ScreenRecorder` component where we are actually going to capture the application screens and resolve them as `Node` tree equivalents. 
Please note that for now the `SnapshotProducer` is quite dummy and can only handle basic application screens mostly from our Android Sample App. The way we will work on this component is through multiple iterations by running it with different sample applications and improving the output.

RUMM-2356 Add session replay recorder basic logic

---

docs/configure_rum_android_sdk.md

https://github.com/DataDog/dd-sdk-android/pull/521 added sensible defaults to the RUM config, but docs were not updated. This PR fixes that.
Note: This PR is targeting `master` branch, because it is related to the functionality which was released a long time ago already. Once merged, it needs to be moved to `develop` as well.

Update statement about default view tracking strategy in the docs

---

README.md
docs/integrated_libraries_android.md

Surface the Jetpack Compose integration in the integrated libraries page and list of RUM integrations.
#support-rum Slack

DOCS-3982 Android Integrated Libraries Update

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/LogAttributes.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/LogGeneratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt

**THIS PR TARGETS 1.14.0 RELEASE BRANCH**
This change adds `variant` to `ddTags` of Logs events to be able to support stacktraces de-obfuscation in Logs dashboard.

RUMM-2448: Add variant tag to logs

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/SnapshotProcessor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/SessionReplayRumContext.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/utils/SessionReplayTimeProvider.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/SnapshotProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/ForgeExt.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/SnapshotProducerTest.kt

RUMM-2422 Process Session Replay touch and orientation change events

---

docs/configure_rum_android_sdk.md

Small Link Nit

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/StorageEvent.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEventExt.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ActionEventForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ViewEventForgeryFactory.kt

This change adds `view.frustration.count` data point, which is a total count of the all the frustrations happened in all the nested actions.
To support this I've changed `EventType` enum to the sealed class, so it is possible to send a payload on the data storage notification loopback.

RUMM-2353: Report frustration count on views

---

Dockerfile.gitlab
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-sdk-android-ndk/CMakeLists.txt
instrumented/nightly-tests/src/main/cpp/CMakeLists.txt
sample/kotlin/src/main/cpp/CMakeLists.txt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/crash/CrashFragment.kt

This change updates Cmake to `3.22.1` to address the previous rollback done in https://github.com/DataDog/dd-sdk-android/pull/716.

RUMM-2477: Update Cmake to 3.22.1

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ConfigurationRumAssert.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt

This allows users to replace the current UserAcitonTrackingStategy with a NoOpUserActionTrackingStrategy.
This is mostly for Flutter, since the initialization of the UserActionTrackingStrategy happens after the MainActivity is live, so the initial creation misses hooking into the Activity anyway, and subsequent attempts to listen to the Activity result in logcat spam, as there are no views that the tracking strategy can see.

Add configuration method to disable action tracking.

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/SDKCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/context/DatadogContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/ContextProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/DatadogContextProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/config/CoreFeatureTestConfiguration.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/DatadogContextForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/DatadogContextProviderTest.kt
detekt.yml

A small change allowing features to store their context in the SDK context. The actual usage and (maybe) subscription model for the changes will come later.

RUMM-2333: Features can store their context in SDK context

---

build.gradle.kts
dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationSessionReplayForgeryFactory.kt
detekt.yml
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayLifecycleCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/RecorderOnDrawListener.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/ScreenRecorder.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/SnapshotProducer.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/AllowAllWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/GenericWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/MaskAllTextWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/MaskAllWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayLifecycleCallbackTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/ScreenRecorderTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/SnapshotProducerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/AllowAllWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/MaskAllTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/MaskAllWireframeMapperTest.kt

RUMM-2423 Add the Sesion Replay MASK_ALL/ALLOW_ALL privacy strategies

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/ForgeExt.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ViewWireframeMapperTest.kt

In this PR we are fixing the collision problem when taking the screen snapshot as a tree of wireframes. We were currently using the following approach:
```return if(view.id!=View.NO_ID) view.id else view.hashCode``` to resolve the view unique identifier to be used in the equivalent mapped `Wireframe`. Following our tests we cannot rely on the `view.id` property as this is not unique in a view tree and it can actually be the same for more views in a tree creating collisions. 
Instead we are going to use the `View` reference address returned by the `View.hashCode` function. In addition to this in order to avoid problems in case subclasses of the `View` class override the `hashCode` class we will use the `System.identityHashCode` function which will always return the default value from the …

RUMM-2494 Use View hashcode as unique identifier for mapped Wireframe

---

build.gradle.kts
detekt.yml
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/MutationResolver.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/SnapshotProcessor.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/MutationResolverTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/SnapshotProcessorTest.kt

RUMM-2497 SnapshotProcessor - do not write anything if there was no mutation detected

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallback.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtils.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/lifecycle/ProcessLifecycleCallbackTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt

This PR adds a check to see if `WorkManager` is initialized before using it, because `WorkManager.getInstance` will throw `IllegalStateException` if `WorkManager` is not initialized and this add the noise to our telemetry.
Unfortunately, there is no `WorkManager#isInitialized` method yet (it will be added only in WorkManager 2.8, which is still in alpha), so had to write a hacky workaround.
Another option would be to check if we are in the main process before accessing `WorkManager`, but this won't work because:
* with `work-multiprocess` artifact execution/initialization of WorkManager may be shifted to any process
* User may do a custom initialization which happens after we are calling `WorkManager`.
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an …

RUMM-2492: Check if WorkManager is initialized before using it

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/BatchWriterListener.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/EventBatchWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/ContextProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/storage/ConsentAwareStorage.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFilePersistenceStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/RumDataWriterTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/storage/ConsentAwareStorageTest.kt
detekt.yml

This change does a switch to the `Storage` implementation written earlier. While it is not used as it should be in the feature configuration per SDK v2 plan, this change helps to minimize the diff of the transition and makes a proof that new component works.

RUMM-2504: Switch to the SDK v2 storage component

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/FeaturesContextResolver.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayRecordCallback.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayRumContextProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRecordPersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ActionEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ErrorEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/LongTaskEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ResourceEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/FeaturesContextResolverTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayRecordCallbackTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayRumContextProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt
detekt.yml
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/NoOpRecordCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/RecordCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayLifecycleCallback.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayLifecycleCallbackTest.kt

RUMM-2542 Send hasReplay property for RUM events

---

CHANGELOG.md

Merge release `1.14.1` into `develop`.

Merge release 1.14.1 into develop

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/MiscUtils.kt

I noticed a small issue in the related code: since `JsonArray` actually implements `Iterable`, `is JsonArray` branch will never be executed, because it goes after `is Iterable` branch.
By moving `is JsonArray` up we skip useless `toJsonArray` call which will create new object and copy elements there from the old object.

Minor performance optimization during serialization into JSON format

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/TracingFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracesFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/log/WebViewLogFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/log/WebViewLogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFilePersistenceStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutTracesTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNotSendingSpanTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/TracingFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/log/WebViewLogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFeatureTest.kt

`Storage` and `DataUploader` are pulled outside of the feature-specific classes, because `core` module will be responsible for those two.

RUMM-2563: Create storage and uploader outside of the feature

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/PersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/RumFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/domain/TracesFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/storage/ConsentAwareStorage.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/storage/Storage.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/log/WebViewLogFilePersistenceStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/rum/WebViewRumFilePersistenceStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFilePersistenceStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/storage/ConsentAwareStorageTest.kt

Remove the remaining usages of `DataReader` used in v1, because we are now using `Storage` for reading raw data and de-serialization is not needed anyway.

RUMM-2568: Remove DataReader v1 usages

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/Processor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/SnapshotProcessor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/RecorderOnDrawListener.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/SnapshotProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/RecorderOnDrawListenerTest.kt

This PR fixes the way we are handling the orientation change for Session Replay. Previously we were handling this in a separated flow which introduced a new state into the `SnapshotProcessor` causing problems regarding the `new view` detection and the order of the records. With this new approach we are handling the `OrientationChanged` event in the same stack used for handling the screen snapshot and by doing this we eliminate the potential issues resulting from introducing a new state for the `SnapshotProcessor`. …

RUMM-2562 Correct the way we handle orientation change events in SR

---

dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
detekt.yml

Prevent crashes from calling `peekBody` in DatadogInterceptor. Some implementations had some unchecked exceptions we missed. 
Fixes #1049

RUMM-2528 prevent crash on peekBody

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ButtonWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/TextViewWireframeMapperTest.kt

Sometimes the `TextView#typeface` property is `Null` and this was causing NPE when trying to resolve the `fontStyle` for the equivalent `TextWireframe`.

RUMM-2600 SR accept optional Typeface when resolving fontStyle

---

.gitlab-ci.yml

Use the Ktlint job from the shared pipeline (should be merged after the shared template update PR)

Migrate ktlint CI job to shared gitlab template

---

detekt.yml
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/MaskAllTextWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/StringObfuscator.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/MaskAllTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/StringObfuscatorTest.kt

We need to skip the new lines and spaces characters when applying the obfuscation on the text values to keep the aspect ratio of the replicated text view element in the Web Player.

RUMM-2651 SR - skip new lines and spaces when obfuscating texts

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/rum/_common-schema.json
dd-sdk-android/src/main/json/rum/_perf-metric-schema.json
dd-sdk-android/src/main/json/rum/action-schema.json
dd-sdk-android/src/main/json/rum/view-schema.json
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumPerformanceMetric.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/_RumInternalProxy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumInternalProxyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt

This creates an internal API for adding cross platform technical performance metrics (currently only Flutter Build Time, Flutter Raster Time and JS Refresh Rate). Each update is a single sample, which is aggregated via the same method as the Vitals aggregation, and posted to View events.
The Flutter and React Native SDKs will use this method to send in their performance metrics. The API was left open to potentially support sending different metrics in the future just by adding to the enum and serializing to the proper property on the View event.

Create internal API for sending technical performance metrics

---

.gitlab-ci.yml
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/utils/Version.kt
buildSrc/src/test/kotlin/com/datadog/gradle/utils/VersionTest.kt

Add 'SNAPSHOT' as a version tag, and default new versions to it. Change the build so that `develop` triggers all `publish` stages.
The cross platform frameworks would like to work from SNAPSHOTS in order to speed up development.

Publish SNAPSHOT builds to sonatype on pushes to develop

---

library/dd-sdk-android-session-replay/build.gradle.kts
library/dd-sdk-android-session-replay/src/main/AndroidManifest.xml

With AGP 7.3.0 `package` property in `AndroidManifest` is obsolete, `namespace` property in the AGP configuration should be used instead.
Since `AndroidManfest` is empty after the removal, it is deleted.

Move package from AndroidManifest to namespace plugin config property for Session Replay module

---

build.gradle.kts

It appears the nexusPublishing extension only evaluates whether a deployment goes to staging or not at the Project level, so we need to add the version at that level in order for snapshot builds to go through

Add version to top level project for nexusPublishing extension

---

detekt.yml
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/_common-wireframe-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/_common-wireframe-update-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/wireframe-clip-schema.json
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/MobileSegmentExt.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/MutationResolver.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/NodeFlattener.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/SnapshotProcessor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtils.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/Node.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/SnapshotProducer.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/ViewUtils.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ViewWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/MutationResolverTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/NodeFlattenerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/SnapshotProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtilsTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/ForgeExt.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/SnapshotProducerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/ViewUtilsTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/ForgeConfigurator.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/NodeForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/ShapeWireframeForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/ShapeWireframeMutationForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/TextWireframeForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/TextWireframeMutationForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/WireframeClipForgeryFactory.kt

In this PR we are introducing the capability of the SR recorder to add the clipping property to each `Wireframe` whenever it is outside of any of its parents bounds. The following updates where added:
- the `WireframeClip` optional property was added into the `Wireframe` and `WireframeUpdate` SR schemas
- SR recorder keeps track of all the parents when resolving an element in the tree to a `Node`
- when processing the tree of `Nodes` into a `List<Wireframe>` we keep track of the parents for each of the `Wireframe` and we are computing the `WireframeClip` property. This will solve also the issue when a `Wireframe` is rendered inside a `ScrollableList`
- when excluding the completely overlayed `Wireframe` we take into account also the `clipping` dimensions 
What inspired you to submit this …

RUMM-2496 SR Correctly handle clipped elements and scrollable lists

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/RecorderWindowCallback.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/RecorderWindowCallbackTest.kt

Before for each intercepted gesture in SR we were buffering all the gesture `MotionEvents` as `TouchData.Position` from the moment we received the `MotionEvent.ACTION_DOWN` until the moment we received the `MotionEvent.ACTION_UP`. 
If the gesture was long enough this approach could create some glitches in the player (if you have a fragments view pager the gesture could start playing after half of the new fragment became visible already). In order to avoid this we will flush the buffer every 160 ms, equivalent to 16 frames. This is a heuristically determined value and probably we will adjust it during dogfooding.
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an …

RUMM-2689 SR Flush buffered motion event positions periodically

---

dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/net/SessionReplayOkHttpUploader.kt

Fix source key in SR upload form

---

buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/GenerateJsonSchemaTask.kt

This change fixes the caching of `GenerateJsonSchemaTask` task. Before it was reading input files by calling `listFiles` for the given input dir, which will return only top-level files.
But it can be the case that top-level files are actually only the reference to the files deeper, like this:
```
{
"$schema": "http://json-schema.org/draft-07/schema",
"$id": "session-replay-mobile-schema.json",
"$ref": "session-replay/mobile/segment-schema.json"
}
```
It means that top-level file will receive no change when referenced file `session-replay/mobile/segment-schema.json` actually changes, making Gradle think that inputs didn't change and skipping models generation.
With this change we track all files recursively with Gradle, but take only top-level files for the model generation.

Fix caching of models generation task

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/RecorderOnDrawListener.kt

When replaying scrolling effects the 16ms delay was too big as it could indefinitely postpone a snapshot during a continuous scrolling. We are currently lowering that to 4ms and based on the tests everything looks fine. During dogfooding we might need to adjust this value again or maybe just remove it but for performance reasons we will keep it for now.

RUMM-2693 Increase the screen snapshot frequency

---

library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtilsTest.kt

Fix WireframeUtils flaky tests

---

.gitlab-ci.yml
dogfood.py

Removes all dogfooding steps that push new versions to the Flutter repo.
Flutter is now developing off source and will "pull" new versions when it deploys. This removes the Android step of "pushing" the new releases as that is no longer necessary

Remove Flutter from Dogfooding scripts

---

dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnableTest.kt

This change fixes flaky test by adding a bit more delay for the main thread, because otherwise it seems it can continue the execution before the ANR detection thread (which is sleeping for the same amount of time [here](https://github.com/DataDog/dd-sdk-android/blob/8ba3c1fea0df6b8651bcd6de9ece9daed5151e22/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/anr/ANRDetectorRunnable.kt#L56)).

Fix flaky ANR detection test

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

In this PR we are making sure that the Session recording is being stopped/resumed according with the RUM session state: tracked or not tracked.

RUMM-2685 Start/Stop Session recording based on the RUM session state

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt

It is possible that Kronos is accessed from tasks still running on executors (like from telemetry caught during some I/O operation) and it will lead to the `IllegalStateException`, like here:
```
11-04 04:04:42.160: E/AndroidRuntime(7085): Process: com.datadog.android.sdk.integration, PID: 7085
11-04 04:04:42.160: E/AndroidRuntime(7085): java.lang.IllegalStateException: Service already shutdown
11-04 04:04:42.160: E/AndroidRuntime(7085): 	at com.lyft.kronos.internal.ntp.SntpServiceImpl.ensureServiceIsRunning(SntpService.kt:142)
11-04 04:04:42.160: E/AndroidRuntime(7085): 	at com.lyft.kronos.internal.ntp.SntpServiceImpl.currentTime(SntpService.kt:98)
11-04 04:04:42.160: E/AndroidRuntime(7085): 	at com.lyft.kronos.internal.KronosClockImpl.getCurrentTime(KronosClockImpl.kt:19)
11-04 …
```

Shutdown Kronos clock only after executors

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/thread/LoggingScheduledThreadPoolExecutor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/thread/LoggingThreadPoolExecutor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/thread/ThreadExt.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/storage/ConsentAwareStorage.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/thread/AbstractLoggingExecutorServiceTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/thread/LoggingScheduledThreadPoolExecutorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/thread/LoggingThreadPoolExecutorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/storage/ConsentAwareStorageTest.kt
detekt.yml

Turns out we were swallowing uncaught exceptions raised during the execution of the tasks submitted via `Executor#execute`, `ExecutorService#submit` or `ScheduledExecutorService#schedule` calls, because the behavior is like the following:
* If uncaught exception is raised for task submitted via `Executor#execute`, then worker thread is killed and exception is printed to the console.
* If uncaught exception is raised for task submitted via `ExecutorService#submit` or `ScheduledExecutorService#schedule`, then worker thread is kept running and exception is thrown on the thread is which doing `Future#get` call (normally the thread getting the result). We were always ignoring the `Future` returned after the task is submitted, so we were swallowing such exceptions.
This change closes this gap …

RUMM-2684: Observe uncaught exception in executors

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTest.kt

Follow-up for #1118: now we have configuration telemetry event [sent with the delay](https://github.com/DataDog/dd-sdk-android/blob/b260f33d8355290d3606f8bab085786a4791d940/dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt#L418), which makes RUM instrumented tests flaky, because configuration telemetry event may or may not be in the intercepted RUM requests.
This changes filters out telemetry events from the list of RUM events against which the assertion will be done.

Filter out telemetry in the assertions of instrumented RUM tests

---

Dockerfile.gitlab
buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
dd-sdk-android-compose/src/main/kotlin/com/datadog/android/compose/Navigation.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/config/ApplicationContextTestConfiguration.kt
detekt.yml
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/utils/BundleExtensions.kt
sample/kotlin/src/main/cpp/datadog-native-sample-lib.cpp

This change adds support of Android 13 by doing the following:
* Build tooling and target API are now set to API 33.
* API changes are addressed.
* Docker image is updated to use build tooling for API 33.
Important points:
* `BaseBundle#get` type-agnostic call is deprecated, but there is no replacement. https://issuetracker.google.com/issues/243119654 is opened to track this (we are not alone here).
* NDK version was bumped to v25 (changelog is [here](https://developer.android.com/ndk/downloads/revision_history), it still supports KitKat, so it is fine to do the version bump)
* Legacy Cmake was removed from the docker image, because by some reason it is not shown in the list of the available packages for the latest version of `sdkmanager` for Linux (when I download latest `cmdline-tools` …

RUMM-2476: Target Android 13

---

instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/CrashService.kt

Fixes a compilation error after [migration to Android 13](https://github.com/DataDog/dd-sdk-android/pull/1130), where `Bundle#get` was deprecated.

Suppress the deprecation of Bundle#get in nightly test

---

dogfood.py

Follow-up for https://github.com/DataDog/dd-sdk-android/pull/1120: remove the usage of the function which was deleted. Otherwise it breaks all the dogfood updates with exception like this:
```
Traceback (most recent call last):
File "dogfood.py", line 160, in <module>
sys.exit(run_main())
File "dogfood.py", line 156, in run_main
return update_dependant(cli_args.version, cli_args.target, gh_token, cli_args.dry_run)
File "dogfood.py", line 135, in update_dependant
update_version_table(target, temp_dir_path, version)
NameError: name 'update_version_table' is not defined
```

Remove non-existent function in dogfood script

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/_InternalProxy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/RumEventMapperFactory.kt

This will allow cross platform SDKs to modify the configuration before sending it to telemetry.
The actual function on `Configuration.Builder` is internal, and exposed through the companion object on `_InternalTelemetry` to make it obvious this is meant as an internal mechanism.
Currently, this method is useless because none of the properties on `TelemetryConfigurationEvent` are mutable, but a PR is up modify the schema to fix that.

Add telemetry configuration mapper

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/CombinedLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/ConditionalLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/InternalLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/LogcatLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/logger/TelemetryLogHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/CombinedLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/InternalLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/TelemetryLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/MixedWebViewEventConsumerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/internal/rum/WebViewRumEventConsumerTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt

Add a logger method to log error information from strings.  This is needed for Flutter and React Native to pass their stack traces to the SDK for serialization.
I added a method to Logger (without adding any additional convenience methods, as Flutter and ReactNative likely won't use them anyway) as well as a new method to the LogHandler interface, which I propagated to all of the implementations.
Cross Platform frameworks needed a way to post errors / stack traces to logs, which we do using Strings.

Add a logger method to log error information from strings

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/Debouncer.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/RecorderOnDrawListener.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/DebouncerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/RecorderOnDrawListenerTest.kt

RUMM-2746 Sync SR touch and screen recorders

---

library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/DebouncerTest.kt

Fix flakiness in DebouncerTest class

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ViewWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/BaseTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/mapper/ViewWireframeMapperTest.kt

Previously we were resolving the `ShapeStyle` opacity from the `View.backround` which is not correct. For example a `TextView` can use a transparent background but still have a visible content. We need to resolve this attribute directly from the `View.alpha` property.

RUMM-2298 Correctly resolve ShapeStyle opacity in Wireframes

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/DefaultAndroidInfoProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/time/SessionReplayTimeProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/SdkCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/NoOpSdkCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorWithoutTracesTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/data/upload/UploadWorkerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/time/SessionReplayTimeProviderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNonDdTracerNotSendingSpanTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNonDdTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNotSendingSpanTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/DatadogEventBridgeTest.kt

This change does the following:
* Wraps OS/device info in `lazy`, because it shouldn't be changed during the app lifetime anyway. `PUBLICATION` mode is used for `lazy` which is using `compareAndSet` vs synchronisation by default (see docs for the difference), which should be a bit faster.
* `SdkCore` gets `time` property in order to avoid pulling the whole `DatadogContext` when only time piece is needed. I had to implement `NoOpSdkCore` by hand because of that, because no-op generation doesn't support properties and anyway if it would it cannot know what default value of `TimeInfo` to create.
* Usage of `CoreFeature` is completely removed from the `SessionReplay` feature.
- [ ] Make sure each commit …

RUMM-2753: Improve SDK performance a bit

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/InternalLogger.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/SdkInternalLogger.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/SdkInternalLoggerTest.kt

Simple implementation of `InternalLogger` interface which forwards logs according to the target specified.
Task RUMM-2764 created to start using it in the codebase, not a part of SDK v2 goals.

RUMM-2754: Create implementation of InternalLogger

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/RuntimeUtils.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/RuntimeUtilsTest.kt

`devLogger` wasn't really working because `sdkCore` was always `null` for it. This PR fixes this issue.

Fix devLogger

---

library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/MutationResolverTest.kt

RUMM-2765 Fix unit tests flakiness in MutationResolverTest

---

LICENSE-3rdparty.csv
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/data/upload/DataFlusher.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/storage/FileEventBatchWriter.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/data/upload/DataFlusherTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/storage/FileEventBatchWriterTest.kt
gradle/libs.versions.toml
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingCustomSpanAttributesActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ResourceTrackingNetworkInterceptorActivity.kt

Some improvements for the nightly tests run:
* Don't attempt to read metadata if meta file doesn't exist (doesn't impact the functionality, just removes some error noise).
* Update Android X test libraries for the better compatibility with API 33.
* Replace [source.unsplash.com](source.unsplash.com) with [picsum.photos](picsum.photos), because the former is not reliable anymore (it was deprecated one year ago and is currently down for few days already).

Nightly tests improvements

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/NoOpWindowCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/ScreenRecorder.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/ScreenRecorderTest.kt

RUMM-2769 Fix NPE in ScreenRecorder when wrapping a null window.callback

---

dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/PlainBatchFileReaderWriterTest.kt

This change fixes flaky test - it was allowing to generate the value of block type which is perfectly correct instead of incorrect.

Fix flaky TLV format reader test

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/Logger.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/LoggerTest.kt

We need to make a copy of `tags`, because by the time we create `LogEvent` (on the worker thread) it may have been changed by another thread.

Make a local copy of tags before creating LogEvent

---

dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
detekt.yml

This changes makes Java crash reporting use message bus to forward crash to RUM (as RUM error).

RUMM-2787: Use message bus to report Java crashes to RUM

---

dd-sdk-android/src/main/json/telemetry/configuration-schema.json

Update telemetry configuration schema.
This allows cross-platform SDKs to update more fields in the configuration.

Update telemetry configuration schema

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/info/NetworkInfoDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/Deserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/JsonObjectDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/user/UserInfoDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/DatadogExceptionHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashEventHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/ndk/NdkCrashEventHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/JsonObjectDeserializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventDeserializerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashEventHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/ndk/DatadogNdkCrashHandlerTest.kt
detekt.yml

This PR changes the way NDK crashes are reported to RUM: now they will be sent through the message bus, because RUM feature may be optional and will reside in another module anyway.
Also there are now 2 different message types for the crashes coming to Logs and RUM: `jvm_crash` and `ndk_crash`. This way the code is simpler and is easier to test.
`DatadogNdkCrashHandler` now reads last view event as JSON (because RUM-specific deserializers won't be available), takes view ID, session ID and application ID from it and passes it to the RUM feature where further deserialization from `JsonObject` to the RUM-specific type is done. …

RUMM-2789: Use message bus to report NDK crashes to RUM

---

dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/data/upload/DataUploadRunnable.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/data/upload/DataUploadRunnableTest.kt

This change improves lock handling scenario in the batch upload. Before, if any exception would happen during the batch upload if `Storage#readNextBatch` is async (which is not the case right now), lock would be removed only after timeout. Now lock is removed immediately. 
This is mostly a safeguard if at any point `Storage#readNextBatch` becomes async, but we probably need to revert the switch to async-like API in the upload pipeline back to the blocking API, because async one doesn't really bring any benefit and actually makes code more complex.

Improve batch upload wait timeout handling

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/context/DatadogContext.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/DatadogContextProvider.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/NoOpContextProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/DatadogContextForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/DatadogContextProviderTest.kt

`site` property is not used neither in the write, nor in the upload flows by the features, so removing it from `DatadogContext`. Also it is not possible to have it when custom URLs are used anyway.

RUMM-2755: Remove site property from DatadogContext

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt

It is possible to have a crash like this:
```
java.lang.IllegalStateException: Service already shutdown
at com.lyft.kronos.internal.ntp.SntpServiceImpl.ensureServiceIsRunning(SntpService.kt:142)
at com.lyft.kronos.internal.ntp.SntpServiceImpl.currentTime(SntpService.kt:98)
at com.lyft.kronos.internal.KronosClockImpl.getCurrentTime(KronosClockImpl.kt:19)
at com.lyft.kronos.KronosClock$DefaultImpls.getCurrentTimeMs(Clock.kt:39)
at com.lyft.kronos.internal.KronosClockImpl.getCurrentTimeMs(KronosClockImpl.kt:8)
at com.datadog.android.core.internal.time.KronosTimeProvider.getServerOffsetMillis(KronosTimeProvider.kt:25)
at com.datadog.android.telemetry.internal.TelemetryEventHandler.handleEvent(TelemetryEventHandler.kt:48)
at com.datadog.android.rum.internal.monitor.DatadogRumMonitor.handleEvent …
```

Fix possible crash during the telemetry processing

---

library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/common/pointer-interaction-data-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/common/pointer-interaction-schema.json
library/dd-sdk-android-session-replay/src/main/json/schemas/session-replay/mobile/incremental-data-schema.json
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayLifecycleCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/Processor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/RecordedDataProcessor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/RecorderOnDrawListener.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/RecorderWindowCallback.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/RecordedDataProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/RecorderOnDrawListenerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/RecorderWindowCallbackTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/ForgeConfigurator.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/PointerInteractionDataForgeryFactory.kt

As a follow up task on the approved [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/2717813560/RFC+2022-11-16+-+Multi+touch+support+in+the+renderer) we will be sending each touch event as a single `PointerInteractionData` in a `MobileIncrementalSnapshotRecord`. This will allow the player to treat the `touch events` related records as any other record and not have to do extra operations to flatten the `TouchData#positions` in multiple records as before.

RUMM-2783 Provide SR touch data following the new proposed format

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Fixes #1178. When processing fatal error `rootScope` should be synchronized as well, as for the normal flow.
Otherwise 2 threads may enter `RumScope` simultaneously, leading to the different bugs like `ConcurrentModificationException`.

RUMM-2780: Synchronize access to DatadogRumMonitor#rootScope when processing fatal error

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProviderTest.kt

This change fixes a flaky failure:
```
BroadcastReceiverSystemInfoProviderTest > M read system info W register() {Lollipop}(BatteryStatus, int, int, boolean) > com.datadog.android.core.internal.system.BroadcastReceiverSystemInfoProviderTest.M read system info W register() {Lollipop}(BatteryStatus, int, int, boolean)[6] FAILED
java.lang.AssertionError at BroadcastReceiverSystemInfoProviderTest.kt:153
```
It happens because of the `Float` to `Int` conversion in the following operations:
```
> in code (level * 100) / scale
> in test (level * scale) / 100
```
Since this conversion simply truncates the floating part we may end up loosing too much precision for the final comparison. This change instead of the truncation of the decimal part does a proper rounding.
- [ ] Make sure you discussed …

Fix flaky BroadcastReceiverSystemInfoProvider test

---

dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt

This changes fixes flaky `TelemetryEventHandlerTest#𝕄 count the limit only after the sampling 𝕎 handleEvent(SendTelemetry)` test.

Fix flaky telemetry test

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtils.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtilsTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/ForgeConfigurator.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/ShapeStyleForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/ShapeWireframeForgeryFactory.kt

Before we were filtering out all the overlayed wireframes no matter if the top ones were having a solid background or not. This creates a problem because if the removed wireframe is actual the one that gives the main background in a View we will be loosing the contrast in the replay and will make some elements invisible (e.g. texts).
In order to fix this we are now only considering as valid overlays the wireframes that also have a solid backround.

RUMM-2806 Drop the covered wireframes only if top ones have a background

---

.gitlab-ci.yml

Bump the pipeline dependency (cf [dd-source#21171](https://github.com/DataDog/dd-source/pull/21171) )

MTG-8 use latest version of shared pipeline

---

.github/workflows/codeql-analysis.yml
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/ext/ReceiverExt.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/InvalidStringFormat.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/ThreadSafety.kt
tools/detekt/src/main/kotlin/com/datadog/tools/detekt/rules/UnsafeThirdPartyFunctionCall.kt

Commit made on top of #1203 to fix compile issues
The custom detekt rules we have was using soon to be deprecated APIs in Kotlin, which made the build fail
It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code

Enable CodeQL analysis

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogInterceptor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumResourceKind.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/resource/RumResourceInputStream.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sqlite/DatadogDatabaseErrorHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/TracingInterceptor.kt

Small change to remove companion objects with only non-public members from the public API. Otherwise empty `Companion` class may be hanging in the suggestions list on the user side.

Remove Companion objects with non-public member from Public API

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
docs/mobile_data_collected.md

Fixes #854
Fixes #1116
Uses the `createDeviceProtectedStorageContext` to ensure Kronos works in all edge cases. 
Note that the safe context should only be used for Kronos.

RUMM-2038 Use safe context for directBootAware host apps

---

library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtilsTest.kt

This change fixes flaky `M return false W checkIsValidWireframe(){ covered by another with solid background }` test.
Test was failing because there was a possibility to generate wireframe without background color, so it has `isOpaque == false`.

Fix flaky WireframeUtils test

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/handlers/AndroidSpanLogsHandlerTest.kt

This change removes direct dependency between `AndroidSpanLogsHandler` and `Logger` to allow sending logs for the particular span (via `Span.log` API) using message bus.

RUMM-2828: Send logs for Span using message bus

---

dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/DatadogContextProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/internal/DatadogContextProviderTest.kt

This change fixes a possible concurrency issue, when feature context can be modified by another thread while it is read by the caller. To solve this we are going to make a snapshot for the top 2 levels (features and feature-specific keys), this should be enough to get completely immutable map for cases of storage for our features (they are storing only strings, which are immutable, and no deeper than 2 levels).

Provide frozen snapshot of features context when requested

---

sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

Currently properties of `SampleApplication` are initialized before `onCreate` method completes, and since `DatadogInterceptor`/`TracingInterceptor` resolve global first party host detector at the construction time, it is not available at this moment (because Datadog SDK is not yet initialized), so not resource tracing is available.
This change fixes it by switching to the lazy initialization.

Use lazy initialization of network-related properties in SampleApplication to be able to pick global first party hosts

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/DatadogLogGenerator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/tracing/AndroidTracer.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/FeatureScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/domain/DatadogLogGeneratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/logger/DatadogLogHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/internal/AndroidTracerTest.kt

This change makes tracing feature to store its context (active span) in the common context storage.
The tricky part is that active span (span backed by the current active scope) is thread-local, so each thread may have its own active span. To support such thread-local storage I'm using `addScopeListener` API to associate the active context with the particular thread and then later to read it from `DatadogContext` for the particular thread as well (reminder: `DatadogContext` is created on the caller thread). 

RUMM-2834: Tracing feature stores context in the common context storage

---

.github/workflows/codeql-analysis.yml

Gradle build for the CodeQL scan take 35-40 minutes it seems, because all the variants ((`eu1`, `us1`, `us3`, `us5`, `us1_fed`, `staging`) x (`debug`,`release`) = 12) are built (it takes majority of the build).
~~To speed it up and still have a complete coverage of all the binaries which can be created in the customer environment (not only release artifacts, but also binaries which can be created by cloning this repo), let's build only `us1` flavor for sample app, because all DC flavors are the same code-wise.~~
To speed it up we are going to build only releasable modules.

RUMM-2845: Speed up build of sample app for CodeQL scan

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt

This change applies extra sampling rate (20%) to the configuration telemetry events on top of the telemetry sampling rate configured.

RUMM-2868: Apply extra sampling rate to the configuration telemetry

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtils.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/WireframeUtilsTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/utils/ShapeStyleForgeryFactory.kt

We were using assuming that the Wireframe `backgroundColor` will always be reported in capital letters when checking for its opacity. This was buggy and in this PR we are fixing this by using a case insensitive `RegEx` instead.

SR use case insensitive when checking wireframe background color opacity

---

docs/trace_collection.md

Fixes ordered list numbering
maintenance
docs only change

Fix numbering in Android tracing instructions markdown

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

- Makes sure a view update is sent when a cross-platform crash is detected
- Do not send the native crash if there already was a crash
Remove duplicated errors for JS crashes in React Native.
I'm not sure why we had 2 different behaviours in the first place depending on whether the crash was cross-platform or native: https://github.com/DataDog/dd-sdk-android/pull/764

RUMM-2516: Remove cross platform duplicates crashes

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/FeaturesContextResolver.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayRecordCallback.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/FeaturesContextResolverTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayRecordCallbackTest.kt
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/NoOpRecordCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/RecordCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayLifecycleCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/processor/RecordedDataProcessor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/recorder/ScreenRecorder.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/processor/RecordedDataProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/recorder/ScreenRecorderTest.kt

We were adding the has_replay:true property on the RUM events whenever the SR is recording no matter if the view in progress produced any records or not. Following the latest discussions we needed to fix this and set this property to true only if there was at least one SR record sent for this event.
There is still a corner case for which this flag can have wrong values due to the async way of intercommunication between our features but this was explained in the PR comments and for now we are accepting this as a non blocker issue.

RUMM-2898 Add hasReplay=true only when the view produced SR records

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt

Fixes #1067 
This PR prevents reporting false positive ANRs when the application is in background. 
In some cases (#1067) the host application is in background and the SDK detekts multiple SDKs that are not actually perceived by the end user.

RUMM-2931 prevent reporting ANR when app is in background

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/error/internal/CrashReportsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/api/SdkCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/NoOpSdkCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/CrashReportsFeatureTest.kt

This PR adds `SdkCore#registerFeature(Feature)` method, which takes `Feature` interface. This method is supposed to be called from outside of `DatadogCore`, but for now it is called from `initialize`.
`SdkFeature` as internal class wraps `Feature` and creates storage/uploader only if needed (only if `StorageBackedFeature` interface is implemented).
Maybe some things will change things later internally, but from the public perspective this method is here to stay.

RUMM-2918: Add registerFeature method

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallback.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/vitals/VitalFrameCallbackTest.kt

Cherry-pick fix made in https://github.com/DataDog/dd-sdk-android/pull/1251 into the 1.17.0 release.

Cherry-pick: RUMM-2903 detect device's refresh rate from vital monitor

---

dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/LogsFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/log/internal/net/LogsRequestFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/log/internal/LogsFeatureBuilderTest.kt

This change creates `LogsFeature.Builder` class which allow to make a configuration of the `LogsFeature` to be created. It will replace `Configuration.Feature.Logs` usage (in the next PRs).

RUMM-2927: Logs feature configuration is extracted into dedicated class

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/NodeFlattener.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/Node.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducer.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ButtonWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/GenericWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ViewScreenshotWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ViewWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/WireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/NodeForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/NodeFlattenerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/SnapshotProducerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/AllowAllWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ButtonWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllTextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextViewWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ViewScreenshotWireframeMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ViewWireframeMapperTest.kt

Currently our `ViewToWireframe` mappers resolve a `View` as a single `Wireframe` . Following the RFC for recording/representing input elements we will need to add the capability to our mappers to resolve a `View` as a collection of `Wireframe`.

RUMM-2998 Add view to multiple wireframes mapper capability

---

dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogInterceptorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNonDdTracerNotSendingSpanTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNonDdTracerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/tracing/TracingInterceptorNotSendingSpanTest.kt

We used to require all urls to be fully lowercase in our tests assertions, as case sensitivity used to make the tests fail. 
After investigation, we noticed that OKHttp automatically standardize the host name to be all lowercasen because the host name [by definition (RFC-4343)](https://www.rfc-editor.org/rfc/rfc4343#section-3). 
> According to the original DNS design decision, comparisons on name lookup for DNS queries should be case insensitive.
This PR updates our test to follow closely this principle and OkHttp behavior, by forging random URLs with a lowercase hostname, and a path that is still case sensitive.

RUMM-2900 make tests more accurate with url case sensitivity

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEndpoint.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogSite.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogSiteTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
sample/kotlin/build.gradle.kts

Adds support to the AP1 (Japan) datacenter
We also use subdomainless endpoints, which are not necessary since API v2 where the track is part of the path.

RUMM-2864 add support to AP1

---

dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt

This minor change remove unused `crashReportsFeature` property.

Remove unused property

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt

I hope this should fix some flakiness in tests, related to the fact that during `CoreFeature` initialization Kronos can do background sync without a special flag set, and this background sync can call `internalLogger` which can be a mock at the time, adding unwanted interactions.

Disable Kronos background sync in the CoreFeature unit test

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/CoreFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/utils/WorkManagerUtilsTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/error/internal/DatadogExceptionHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/config/CoreFeatureTestConfiguration.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt

Another attempt to fix flaky tests - we will disable Kronos sync for all the tests which are instantiating `CoreFeature` under the hood (which are calling `Datadog.initialize` or create `DatadogCore` instances).

Disable Kronos sync for all unit-tests impacted

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapperTest.kt

There was a bug in the `RumEventMapper` because for the `ViewEvent` we were comparing the original object with the mapped one by value and not by reference as required.

RUMM-3041 The RumEventMapper checks ViewEvents by reference

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/DatadogEventBridge.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/webview/DatadogEventBridgeTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/webview/WebViewTrackingE2ETests.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/WebViewTrackingActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/WebViewTrackingBridgeHostsActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/webview/WebFragment.kt

This change makes `DatadogEventBridge` to require SDK instance explicitly via its public API. This is needed in order to avoid having a dependency on `DatadogCore` class, which won't be available after the WebView-related code extraction into the dedicated module.

RUMM-3060: Associate DatadogEventBridge with the particular SDK instance

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifier.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/net/RequestUniqueIdentifierTest.kt

Fixes #1282. This PR removes `okhttp3.internal` package usage, we were using `okhttp3.internal.Util.EMPTY_REQUEST`.
There is a [warning](https://square.github.io/okhttp/changelogs/upgrading_to_okhttp_4/#internal-api-changes) about `okhttp3.internal` package usage for OkHttp 4.x, but with OkHttp 4.x this usage didn't cause any problems - the class and field were still there.
However, it seems things are finally moved for OkHttp 5.x (which is in alpha for now, changelog is [here](https://square.github.io/okhttp/changelogs/changelog/)), so to be on the safe side we are getting rid of reference to `okhttp3.internal`. …

RUMM-3051: Remove okhttp3.internal package usage

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/_InternalProxy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/webview/internal/WebViewEventConsumer.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/InternalProxyTest.kt

Adds internal function to consume web view events for cross-platform SDKs

Implement webview proxy for cross platform

---

build.gradle.kts
dd-sdk-android/apiSurface
instrumentation-tools/src/constants.py
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanConfigE2ETests.kt
library/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/LogsFeature.kt
library/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/internal/net/LogsRequestFactory.kt
library/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/LogsFeatureBuilderTest.kt
library/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/LogsFeatureTest.kt
library/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/internal/net/LogsRequestFactoryTest.kt

Since WebView Logs doesn't use `LogsRequestFactory` explicitly now, we can move this class to the Logs module and make it internal.
Also this PR updates coverage for nightly tests.

Move LogsRequestFactory into Logs module, update coverage for nightly tests

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckBoxMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableCompoundButtonMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableTextViewMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckableWireframeMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/CheckedTextViewMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllCheckBoxMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllCheckedTextViewMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/MaskAllRadioButtonMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/RadioButtonMapper.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ViewWireframeMapper.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseCheckBoxMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseCheckedTextViewMapperTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseRadioButtonMapperTest.kt

We needed to refactor and clean a bit the `WireframeMapper` architecture to make it more scalable for future implementations.
We will now have an abstract `CheckableWireframeMapper` which can be extended by any `Mapper` that maps a `View` with a checked state.
Further on we introduced the `CheckableTextViewMapper` which extends the `CheckableWireframeMapper` and offers a simple implementation of a checkable `TextView`. This is extended by the `CheckedTextViewMapper` and the `CheckableCompoundButtonMapper`. Later on we will introduce the `SwitchViewMapper` which will extend the `CheckableWireframeMapper` and will offer a different representation of the `checkable` widget by using a list of `ShapeWireframe`.
Anything else we should know when …

RUMM-1391 Refactor the SR ViewMapper implementations

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/FragmentViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt

This change removes explicit reference to RUM feature from `DatadogCore` by switching to the `FeatureScope#unwrap` usage.

RUMM-3080: Remove explicit reference to RUM feature from DatadogCore

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/InternalSdkCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/RumMonitorBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumApplicationScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumContinuousActionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumResourceScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt

This change removes references to `CoreFeature` (which will stay as internal) from the `RumMonitor` and `DatadogRumMonitor` (meaning from `RumViewScope`, `RumActionScope`, etc.).
This is mostly achieved by the properties of `SdkCore`. But for the action/resource scopes we need to know the network info at the scope start, and since I don't think we should expose `networkInfo` in the `SdkCore` (quite specific property), it is exposed in the `AdvancedSdkCore` instead. Later however, we may promote this property to the `SdkCore`.
Expecting SDK instance to implement `AdvancedSdkCore` is not an issue, because it is not created outside anyway and managed by us.
Also `RumFeature.Builder` now requires `applicationId` explicitly, this will allow later to remove `rumApplicationId` from `Credentials` …

RUMM-3082: Remove CoreFeature usage from RumMonitor/DatadogRumMonitor

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/assertj/ViewEventAssert.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

When a view has a short lifespan (less than one second), the estimation of ticks per seconds can go through the roof.
We limit the computation of ticks per second to views spanning longer than 1 seconds to avoid erroneous values

RUMM-3081 prevent reporting invalid cpu ticks per seconds 

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/_InternalProxy.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/SdkInternalLogger.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/InternalProxyTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/instrumentation/gestures/WindowCallbackWrapperTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/SdkInternalLoggerTest.kt

Since telemetry is depending on the RUM feature, which will move to its own module and is not guaranteed to be enabled, this change switches to the usage of message bus to send telemetry to RUM.
**NOTE**: This doesn't touch configuration telemetry, this one will be handled later.

RUMM-3085: Remove explicit references to the telemetry from core module

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/AdvancedRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryCoreConfiguration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/RumFeatureTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryCoreConfigurationTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/telemetry/internal/TelemetryEventHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/TelemetryCoreConfigurationForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt

RUM is going to be extracted into the dedicated module, so we cannot use `GlobalRum` from the core.
This change makes the use of message bus in order to submit configuration to the telemetry and also reads RUM-related configuration from `RumFeature.Configuration` now instead of `Configuration.Feature.RUM`.

RUMM-3089: Use message bus to report configuration telemetry from the core

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/RumFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/configuration/ConfigurationBuilderTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/ConfigurationRumForgeryFactory.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreInitializationTest.kt

Add a property that can be supplied through additionalConfiguration which sets the extra sample rate for configuration telemetry. This serves as a way for the cross platform SDKs to modify whether telemetry gets sent in order to test our own telemetry logic.

Add internal telemetry configuration sampling rate

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ActivityTrackingTest.kt

Fix the timing of ApplicaitonLaunch vie and application_start events. The events were incorrectly using the nano time for their timestamp instead of using an ms timestamp. We use the difference between the triggering event's timestamp and nano time to determine how far apart they are, and add that to the application start time.

Fix timing of ApplicationLaunch view and application_start events

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProvider.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/system/BroadcastReceiverSystemInfoProviderTest.kt

On some devices (e.g. Fire TV on OS 7.6.2.4), the `BatteryManager.EXTRA_PLUGGED` returns `0`, when the device is clearly plugged. Because we only upload tracked data when the device as enough power (battery > 10% or device is plugged), the device doesn't upload anything on those devices. 
The fix relies on the `BatteryManager.EXTRA_PRESENT` that tells if a battery is present on the device. We can then assume that if the battery is not present, and the device is alive running the app, that it has another power source.

RUMM-3094 fix unreliable plugged battery info

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ActivityTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/FragmentTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/RumTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/telemetry/TelemetryTest.kt

This attempts to remove flakeyness from our integration tests by fixing 3 major issues:
1. The TelemetryTest was expecting a very specific set of telemetry in a very specific order. There is a new piece of telemetry that is getting sent on Activity launch that can be sent anywhere in that order. The new test checks that all expected telemetry is there, but ignores any extra telemetry.
2. Activity and Fragment tests could attempt to capture RUM context while other events were processing, giving them either an incorrect View ID during the capture or "null". Add a (private) method that waits for the RUM queue to process events before continuing to capture the RUM context
3. The ApplicationLaunchView does not stop until the `application_start` action is sent, which is highly dependent on how …

Stabilize integration tests

---

dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt

Flutter sends the telemetry configuration sample rate as a Double, not a Float. Use Number instead.

Fix telemetry sampling internal configuration for Flutter

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/telemetry/configuration-schema.json
dd-sdk-android/src/test/kotlin/com/datadog/android/utils/forge/TelemetryConfigurationEventForgeryFactory.kt

Update the RUM Telemetry event schema to the latest version.
This was mostly wanted for the new React Version and Dart Version fields, but it looks like some other properties may have been changed / added recently.

Update RUM Telemetry event schema to latest

---

instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/rum/ResourceTrackingTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/security/EncryptionTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/rules/MockServerActivityTestRule.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/utils/ExtraIntentExtensions.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/log/ActivityLifecycleLogs.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/telemetry/TelemetryPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/trace/ActivityLifecycleTrace.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/utils/IntentExtensions.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/crash/JvmCrashHandlerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/crash/NdkCrashHandlerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/GdprLogsE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/GdprRumE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/GlobalRumE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorBackgroundE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumMonitorE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumResourceTrackingE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumUserInteractionTrackingE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumViewTrackingE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/GdprSpanE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/webview/WebViewTrackingE2ETests.kt

Features can be registered at any time (using `Datadog#registerFeature` API) and to check that any order works, we are adding some randomization to the order they are registered.
So far it only makes features be registered before Logger/Tracer/RUM monitor are registered.

Randomize SDK initialization sequence (feature-wise) for instrumented tests

---

dd-sdk-android/src/main/kotlin/com/datadog/android/ndk/DatadogNdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/ndk/NdkCrashHandler.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/DatadogCore.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/net/DataUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/ndk/DatadogNdkCrashHandlerTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/v2/core/DatadogCoreTest.kt

This update brings back NDK crash submission, which was not working during the dynamic nature of feature registration.
Now we will check what is the feature registered via `registerFeature` call, and if it is RUM or Logs, then we will proceed with the crash data submission to the relevant channel.
Also this PR makes a bit of change in the data preparation flow - now deserialization happens at the `prepareData` call (it was handled only in `handleNdkCrash` before), which should be fine, because deserializers are simple and everything needed should be ready by the time deserialization is performed.
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) …

RUMM-2995: Handle NDK crashes considering the dynamic feature registration

---

.gitlab-ci.yml

Update the static analysis dependency to us the shared woke step

MTG-13 update static analysis dependency

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt

Removes a piece of telemetry we're seeing a lot of at the moment.

Remove extra telemetry sent when detecting refresh rate scale

---

dd-sdk-android-glide/build.gradle.kts

This PR removes the reference both to Glide compiler and KAPT from Glide module, because they are not needed - this module doesn't use `GlideModule` or `GlideExtension` annotations, they are used in the sample app directly only.

Remove redundant Glide compiler reference from Glide module

---

library/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/GlobalRum.kt
library/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/GlobalRumTest.kt

Small change that removes the usage of `InternalLogger.UNBOUND` in `GlobalRum` class.

Use SDK-bound internal logger in GlobalRum

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/CoreFeature.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileMigrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/advanced/FeatureFileOrchestrator.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/time/NoOpKronosClock.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/ndk/NdkNetworkInfoDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/ndk/NdkUserInfoDataWriter.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/net/DataOkHttpUploader.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileMigratorTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/advanced/ConsentAwareFileOrchestratorTest.kt

Prevent any recurring I/O operation that could happen on the main thread.
I/O operations no the main thread can be costly and block the UI, making the host app laggy. 
A couple of I/O operation can still occur during the initialization of the SDK. They are very short and don't impact the app's performance whatsoever.

RUMM-1503 handle  strict mode I/O operations

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewManagerScopeTest.kt

Stopping a session leaves the session in the list of child scopes until the session is done with all of its work (Resources and user actions are stopped).  If a StartView event happens while that session is stopped but still processing events, it was incorrectly being created in the stopped ViewManagerScope.
I double checked Resources and Actions in the ViewScope and those should be safe, as they are only created if the view is active (and stopping the session stops the active view)

Fix stopped RUMViewManager from being able to start new views.

---

dd-sdk-android/apiSurface
dd-sdk-android/src/main/json/rum/_common-schema.json
dd-sdk-android/src/main/json/rum/view-schema.json

Update the event schema to only post session.is_active on View events.

Update RUM Event Schema

---

dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/SdkCoreRegistry.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/DatadogTest.kt

Remove the usage of the Client token in the instance id. This allows an application to rotate their token and still send previous data.

RUMM-2986 update sdk instance id hash to use only instance name and datacenter

---

library/dd-sdk-android-session-replay-material/src/main/kotlin/com/datadog/android/sessionreplay/material/MaterialExtensionSupport.kt
library/dd-sdk-android-session-replay-material/src/test/kotlin/com/datadog/android/sessionreplay/material/MaterialExtensionSupportTest.kt

REPLAY-1612 Use default TabWireframeMapper for MASK_USER_INPUT privacy option

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

Introduces the SdkInit event at the initialization of RumMonitor in order to make sure a session is started before the first RUM interaction. 
This makes it so that logs and traces are correctly correlated to a valid session if they occur before the first view or action takes place.

Force new session at sdk initialization

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
buildSrc/src/main/kotlin/com/datadog/gradle/config/KotlinConfig.kt
dd-sdk-android-coil/build.gradle.kts
dd-sdk-android-compose/build.gradle.kts
dd-sdk-android-fresco/build.gradle.kts
dd-sdk-android-glide/build.gradle.kts
dd-sdk-android-ktx/build.gradle.kts
dd-sdk-android-ndk/build.gradle.kts
dd-sdk-android-rx/build.gradle.kts
dd-sdk-android-sqldelight/build.gradle.kts
dd-sdk-android-timber/build.gradle.kts
dd-sdk-android-tv/build.gradle.kts
dd-sdk-android/build.gradle.kts
instrumented/integration/build.gradle.kts
instrumented/nightly-tests/build.gradle.kts
library/dd-sdk-android-session-replay/build.gradle.kts
sample/kotlin/build.gradle.kts
tools/unit/build.gradle.kts

Rolling back some changes done in https://github.com/DataDog/dd-sdk-android/pull/1406: we need to keep bytecode produced at the Java 11 level, because `aar` files are distributed non-dexed (meaning they carry simple `.class` jvm files), so old AGP versions may be not able to handle bytecode produced by Java 17.

RUMM-3250: Keep bytecode produced compatible with Java 11

---

gradle.properties

As a result of changes being made in https://github.com/DataDog/dd-sdk-android/pull/1406, Bitrise is now using Java 17, so need to remove unsupported JVM option.

Remove MaxPermSize JVM option for the compatibility with Java 17

---

dd-sdk-android-glide/apiSurface
dd-sdk-android-glide/src/main/kotlin/com/datadog/android/glide/DatadogGlideModule.kt
dd-sdk-android-glide/src/main/kotlin/com/datadog/android/glide/DatadogRUMUncaughtThrowableStrategy.kt
dd-sdk-android-glide/src/test/kotlin/com/datadog/android/glide/DatadogGlideModuleTest.kt
dd-sdk-android-glide/src/test/kotlin/com/datadog/android/glide/DatadogRUMUncaughtThrowableStrategyTest.kt
dd-sdk-android-glide/src/test/kotlin/com/datadog/android/glide/utils/config/DatadogSingletonTestConfiguration.kt
dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/trace/TracingInterceptor.kt
library/dd-sdk-android-rum/apiSurface
library/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/sqlite/DatadogDatabaseErrorHandler.kt
library/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/sqlite/DatadogDatabaseErrorHandlerTest.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/data/db/sqlite/DatadogSqliteHelper.kt

This PR removes SDK provider for the classes which may be created before SDK initialized in favour of the SDK instance name + `SdkReference` usage, so that SDK can be resolved lazily.
`DatadogRUMUncaughtThrowableStrategy` requires lazy resolution as well, because `AppGlideModule#applyOptions` is called once and this call may happen before Datadog SDK is actually initialized.

RUMM-3196: Remove SDK instance provider in favour of SdkReference usage

---

library/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumFeature.kt
library/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/ActivityLifecycleTrackingStrategy.kt
library/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/RumFeatureTest.kt

This PR adds more logs to the cases when SDK instance is missing:
* For `enableRumDebugging` it has `warn` level, because it is the user who controlling the call.
* For view tracking strategy it is `info`, because it is us who control the call.

Add more internal logs to the cases when SDK core instance is missing

---

dd-sdk-android/src/main/kotlin/com/datadog/android/v2/core/internal/net/DataOkHttpUploader.kt

We currently send failed upload information to the maintainer logger, but not to the user console. I've added a line at the `verbose` level for users to help diagnose network errors.
I am trying to diagnose an error on batch upload and can't seem to get enough information to figure out what's happening. Hoping this will help in the future.

Add extra error output in case of a failed upload

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScopeTest.kt

We need to keep old RUM view scope IDs, because `viewId` can be changed on the [session renewal](https://github.com/DataDog/dd-sdk-android/blob/c9ab67cf0a1565f94a0ed3002eb5a6a78ad0cde0/dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumViewScope.kt#L199), meaning that events like `ActionSent`, etc. which do the match by `viewId` won't match, because they will carry old `viewId`.

RUMM-3314: Keep old viewIds for view scope

---

dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt

There is a flaw in the [following change](https://github.com/DataDog/dd-sdk-android/pull/1399/files#diff-aaf8a259788b94b68810c152e9da1ac6b04935be9ffdfb30edafb9f67ecb5edfR149-R151): since it doesn't update last interaction time, next real interaction event arriving (or valid background event) will see `isExpired = true` and create a new session again, making original session very short-living and doubling the number of sessions (if we think about `ApplicationLaunchView` which may be linked to the original session).

RUMM-3313: Set last interaction time by SdkInit event

---

CHANGELOG.md
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumRawEvent.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitor.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/rum/internal/monitor/DatadogRumMonitorTest.kt

This PR reverts changes related to the `SdkInit` command (because it may introduce unwanted sessions) and prepares 1.19.2 release.

Revert SdkInit command changes

---

buildSrc/src/test/kotlin/com/datadog/android/core/internal/utils/MiscUtils.kt
buildSrc/src/test/kotlin/com/datadog/gradle/plugin/jsonschema/ModelValidationTest.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/utils/MiscUtils.kt
dd-sdk-android/transitiveDependencies
gradle/libs.versions.toml
library/dd-sdk-android-session-replay/transitiveDependencies

This PR updates GSON to the version `2.10.1`, changelog can be found [here](https://github.com/google/gson/releases). It is needed, because otherwise [mvrepository site reports vulnerability](https://mvnrepository.com/artifact/com.datadoghq/dd-sdk-android/1.19.0) from Gson lib (which doesn't affect us, but still better to get rid of it).
Gson added `JsonObject.asMap` method in version `2.10.0` which clashes obviously with the extension method we had in our codebase, so I had to rename out method to `asDeepMap`.

Update GSON library to version 2.10.1

---

dd-sdk-android/api/dd-sdk-android.api
dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogSite.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/SdkReference.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/constraints/DatadogDataConstraints.kt
features/dd-sdk-android-rum/api/dd-sdk-android-rum.api
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/RumMonitor.kt
features/dd-sdk-android-session-replay/api/apiSurface
features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseWireframeMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/TextViewMapper.kt
integrations/dd-sdk-android-coil/api/apiSurface
integrations/dd-sdk-android-coil/api/dd-sdk-android-coil.api
integrations/dd-sdk-android-coil/src/main/kotlin/com/datadog/android/coil/DatadogCoilRequestListener.kt
integrations/dd-sdk-android-fresco/api/apiSurface
integrations/dd-sdk-android-fresco/api/dd-sdk-android-fresco.api
integrations/dd-sdk-android-fresco/src/main/kotlin/com/datadog/android/fresco/DatadogFrescoCacheListener.kt
integrations/dd-sdk-android-okhttp/api/dd-sdk-android-okhttp.api
integrations/dd-sdk-android-okhttp/src/main/kotlin/com/datadog/android/okhttp/DatadogEventListener.kt
integrations/dd-sdk-android-rx/api/apiSurface
integrations/dd-sdk-android-rx/api/dd-sdk-android-rx.api
integrations/dd-sdk-android-rx/src/main/kotlin/com/datadog/android/rx/DatadogRumErrorConsumer.kt
integrations/dd-sdk-android-sqldelight/api/apiSurface
integrations/dd-sdk-android-sqldelight/api/dd-sdk-android-sqldelight.api
integrations/dd-sdk-android-sqldelight/src/main/kotlin/com/datadog/android/sqldelight/DatadogSqliteCallback.kt

This PR does the minor changes to the codebase to improve the public API surface from the Java side:
* All internal proxy methods are made synthetic - they are supposed to be called only by us and only from Kotlin, no need to have them in Java.
* No changes are done to the classes in the `internal` packages, they are used only by us.
* Prevent empty `Companion` objects from being visible.

RUMM-3318: Improve Java public API surface

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorder.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RumContextData.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RumContextDataHandler.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ForgeConfigurator.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/RumContextDataForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RumContextDataHandlerTest.kt

Extracts the RumContext logic from the Processor as preparation for the blockingQueue implementation
BlockingQueueHandler is also going to need to perform the RumContext logic, since it will enrich the BlockingQueueItems at the time they are inserted into the queue

REPLAY-1768 Extract RumContext logic from Processor

---

features/dd-sdk-android-ndk/src/main/cpp/datadog-native-lib.cpp

Reference to the `NdkCrashReportsFeature` was broken in the JNI bindings after changes done in https://github.com/DataDog/dd-sdk-android/pull/1474.
Fixing it.

Update JNI bindings in NDK module

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
library/dd-sdk-android-session-replay/apiSurface
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayFeature.kt

In version 1.20.0 we made internal the `start/stop recording` functions with the intention to expose them later. Those functions were currently used by the Datadog Mobile App so we need to change them back as they are ready to be used anyway.

Release hotfix 1.20.1

---

library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayFeature.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorder.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueItem.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/SnapshotRecordedDataQueueItem.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/TouchEventRecordedDataQueueItem.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/Processor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewOnDrawInterceptor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowCallbackInterceptor.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallback.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListener.kt
library/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/storage/SessionReplayRecordWriter.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayRecorderTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/ForgeConfigurator.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/SnapshotRecordedDataQueueItemForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/forge/TouchEventRecordedDataQueueItemForgeryFactory.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/SnapshotRecordedDataQueueItemTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/TouchEventRecordedDataQueueItemTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/processor/RecordedDataProcessorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/ViewOnDrawInterceptorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/WindowCallbackInterceptorTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/callback/RecorderWindowCallbackTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/listener/WindowsOnDrawListenerTest.kt
library/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/storage/SessionReplayRecordWriterTest.kt

The traversal of nodes and production of snapshots (and touch events) was, up until now, synchronous. The recorded data queue enables asynchronous tasks to be performed during the traversal and for snapshots and touch events to still be generated in order and sent. 
In general terms what happens is this (for a snapshot item):
1) An item is generated and inserted into the queue, however this item has no nodes yet and so cannot be processed. A reference to this item will be passed during the traversal through all the mappers.
2) The traversal of the node tree finishes. If we didn't find any images on the way and if we successfully got a list of nodes then we update the item and try to process the queue. In a future pr the logic will be: If we encounter an image in a mapper during the …

REPLAY-1722 Implement recorded data queue

---

dd-sdk-android-core/src/main/kotlin/com/datadog/android/log/LogAttributes.kt
features/dd-sdk-android-logs/api/apiSurface
features/dd-sdk-android-logs/api/dd-sdk-android-logs.api
features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/Logger.kt
features/dd-sdk-android-logs/src/main/kotlin/com/datadog/android/log/LogsConfiguration.kt
features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/LoggerBuilderTest.kt
features/dd-sdk-android-logs/src/test/kotlin/com/datadog/android/log/LogsConfigurationBuilderTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LogsUtils.kt
integrations/dd-sdk-android-timber/src/main/kotlin/com/datadog/android/timber/DatadogTree.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/logs/LogsFragment.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/traces/TracesViewModel.kt

This change aligns APIs used to configure Logs feature and `Logger` with wording used in iOS SDK.
Changes:
For `Logger`:
* `setLoggerName` -> `setName`
*  `setSampleRate` -> `setRemoteSampleRate`
* `setDatadogLogsMinPriority` -> `setRemoteLogThreshold` 
`setDatadogLogsEnabled` method is removed, because it duplicates functionality which can be achieved by the `setRemoteSampleRate` method.
`setLogcatLogsEnabled`, `setNetworkInfoEnabled`, `setBundleWithTraceEnabled` and `setBundleWithRumEnabled` are not changed, because this naming works better with `Builder` pattern and anyway wording stay the same in general (iOS SDK is using `bundleWithRUM`, `bundleWithTrace`, `consoleLogFormat`, `sendNetworkInfo` properties).
`LogsConfiguration` got `setLogEventMapper` renamed to `setEventMapper`, …

RUMM-3367: Align APIs of Logs feature and Logger configuration with iOS SDK

---

features/dd-sdk-android-trace/api/apiSurface
features/dd-sdk-android-trace/api/dd-sdk-android-trace.api
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/AndroidTracer.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/Trace.kt
features/dd-sdk-android-trace/src/main/kotlin/com/datadog/android/trace/TraceConfiguration.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/TraceConfigurationBuilderTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/trace/TraceTest.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/Configurator.kt
features/dd-sdk-android-trace/src/test/kotlin/com/datadog/android/utils/forge/TraceConfigurationForgeryFactory.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/security/EncryptionTest.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/log/ActivityLifecycleLogs.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/rum/KioskSplashPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/trace/ActivityLifecycleTrace.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/main/NotTestableApis.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanBuilderE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanConfigE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanE2ETests.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/JvmCrashService.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/services/NdkCrashService.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/wear/src/main/java/com/datadog/android/wear/sample/WearApplication.kt

Some minor changes in the wording in order to align with iOS SDK.
**NOTE**: `Tracer` object is created outside of `Trace.enable` call, because we have to use anyway `GlobalTracer` from `io.opentracing` (meaning we cannot remove the method responsible to `Tracer` object registration in `GlobalTracer` like in https://github.com/DataDog/dd-sdk-android/pull/1502).

RUMM-3368: Align pubilc API of Traces with iOS SDK

---

dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/FilePersistenceConfig.kt
dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestrator.kt
dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/persistence/file/batch/BatchFileOrchestratorTest.kt
detekt_custom.yml

The goal of this PR is to reduce CPU consumption during the scenarios like described in https://github.com/DataDog/dd-sdk-android/issues/1469.
The issue comes from the fact that when we have many batch files on the disk calling `listSortedBatchFiles` as-is (which is called several times during `getWritableFile`, for example) becomes quite expensive because:
* syscalls (like `isFile`) are expensive
* pattern matching becomes expensive as well.
In order to optimize that, the following is done:
* Introduced the cache for the files already known to be batch files, so that we don't need to call `isFile` and use regex.
* Introduce throttling for the cleanup (only for the `getWritableFile` path, because a) it can be called much more often than `getReadableFile`, for every event; b) cleanup …

RUMM-3338: Introduce known file cache and cleanup throttling in `BatchFileOrchestrator` in order to reduce the number of syscalls

---

features/dd-sdk-android-session-replay/api/apiSurface
features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayConfiguration.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayConfigurationBuilderTest.kt
instrumented/integration/src/androidTest/kotlin/com/datadog/android/sdk/integration/security/EncryptionTest.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/RuntimeConfig.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplayPlaygroundActivity.kt
instrumented/integration/src/main/kotlin/com/datadog/android/sdk/integration/sessionreplay/SessionReplaySampledOutPlaygroundActivity.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt

In the iOS sdk we are currently explicitly require the `sampleRate` value when enabling the Session Replay feature. We need to align on the Android side also and require this when building the SR configuration object.
Please also note that given this change the `setSessionReplayRate` method doesn't make sense anymore and was removed.

REPLAY-1817 Require sampleRate when building the SR configuration

---

dd-sdk-android-core/api/apiSurface
dd-sdk-android-core/api/dd-sdk-android-core.api
dd-sdk-android-core/src/main/kotlin/com/datadog/android/Datadog.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/SdkCore.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/DatadogCore.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/NoOpInternalSdkCore.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/DatadogTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/DatadogCoreTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/trace/SpanConfigE2ETests.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/SampleApplication.kt
sample/kotlin/src/main/kotlin/com/datadog/android/sample/user/UserFragment.kt
sample/wear/src/main/java/com/datadog/android/wear/sample/WearApplication.kt

Changing `Datadog.setUserInfo` arguments was not necessary for v2, restoring v1 version (same as in iOS SDK).

Restore Datadog.setUserInfo method signature from v1

---

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/ComposedOptionSelectorDetectorTest.kt

In this PR we are increasing the SR batch size limit to 10MB into the core to support large payloads containing embedded base64 images. This follows the same approach as in iOS introduced with the Image recording feature added lately. 
Please note that the SR intake unlike RUM accepts payloads up to 10MB size.

REPLAY-1862 Increate batchSizeLimit to 10MB for SR feature

---

instrumented/integration/proguard-rules.pro
instrumented/nightly-tests/proguard-rules.pro
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/utils/MiscUtils.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/webview/WebViewTrackingE2ETests.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/WebViewTrackingActivity.kt

This PR does 2 small fixes:
* Fixes a reflection call to clean up `GlobalRumMonitor`.
* Fixes `WebViewTracking` test when there is no allowed hosts defined.

Fixes for nightly E2E tests

---

instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumViewTrackingE2ETests.kt

This change reduces flakiness of RUM View Tracking tests. The issue is that `launch` [exists once Activity transitions to the `RESUMED` state](https://developer.android.com/reference/androidx/test/core/app/ActivityScenario#launch(java.lang.Class%3CA%3E)), meaning if there is no more interaction test completes and `waitForIdleSync` in `NightlyTestRule` can be executed before activity actually transitions to the `DESTROYED` state (when `stopView` is called).
This change ensures activity explicitly transitions to the `DESTROYED` state, so that `stopView` event is fired before test actually completes.
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) …

Reduce flakiness of RUM View Tracking tests

---

features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt

We have an issue at the moment with base64 where too many bitmaps are being created and recycled, resulting in excessive garbage collection. We need to turn off the feature until it can be fixed. In this PR I'm temporarily removing `ImageButtonMapper` from the list of mappers used in the traversal, as this is the only place where we enter the base64 logic. 

Temporarily remove imagebutton mapper

---

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/debug/UiRumDebugListener.kt
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt
features/dd-sdk-android-rum/transitiveDependencies
gradle/libs.versions.toml
instrumented/integration/test-proguard-rules.pro

`androidx.navigation:navigation-runtime-ktx` was used just for a single method, but it was bringing quite a lot of dependencies, and also Kotlin Coroutines, which attributed quite a lot to the transitive dependencies size.

Remove dependency on Navigation Kotlin extensions

---

dd-sdk-android-core/api/apiSurface
dd-sdk-android-core/api/dd-sdk-android-core.api
dd-sdk-android-core/src/main/kotlin/com/datadog/android/api/storage/FeatureStorageConfiguration.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/v2/DataUploadRunnable.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/data/upload/v2/DataUploadScheduler.kt
dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/internal/persistence/ConsentAwareStorage.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
dd-sdk-android-core/src/test/kotlin/com/datadog/android/utils/forge/FeatureStorageConfigurationForgeryFactory.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt

This PR is follow - up on the [ios PR](https://github.com/DataDog/dd-sdk-ios/pull/1363) where we are providing a custom (batchSize, uploadFrequency) configuration for Session Replay feature to decrease the number of sessions with corrupted/not-enough records.

REPLAY-1887 Provide the uploadFrequency per feature

---

features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScope.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeature.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/SessionReplayFeatureTest.kt

SR always listens and reacts to RUM session state

---

detekt_custom.yml
features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategy.kt
features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/tracking/NavigationViewTrackingStrategyTest.kt
instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/rum/RumViewTrackingE2ETests.kt
instrumented/nightly-tests/src/main/AndroidManifest.xml
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/activities/ViewTrackingNavigationFragmentContainerViewActivity.kt
instrumented/nightly-tests/src/main/kotlin/com/datadog/android/nightly/fragments/ViewTrackingNavigationFragmentContainerViewHomeFragment.kt
instrumented/nightly-tests/src/main/res/layout/tracking_strategy_navigation_fragment_container_view.xml
instrumented/nightly-tests/src/main/res/navigation/nav_graph_fragment_container_view.xml
instrumented/nightly-tests/src/main/res/values/strings.xml
sample/kotlin/src/main/kotlin/com/datadog/android/sample/NavActivity.kt

This PR addresses the issue described [here](https://github.com/DataDog/dd-sdk-android/issues/760#issuecomment-1511050310). Basically now the [recommendation](https://developer.android.com/guide/navigation/get-started#add-navhostfragment) is to use `FragmentContainerView` for hosting `NavHostFragment`, this now will be the priority for lookup, and if not found we fall back to the old strategy.

RUMM-3445: Support `navHost` hosted by `FragmentContainerView` for `NavigationViewTrackingStrategy`

---

features/dd-sdk-android-rum/src/test/kotlin/com/datadog/android/rum/internal/domain/scope/RumSessionScopeTest.kt

The issue is that in the test mentioned sometimes background tracking can be enabled, leading to the `keepSession = true`.

Fix flaky test related to the Session Replay context update

---

integrations/dd-sdk-android-glide/build.gradle.kts

There are no OkHttp symbols in the public API of Glide integration module, so no need to re-export it.

Don't reexport OkHttp from Glide

---

features/dd-sdk-android-session-replay/build.gradle.kts
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactory.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/domain/SessionReplayRequestFactoryTest.kt
sample/kotlin/build.gradle.kts

We were using just few symbols from RUM module, and they probably even are not needed.
This change is to have the consistency in the setup with iOS SDK, where `DatadogRUM` should be added alongside with Session Replay module.

REPLAY-1894: Remove explicit dependency on RUM module from Session Replay

---

detekt_custom.yml
features/dd-sdk-android-session-replay/api/apiSurface
features/dd-sdk-android-session-replay/api/dd-sdk-android-session-replay.api
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacy.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandler.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64LRUCache.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64Serializer.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Cache.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/BaseWireframeMapper.kt
features/dd-sdk-android-session-replay/src/main/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapper.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/SessionReplayPrivacyTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/async/RecordedDataQueueHandlerTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64LRUCacheTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/base64/Base64SerializerTest.kt
features/dd-sdk-android-session-replay/src/test/kotlin/com/datadog/android/sessionreplay/internal/recorder/mapper/ImageButtonMapperTest.kt

Adds an LRUCache for base64 strings - cache base64 strings against drawable hashcodes. 
Evict all items in the LRUCache every time we change views. 
Without a caching mechanism we create and garbage collect an excessive number of bitmaps. 
This PR contains a revert commit of the revert of imagebuttonmapper (iow it adds base64 functionality back)

REPLAY-1727: Base64 Caching Mechanism

---

build.gradle.kts
buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt
instrumented/integration/build.gradle.kts
instrumented/nightly-tests/build.gradle.kts
integrations/dd-sdk-android-coil/build.gradle.kts
integrations/dd-sdk-android-compose/build.gradle.kts
integrations/dd-sdk-android-fresco/build.gradle.kts
integrations/dd-sdk-android-glide/build.gradle.kts
integrations/dd-sdk-android-okhttp/build.gradle.kts
integrations/dd-sdk-android-rx/build.gradle.kts
integrations/dd-sdk-android-sqldelight/build.gradle.kts
integrations/dd-sdk-android-timber/build.gradle.kts
integrations/dd-sdk-android-tv/build.gradle.kts
sample/kotlin/build.gradle.kts
sample/wear/build.gradle.kts

This change switches from `api` to `implementation` dependency type for features in integrations modules, in order to put more focus towards the individual feature setup.

Use `implementation` dependency for features in integrations modules
